### ISSUE TITLE
Make sure wazuh kibana app is compatible with latest amazon elasticsearch version 

### ISSUE THREAD

**Issue by fluential** [wazuh/wazuh-kibana-app#1065]
New releases of wazuh and wazuh kibana app are quickly dropping support for slightly older versions of elasticsearch, this is a problem for anyone using amazon elasticsearch as a service as they are not always on the latest available version of ES.

TODO:
Consider releasing wazuh kibana app that support latest version of ES supported by amazon as visible here https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html

**Comment by JPLachance** [comment]
Greetings!

I need the exact same thing. The [Amazon Elasticsearch Service](https://aws.amazon.com/elasticsearch-service/) is a nice alternative to deploying and managing an Elasticsearch cluster all by ourselves.

The only drawback of using Amazon Elasticsearch Service is that they are one or two minor versions behind because they must test and re-test every new version of Elasticsearch before releasing them worldwide to all customers.

I think using Amazon Elasticsearch Service should be officially endorsed by the Wazuh team.

Can we create a build for Wazuh 3.7.1 on Kibana 6.3.2? :) Are there breaking changes preventing you from doing such build?

**Comment by jesusgn90** [comment]
Hi @JPLachance and @fluential ,

This is not in our roadmap and our app is stuck to the Wazuh version plus the Elasticsearch version. If we support each Wazuh version with each Elasticsearch version we'd have tons of packages to maintain which is unmaintainable. 

I hope that Amazon service updates the Elastic stack soon. In any case, I'll discuss this with my colleagues from Wazuh, it's interesting but I think we are not planning to maintain so many apps.

Regards,
Jesús

**Comment by fluential** [comment]
@jesusgn90 you only need to support one additional version which is latest available from AWS, as in we are not saying you need to support every version in there, just latest would be good enough.

**Comment by jesusgn90** [comment]
Yes @fluential , but each time Amazon updates the Elastic stack we'd need to make a new app. Also, the Elastic stack is publishing new releases about each one and half month, same as Wazuh, it's a bit crazy but the team will talk about this.

Regards

**Comment by JPLachance** [comment]
@jesusgn90, the [Wazuh server](https://github.com/wazuh/wazuh) is independent of the Elasticsearch version right?

On top of that, I think the Wazuh Kibana application is not forced to always use the latest version of Elasticsearch. The Wazuh Kibana application could always be two versions behind the Kibana version and it would not change much for Wazuh users (in my opinion).

At the moment, we are basically forced to upgrade our Elasticsearch cluster each time we want to upgrade Wazuh. If the Wazuh Kibana application would always be compatible with the latest 3 versions of Elasticsearch (6.5, 6.4 and 6.3 as I'm writing this comment), it would make our life easier. :)

**Comment by JuanjiJG** [comment]
Hi @JPLachance,

Keep in mind that we have an [Elasticsearch template](https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/wazuh-elastic6-template-alerts.json) used to give format to the Wazuh alerts. Each Wazuh release includes new or updated alert fields that must be updated on the Elasticsearch template, and also, our Kibana app must be updated to reflect those changes on some visualizations.

Sometimes, the Elasticsearch upgrades forced us to update the template to avoid compatibility issues or some critical errors. As you can see, the Wazuh integration can be a little bit complex sometimes.

Besides, the plugin development API from Kibana is not stable, so sometimes a new version requires critical code updates in order to keep compatibility with the latest version.

As @jesusgn90 said, we'll discuss this matter with the team, but for now, it's quite difficult to maintain a wider compatibility scope with different Elastic Stack versions.

Regards,
Juanjo

**Comment by JPLachance** [comment]
Hello!

The Amazon Elasticsearch Service [now supports Elasticsearch 6.5.4](https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-elasticsearch-service-announces-support-for-elasticsearch-6-5/), meaning the latest version of Wazuh (currently 3.8.2) can be deployed on top of Amazon Elasticsearch.

🎉 

Now, I'm looking at this project branches, and I see there is no 3.9-6.5 branch.

Are there braking changes between Kibana 6.5 and 6.7 preventing you from keeping the compatibility with Kibana 6.5?

Amazon Elasticsearch is becoming a really nice service. They started to integrate [Open Distro for Elasticsearch](https://opendistro.github.io/for-elasticsearch/) features in Amazon Elasticsearch. They [just added](https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-elasticsearch-service-adds-event-monitoring-and-alerting-support/) the [Alerting plugin](https://opendistro.github.io/for-elasticsearch/features/alerting.html). I'm quite sure they won't stop with the Alerting plugin 😄

It would be nice to make a Wazuh Kibana App 3.9 build for Elasticsearch 6.5.4. 🙂

Regards,
Jean-Philippe

**Comment by natesilverman** [comment]
Has anyone successfully integrated Wazuh with AWS Elasticsearch 6.5.4 yet?  Esp via Docker containers?

**Comment by JPLachance** [comment]
Hello,

I did not make it happen yet (because I've too many ongoing projects), but I think the solution is to use the [Logstash output plugin for Amazon ES](https://github.com/awslabs/logstash-output-amazon_es).

Then for the Wazuh Kibana application, I would follow the [AWS documentation](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-kibana.html#es-managedomains-kibana):
- Create an Nginx proxy that can access the Amazon Elasticsearch domain using Signature V4
- Set the proper policy on the Amazon Elasticsearch domain to allow the Nginx proxy
- Connect the Kibana instance with the Wazuh Kibana application to the Nginx proxy

Does that make sense? I've not done it yet, but that's how I plan to make it work 🙂 

Regards,
Jean-Philippe
