### ISSUE TITLE
Integrity monitoring shows too view File Changes for Agent in Bottom Table "Events summary"

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh-kibana-app#1066]
### Release
* all components are on release level _3.6.1_

### Steps to Reproduce
1. Have an agent which has a lot of FIM changes detected by `syscheck` (in my current case there are _~1.900_
1. Go to `Overview / Security events` in `Kibana`, the _Top five agents_ and the _Alerts evolution - Top 5 agents_ digram indicate you the corresponding agent with high FIM change rate, the bottom table _Alerts summary_ indicates for rule id `550` _~2.000_ changes.
1. Go to `Overview / Integrity monitoring`, the `Events over time` diagram corresponds with the `syscheck` result but the bottom table `Events summary` shows for the affected agent just _11_ changed files.
1. Go to `Discovery` and filter for the affected agent and the _~1.900_ are listed.

### Side Note
I observe this behviour for a certain time, it happens also if an agent has much less FIM changes, they are not all shown in the bottom table `Events summary`. I can understand that we probably do not want to show all events especially in that case where you have many cause of long browser loading times. If I remember correctly, it was different in release _3.5.0_, the length of the listed changed files rather correspond to the number of changed files.

**Comment by jesusgn90** [comment]
Hi @juergenc,

Visualizations have their own limits due to Elasticsearch performance reasons. Each visualization tries to show the most relevant results, but in fact, not always matches what you are seeing on Discover. We are trying to re-work in all our visualizations to avoid this kind of situation, but some kind of visualizations such tables uses aggregations from Elasticsearch which is not as cheap as we want so we reduced it.

Currently, our latest version is for Wazuh 3.7.1, I'm going to include in our roadmap for 3.8.0 this ticket, this way you'll be updated about this.

Thanks for your feedback, very appreciated.

Regards,
Jesús
