### ISSUE TITLE
Reporting. 5029 - Reporting was aborted (Cannot read property '2' of undefined)

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#1075]
![image](https://user-images.githubusercontent.com/2720787/49750144-1a3e6b80-fca2-11e8-8064-53bec1546975.png)

**OS** CentOS 7.5
**Wazuh version** 3.7.1
**Wazuh API version** 3.7.1
**Wazuh app** 3.7.1
**Kibana** 6.5.0

**Comment by jesusgn90** [comment]
Hi @rossengeorgiev ,

I've just tried to generate some reports for an agent and I could not reproduce it, which section is generating that error? all the tabs or some specific tabs? Is there something special in that agent that we should know?

Please let me know some more information in order to help you. Also, a full-size screenshot might be fine. The error probably comes from https://github.com/wazuh/wazuh-kibana-app/blob/master/server/reporting/raw-parser.js but I don't know exactly why it's failing, I need more details.

Thanks in advance and sorry about the inconveniences.

Best regards,
Jesús

**Comment by rossengeorgiev** [comment]
Hi @jesusgn90, I forgot to specify. This is the inventory page on one of the agents.

**Comment by jesusgn90** [comment]
Hello again @rossengeorgiev ,

![image](https://user-images.githubusercontent.com/8860227/49790353-469fc980-fd2e-11e8-991f-8a42ed9228af.png)

I can't reproduce your error, I'm using a CentOS 7 agent too. Is the error appearing always?

**Comment by rossengeorgiev** [comment]
I updated everything to the latest version, and the error is gone. I get report success as on your screenshot, but when I got to "Management -> Reprorting" there is nothing there.

**Comment by jesusgn90** [comment]
Hi @rossengeorgiev ,

You've probably fallen into Kibana > Management > Reporting, what I meant is Wazuh > Management > Reporting, we may change that name, by the way, it's a bit confusing.

Regards!

**Comment by rossengeorgiev** [comment]
Ah, that was is. The message could in include "Wazuh >Managment ...".

The report I get from that page generates a single page without any of the data (e.g. packages, network ports).
