### ISSUE TITLE
Kibana, Wazuh HIDS, Wazuh RESTful API installd in same server ??

### ISSUE THREAD

**Issue by tatdatpham** [wazuh/wazuh-kibana-app#13]
Hi, 
i installed wazuh-kibana plugin in kibana (5.3) successed.
When i run kibana, i got error

![image](https://cloud.githubusercontent.com/assets/3429970/25300520/3cb9718e-273b-11e7-9f6d-19aacccd2332.png)

Need install Kibana, Wazuh HIDS, Wazuh RESTful API in same server ???

**Comment by snaow** [comment]
Hi @tatdatpham, 

Sorry for late response, let me try to help here.

You don't need to install Wazuh HIDS and the API in the same server where Kibana is, Wazuh App will be able to handle an external Wazuh API IP Address.

I believe the error you got is not related with Wazuh HIDS or Wazuh API, it is because Wazuh App is not able to create some indices and templates when booting, usually it is related to Elasticsearch credentials configuration.
Are you using Security plugin from X-Pack ? Could you tell us your "elasticsearch.url" value at /etc/elasticsearch/elasticsearch.yml file configuration ? Are Kibana and Elasticsearch node on the same host?

Sorry for all the questions, I am kinda lost here because the App is working as expected in many other users, please give us some more information and I will try to keep helping.

Cheers,
Pedro 'snaow' Sanchez.

**Comment by tatdatpham** [comment]
Thank for reply @snaow ,

> Are you using Security plugin from X-Pack ? 
Yes,

> Could you tell us your "elasticsearch.url" value at /etc/elasticsearch/elasticsearch.yml file configuration
This is my config [elasticsearch.yaml](https://pastebin.com/TBcNLmzD)


> Are Kibana and Elasticsearch node on the same host?
Yes.

**Comment by snaow** [comment]
Hi @tatdatpham,

No worries, let see if we can solve your problem.

Cool! If you are using X-Pack I think we are closer to find the problem.
My mistake was to ask you about elasticsearch.yml, I think we need kibana.yml.
Wazuh App uses Elasticsearch API for inserting templates and creating indices, the credentials for Elasticsearch API are the same than Kibana uses, they are set on kibana.yml:

> elasticsearch.username: "elastic"
> elasticsearch.password: "changeme"

If those credentials does not have enough privilegies to create indices, load templates etc.. Wazuh App won't work properly, please try to review those credentials.

Hope it helps.

**Comment by tatdatpham** [comment]
Sure! I setup ES username and password in kibana.yaml before but still got error ...

**Comment by snaow** [comment]
Hi @tatdatpham,

So it was related to permissions like I thought, I am glad you solve your problem.

How about the last error? is still there? I think the problem is related to the ending URL you have:
"h@44136fa".
I think you have activated in "Advanced options" the shorten URL's, try to disabled them and try again.

Regards,
Pedro.

**Comment by tatdatpham** [comment]
Yeah, thanks for suggestion.
I found option in advance in kibana. Just disable session storage and it work!
And error not show chart in rule set fixed too.

![image](https://cloud.githubusercontent.com/assets/3429970/26091129/7b056a96-3a33-11e7-8d35-05771f74fd9f.png)

![image](https://cloud.githubusercontent.com/assets/3429970/26091182/e00ab93c-3a33-11e7-9861-5fa27b80969a.png)

**Comment by dineshmickey** [comment]
I have kibana and ElasticSearch on different hosts. that may cause any problems ??

**Comment by jesusgn90** [comment]
Hi @dineshmickey ,

It's not a problem. Indeed, we recommend to have a distributed architecture, the performance is better.

The only thing to take care is about the networking and the configuration files. 

Elasticsearch must expose its API for Kibana and it must be reachable from the Kibana network.

`/etc/elasticsearch/elasticsearch.yml`

```yml
network.host: elastic-ip
```

`/etc/kibana/kibana.yml`

```yml
elasticsearch.hosts: ["http://elastic-ip:9200"]
```

I hope it helps.

Best regards,
Jesús
