### ISSUE TITLE
Add explanation on how to register agents or link when there are no agents

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1320]
Currently, our agent preview page shows an empty table when there are no agents, we should add link and references on how to register agents so the user has a meaningful view when there are no agents.

**Comment by juankaromo** [comment]
This issue has been adapted in order to carry out an interactive agent registration process (when there are no agents) for each type of operating system.

Now, the issue must comply with the following points:

- [x] Linux registration process
  - [ ] Step 1: add the agent to the manager using an API call in order to obtain the regsitration key
  - [ ] Step 2: import the key telling the user to execute a command
  - [ ] Step 3: edit the Wazuh agent configuration to add the Wazuh manager IP telling the user to execute a command
  - [ ] Step 4: Restart the manager and navigate to agents preview table

- [ ] Windows registration process
  - [ ] Step 1: register agent with CLI

- [ ] OSX registration process

This interactive process will also have to be accessible from the agents table, in order to be able to use it even if agents already exist.

- [ ] Implements a directive for use it anywhere

**Comment by santiago-bassett** [comment]
Please keep in mind that agents can't be added unless the app is running in admin mode. In those cases we should just point them to the documentation and maybe include a summary of  how to register an agent.

**Comment by juankaromo** [comment]
That's right. Thank you for the reminder. I update the issue to take it into account and we work on it!
