### ISSUE TITLE
issue with email alert?

### ISSUE THREAD

**Issue by killmasta93** [wazuh/wazuh-kibana-app#1337]
Hi,
I was wondering if someone could shed some light on the issue im having. Currently trying to get email alert when ssh gets login from one of my agents. I have configured SSMTP and checked to see if it works. then on the /var/ossec/etc/ossec.conf added this line under global

`<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>mail.mydomain.com</smtp_server>
    <email_from>sistemas@mydomain</email_from>
    <email_to>sistemas@mydomain.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <queue_size>131072</queue_size>
  </global>
 <email_alerts>
  <email_to>sistemas@mydomain.com</email_to>
  <rule_id>5715</rule_id>
  <do_not_delay />
</email_alerts>
  <alerts>
   <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
  <logging>
`
i check the logs from the alert and see that rule.mail= false

any ideas?
Thank you

**Comment by juankaromo** [comment]
Hi @killmasta93 

Did you configure the email settings in the manager side?
You can find all the information on how to configure it here: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html

On the other hand, you have set a minimum alert level 12, and if you rule level is lower, it won't be sent. You can change this configuration setting (to **10** for example) like this: E.g.:

```
<ossec_config>
  <alerts>
      <email_alert_level>10</email_alert_level>
  </alerts>
  ...
</ossec_config>
```

Once configured restart the manager
`systemctl restart wazuh-manager`

Alternatively, you can enforce the email notification for a particular rule adding the flag **alert_by_email**. E.g.:

```
<rule id="502" level="3">
  <if_sid>500</if_sid>
  <options>alert_by_email</options>
  <match>Ossec started</match>
  <description>Ossec server started.</description>
</rule>
```

I hope it helps.

Best regards,
Juan Carlos

**Comment by killmasta93** [comment]
Thanks for the reply, sorry for the late reply as i did not get an email alert of the thread. This is my config
`<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>mail.mydomain.com</smtp_server>
    <email_from>sistemas@mydomain.com</email_from>
    <email_to>sistemas@mydomain.com</email_to>
    <email_maxperhour>10</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <queue_size>131072</queue_size>
  </global>
 <email_alerts>
  <email_to>sistemas@mydomain.com</email_to>
  <rule_id>5715</rule_id>
  <do_not_delay />
</email_alerts>
  <alerts>
   <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
`

Also configure email with SMTP authentication so not sure what im doing wrong?

Thank you

**Comment by juankaromo** [comment]
Hi @killmasta93

Do you check the tips I gave you in my previous comment? Anyway, I keep thinking that the problem is that you are setting a minimum level alert for sending mails in 12 (`<email_alert_level>12</email_alert_level>`), and the rule that you are expecting to receive has a level 3, so this will not be sent.

As I see you're trying to send a mail when rule **5715** is triggered, and knowing that is its level (3) is below the configured minimum level (12),  you can configure your rule with the option `<options>alert_by_email</options>`, in order to send the mail  regardless of what the minimum level is set to. 

To carry this out, you must modify the default rule. For that purpose, we are not going to modify the rule file inside the `/var/ossec/ruleset/rules` folder because will be lost in the update process. We are going to use the following procedure to preserve your changes.

Open the file `/var/ossec/etc/rules/local_rules.xml` and paste the code below:

```  
<rule id="5715" level="3" overwrite="yes">
    <if_sid>5700</if_sid>
    <options>alert_by_email</options>
    <match>^Accepted|authenticated.$</match>
    <description>SSHD authentication success.</description>
    <group>authentication_success,</group>
  </rule>
```

Once configured restart the manager
`systemctl restart wazuh-manager`

You can learn more about custom rules here https://documentation.wazuh.com/3.x/user-manual/ruleset/custom.html
You can find more information about force forwarding an alert by email here https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?highlight=alert_by_email#force-forwarding-an-alert-by-email. 
And you can learn more about the rules options here https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=alert_by_email#options

I hope it helps and, If the problem continues, please let us know.

Best regards,
Juan Carlos

**Comment by killmasta93** [comment]
Thanks for the reply, you were right about that, i change from 12 to 3 and got alerts like crazy is there a way i can only trigger that rule for one agent?

Thank you again

**Comment by juankaromo** [comment]
Hi @killmasta93 

Sure! You can send emails alert based on an agent with a configuration like this (**I'm relying on the configuration you put in here**): 

```
<email_alerts>
  <email_to>sistemas@mydomain.com</email_to>
  <event_location>AGENTIP, AGENTHOSTNAME OR AGENTNAME</event_location>
  <rule_id>5715</rule_id>
  <do_not_delay />
</email_alerts>
```

As you know, it is configured in `/var/ossec/etc/ossec.conf` and what you've done is add a granular email option to fire when the rule 5715 is triggered and it comes from the agent specified. You can use the IP, hostname or agent name.

You can find more information about this here https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?highlight=alert_by_email#email-alert-based-on-level-and-agent

I hope it helps and don't hesitate to ask if you have any other questions.

Regards.
Juan Carlos

**Comment by killmasta93** [comment]
Thanks for the reply, that did the trick wonderful help

**Comment by juankaromo** [comment]
Happy to help @killmasta93 , I'm glad that your problem got solved.

Don't hesitate to open a new issue whenever you have more questions or problems using Wazuh and/or the Wazuh app.

Regards.
Juan Carlos
