### ISSUE TITLE
Nginx No such file or directory + some issues reported

### ISSUE THREAD

**Issue by eowin** [wazuh/wazuh-kibana-app#1339]
Hi,

I have installed wazuh the last week on my elasticsearch server, and i encounter some issues with the kibana app.

1. When I have the health_check, an error 404 appear on my browser, when I check the link I have the following link : 

localhost.home/app/wazuh 

but when I manually change the link by : 

localhost.home/kibana/app/wazuh

Every thing is working.

------------

2. When I want analyze a rule ID from the dashboard "Security Events", I get an error 404 whit the following link : 

localhost.hom/kibana/app//app/wazuh#/manager/?tab=ruleset&ruleid=31101

But, when I edit the link to get this : 

localhost.hom/kibana/app/wazuh#/manager/?tab=ruleset&ruleid=31101

Every thing is working, (I tried to change it from the index patern, but every day the configuration is reset)

-----------
3. The principal issue where I didn't find the solution yet. I have nginx installed on my server, but when I go on the wazuh kibana app I get many error in the Nginx log when I load page : 

> 2019/04/01 11:28:02 [error] 28645#28645: *23045 open() "/var/www/plugins/wazuh/img/icons/app_dashboard.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_dashboard.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23050 open() "/var/www/plugins/wazuh/img/icons/app_logging.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_logging.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23046 open() "/var/www/plugins/wazuh/img/icons/app_advanced_settings.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_advanced_settings.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23045 open() "/var/www/plugins/wazuh/img/icons/app_security.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_security.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23050 open() "/var/www/plugins/wazuh/img/icons/app_monitoring.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_monitoring.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23054 open() "/var/www/plugins/wazuh/img/icons/app_discover.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_discover.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"
> 2019/04/01 11:28:02 [error] 28645#28645: *23055 open() "/var/www/plugins/wazuh/img/icons/app_visualize.svg" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: localhost.home, request: "GET /plugins/wazuh/img/icons/app_visualize.svg HTTP/1.1", host: "localhost.home", referrer: "https://localhost.home/kibana/app/wazuh"

Someone can help me the find solution to fix these 3 issue ( my first and second point I juste want to have a solution to fix link issue permanently and for the third I don't have the solution to fix theses issue)

Thx :)

**Comment by jesusgn90** [comment]
Hi @eowin this is a known issue, another user (@candlerb) reported the same behavior here https://github.com/wazuh/wazuh-kibana-app/issues/1135, now we have a branch where we are fixing it, it's also a Kibana known issue, but our plugin can manage it so it can work properly.

The main issue here is about "base paths" and Kibana routing system, in addition, the Wazuh app is not handling it properly under certain situations.

Woking branch: https://github.com/wazuh/wazuh-kibana-app/tree/issue-1339

Stay updated tracking this ticket, and sorry about the inconveniences.

Regards

**Comment by eowin** [comment]
Hi @jesusgn90,

Thank you for your answer, I will check that, juste to be sure, can I juste copy and paste the file from this branch without uninstall anything ?

**Comment by jesusgn90** [comment]
Hi @eowin (and @candlerb), our patch is not ready yet, the branch hasn't got the latest changes and the fix is designed for the incoming version.

Of course, I'll share with you how to apply the patch for your current installation.

In addition, I want to say that we've found the cause for all the issues related to this so we hope to have the fix soon.

I'll let you know about any news into this issue.

Best regards,
Jesús

**Comment by eowin** [comment]
Ah good news :D 

Thank you for your help !

**Comment by jesusgn90** [comment]
**Update**

Hi @eowin and @candlerb, here we've merged the PR for fixing this issue, [#1342](https://github.com/wazuh/wazuh-kibana-app/pull/1342), into our next version branch, thanks to @juankaromo

Let us prepare a patch for the previous app version so you can apply to your existing installation with no need to wait for the next version.

Regards,
Jesús

**Comment by jesusgn90** [comment]
**Update**

Hi @eowin and @candlerb, since our fix was done for the next version (not released yet), we've prepared a branch and a zip package with the patch for Wazuh 3.8.2 plus Kibana 6.7.0 so you can give a try to it while waiting for the next version.

- Patch branch: [3.8-6.7-fix-basepath](https://github.com/wazuh/wazuh-kibana-app/tree/3.8-6.7-fix-basepath)
- Diff: [click here](https://github.com/wazuh/wazuh-kibana-app/compare/3.8-6.7...3.8-6.7-fix-basepath)
- ZIP package: [wazuhapp-3.8.2-6.7.0-basepath-patch.zip](https://packages-dev.wazuh.com/pre-release/app/kibana/custom/wazuhapp-3.8.2-6.7.0-basepath-patch.zip)

I hope it helps. In case you consider this thread may be closed, just close it or ask us to close it.

Best regards,
Jesús

**Comment by eowin** [comment]
Hi @jesusgn90 

Thank you for your help, I have to update my Elasticsearch to 6.7.1n do you think that this package will work on this version ?

I will try it the next week, I'll do a feed back when I my tests are done !

Regards,

**Comment by jesusgn90** [comment]
**Update**

Hello again @eowin and @candlerb, we've just released the Wazuh app for Wazuh 3.8.2 and Kibana 6.7.1 which includes the fix for the base path issues.

- You can download it [here](https://packages.wazuh.com/wazuhapp/wazuhapp-3.8.2_6.7.1.zip).
- You can read our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrade-kibana) too.

I hope it helps guys and if this ticket is solved, please let us know so we can close it.

Regards,
Jesús

**Comment by eowin** [comment]
Hi @jesusgn90 

I'll try it the next week, I'll close this ticket if everything working fine !

Regards,

**Comment by eowin** [comment]
Hi @jesusgn90 

I did some tests today and I confirm to you that all link seem to working fine, and icon appears now on kibana !

Thank for your help !

**Comment by jesusgn90** [comment]
That's great @eowin,

I want just to point that @juankaromo did the fix here.

Don't hesitate to open a new ticket if needed.

Regards,
Jesús

**Comment by eowin** [comment]
So thank you to @juankaromo ;)
