### ISSUE TITLE
Allow save searches in the Wazuh App

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-kibana-app#1398]
Hi team,

Discover tab allows saving the current search.
![image](https://user-images.githubusercontent.com/1523318/56298235-17f98b80-6132-11e9-89f7-914b5b3931d4.png)

Could we do the same inside the app?

![image](https://user-images.githubusercontent.com/1523318/56298099-da94fe00-6131-11e9-80f9-f07e213da02f.png)

Thanks.

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh-kibana-app/issues/1507, https://github.com/wazuh/wazuh-kibana-app/issues/1499

**Comment by adri9valle** [comment]
**Update**

I've created a React component in order to display a modal with a form to save the search, at the moment only show the modal.

![rrrr](https://user-images.githubusercontent.com/7983984/60263681-9bc5b600-98e1-11e9-8fe4-850e877bc758.gif)

**Comment by adri9valle** [comment]
**Update**

Now the react component can get the search written also, checks if the search has not a name or is empty in order to prevent to save an empty search.

![test](https://user-images.githubusercontent.com/7983984/60277355-aee67f00-98fd-11e9-964e-3178cf6a0153.gif)

**NOTE**: Only is working the view to save it, in fact, the logic to save the search needs to be designed yet.

**Comment by juankaromo** [comment]
Since Kibana 7.6.X saved searches are displayed in the Wazuh app by default.

![image](https://user-images.githubusercontent.com/21195730/79970668-900c3700-8493-11ea-948f-c30515bcae8f.png)

Regards,
