### ISSUE TITLE
Move ".wazuh-version" information to a registry file

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1467]
Hi team,

The `.wazuh-version` is a useless index right now. Every index in Elasticsearch implies shards, replicas, and a few other things that might generate errors.

**Description**

The information stored in `.wazuh-version` must be replaced with a non-indexed solution.

**Proposal**

Create a `registry file` as Filebeat does. This index just let us now the installation date and the last Kibana restart time. That information can be written to a registry file. Other data in that index is about the version, revision, and all that information can be parsed from our package.json so there is no need for having a document in an internal index.

**Other changes**

- Remove all logic related to the index creation, reindex or any other Elasticsearch related logic.

**Comment by juankaromo** [comment]
**Update 05/06** https://github.com/wazuh/wazuh-kibana-app/pull/1509/commits/7bd45776ec21aaabb2df1a7a844468ec01f82eb4

`registry file` will be placed on the server root directory.

### Initialize.js

First of all `checkWazuhVersionIndex` has been changed by `checkWazuhVersionRegistry`. In this function, the first step is to delete .wazuh-index from Elasticsearch if exists (`wzWrapper.deleteWazuhVersionIndex()`).

After we check if registry already exists with `fs.existsSync(wazuhVersion)`, when WazuhVersion is the path of `registry file`. 

If it doesn't exist, we are going to create it in `saveConfiguration` existing method. On it, instead of creating an index, we create a file with the same configuration that we inserted before on the `.wazuh-index`: 
```js
fs.writeFileSync(wazuhVersion, JSON.stringify(configuration), (err) => {
   if (err) {
     throw new Error(err);
   }       
 });
```

Once created, we update the field `lastRestart`:

```js
let source = JSON.parse(fs.readFileSync(wazuhVersion, 'utf8'));
source.lastRestart = new Date().toISOString(); // Registry exists so we update the lastRestarted date only
```

### Wazuh-elastic

We have removed `'/elastic/timestamp'` and `'/elastic/setup'` endpoint from the elastic API because don't make sense here anymore. Instead, the endpoints have been relocated to `Wazuh-api`.

And the getters methods on it have been replaced from `await this.wzWrapper.getWazuhVersionIndexAsSearch()` to a simple file reader.

Now the files `check-timestamp`, `settings`, and `health-checks` make its requests to `'/api/XXX'`
### Elastic wrapper

All these methods have been removed from this wrapper cause them don't make sense:

```js
createWazuhVersionIndex()
insertWazuhVersionConfiguration()
getWazuhVersionIndex()
updateWazuhVersionIndexLastRestart()
getWazuhVersionIndexAsSearch()
```
Instead the method `deleteWazuhVersionIndex()` has been added for deelting the index when exists (an upgrade e.g.)

### Configurations

`wazuh-version.shards` and `wazuh-version.replicas` have been removed from the configuration files.

**Comment by juankaromo** [comment]
### Update 19/06

**Changes**

- `.wazuh-version` is deprecated and must disappear.
- Its role is taken by `wazuh-version.json` server file.
- The transition must be automatic and not generate errors.

**Tests in a Production enviroment**

| Test | Expected behavior | Result |
|-------|----------|----------|
| New installation | Check that .wazuh-version doesn't exists and create wazuh-version.json` file | pass |
| Update | Delete that .wazuh-version if exists and create `wazuh-version.json` file | pass |
| Restart | lastRestart filed in `wazuh-version.json` must be updated | pass |
| File is OK created | The props are read from app successfully | pass |
| File is OK created but doesn't have read permissions | The props are not read from the app and show error | pass |
| File is NOT created | App and shows error | pass |

**App on a fail file scenario**
![image](https://user-images.githubusercontent.com/21195730/59744981-0472ba00-9274-11e9-910f-3c4217371b31.png)

**File in OK scenario**
```js
{"name":"Wazuh App","app-version":"3.10.0","revision":"0516","installationDate":"2019-06-18T16:06:11.594Z","lastRestart":"2019-06-18T16:19:06.012Z"}
```

**Comment by juankaromo** [comment]
**Production error pointing**

I've been getting this error when installing the app in production from the package and updating the `.wazuh-version` index to the log file:

![image](https://user-images.githubusercontent.com/21195730/59916838-8c95c280-9420-11e9-8fcf-be9cdc3bc314.png)

As the calls have changed from `/elastic/timestamp` to `/api/timestamp` it was strange to me that calls were still being made to the previous route.

In the end it was because the bundles generated had not been updated. I proceed to erase them and launch Kibana again to regenerate them.

`rm -rf /usr/share/kibana/optimize/bundles`
`systemctl restart kibana`

Now everything works properly.

**Comment by adri9valle** [comment]
**Update**

Currently, we're saving properly the API information in the `config.yml` file.

```
wazuh.hosts:
  - 1562642463569:
      url: http://172.16.1.2
      port: 55000
      username: foo
      password: YmFy
  - 1562642463569:
      url: http://172.16.1.3
      port: 55000
      username: foo
      password: YmFy      
```

The previous configuration block contains the basic information to authenticate against the API but there is missing information which provokes empty fields in the table with the API entries.


![image](https://user-images.githubusercontent.com/7983984/61220874-8c36d180-a717-11e9-832b-413352061d18.png)


The extensions and cluster/manager information is missing and we need to find out the best way to include this.

The `config.yml` file contents a default extension configuration and in case of this configuration is missing or commented there is a `default-ext.js` file which has the extensions.

I think that we should use the default configuration of the `config.yml` file for all the API entries, and if there is some change in the extensions save this in the local storage.

On the other hand, the cluster information we receive the following information about the cluster/manager when we add a new API:

```
{
     manager: 'master',
     node: 'node01',
     cluster: 'wazuh',
     status: 'enabled' 
 }

```

I think that we should save in the API entry the manager, node and cluster information but not the status, the status should be saved in the local storage or the browser cache and when the status will be checked if changes save it in the browser. An API entry will be:

```
wazuh.hosts:
  - 1562642463569:
      url: http://172.16.1.2
      port: 55000
      username: foo
      password: YmFy
      manager: 'master',
      node: 'node01'
      cluster: 'wazuh'

```
