### ISSUE TITLE
Interactive guide for registering agents

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1468]
Hi team,

This issue is the second part of https://github.com/wazuh/wazuh-kibana-app/issues/1320 that unfortunately was not finished properly and we must complete it before 3.10.

**Description**

Give the user a new component where he can fill a simple (and dynamic) form and the app tells you how to install the agent with just a _copy & paste_ commands from a dynamic box.

We must use the new syntax for auto-deployment that the @wazuh/cicd team implemented for the users, an example can be found here https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_linux_rpm.html#installing-wazuh-agent

**Proposal**

Create a new React component that we can use where we want in the Wazuh app. The agents preview must know if there are no agents, then show it by default. If there are agents, it should show a _link_ or a _button_ that enables this component.

We must cover at least the most common agent types: RPM, DEB, Windows and MacOS.

**Comment by juankaromo** [comment]
**Update**

Today I started to implement a react component to migrate the first iteration of the agent registration process, which was implemented as a directive.

I've been learning how to implement the react components, and I've made a first approximation, which looks like this:

![image](https://user-images.githubusercontent.com/21195730/58569305-290be100-8236-11e9-908c-68c16c8e452b.png)

**Comment by juankaromo** [comment]
**Update**

Today I have continued to improve my react knowledge, and I have advanced almost finishing the issue.

I found this problem during the morning as I navigated through the component:

![image](https://user-images.githubusercontent.com/21195730/58630991-66797880-82e1-11e9-880d-fbd031752a07.png)

It turned out to be due to the syntax of how the installation instructions showed conditionally. 

Wrong behavior 
```js
 f (this.state.selectedOS === 'win') {
      guide = (
        <div>
          <EuiText>
            <p>Deploy the installation</p>
            <EuiCodeBlock language="js">
              {winText}
        </EuiCodeBlock>
          </EuiText>
        </div>
      );
    } else if (this.state.selectedOS === 'macos') {
      guide = (
        <div>
          <EuiText>
            <p>Deploy the installation</p>
            <EuiCodeBlock language="js">
              {macosText}
            </EuiCodeBlock>
          </EuiText>
        </div>
      );
    }
```

Good behavior 
```js
        {this.state.selectedOS === 'win' ? (
          <EuiText>
            <p>Deploy the installation</p>
            <EuiCodeBlock language="js">
              {winText}
        </EuiCodeBlock>
          </EuiText>
        ) : (<EuiFlexItem />)}
        {this.state.selectedOS === 'macos' ? (
          <EuiText>
            <p>Deploy the installation</p>
            <EuiCodeBlock language="js">
              {macosText}
            </EuiCodeBlock>
          </EuiText>
        ) : (<EuiFlexItem />)}
```

Finally this is the aspect that is currently almost finished. I still have to make the button to copy the code in the `EuiCodeBlock` works.

![image](https://user-images.githubusercontent.com/21195730/58630974-5792c600-82e1-11e9-8ed9-cc2d0f5090af.png)

**Comment by juankaromo** [comment]
**Update**

I implemented de copy function in this way:

https://github.com/wazuh/wazuh-kibana-app/blob/d7939e902365ac51e05a2df57281e0f12aee182e/public/components/register-agents.js#L24-L31

Now, the last point remaining is how to manage the no-agents scenario. We need to avoid this flick while it's searching agents and finally, there are not any agents yet:

![add-agents](https://user-images.githubusercontent.com/21195730/58641395-66867200-82fb-11e9-9b29-bcd32a0eb5d3.gif)

**Comment by juankaromo** [comment]
**Update**

The flick on the component shown has been fixed checking if the `lastAgent` is not empty (API call), instead of checking if the agents search result is empty (Elasticsearch query).  

On the other hand, the copy method that had implemented yesterday has been replaced by the `EuiCopy` eui native component.

**Comment by jesusgn90** [comment]
https://github.com/wazuh/wazuh-kibana-app/pull/1504#issuecomment-498292107

**Comment by jesusgn90** [comment]
https://github.com/wazuh/wazuh-kibana-app/pull/1504#pullrequestreview-245901084

**Comment by juankaromo** [comment]
**Update**

I've changed the multi instructions in every OS to leaving only the installation command.
