### ISSUE TITLE
Hang up when editing a CDB list value

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#1485]
In the Management / Ruleset / Lists section
If a value within a list is edited, accepted and then edited again the system will get stuck and not allow any more changes, except new additions, to be made without refreshing this section of the interface.
![cdb-list-edit-error](https://user-images.githubusercontent.com/36071202/58462952-368c7280-8133-11e9-8d0a-997b02f80741.gif)
Saving the list while in this state will save the values as shown. 

Hitting remove while in this state will remove all entries from the list, even ones that existed before the edit was done.

This has been observed both in Firefox and Chromium.

**Comment by adri9valle** [comment]
**Update**

This problem has been solved in https://github.com/wazuh/wazuh-kibana-app/pull/1566.

The problem was that when editing a value the `loadingChange` variable was set to **true** but when the edition has finished this variable was still **true** instead of **false**.

In the template, there is a condition to show a spinner instead of the pencil icon and this condition checks this variable:

```
<span ng-show="editingKey === item[0] && loadingChange">
    <i class="fa fa-fw fa-spin fa-spinner"></i>
</span>
```

This provokes that when click on the edition button at the second time always shows the spinner.

To solve this in the executed function after editing the value I added a line to set `loadingChange` to **false** again:

https://github.com/wazuh/wazuh-kibana-app/blob/2776b530e985114fca91148df7ce98d155dccf2d/public/directives/wz-list-manage/wz-list-manage.js#L197-L201

**Comment by adri9valle** [comment]
**Update**

This problem comes since 3.9.3 and will be solved in a PR with several fixes to the bugs related in this issue: https://github.com/wazuh/wazuh-kibana-app/issues/1568 that's why this  PR https://github.com/wazuh/wazuh-kibana-app/pull/1566 is closed.
