### ISSUE TITLE
Plugin wazuh [7.1.0] is incompatible with Kibana [7.1.1]

### ISSUE THREAD

**Issue by shawnbyday** [wazuh/wazuh-kibana-app#1491]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
|  3.9.1_7.1.0      |  7.1.1      | |

**Description**
Been waiting for Wazuh to hit compatibility with ELK7.0. you guys skipped to 7.1 so I decided to upgrade and I got upgraded to 7.1.1 and now I'm back to Wazuh not being compatible lol.

**Steps to reproduce**
`sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
Transferring 20946766 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin wazuh [7.1.0] is incompatible with Kibana [7.1.1]"
`
Wondering if you guys had started working on a patch for this or not? No rush. Thanks!

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by juankaromo** [comment]
Hi @shawnbyday 

The latest version supported by our app is ELK 7.1.0 and you can find it here: https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip

ELK 7.1.1 version was released yesterday, and as soon as we test its correct functioning with the plugin we will release a new version of our Wazuh app. 

Be careful because we will keep you informed here as soon as it is ready, which will be very soon.

Regards.

**Comment by jesusgn90** [comment]
https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.1.zip
