### ISSUE TITLE
Authorization problems with standard install

### ISSUE THREAD

**Issue by crankedguy** [wazuh/wazuh-kibana-app#1495]
Hi,

there seem to be a lot of problems if X-Pack security is enabled with your standard install.

Starting from an OS point of view on RHEL/CentOS systems one cannot install the plugin with your proposed sudo or 'su' commands. On these systems you cannot su to kibana as this user is created without any possibility to login automatically (which is ok from a security standpoint).

Then, if you have X-Pack security enabled the 'kibana' Elasticsearch user simply does not have enough rights to be used by the wazuh app. You are getting authorization errors both when starting up Kibana and also when you want to access the wazuh app in Kibana (it is not enough to login to Kibana with the 'elastic' user when you are running Kibana with the 'kibana' user.
The only way to workaround with a vanilla install is to use the 'elastic' (super)user both for running Kibana ... and in the Kibana UI.

Would you mind to provide the Kibana/Elasticsearch rights a user needs in order that the wazuh app works? Then a user could be created with these rights in Elasticsearch and could be used for running and logging in to Kibana without the need to use the 'elastic' superuser.

Running versions are Wazuh 3.9.1 and ELK 7.1.0

Would be great, thanks.

**Comment by jesusgn90** [comment]
Hi @crankedguy,

> Starting from an OS point of view on RHEL/CentOS systems one cannot install the plugin with your proposed sudo or 'su' commands. On these systems you cannot su to kibana as this user is created without any possibility to login automatically (which is ok from a security standpoint).

Next command works under RHEL/CentOS and it is the command we usually execute for installing the app:

```sh
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
Transferring 20946766 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation complete
```

The different command using `su -c` may have problems under certain OS:

```sh
su -c '/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip' kibana
This account is currently not available.
```

The first command is in our [documentation](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#kibana) and it's the recommended way by the Elastic team. The second command is just present in the repository [README.md](https://github.com/wazuh/wazuh-kibana-app/blob/master/README.md) because it may cause problems but some users from our community ask for including it at least in the readme file.

> Then, if you have X-Pack security enabled the 'kibana' Elasticsearch user simply does not have enough rights to be used by the wazuh app. [...] The only way to workaround with a vanilla install is to use the 'elastic' (super)user both for running Kibana ... and in the Kibana UI.

That's right, and why [our docs](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/protect-installation/xpack.html#adding-authentication-for-elasticsearch) are using the `elastic` user for all the components.

> Would you mind to provide the Kibana/Elasticsearch rights a user needs in order that the wazuh app works? 

Sure, in fact, our old documentation, related to Wazuh 3.8.x, had a guide for that purpose, [see guide](https://documentation.wazuh.com/3.8/user-manual/kibana-app/configure-xpack/defining-xpack-users.html), but with Wazuh 3.9 and Elastic 7 we decided to remove and create the [new docs](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/protect-installation/xpack.html#adding-authentication-for-elasticsearch) but we are working on a new guide for RBAC and granular roles, so you'll see it soon (I don't know a date so far).


Regards,
Jesús

**Comment by crankedguy** [comment]
Oh you are right about the sudo command, sorry on that, I missed something there it seems.

> Sure, in fact, our old documentation, related to Wazuh 3.8.x, had a guide for that purpose, see guide, but with Wazuh 3.9 and Elastic 7 we decided to remove and create the new docs but we are working on a new guide for RBAC and granular roles, so you'll see it soon (I don't know a date so far).

Great, thanks for the heads up.

Tom

**Comment by jesusgn90** [comment]
Hi @crankedguy,

Closing this ticket due to inactivity. Feel free to re-open it or to create a new one if needed.

Best regards,
Jesús
