### ISSUE TITLE
Wazuh plugin and Kibana 5.3.2 in CentOS7

### ISSUE THREAD

**Issue by toniblyx** [wazuh/wazuh-kibana-app#15]
Hi,
Following your official installation instructions for CentOS7, command "yum install kibana" installs Kibana 5.3.2 wich is not supported by your plugin as you can see here:

```
# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 16637026 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.3.2]; found [5.3.1]"
```
I looked at package.json inside the zip file and it looks like only "kibana": { "version" : "5.3.1" } is allowed. So it fails.

A workaround I used was as follows in case you may be interested:

```
yum erase -y kibana
curl https://artifacts.elastic.co/downloads/kibana/kibana-5.3.1-x86_64.rpm -o kibana-5.3.1-x86_64.rpm
yum localinstall -y kibana-5.3.1-x86_64.rpm
```
Right after that the plugin installation command completes without error.

It would be great if the plugin also supports 5.3.2 in order to make the installation process smoother. 

Cheers

**Comment by alberpilot** [comment]
Hello toniblyx

  Thanks for your feedback. Indeed, yesterday (27th April) a new release of kibana has come. When a new kibana version arrives, we immediately work on our Wazuh App in order to check all compatibilites. But sometimes our community are faster than us.

  So, a version 5.3.2 will be available really soon, then you will able to update your Kibana in order to have the last version installed. 

Best regards, 
Alberto
