### ISSUE TITLE
Unable to find message information in Kibana Logs

### ISSUE THREAD

**Issue by Parthasarathi7722** [wazuh/wazuh-kibana-app#1500]
Hi 
I am new to ELK stack and trying to use Wazuh for monitoring my internal servers. I was able to install and configure Wazuh successfully an added some dummy agents as well. Now I can see some information on dashboard but when drilling down to the logs unable to find message/ raw logs. I am attaching screenshots for reference, any help resolving the issue will be highly appreciated.

Regards
Partha 

<img width="1656" alt="Screenshot 2019-05-30 at 11 29 15 AM" src="https://user-images.githubusercontent.com/26519825/58612179-5062bc80-82cf-11e9-89d4-e92fe23e39b7.png">
<img width="1633" alt="Screenshot 2019-05-30 at 11 29 53 AM" src="https://user-images.githubusercontent.com/26519825/58612180-5062bc80-82cf-11e9-9df3-989bbacf3560.png">
<img width="1662" alt="Screenshot 2019-05-30 at 11 30 55 AM" src="https://user-images.githubusercontent.com/26519825/58612181-5062bc80-82cf-11e9-8779-63e76fc3aad8.png">
<img width="1662" alt="Screenshot 2019-05-30 at 11 31 53 AM" src="https://user-images.githubusercontent.com/26519825/58612182-5062bc80-82cf-11e9-957e-13608f90f602.png">

**Comment by jesusgn90** [comment]
Hi @Parthasarathi7722,

Wazuh creates two different indices every day. The first one is about the Wazuh alerts, those indices use the pattern `wazuh-alerts-3.x-*`, then the Wazuh app creates the second daily index using the pattern `wazuh-monitoring-3.x-*` and those indices are the agents status history.

The documents you are showing in your screenshots are related to `wazuh-monitoring-3.x-*` and I'm assuming you are on the Discover tab from Kibana. In order to see the alerts change the index pattern to `wazuh-alerts-3.x-*`:

![image](https://user-images.githubusercontent.com/8860227/58616042-ee995700-82bc-11e9-9ae9-a8ae05daa4cd.png)

All the alerts are not about log files, but here is an example of an alert from a log file:

![image](https://user-images.githubusercontent.com/8860227/58616166-42a43b80-82bd-11e9-8be0-033b1817e475.png)

I hope it helps.

Let us know.

Best regards,
Jesús

**Comment by Parthasarathi7722** [comment]
Hi Jesus,

Thank you for the quick response, as instructed I checked the alerts tab and unable to find any information. I am attaching two more screenshot could you check and let me know if I missed some configuration.

Regards
Partha 

<img width="1662" alt="Screenshot 2019-05-30 at 1 33 56 PM" src="https://user-images.githubusercontent.com/26519825/58618871-3f22ab80-82e1-11e9-910f-2c9851eaec40.png">
<img width="1662" alt="Screenshot 2019-05-30 at 1 39 27 PM" src="https://user-images.githubusercontent.com/26519825/58618872-3f22ab80-82e1-11e9-9036-30b81a744c76.png">
<img width="1662" alt="Screenshot 2019-05-30 at 1 40 05 PM" src="https://user-images.githubusercontent.com/26519825/58618873-3f22ab80-82e1-11e9-92f0-8a6dc2e754ac.png">

**Comment by jesusgn90** [comment]
Hi @Parthasarathi7722,

As I can see here:

![image](https://user-images.githubusercontent.com/8860227/58635235-a6465d00-82ed-11e9-9ac6-d3b5a123a600.png)

Your `wazuh-alerts` indices have no data yet.

But looking at your screenshot it seems like you commented the `output.elasticsearch` section:

![image](https://user-images.githubusercontent.com/8860227/58635458-3f757380-82ee-11e9-85d5-ca75ce5373c5.png)

Are you using Logstash? If not the case, your Filebeat configuration output section should look like the next one:

```yml
output.elasticsearch:
  hosts: ['http://YOUR_ELASTIC_SERVER_IP:9200']
  indices:
    - index: 'wazuh-alerts-3.x-%{+yyyy.MM.dd}'
```

Reference: https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/filebeat/7.x/filebeat.yml

Once fixed, restart the Filebeat service.

Best regards,
Jesús

**Comment by Parthasarathi7722** [comment]
Hi Jesus, 

I modified the file and restarted filebeat even-though it's not working.

Regards
Partha :-(

**Comment by Parthasarathi7722** [comment]
Hi Jesus,
I fixed the issue by binding service to the localhost. Appreciate your help.

**Comment by jesusgn90** [comment]
You are welcome
