### ISSUE TITLE
Menu directive is hidden when the route changes

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1502]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
|  3.x      |  6/7      | n/a |

**Description**
Menu directive is hidden when the route changes.

**Steps to reproduce**
Let's say you are in Wazuh > Overview, now click on Wazuh > Management, the menu directive is hidden until the new controller loads.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/58618927-00cac380-82c4-11e9-807a-ea1ccd49b3d6.png)

**Proposal**
The menu directive should be persistent regardless of the route.

**Comment by adri9valle** [comment]
**Update** 

I tried to load the `.pug`file in an HTML to test if it was a rendering problem of the templates since DevTools does not use pug is a simple HTML file and the problem does not occur here.

I have tried to put the content of the `.head` into a `<md-content>` except the `wz-menu`.

I've simplified everything to a simple HTML file that only contains the `wz-menu` simulating the DevTools HTML and keeps blinking.

I'm trying to make all `.pug` files inherit from one but I think I would need a controller to manage which section it is in and depending on that select a title in the `wz-menu` and load the corresponding `.pug`.

**Comment by adri9valle** [comment]
**Update**

I've tried to create nested templates with `ngView`  in order to the main template always contents the `wz-menu` directive.

Also, I tried to use `ng-include` instead of `include` and I change `{file}.pub` by `{file}.html` but is not working either.

**Comment by adri9valle** [comment]
**Update**

I changed `overview.pug` by single HTML file that contents all overview HTML files content and the menu is hidden when changing between sections.

**Comment by adri9valle** [comment]
**Update**

I set the `resolve` of DevTools route in all routes to check if this could be provoking the flick, but this change provokes several errors while navigating through the app.

**Comment by adri9valle** [comment]
**Update**

I've tried to extend all the pug from a template that only has the `wz-menu` but does not work either.

Pug documentation: https://pugjs.org/language/inheritance.html

**Comment by adri9valle** [comment]
**Update**

I thought in change the routing system to [ui-router](https://ui-router.github.io/ng1/) which permits use nested states and views, but while working on this I realized that the change will be huge.

Also, I've tried to use `ng-view` again but Kibana loads the Wazuh plugin with its loader and cannot use an index.html to implement ng-view.

**Comment by adri9valle** [comment]
**Update**

I've tried to use `ng-include` in an index template to modify the `wz-menu` directive in order to change the `ng-include` value to load the respective templates, I receive this error:

![image](https://user-images.githubusercontent.com/7983984/59909144-4ab05080-940f-11e9-9654-0f237c698472.png)

But the template is loaded:

![image](https://user-images.githubusercontent.com/7983984/59909214-6f0c2d00-940f-11e9-8d33-d3e614381911.png)

Now, I'm trying to fix this problem, I think that if I could load the respective templates and changing the  behavior of the `wz-menu` directive is possible to fix this problem.

**Comment by adri9valle** [comment]
**Update**

I've tried several ways to load the other controllers inside the main controller in order to the `wz-menu` directive is always visible but any way works fine.

I created an index template and the main controller:

##### Template 

![image](https://user-images.githubusercontent.com/7983984/59916755-51938f00-9420-11e9-967b-5761f2d8cbff.png)

Any method worked properly.

##### Main controller

![image](https://user-images.githubusercontent.com/7983984/59916876-aafbbe00-9420-11e9-82e8-3b0048a8f80e.png)

I tried to import in the controllers the HTML and PUG templates, from the HTML templates I receive the HTML code but when I used `ng-bind-html` doesn't work, from PUG templates I received an object:

![image](https://user-images.githubusercontent.com/7983984/59917008-fc0bb200-9420-11e9-8749-3a934bc4642f.png)

At the moment, no methods work properly.

**Comment by adri9valle** [comment]
**Update**

I loaded **ui-router** in the `app.js`: https://github.com/wazuh/wazuh-kibana-app/commit/c1e0d4963df03596fee6acc71e240a27eb324039.

Now I load **ui-router** only in the `routes.js` and I'm trying to create a simple route:

![image](https://user-images.githubusercontent.com/7983984/60025953-fd481380-969a-11e9-84b7-5dbbb314ed51.png)

But when accessing the App I receive the following error:

![image](https://user-images.githubusercontent.com/7983984/60025999-14870100-969b-11e9-8465-fb9b82e59a77.png)

**Comment by adri9valle** [comment]
**Update** 

The error found in the previous comment is provoked because **ngRoute** is not loaded and when trying to access to **$route** fails: 

![image](https://user-images.githubusercontent.com/7983984/60027353-9841ed00-969d-11e9-9556-9b5e0776a900.png)

Once is removed **$route** this error disappears but I get these others:

```
[$injector:modulerr] Failed to instantiate module kibana due to: Error: [$injector:modulerr] Failed to instantiate module app/wazuh due to: TypeError: Cannot read property 'otherwise' of undefined 
```

This error comes from: 

![image](https://user-images.githubusercontent.com/7983984/60028795-43ec3c80-96a0-11e9-8b94-26c61ed974cc.png)

**Comment by adri9valle** [comment]
**Update**

The error `[$injector:modulerr] Failed to instantiate module kibana due to: Error: [$injector:modulerr] Failed to instantiate module app/wazuh due to: TypeError: Cannot read property 'otherwise' of undefined ` of the previous comment was solved, the **$urlRouterProvider** was not injected that's why it was undefined.

**Comment by adri9valle** [comment]
**Update**

I've made that a simple route works:

![image](https://user-images.githubusercontent.com/7983984/60083567-3da89f80-9736-11e9-9bd0-fb3e1cb91d5b.png)
![image](https://user-images.githubusercontent.com/7983984/60083608-531dc980-9736-11e9-84a0-1d2d2a70a72a.png)

The resolve is executed properly:

![image](https://user-images.githubusercontent.com/7983984/60083783-a2fc9080-9736-11e9-8028-3ed273948a18.png)

But when trying to load the template fails:

![image](https://user-images.githubusercontent.com/7983984/60083895-d50df280-9736-11e9-9994-59042dccab6a.png)

I'm trying to solve this.

**Comment by adri9valle** [comment]
**Update**

The `templateUrl` parameter fails because expects a file, but we are using:

```
import devToolsTemplate from '../templates/dev-tools/dev-tools.html';
```

And when using **devToolsTemplate** variable in the `templateUrl` this var contains the HTML code not the link to the file.

If I use the path `../templates/dev-tools/dev-tools.html'` still generating an error because the file is not found:

![image](https://user-images.githubusercontent.com/7983984/60107396-2a61f800-9767-11e9-923d-065534016146.png)

**Comment by adri9valle** [comment]
**Update**

I've been experimenting with JQuery in order to append to the Kibana navbar a div with the `wz-menu` below it.

This menu won't disappear when changing the view but we have a problem, the menu is not now in the scope of angularjs and is necessary to change its logic.

![image](https://user-images.githubusercontent.com/7983984/60173637-7d8f8580-980f-11e9-839f-0f3d8dd096d5.png)

**Comment by adri9valle** [comment]
**Update**

Now is possible to navigate without losing the `wz-menu` but the previously commented problems persist:

![menu](https://user-images.githubusercontent.com/7983984/60175290-6d79a500-9813-11e9-873b-2fd31a8bcb66.gif)

**Comment by adri9valle** [comment]
**Update**

The menu does not disappear while changing view only the select API and index pattern for a while.

![nohide](https://user-images.githubusercontent.com/7983984/60181632-ed5b3b80-9822-11e9-8d6e-3419d36502e9.gif)

**NOTE**: Missing icons.

**Comment by adri9valle** [comment]
**Update**

The menu icons were added. Also, were solved several problems with the margins after change the `wz-menu` style.

![nohide](https://user-images.githubusercontent.com/7983984/60186061-5e065600-982b-11e9-906a-a9524dcbd5da.gif)

**Comment by adri9valle** [comment]
**Proposal**

Add the Wazuh logo to the header nav bar:

![image](https://user-images.githubusercontent.com/7983984/60187475-ef76c780-982d-11e9-8f64-177ac66ab111.png)

**Comment by adri9valle** [comment]
**Update**

The logic which makes that the `wz-menu` does not disappear was exported to an external file in order to clean the `app.js`.

Now only is necessary to import a function and execute it:

```
import { changeNavBar } from './utils/pin-wz-menu.js';
```

**Comment by adri9valle** [comment]
**Update 30.07.19**

I merged with 3.10-7.2 and resolved the conflicts. Also, I adapted to the dark mode theme and test it in the following browsers:

- Google chrome.
- Mozilla firefox.

**Comment by juankaromo** [comment]
**Update 13/08/2019**

All previous logic has been deleted. We have abandoned the solution approach using jQuery.

What has been done now is to use Kibana's `setRootTemplate` method. This method alters the root template through which the plugin is instantiated. This root template simply consists of an `<ng-view>` that loads the angular application and is affected by the routing module.

The solution we are going to adopt then is to take the `wz-menu` directive out of this `ng-view`, so it will not be affected when changing the route.

This is done here:

https://github.com/wazuh/wazuh-kibana-app/blob/7568e6d88a3d20ab4658140d94c2f78c350a4974/public/app.js#L91-L94

And that's what it looks like now:

![navigateionmenu](https://user-images.githubusercontent.com/21195730/62946569-3b32ff80-bde1-11e9-917a-e3384daaefcf.gif)

**Comment by juankaromo** [comment]
**Update 14/08/2019**

Today I've fixed some minor things:

- Now, when we enter for the first time to de app, the suitable section is set as active in the wz-menu (first access or healt-check -> Overview, F5 o refresh the page -> previous location).
- Now, the wz-menu is not being shown when health-check is performing.
- I fixed some styles to adapt it to all browsers.
- Wazuh logos have been changed to adapt them to the new corporative colors.

**Comment by jesusgn90** [comment]
I've already merged https://github.com/wazuh/wazuh-kibana-app/pull/1558 @juankaromo but we still need some changes before closing this ticket:
1. Keep the old background color for the app.
2. Fix the menu size, not it differs from the Kibana left menu alignment, this was fixed previously and broken here.
3. Keep the health check sizes, as usual, the new logo is cool, but the size of it, and the size of the checks are not fine.

**Comment by juankaromo** [comment]
Hi **@jesusgn90** 

1, 2 and 3 have been solved here: https://github.com/wazuh/wazuh-kibana-app/pull/1696/commits/513162c1aa670b2df907c75244e5231ada40a42f

4 I have not been able to replicate it. I will continue to investigate and debugging it.

**Comment by juankaromo** [comment]
**Update**

The 4th point has been fixed calling the initialization of the `wz-menu` controller after the main `app.js` execution, in order to load the menu data when the app is already loaded.
