### ISSUE TITLE
No log, event in Kibana after Update

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-kibana-app#1514]
Hi,
Yesterday I do a update of my Kibana, Logstash, Elasticsearch. I hava wazuh 3.9.1 and I do a update to 7.1.1 of Kibana, Logstash and Elasticsearch since this update in my web inteface Kibana in Security Event they are nothing, no log, but the event continue to send in our SIEM. The elasticsearch is running, logstash too, the index is green or yellow but ok.  Can you help me please ? 

Bests regards

**Comment by juankaromo** [comment]
Hi @John33000 

On new Elastic 7.X Logstash is no longer required in Wazuh architecture if you don't have to perform any data transformation, and now, Filebeat is the tool on the Wazuh server that securely forwards alerts and archived events to Elasticsearch.

So, if you are sure that you are still generating alerts (you can check it in the alerts.json file `cat /var/ossec/logs/alerts/alerts.json`), you have to configure Filebeat to start sending this alerts to Elasticsearch.

Here you can find how to install and configure Filebeat to forward alerts (on centos) from scratch https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm_centos.html#installing-filebeat

And to keep your environment clean, and if you don't need Logstash, you can uninstall it.

Let us know the results.

Regards,

**Comment by John33000** [comment]
Hi @juankaromo 
I see alert in alerts.json. 
I follow your link and I do the step for filebeat , I restart kibana and always nothing in web interface. I uninstall logstash.

**Comment by John33000** [comment]
Now I have this error in Kibana ; 

Discover: Request Timeout after 30000ms

 Less Info
OK
SearchError: Request Timeout after 30000ms
    at http://X.X.X.X:5601/bundles/commons.bundle.js:3:1196465
    at processQueue (http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:199687)
    at http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:200650
    at Scope.$digest (http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:210412)
    at http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:212944
    at completeOutstandingRequest (http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:64425)
    at http://X.X.X.X:5601/built_assets/dlls/vendors.bundle.dll.js:427:67267

**Comment by juankaromo** [comment]
Hi @John33000 

It appears that Elasticsearch is down or that Kibana is not able to communicate properly with Elasticsearch.

Please, check if Elasticsearch is running please:

`systemctl status elasticsearch`

If it's running, let's do another check. This is commonly caused by a heavy request to Elasticsearch, Kibana tries until 30 seconds, then it shows timeout.

We can try to check the status and if your indices are so large for a single request:

`curl "<elastic_ip>:9200/_cat/indices?v=true&s=docs.count:desc" -s | head -10`

What we are doing with that command is getting an index list, where we can see the number of events store per index. We are also sorting that list and showing just the top 10 results.

That command should be useful to determine if we have very large indices or not.

And finally, could you copy and paste the output of the following command:

`cat /var/log/elasticsearch/<your-cluster-name>.log | grep -E "(ERROR|WARN|CRITICAL|FATAL)"`

Regards,

**Comment by John33000** [comment]
Hi @juankaromo 

Elasticsearch is running  I have just a message who say :

**Comment by Zenidd** [comment]
Hello @John33000,

It's possible that some of Kibana's indices are corrupt. Please paste here the output of this command:
```
# curl <elastic_ip>:9200/_cat/health
```

That command should be useful to determine if we have some corrupt index.
<br></br>
Greetings,

Juan Pablo Sáez

**Comment by John33000** [comment]
Hi,
The problem is resolve, we downgrade version from 7.1 to 6.8. Thanks you I close the issue.
