### ISSUE TITLE
Do not show unsupported modules in agents depending on the OS

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1524]
| Wazuh | Elastic | Rev |
|-----------|----------|-------|
|  3.9      |  6/7      | n/a |

**Description**
Some sections such as the welcome screen of an agent and its configuration are showing unsupported modules. Our community might think that a Windows agent can use Vulnerability detector for example (it will, but not so far)

**Steps to reproduce**
1. Go to "Agents"
2. Click on an agent that is not a Linux agent

**Screenshots**
For example, for a Windows agent:

![image](https://user-images.githubusercontent.com/8860227/59205201-b6d6bd00-8ba2-11e9-9c78-3f07a361b60b.png)

**Proposal**

Properly filter modules and their related configuration depending on the agent OS.

**Comment by juankaromo** [comment]
**Update**

There's the list of supported modules from the different OS:

Linux: OpenScap, Audit, Vulnerabilities and Docker.
Whodata is supported by Windows too, but the method is different that's why Audit is not enabled in Windows.
Vulnerability detection actually only supports RedHat/Centos, Debian, Ubuntu, and Amazon Linux, this means that it is only enabled for Linux agents.
Docker is only supported by Linux natively, that's why docker-listener module is only for Linux now.
The rest of the modules are supported by all OS.

**Changes**
In Management > Configuration for non-Linux agents, we should hide OpenScap and Docker Listeners that actually are shown.

In a Windows or MacOs agent the welcome view must not have Vulnerabilities or Docker listener.

**Problem to be taken into account**
When you are a Windows or MacOs agent and have VirusTotal and OsQuery disabled, the welcome card appears empty.

![image](https://user-images.githubusercontent.com/21195730/59284415-80657480-8c6c-11e9-8dbe-c9aa61f5c696.png)

**Comment by juankaromo** [comment]
**Update**

**Thread Detection and Response** card were empty in Windows or Mac agents if any extension was enabled. Now, an empty alert is shown to alert the user to enable the available extensions.

![image](https://user-images.githubusercontent.com/21195730/59340591-94f64b00-8d06-11e9-9b73-7cce2e5e5527.png)

**Comment by juankaromo** [comment]
**Update**

The code has been refactored for clarity, and a new importable object has been included that establishes a component-operating system compatibility matrix. With it, we can check if a component or module is supported by a certain agent and thus show it or hide it. This is done with checks such as this one:

`ComponentsOsSupport[component].includes(agent.agentOS)`

**About removing the welcome card**

By studying the case that all the elements of a welcome card were not compatible with the operating system, and if it would be necessary to remove the welcome card completely, we have come to the conclusion that FOR THE MOMENT there is no section that for a certain operating system does not have any component supported.

For example, the card `THREAT DETECTION AND RESPONSE` will always have at least the extension `Virus Total`, as it is supported by all platforms.
