### ISSUE TITLE
add search/discover logs to "Overview / Integrity monitoring" dasboard

### ISSUE THREAD

**Issue by petersutty** [wazuh/wazuh-kibana-app#1527]
it would be great if I could at the bottom of the dashboard see all the relevant logs - so I can see what files changed and what was the actual diff/change (and I can filter based on hostname, file name etc.)

**Comment by adri9valle** [comment]
Hi @petersutty,

Thank you very much for your suggestion! 
We are always listening to the community looking to improve the product. We will study it to try to include it in our roadmap.

Regards,

Adri,

**Comment by jesusgn90** [comment]
Hi @petersutty, we've added a new table visualization with the agent name, the path and the action occurred. For more in deep details just click on "Discover" button for that dashboard so you can fully search across your alerts. The table itself can show certain fields only due to efficiency and the different operative systems we support. Some users might not see anything in the table depending on the fields being used, that's why we've added agent name, path, and actions only.
