### ISSUE TITLE
Error fetchings agents on "Agents" page

### ISSUE THREAD

**Issue by july207** [wazuh/wazuh-kibana-app#1540]
Hi,
We have installed Wazuh plugin 3.9.2 on Kibana 7.1.1
We have only a problem when we clicked on the "Agents" page with an error :

 Error fetching agents : 4004 - Not Found

![image](https://user-images.githubusercontent.com/10080547/59850531-c3a99c80-936a-11e9-9621-09e7238ef18c.png)

We have checked with Management -> Group -> Agent and all of agents deployed works well.

Please kindly advise.

**Comment by juankaromo** [comment]
Hi @july207 

That error is occurring because the app is trying to make a request on an index-pattern that it is not finding (**fa3b...**). This seems to be happening because you are using a custom space (**viia**) and that index-pattern it doesn't find was created in the default space.

Since Kibana introduced the custom spaces, the Wazuh app doesn't have the right behavior inside them, and at the moment we must use default space. Anyway, we have an open issue that already has the testing done and probably in future versions of Wazuh this is fixed. Here it is https://github.com/wazuh/wazuh-kibana-app/issues/1234

Try to work from the default space and tell us if everything works correctly. And any other question you have let us know.

Greetings!

**Comment by july207** [comment]
Thanks @juankaromo for your help,
We fixed this problem by importing the index pattern from the "Default" space.
