### ISSUE TITLE
Question about custom decoders and rules

### ISSUE THREAD

**Issue by NutellaPie** [wazuh/wazuh-kibana-app#1545]
Hi, I'm trying to create custom decoders and rules for Palo Alto Firewall. I'm new to this, and I'm only referring to one link that mentions about it [https://groups.google.com/forum/#!topic/wazuh/WuUharFMINU](url). I'm trying to create custom decoders and rules for different types of logs (Traffic, Configuration and System) but I don't think that I will use all the fields of the log. Thus, is there a way to skip certain fields instead of creating a regex expression for every field?

For example, the traffic log fields are as follows:
`FUTURE_USE, Receive Time, Serial Number, Type, Threat/Content Type, FUTURE_USE, Generated Time, Source IP, Destination IP, NAT Source IP, NAT Destination IP, Rule Name, Source User, Destination User, Application, Virtual System, Source Zone, Destination Zone, Inbound Interface, Outbound Interface, Log Action, FUTURE_USE, Session ID, Repeat Count, Source Port, Destination Port, NAT Source Port, NAT Destination Port, Flags, Protocol, Action, Bytes, Bytes Sent, Bytes Received, Packets, Start Time, Elapsed Time, Category, FUTURE_USE, Sequence Number, Action Flags, Source Location, Destination Location, FUTURE_USE, Packets Sent, Packets Received, Session End Reason, Device Group Hierarchy Level 1, Device Group Hierarchy Level 2, Device Group Hierarchy Level 3, Device Group Hierarchy Level 4, Virtual System Name, Device Name, Action Source, Source VM UUID, Destination VM UUID, Tunnel ID/IMSI, Monitor Tag/IMEI, Parent Session ID, Parent Start Time, Tunnel Type, SCTP Association ID, SCTP Chunks, SCTP Chunks Sent, SCTP Chunks Received`

I would only want to create regex expressions within the <regex> tag for fields such as Receive Time, Serial Number and maybe Source and Destination Location. Is there a way to "skip" the fields which are not needed so that regex can only identify these 4 fields?

Thank you so much!

**Comment by adri9valle** [comment]
Hi @NutellaPie,

Yes, in the regex you can choose which fields will be selected. I go to use a simple example of our official documentation about how to [add new decoders and ruels](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#adding-new-decoders-and-rules).


The log is `Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'`

And the decoder:

```
<decoder name="example">
  <program_name>^example</program_name>
</decoder>

<decoder name="example">
  <parent>example</parent>
  <regex>User '(\w+)' logged from '(\d+.\d+.\d+.\d+)'</regex>
  <order>user, srcip</order>
</decoder>
```

To test the decoder we can use `/var/ossec/bin/ossec-logtest`.

```
# /var/ossec/bin/ossec-logtest 
2019/06/24 11:13:16 ossec-testrule: INFO: Started (pid: 22065).
ossec-testrule: Type one log per line.

Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'User 'admin' logged from '192.168.1.100''

**Phase 2: Completed decoding.
       decoder: 'example'
       dstuser: 'admin'
       srcip: '192.168.1.100'
```

As you can see the **user** and the **IP** match properly and the fields are extracted. Both fields were matched and assigned to a field because we used a regex between parentheses `()`. If you need to match some field but you are not interested in including this field into the alert you only need to use the regex without parentheses.  

Now the log is `Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100' with the id: 23` and the decoder is:

```
<decoder name="example">
  <program_name>^example</program_name>
</decoder>

<decoder name="example">
  <parent>example</parent>
  <regex>User '(\w+)' logged from '\d+.\d+.\d+.\d+' with the id: (\d+)</regex>
  <order>user, id</order>
</decoder>
```

The output of the `ossec-logtest`:

```
[root@master wazuh]# /var/ossec/bin/ossec-logtest 
2019/06/24 12:01:13 ossec-testrule: INFO: Started (pid: 24492).
ossec-testrule: Type one log per line.

Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100' with the id: 23


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100' with the id: 23'
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'User 'admin' logged from '192.168.1.100' with the id: 23'

**Phase 2: Completed decoding.
       decoder: 'example'
       dstuser: 'admin'
       id: '23'
```

As you can see the `IP` filed match but is not extracted because is not between parentheses.

I hope it helps you if you need more help please don't hesitate to ask again.

Regards,

Adri,

**Comment by NutellaPie** [comment]
Hi @adri9valle 

Thank you so much for your help! I have another question, is there a way to add child decoders to child decoders? This is because between the Palo Alto logs I'm receiving, there are several different types of log format. Currently I'm working with Traffic, System and Config logs. All 3 of them have some fields in common at the start, but will have different fields at the back. Thus, I'm trying to create child decoders for each individual log after decoding the fields which all 3 of them have in common (as seen in the screenshot below)

<img width="564" alt="Capture" src="https://user-images.githubusercontent.com/47778098/60082747-f4bd0f00-9766-11e9-8d1c-039df9bd2ed4.PNG">

**Comment by adri9valle** [comment]
Hi @NutellaPie 

You cannot have a child decoder from another child decoder but you can have several child decoders from the same parent decoder.  I guess that you want to follow matching from a child decoder in another child decoder if the log contents match with the *"sub-child"*. How I said this is not possible but you can create two or more child decoders with the same name that each one matches with different logs, for example:

```
<decoder name="example">
  <program_name>^example</program_name>
  <prematch>User</prematch>
</decoder>

<decoder name="example-child">
  <parent>example</parent>
  <regex offset="after_parent">^ '(\w+)' logged from '(\d+.\d+.\d+.\d+)'</regex>
  <order>user, srcip</order>
</decoder>

<decoder name="example-child">
  <parent>example</parent>
  <regex offset="after_parent">^ '\w+' logged from '\d+.\d+.\d+.\d+' with id '(\d+)'</regex>
  <order>id</order>
</decoder>
```

After creating the previous decoders we go to test the following logs:
- Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10'
- Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10' with id '037'

```
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'User 'admin' logged from '192.168.1.10''

**Phase 2: Completed decoding.
       decoder: 'example'
       dstuser: 'admin'
       srcip: '192.168.1.10'
```
```
Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10' with id '037'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.10' with id '037''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'User 'admin' logged from '192.168.1.10' with id '037''

**Phase 2: Completed decoding.
       decoder: 'example'
       dstuser: 'admin'
       srcip: '192.168.1.10'
       id: '037'
```

As you can see this works properly but you need to match again all fields in the following child decoders, please be careful with the regex and the order of the child decoders, if in the regex of the first child was extracted a field in the following child decoders is not necessary to extract this field again, to prevent this don't use parenthesis  in the following child decoders because if you use it the fields that match on each decoder will be repeated.

![image](https://user-images.githubusercontent.com/7983984/60088932-cc6dea00-973f-11e9-8b24-1c19973fce2b.png)

I hope it solves your problem if you still have doubts please don't hesitate to ask again.

Regards,

Adri,

**Comment by NutellaPie** [comment]
Hi @adri9valle 

Thank you so much for your help. I am now identifying the type of logs based on the field tag in the local rules. However, I am having some problems with creating some regular expressions. I have read from the documentation [https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/regex.html](url) that alteration in a group is not permitted. For example, I am trying to fit a regex expression where the accepted fields are either "vsys<number>" OR nothing (e.g. ,,) [nothing between the commas]. I am also trying to match between a set of words (e.g. match either _informational_, _low_, _medium_, _high_, or critical ONLY). Would this be possible? Thank you!

**Comment by adri9valle** [comment]
Hi @NutellaPie 

In order to give you better assistance please, could you send me an example log that contains these fields?

But from what I understand you cannot match in the decoder `(informational|low|medium|high|critical)` as you could see in our official documentation this is not possible. However, there is an alternative, you could create a decoder which matches this as string `(\w+)` and in the rule process with a **var** in order to check if is any of these possible values. 

##### Example log: 
```
Dec 25 20:45:02 MyHost example[12345]: Log type medium received
```

#####  Decoder:
```
<decoder name="example">
  <program_name>^example</program_name>
  <prematch>Log</prematch>
</decoder>

<decoder name="example-child">
  <parent>example</parent>
  <use_own_name>true</use_own_name>
  <regex offset="after_parent">^ type (\w+) received</regex>
  <order>severity</order>
</decoder>
```

#####  Rule:
```
<var name="severity">informational|low|medium|high|critical</var>

<group name="test">
  <rule id="100015" level="3">
    <field name="severity">$severity</field>
    <description>Test.</description>
  </rule>
</group>
```

As you can see in the previous code block, there is a **var** that contains several possibilities if you use this **var** the rule will check if matches in order to generate an alert or not, you can test this in `ossec-logtest`:

![image](https://user-images.githubusercontent.com/7983984/60160333-6e9bd980-97f5-11e9-906e-b768777a5c3e.png)

The severity matches and the alert will be generated.

![image](https://user-images.githubusercontent.com/7983984/60160387-90955c00-97f5-11e9-850b-53a738671bae.png)

As you can see in the previous image the decoder matches the event log but the rule not, then the alert won't be generated.

I hope it helps if you have more doubts please don't hesitate to ask again.

Regards,

Adri,

**Comment by NutellaPie** [comment]
Hi @adri9valle 

Here is my local_decoders.xml file. 
```xml
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015-2019, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>

<!-- Custom decoder for PaloAlto Firewalls Events -->  
<decoder name="paloalto">  
    <prematch>,\d\d\d\d\d\d\d\d\d\d\d\d,</prematch>
</decoder>

<!-- Child decoder for common fields between PAN FW logs -->
<decoder name="paloalto-common">
    <parent>paloalto</parent>
    <use_own_name>true</use_own_name>
    <regex offset="after_parent">^(\w+),(\w+),\S+,(\d\d\d\d/\d\d/\d\d \d\d:\d\d:\d\d)</regex>
    <order>pacommon.type,pacommon.stype,pacommon.gtime</order>
</decoder>

<!-- Child decoder for PAN FW traffic logs -->
<decoder name="paloalto-common">
    <parent>paloalto</parent>
    <use_own_name>true</use_own_name>
    <regex offset="after_parent">^\w+,\w+,\S+,\d\d\d\d/\d\d/\d\d \d\d:\d\d:\d\d,(\d+.\d+.\d+.\d+),(\d+.\d+.\d+.\d+)</regex>
    <order>patraffic.srcip,patraffic.dstip</order>
</decoder>

<!-- Child decoder for PAN FW system logs -->
<decoder name="paloalto-common">
    <parent>paloalto</parent>
    <use_own_name>true</use_own_name>
    <!-- <regex offset="after_parent">^\w+,\w+,\S+,\d\d\d\d/\d\d/\d\d \d\d:\d\d:\d\d,\w+|**a^**,\w+,\w+|**a^**,\S+,\S+,(general|management|auth|ha|upgrade|chassis),(informational|low|medium|high|critical),(\.+),(\d+)</regex> -->
    <regex offset="after_parent">^\w+,\w+,\S+,\d\d\d\d/\d\d/\d\d \d\d:\d\d:\d\d,,(\w+),,\S+,\S+,(\w+),(\w+),(\.+),(\d+)</regex>
    <order>pasystem.eventid,pasystem.module,pasystem.severity,pasystem.description,pasystem.seqno</order>
</decoder>
```

Thank you for your advice! I think I will be using var for those `(general|management|auth|ha|upgrade|chassis)` and `(informational|low|medium|high|critical)`. However, is there a way to match an expression, including to match "null"? (represented by **a^** above)

For example, `\w+|a^` to match A-Z, a-z, 0-9, ‘-‘, ‘@’, ‘_’ characters OR match null (nothing)

**Comment by adri9valle** [comment]
Hi @NutellaPie,

I'm glad that this helps you. 

>For example, \w+|a^ to match A-Z, a-z, 0-9, ‘-‘, ‘@’, ‘_’ characters OR match null (nothing)

A way to do this would be using the previous method and create different child decoders, one of them that matches `\w+` and the other the null.

For this example, we go to use the following example event logs:
- Dec 25 20:45:02 MyHost example[12345]: Example of critical log coming from '192.168.1.100'
- Dec 25 20:45:02 MyHost example[12345]: Example of log coming from '192.168.1.100'

Assuming that you want to match `critical`  or an empty string you will need to child decoders that extends from the same father decoder with different regex:

```
<decoder name="example">
  <program_name>^example</program_name>
  <prematch>Example</prematch>
</decoder>

<decoder name="example-child">
  <parent>example</parent>
  <regex offset="after_parent">^ of(\s*)log coming from '(\d+.\d+.\d+.\d+)'$</regex>
  <order>severity, srcip</order>
</decoder>

<decoder name="example-child">
  <parent>example</parent>
  <regex offset="after_parent">^ of (\w*) log coming from '(\d+.\d+.\d+.\d+)'$</regex>
  <order>severity, srcip</order>
</decoder>
```

As you can see both child decoders are very similar except when trying to match the content between **of** and **log**.

**NOTE**: `of(\s*)log` This regex is together not like `of (\w*) log` because `\s*` matches zero or more white spaces, then if you use `of (\s*) log` it will try to match as minimum two white spaces and the regex doesn't work properly.

Let's check the result:

##### Dec 25 20:45:02 MyHost example[12345]: Example of critical log coming from '192.168.1.100':

```
# /var/ossec/bin/ossec-logtest 
2019/06/27 08:12:58 ossec-testrule: INFO: Started (pid: 6909).
ossec-testrule: Type one log per line.

Dec 25 20:45:02 MyHost example[12345]: Example of critical log coming from '192.168.1.100'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: Example of critical log coming from '192.168.1.100''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'Example of critical log coming from '192.168.1.100''

**Phase 2: Completed decoding.
       decoder: 'example'
       severity: 'critical'
       srcip: '192.168.1.100'
```

##### Dec 25 20:45:02 MyHost example[12345]: Example of log coming from '192.168.1.100':

```
# /var/ossec/bin/ossec-logtest 
2019/06/27 08:14:23 ossec-testrule: INFO: Started (pid: 6922).
ossec-testrule: Type one log per line.

Dec 25 20:45:02 MyHost example[12345]: Example of log coming from '192.168.1.100'


**Phase 1: Completed pre-decoding.
       full event: 'Dec 25 20:45:02 MyHost example[12345]: Example of log coming from '192.168.1.100''
       timestamp: 'Dec 25 20:45:02'
       hostname: 'MyHost'
       program_name: 'example'
       log: 'Example of log coming from '192.168.1.100''

**Phase 2: Completed decoding.
       decoder: 'example'
       severity: ' '
       srcip: '192.168.1.100'
```

As you can see both decoders work fine. 

If you still have problems in order to provide better assistance please if you can send us an example log.

I hope it helps if you have more doubts, please don't hesitate to ask again.

Regards,

Adri,

**Comment by NutellaPie** [comment]
Hi @adri9valle 

Really sorry for the late response. I think my problems regarding writing the decoders has been solved. Thank you so much for your help! 👍

**Comment by greenbitlock** [comment]
how do you make the fields you created in the decoder appear in the kibana?

**Comment by frankeros** [comment]
Hi @greenbitlock 
maybe you need to refresh your `index pattern` from menú Kibana / Stack Management / Index Patterns  select your index pattern 
and refresh it. 
![image](https://user-images.githubusercontent.com/26828184/102344821-394ff200-3f7b-11eb-87b7-8002aaa0e94b.png)
But if you have any problem with this or another question, please open a new issue. This issue is closed.
Best!
