### ISSUE TITLE
Adapt Wazuh app for Kibana 7.2.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1551]
Hi team, Elastic stack 7.2.0 has been released. We need to adapt our app for Kibana 7.2.0.

Tasks:

- [x] Review broken things (https://github.com/wazuh/wazuh-kibana-app/issues/1553).
- [x] Adapt broken things to be working again (add comments in this ticket).
- [x] Testing (https://github.com/wazuh/wazuh-kibana-app/issues/1552).

References:

- Kibana 7.2.0 release notes
  - https://www.elastic.co/guide/en/kibana/7.2/release-notes-7.2.0.html
- Kibana 7.2.0 breaking changes
  - https://www.elastic.co/guide/en/kibana/7.2/breaking-changes-7.2.html
- Kibana 7.2.0 plugins API changes
  - https://www.elastic.co/es/blog/kibana-plugin-api-changes-in-7-2

**Comment by juankaromo** [comment]
**Update**

With all the fixes described here, dashboards are, at least, running.https://github.com/wazuh/wazuh-kibana-app/commit/5d183f79e0d2d386a9bf8e86dc269cd119d9ef3c

![image](https://user-images.githubusercontent.com/21195730/60193176-81cf9900-9837-11e9-9c21-6c08d54572c9.png)

Now we are going to make a first round of tests where we hope that more errors appear that we will have to solve.

**Comment by juankaromo** [comment]
**Update**

babel/polyfill must be imported on a Wazuh app production environment. To do this we need to import `babel-polyfill` as a dependency in `package.json`, and import `babel-polify` in `app.js`

**Comment by juankaromo** [comment]
**Update**

These 2 provider injection errors appear when entering a dashboard or discover in a development environment. However, in the production environment, they are not shown. 

![image](https://user-images.githubusercontent.com/21195730/60272253-18619000-98f4-11e9-9cbc-50547211383a.png)


For now let's leave it at that, as it does not affect the operation apparently.

**Comment by juankaromo** [comment]
**Update**

How we can check here https://www.elastic.co/es/blog/kibana-plugin-api-changes-in-7-2, `kbnSrc` directive has been removed from the Kibana core sources in the process of removing Angular from them.

That's why the paths of some of our images have been lost by not carrying the chromePath base that added kbnSrc.

To fix it I have created a directive that replicates the behavior of the old Kibana directive. 3be9a24974ceeb929816d018edea7701d9ed513e

https://github.com/wazuh/wazuh-kibana-app/blob/3be9a24974ceeb929816d018edea7701d9ed513e/public/directives/wz-src/wz-src.js#L16-L24

**Comment by juankaromo** [comment]
**Update**

The time picker in the cluster monitoring section is not displayed since 7.X. This is because the Kibana directive `kbn-global-timepicker` was deprecated.

From now on we are going to use the `wz-search-bar` as in the rest of the app (dashboards and discovers) but hiding the search bar (leaving only the time selector) if the view we are in is `cluster-monitoring`.
