### ISSUE TITLE
Agent ID not the same as given by the manager server

### ISSUE THREAD

**Issue by AshenOfValheru** [wazuh/wazuh-kibana-app#1571]
| Wazuh | Elastic 
| 3.9.1    | 7.1.1   

**Description**
Hi There,

I'm having an issue where i register an agent via the manager server using "manage_agents" and connect the agent using the key generated, no problem there.

However when i view the logs in Kibana the agent ID appears as a string such as "6a492aa0-65c4-44a8-a4b6-519fa1bd46cf" and not simply "001" etc. This means that when i go to the file integrity etc tabs the visualisations aren't there because it's expecting the "001", not what the agent has actually been allocated.

Any suggestions on how i can fix this?

Kind Regards,
Ashen

**Screenshots**
![image](https://user-images.githubusercontent.com/26899731/60589174-c1930500-9d90-11e9-9f09-5326c2a82737.png)
![image](https://user-images.githubusercontent.com/26899731/60589241-f1420d00-9d90-11e9-8342-e426bf00e2cf.png)

**Comment by AshenOfValheru** [comment]
Quick update on this, it's in fact every agent that displays the same ID, even though if i check them on the management server and in the agent overview on Kibana they do have specific ID's relating to them.

**Comment by adri9valle** [comment]
Hi @AshenOfValheru 

Are you using filebeat system module?

The field `agent.ephemeral_id` comes from this module:

![image](https://user-images.githubusercontent.com/7983984/60875258-c3017900-a239-11e9-8f02-6dac316d1278.png)

I think that you're exploring the `filebeat-7.2.0-x` indices.

Regards,

Adri

**Comment by AshenOfValheru** [comment]
Hi there, the agent type is coming up as filebeat but the index is pulling from the "archives" and "alerts". I've attached my filebeat input conf (with the output funnelling directly into logstash).

Everything else it pretty standard really, the logstash conf splits the input into two outputs for ES based off event_type (alerts going into one index and all_logs going into another).

I understand the manager server uses filebeat to direct the logs to logstash right? Or have i misconfigured something here?

Thank you for the help.

![image](https://user-images.githubusercontent.com/26899731/60886499-0f54b500-a24a-11e9-9195-70b8edf66286.png)

**Comment by AshenOfValheru** [comment]
Just to make things even weirder the logs themselves show the Agent ID as intended no problem. 

![image](https://user-images.githubusercontent.com/26899731/60887779-1c26d800-a24d-11e9-8849-313762cb08ed.png)

**Comment by adri9valle** [comment]
Hi @AshenOfValheru,

Could you please send me your logstash configuration?

Also, you need to know that with elasticsearch 7.x version logstash is not longer necessary although it can be used. If you don't need to transform the data I advise you to use filebeat in order to forward directly the events to elasticsearch.

Regards,

Adri,

**Comment by AshenOfValheru** [comment]
Hi @adri9valle,

Yep we did initially funnel straight into ES but we're looking to hook in a TIP to query logs to Threat Intel so went back to the Logstash model which would provide this.

Here's the conf at the mo:

![image](https://user-images.githubusercontent.com/26899731/60892806-ad02b100-a257-11e9-9345-469202ef4136.png)

**Comment by adri9valle** [comment]
Hi @AshenOfValheru,

You are splitting into two indices the events fetched from `alerts.json` and `archives.json`.

The first I warn you that enabled `logall` or `logall_json` option can consume a lot of disk space.  

Please, could you execute and paste here the output of the following command:

```
curl http://${your_elastic_ip:9200/_cat/indices
```

You should have several `wazuh-alerts-3.x-*` and `wazuh-all-3.x-*` indices.

If the indices are created that means that the events are being received by elasticsearch.

Also please check if there is any index called filebeat-7.1.1-*`.

Supposing that the selected indeces are `wazuh-alers-3.x-2019.07.12` and  `wazuh-all-3.x-2019.07.12` Please execute:

```
curl http://172.16.1.2:9200/wazuh-alerts-3.x-2019.07.12/_search?size=1
```

And

```
curl http://172.16.1.2:9200/wazuh-all-3.x-2019.07.12/_search?size=1
```

The `size=1` param sets the limit of the extracted documents to one.

Please paste here the output. 

Also, could you send me a complete with the "strange" id `6a492aa0-65c4-44a8-a4b6-519fa1bd46cf`? 

I'm waiting for the required information in order to help you.

Regards,

Adri,

**Comment by AshenOfValheru** [comment]
Hi Adri,

Thanks for the heads up yeah we're taking that into account and it allows us to mine deeper into the logs once an alert is triggered.

In regard to the indices i see both multiple instances of "wazuh-alerts-3.x-<Date>" and ""wazuh-all-logs-3.x-<Date>", there aren't any filebeat indices however.

There is also no modules currently enabled:
![image](https://user-images.githubusercontent.com/26899731/61120021-efb0cd00-a493-11e9-9118-84e3746e6979.png)

In regard to the Alerts Index Document: 
![image](https://user-images.githubusercontent.com/26899731/61124622-3821b800-a49f-11e9-93c2-7ad5e8e43bf7.png)

In regard to the All Logs Index:
![image](https://user-images.githubusercontent.com/26899731/61124821-e299db00-a49f-11e9-940c-07826ecdb56f.png)

In regard to the complete that you would like with the strange id, what's that referring to exaclty?

Regards,
Ashen

**Comment by adri9valle** [comment]
Hi Ashen,

I think that I know where is the problem, a work mate describes the problem here https://github.com/wazuh/wazuh-kibana-app/issues/1382#issuecomment-485755296.

Have you in your `filebeat.yml` something like this?:

```
processors:
  - decode_json_fields:
      fields: ['message']
      process_array: true
      max_depth: 200
      target: ''
      overwrite_keys: true
  - drop_fields:
      fields: ['message', 'ecs']
```

It seems that the `ecs` field is overwriting the `agent.*` fields of the Wazuh alert and replace the content with the filebeat information that's why the `ecs` field needs to be dropped. Then if you don't have this configuration block you need to add it to the `filebeat.yml` file in order to make it works properly.

Please check that and let me know if it works for you.

Regards, 

Adri

**Comment by AshenOfValheru** [comment]
Hi Adri,

It appears to already be in the filebeat.yml, please see attached:

`# Wazuh - Filebeat configuration file
filebeat.config.modules.path: /etc/filebeat/modules.d/*.yml
filebeat.inputs:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    fields:
     event_type: alerts
    fields_under_root: true
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true
  - type: log
    paths:
     - "/var/ossec/logs/archives/archives.json"
    fields:
     event_type: archives
    fields_under_root: true
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true

setup.template.json.enabled: true
setup.template.json.path: "/etc/filebeat/wazuh-template.json"
setup.template.json.name: "wazuh"
setup.template.overwrite: true

processors:
  - decode_json_fields:
      fields: ['message']
      process_array: true
      max_depth: 200
      target: ''
      overwrite_keys: true
  - drop_fields:
      fields: ['message', 'ecs', 'beat', 'input_type', 'tags', 'count', '@version', 'log', 'offset', 'type', 'host']
  - rename:
      fields:
        - from: "data.aws.sourceIPAddress"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.aws.sourceIPAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
  - rename:
      fields:
        - from: "data.srcip"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.srcip: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
  - rename:
      fields:
        - from: "data.win.eventdata.ipAddress"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.win.eventdata.ipAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b

# Send events directly to Elasticsearch
#output.elasticsearch:
#  hosts: ['http://192.168.15.18:9200']
#  #pipeline: geoip
#  indices:
#    - index: 'wazuh-alerts-3.x-%{+yyyy.MM.dd}'

# Optional. Send events to Logstash instead of Elasticsearch
output.logstash.hosts: ["192.168.15.23:5000"]
`

Does this look like what's expected in terms of the config? The only part we changed was grabbing the two inputs (alerts and archives) instead of just the one.

**Comment by AshenOfValheru** [comment]
Hey all,

Just wondering if we had an update on this one? Struggling to find the issue to be honest. Everything seems to be as it should based off the documentation but it's just not ingesting the Agent ID correctly.

Kind Regards,
Ashen.

**Comment by juankaromo** [comment]
Hi @AshenOfValheru 

It seems that this problem had no solution or answer for a long time. If the problem still persists, or you have another type of doubt, please open another issue.

Thank you very much and I'm sorry I didn't answer you.
