### ISSUE TITLE
Wazuh Overview getting Error in visualization

### ISSUE THREAD

**Issue by zakirpcs** [wazuh/wazuh-kibana-app#1580]
I am getting below error message while accessing Overview -> SCA tab of Kibana dashboard of Wazuh.
Saved "field" parameter is now invalid. Please select a new field.
Error in visualization "field" is a required parameter.

Please check below screenshot for better understanding. Also, note that my wazuh version is 3.9.3 and ELK version is 7.2.0.
![wazuh-sca-overview-error](https://user-images.githubusercontent.com/39796037/61029857-d9483a00-a3dd-11e9-9713-d1b00be2fbc2.png)
Can anyone help me to resolve this issue?

**Comment by jesusgn90** [comment]
Hi @zakirpcs,

Those errors are commonly caused by a wrong/missing template for Wazuh alerts in Elasticsearch. Have you followed our installation guide? Is it an upgrade from a different major (6.x to 7.x)?

- Wazuh manager, Filebeat and the template, [click here](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm_centos.html#installing-filebeat).
- For fresh installations, [this is the guide](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html).
- For upgrading from 6.x to 7.x, [read these docs](https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.html).

Already created indices won't change even if you fix the template, for those indices you need to reindex the index or to remove them if they are not needed.

Let us know your needs and your environment status.

Regards,
Jesús

**Comment by zakirpcs** [comment]
Hi @Jesús,
Thanks for your reply. Yes, it is has been upgraded from 6.X to 7.X. Also, note that already I reindex the index but no luck. So how can I resolve the issue?

My environment status is: 
OS: Red Hat 7.6
Architecture: 64 Bit
Wazuh Version: 3.9.3
ELK Version: 7.2.0

**Comment by jesusgn90** [comment]
Hi @zakirpcs ,

Sorry for the late response, are you still facing errors?

Wrong mapped indices must be reindexed, then I would suggest to remove the Kibana index pattern, and to restart Kibana service, the Wazuh app will create it again. The index pattern may be wrong due to the wrong mapping in the index.

If you are still in need of help, let me know if you are on the same versions you described in https://github.com/wazuh/wazuh-kibana-app/issues/1580#issuecomment-511169495.

You can check the template as follow:

```sh
$ curl http://elastic:9200/_cat/templates/wazuh
```

And you can check the mapping applied to an index using the next command:

```sh
$ curl http://elastic:9200/wazuh-alerts-3.x-2019.04.26/_mapping?pretty
```
Where _wazuh-alerts-3.x-2019.04.26_ is some index we want to check.

Regards,
Jesús
