### ISSUE TITLE
Kibana Siem no logs from endpoint

### ISSUE THREAD

**Issue by kenyjeanreyes** [wazuh/wazuh-kibana-app#1581]
I am currently using wazuh ran in virtual machine. https://documentation.wazuh.com/current/installation-guide/virtual-machine.html?highlight=machine

I could successfully access the Kibana server and added agents. I also got the logs from those agents. But when I was trying the SIEM app in Kibana, the logs aren't showing even after properly following the setup. How do I resolve this?

I installed Winlogbeat in my Windows7, but there was no data showing.

**Comment by juankaromo** [comment]
Hi @kenyjeanreyes 

Elastic SIEM is a component of the elastic environment but is not part of Wazuh. If you want to see the alerts that your Wazuh manager and your agents are reporting from the app, you have to access the Wazuh app in Kibana.

You can find it in right side menú

![image](https://user-images.githubusercontent.com/21195730/61108808-a193cd80-a483-11e9-87b1-bd56825c992c.png)

Once inside the app, please, can you confirm to me that you can see alerts inside the security events section?

![image](https://user-images.githubusercontent.com/21195730/61109102-5cbc6680-a484-11e9-97b4-77cc034856fd.png)

I'm waiting for your answer.

Best regards.

**Comment by kenyjeanreyes** [comment]
Thank you for answering. I already saw the logs from my agents. 

What I was trying is to use the SIEM of Kibana. I followed the instructions given in Kibana, yet it won't connect to the SIEM. I'm a little confused.

**Comment by kenyjeanreyes** [comment]
![image](https://user-images.githubusercontent.com/32659574/61111600-e8ee7e00-a4c4-11e9-81af-6105dac0f8e5.png)

whenever I get to the part where I setup the beats, I encounter this error.

**Comment by juankaromo** [comment]
Hi @kenyjeanreyes 

I've been replicating all the problems you report in the environment you tell me about (Wazuh OVA and Winlogbeat).

From what I see you are getting the error `connectex: No connection could be made because the target machine actively refused it`. This seems to be because the OVA machine does not allow Elasticsearch access to requests outside its network.

I've been running tests and I've managed to fix it using the following steps:

Add or modify the below config to `/etc/elasticsearch/elasticsearch.yml` in the Wazuh virtual machine:

```
network.host: 127.0.0.1
http.host: 0.0.0.0
```

Then restart elasticsearch

`systemctl restart elasticsearch`

Also, and to make sure it works, you can try this additional step: 

`systemctl edit elasticsearch` and adding 

```
[Service]
LimitMEMLOCK=infinity
```

Save the file and run `systemctl daemon-reload`

Now you can launch the Winlogbeat service and it should work. Here's a sample of how well it works in my environment:

![image](https://user-images.githubusercontent.com/21195730/61229937-5d295b80-a729-11e9-963c-3eb836a874d0.png)

I hope this helps and please let us know the results.
Regards.

**Comment by kenyjeanreyes** [comment]
Thank you very much!
