### ISSUE TITLE
[6.x] Dev-tools shows "self.getPosition is not a function" when debugging in browser

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1587]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 6.8     | 448 |

**Description**
Something is wrong in the latest 6.x app and the DevTools tab, it seems like a function is not being declared, or the scope of _this_ is not reachable.

**Steps to reproduce**

1. Go to DevTools
2. Open the dev tools from your browser
3. A fatal Kibana error appears

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/61112249-b4120500-a48b-11e9-8a5b-eb7aa8383cf8.png)

**Comment by juankaromo** [comment]
Hi team,

The getPosition method (in charge of calculating the position of the dev tools with respect to the window in order to restore it to a dynamic height) had disappeared. It seems to be due to some merge or cheery pick from 7.2. Also, the method of resizing the columns has been fixed because it did not take into account the width of the side menu of Kibana 6.8 (again because of 7.X).

Regards.

**Comment by juankaromo** [comment]
Hi team, 

As believed, the getPosition() method had been removed. It has been added again and everything works correctly by resizing the window.

https://github.com/wazuh/wazuh-kibana-app/blob/0d17edbb19cd644db4b8c06649e2c19ecebbc119/public/controllers/dev-tools/dev-tools.js#L632-L644

On the other hand, the method of resizing the columns has been corrected by adding the width of the Kibana sidebar to the calculation (215 px).

https://github.com/wazuh/wazuh-kibana-app/blob/0d17edbb19cd644db4b8c06649e2c19ecebbc119/public/controllers/dev-tools/dev-tools.js#L430

Regards.
