### ISSUE TITLE
Agents - Preview: Unexpected error. Please, report this error.

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#16]
`Kibana 5.3.1`, `Wazuhapp 2.0 5.3.1`

Error shows up when I navigate to the Agents tab. There is an error in the dev console as well.

![image](https://cloud.githubusercontent.com/assets/2720787/25522814/374f38c6-2bfc-11e7-923d-a768b61c1c62.png)

**Comment by rossengeorgiev** [comment]
After installing `X-pack` this error no longer happens and I see all the graphs. But `X-pack` is not listed as requirement?

**Comment by snaow** [comment]
Hi Rossen,

Sorry for late response.
X-pack is not a requirement of Wazuh, it could be integrated with Wazuh and
add so much value but it is not required.
The error you had is related to internal API communications and/or internal
SQLite DB.

We are currently working on improving the installation guide to prevent all
of first-startup and configuration errors.
Are you still on 5.3.2 or did you move to 5.4.0?

Thanks for the feedback and interest, please let us know if you find more
errors. Thanks!

**Comment by rossengeorgiev** [comment]
I am on `5.4.0` now. I just tested this again.

On my local dev kibana, I uninstalled `xpack` and restarted kbiana:

![image](https://cloud.githubusercontent.com/assets/2720787/25999367/c578f706-371c-11e7-8043-884563d4ec7f.png)

On my stagging env, practically identical, but with `xpack`:

![image](https://cloud.githubusercontent.com/assets/2720787/25999402/e22c4542-371c-11e7-98db-4405e3fd83d0.png)

**Comment by snaow** [comment]
Could you check for "Network" tab in the Chrome development tool? I would
like to check the network requests to inspect if someone is failing.

If X-Pack is what is triggering/not triggering the error, it should be
related to a certain request we do to Elasticsearch API, for example:


> */api/wazuh-elastic/top/'+$scope.defaultManager+'/agent.name
> <http://agent.name>'/api/wazuh-elastic/top/'+$scope.defaultManager+'/agent.id
> <http://agent.id>'*


Requests will be like:

**Comment by snaow** [comment]
Could you check for "Network" tab in the Chrome development tool? I would
like to check the network requests to inspect if someone is failing.

If X-Pack is what is triggering/not triggering the error, it should be
related to a certain request we do to Elasticsearch API, for example:

> /api/wazuh-elastic/top/'+$scope.defaultManager+'/agent.name
> /api/wazuh-elastic/top/'+$scope.defaultManager+'/agent.id

Requests will be like:

![image](https://cloud.githubusercontent.com/assets/1519428/26002029/9046871c-372e-11e7-8213-d597a28a7155.png)

Thanks!

**Comment by rossengeorgiev** [comment]
That request 500s, but with xpack is fine. 😕 

![image](https://cloud.githubusercontent.com/assets/2720787/26003219/fa15f7ae-3729-11e7-804c-3cd6ff1fbd4e.png)

**Comment by rossengeorgiev** [comment]
That request 500s, but with xpack is fine. 😕 

![image](https://cloud.githubusercontent.com/assets/2720787/26003219/fa15f7ae-3729-11e7-804c-3cd6ff1fbd4e.png)

**Comment by snaow** [comment]
Hi Rossen,

Perfect, we now have the error located, we can say a request to
Elasticsearch API is failing.
Wazuh App gets Elasticsearch credentials from Kibana instance, meaning that
we are using credentials and setting located in kibana.yml file.

Could you tell us the url you are using to connect to Elasticsearch in
kibana.yml file?


> *# The URL of the Elasticsearch instance to use for all your
> queries.#elasticsearch.url: "http://localhost:9200 <http://localhost:9200>"*


Are you using a different basePath ?

*#server.basePath: ""*


Wazuh app is currently limited in terms of basePath / proxies, are you
using an Nginx or other proxy to forward requests?

Thanks and sorry for the questions, just trying to help you.

Best,
Pedro.

**Comment by rossengeorgiev** [comment]
Alright, `/etc/kibana/kibana.yml` is:

```yaml
server.host: 127.0.0.1
server.port: 5601
elasticsearch.url: http://10.0.11.22:9200
kibana.index: .kibana.wazuh.localdev
elasticsearch.username: username
elasticsearch.password: password
```

And yes, kibana is behind nginx.

**Comment by snaow** [comment]
Thanks Rossen.

Problem could be related with Elasticsearch credentials or Nginx proxy.
Wazuh App needs enough credentials to fetch the data from Elasticsearch,
have "elasticsearch.username" user enough permissions to access / read
Elasticsearch cluster data? Could you set up root privilegies there, for
example, "elastic" user ?

Are you using Nginx to forward Wazuh API requests as well ? Remember not
set up a redirection for "/api" because Kibana uses internally that URL.

I can see the requests failing:

> *http://127.0.0.1:5601/api/wazuh-elastic/top/manager.name/agent.name
> <http://127.0.0.1:5601/api/wazuh-elastic/top/manager.name/agent.name>*


That is why I am thinking about connectivity/proxy/elasticsearch issue.

Best,
Pedro.

**Comment by rossengeorgiev** [comment]
Hold on, I don't see how any of this is related. Why would it work under xpack, but not otherwise? I tried accessing kibana without nginx, and the result is the same. I'm using the same user, it has all the permissions. If it was connectivity/proxy/es issue, why would it work with xpack, and not without?

**Comment by snaow** [comment]
X-Pack adds some layers of security to Elasticsearch API, including
"credentials" and/or encrypting.
According to your error, following the error trace Wazuh App is failing to
fetch Elasticsearch data using Elastic JS library:

1. Making the request
https://github.com/wazuh/wazuh-kibana-app/blob/master/public/controllers/agentsPreview.js#L113

2. Connecting to Elasticsearch
https://github.com/wazuh/wazuh-kibana-app/blob/master/server/api/wazuh-elastic.js#L10

3. Fetching data
https://github.com/wazuh/wazuh-kibana-app/blob/master/server/api/wazuh-elastic.js#L85

Essentially the request contains the following payload:


>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *{  "size": 1,  "query": {    "bool": {      "must": [{"match":
> {"manager.name <http://manager.name>": "your_manager"}}],      "filter": {
>       "range": {          "@timestamp": {"gte": "now-1d", "lt":"now"}
>   }      }    }  },  "aggs": {    "2": {      "terms": {        "field":
> "agent.name <http://agent.name>",        "size": 1,        "order": {
>     "_count": "desc"        }      }    }  }}*


It will aggregate *agent.name <http://agent.name>* keyword and return us
the top agent.

Could you look for other requests result we do to Elasticsearch? For
example "alertCount":


​


The fetchElastic request could fail due to: Credentials and/or connectivity.
Installing / Uninstalling X-Pack could let Elastic in a awkward situation.



I am trying to help here, we appreciate so much your feedback.

Cheers,
Pedro.

**Comment by rossengeorgiev** [comment]
Alright, after running `tcpdump` I found that its caused by the security features of xpack. Having xpack on elastic, and using kibana without xpack will cause this error.

 The request from https://github.com/wazuh/wazuh-kibana-app/blob/master/server/api/wazuh-elastic.js#L85 will not contain the `Authentication` header and therefore get `401 Unauthorized`.

Worth nothing that outside of this, kibana works fine and correctly sends the auth header. So, perhaps this is something that can be improved in the way wazuh-app sends requests to elastic.

**Comment by snaow** [comment]
Hi Rossen,

I am glad you locate the error, as we thought It was related to X-Pack
security layers.
I can understand now what is happening there, you are right about the
Authentication headers, few weeks ago we were using credentials set on
kibana.yml file, please take a look to:

https://github.com/wazuh/wazuh-kibana-app/issues/11#issuecomment-287752186


We found a new way to do it according to ElasticJS official documentation,
not using credentials but using instead internal Kibana
"elasticsearch.plugin" to perform all the requests:

https://github.com/wazuh/wazuh-kibana-app/blob/master/server/api/wazuh-elastic.js#L10



Actually we did that to make it compatible with full X-pack plugin
(Kibana+Elastic), we will review your case and increase configuration
options to prevent this kind of situations.

Best,
Pedro.
