### ISSUE TITLE
Defects reported by the DevOps team for v3.9.3

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1610]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.2     | 0523 |

- [x] Reporting for Overview > Security Events doesn't work if _wazuh.monitoring_ is disabled due to the Agent Status visualization is missing.
- [x] Console error in PCI-DSS
![image](https://user-images.githubusercontent.com/8860227/61357561-cd92c280-a878-11e9-9da5-8e6be9d5d6e2.png)
- [x] Policy monitoring has unrelated visualizations
  - Top 5 PCI DSS
  - Top 5 CIS
- [x] Path filter doesn't work for custom rules. Using the dropdown or writing it by hand, doesn't work anyway.
- [x] Inconsistent data in VirusTotal dashboard. The number of files is not represented properly in the table
- [x] Different size between created and implicit filters. Add a filter manually. Notice the size difference.
- [x] Problem with SCA filter. <del>Navigate to Agents > SCA. Check that there are alerts. Then go to Overview > SCA. The agent.id filter is kept and it should be removed. It doesn't happen when going to other dashboards so it's fully related to SCA</del>.
- [x] Syscheck visualizations inconsistencies. <del>The number of top agents and top users doesn't match</del>
- [x] Rules and decoders tables don't show the path column. But the path filter is allowed. Check the available columns to select, the path column is not included.
- [x] Grammar typo in VirusTotal dashboard. <del> "No results displayed because all values equal 0." The rest of the empty visualizations displays different messages. </del>
- [x] In Docker section. Empty visualizations when there are no related data. There are related data, but not being used by the visualizations.
- [x] In Osquery section. Osquery alert doesn't resolve variable content | Rule.id: 24052
- [x] Duplicated failing requests (error code 500) are being launched when entering the app.
- [x] Remove Overview > SCA dashboard
- [x] <del>Alerts table is unordered. Review all table visualizations.</del> Ordered by Alerts count
- [x] Weird color selection in several visualizations.
- [x] Ruleset 
  - [x] Make columns _level_, _group_, _pci_, _gdpr_ clickable columns, then it adds a filter for the table. 
  - [x] Make the file column clickable, it should show the file content. 
  - [x] Must be changed in the rule list and the related rules list inside a rule. 
  - [x] Apply the same for decoders. 
- [ ] Rule.id table field is not clickable. Go to the Security Events alerts table and click to the rule.id. It's not taking you anywhere.
- [x] Kibana app not able to remove several agents from a group. Related: https://github.com/wazuh/wazuh/issues/3692
- [x] Chart.js colors must be the same as Kibana visualizations colors
- [x] Add timezone data modification in places where is not being applied.
- [ ] Click "Refresh" button on any dashboard, it should fetch new data, however, it's just working for Discover tabs.
- [x] Never connected agent appears synchronized in the configuration. 
- [x] Disconnected agents have differents messages across sections.
- [x] Tables checks shouldn't be empty, at least one of them should be always checked.
![image](https://user-images.githubusercontent.com/35685689/61542081-21500800-aa41-11e9-87e0-e6add60cdad4.png)
- [x] Visual bug in cluster monitoring
![image](https://user-images.githubusercontent.com/21195730/61540897-df25c700-aa3e-11e9-926d-5372e529ede0.png)
- [x] Flick in CDB lists table deleting a list

**Comment by juankaromo** [comment]
Steps to reproduce **Duplicated failing requests (error code 500) are being launched when entering the app. ~400 ms**

1. Add a new API entry and set it as default (the cookie is created)
2. Get the _id with `GET .wazuh/_search`
3. Delete API from the index with
´´´js
POST .wazuh/_delete_by_query
{
  "query": {
    "term": {
      "_id": "1563305022353"
    }
  }
}
´´´
4. See the error in Network tab of browser dev-tools

**Comment by juankaromo** [comment]
Working on this branch https://github.com/wazuh/wazuh-kibana-app/tree/fixes-issue-1610

**Comment by juankaromo** [comment]
**Path filter doesn't work for custom rules using the dropdown or writing it by hand, doesn't work anyway.**

This isn't really a mistake. What happens is that when you enter the path filter, it is not added because in custom rules/decoders it doesn't make sense (the path for custom is 'etc/[rules, decoders]') and it doesn't make sense to change it inside this section. What we are going to do is to remove the possibility of applying the filter from the dropdown if we are in the custom rules/decoders section.

**Comment by juankaromo** [comment]
**Problem with SCA filter**

We haven't been able to reproduce this casuistry. However, since the SCA overview dashboard will be removed, this no longer applies.

**Comment by pablotr9** [comment]
**Update** 
It has been added the capability to add filters to the rules/decoders table by click on _**level, group, pci, gdpr,path**_ columns. Example: 
![Peek 2019-07-17 17-09](https://user-images.githubusercontent.com/35685689/61387255-15840a80-a8b6-11e9-95d0-b94bf4207825.gif)

**Problems encountered**
Some fields have multiple values, Wazuh API only supports filtering by one value, The temporary solution to this:  When clicking on a column with multiple values just the first value is applied as a filter. e.g. Click on a PCI DSS column with  **5.1, 10.6.1,**  just adds **5.1** as filter

**Comment by juankaromo** [comment]
**Update** 

The performance of the wz-table has been improved to check if the text is truncated and thus show or not the tooltip.

On the other hand, a visual aid has been added in the cells that add filters (chips) to the search, as well as in the Kibana display tables.

![chips](https://user-images.githubusercontent.com/21195730/61455315-73226080-a963-11e9-9819-37bbfbaa8be4.gif)

**Comment by juankaromo** [comment]
**Syscheck visualizations inconsistencies The number of top agents and top users doesn't match**

This is happening because windows alerts don't contain the `uname` field, so we don't have the user.

**Grammar typo in VirusTotal dashboard "No results displayed because all values equal 0." The rest of the empty visualizations displays different messages.**

It seems that this is a known problem in Kibana when there are no results in 'foot' type displays.

https://discuss.elastic.co/t/no-results-displayed-because-all-values-equal-0/66065

![image](https://user-images.githubusercontent.com/21195730/61460205-8dae0700-a96e-11e9-8a73-57933d99c150.png)

**Comment by pablotr9** [comment]
**Update** 
- Inconsistent data between visualizations and tables.
In this example this visualization was showing a total of 4 alerts:
![mal1](https://user-images.githubusercontent.com/35685689/61463346-80941680-a974-11e9-8367-6f910554ce89.png)
Table was showing just 2 of them:
![mal2](https://user-images.githubusercontent.com/35685689/61463684-395a5580-a975-11e9-93b6-b466d0175dd1.png)
It has been fixed and now it shows the real amount of alerts, 4:
![bien2](https://user-images.githubusercontent.com/35685689/61463748-5a22ab00-a975-11e9-813a-838ad069c3db.png)
This problem was caused to a repeated rule.id and differente rule.description, just the one of them was being shown in the table. https://github.com/wazuh/wazuh-kibana-app/commit/b12c600578d80d0715507dec4624a4ebc27ea573

**Comment by juankaromo** [comment]
**Update**

Policy monitoring Overview and Agents dashboards have been refactored removing PCI-DSS and CIS Visualizations and reorganized the rest.

**Overview**

![image](https://user-images.githubusercontent.com/21195730/61528952-60ba2c80-aa20-11e9-823e-be3a29a91ed3.png)


**Agents**

![image](https://user-images.githubusercontent.com/21195730/61529120-e1792880-aa20-11e9-9039-87a76b9408eb.png)

**Comment by pablotr9** [comment]
**Update** 
The agent synchronization status is now shown with its real value:
- Not sync:
![image](https://user-images.githubusercontent.com/35685689/61547621-08991f80-aa4c-11e9-86f0-464536e92d0e.png)
![image](https://user-images.githubusercontent.com/35685689/61547686-2cf4fc00-aa4c-11e9-80db-74a47713e369.png)
- Sync:

![image](https://user-images.githubusercontent.com/35685689/61547648-164ea500-aa4c-11e9-89c8-fd3b1f0ec7eb.png)
![image](https://user-images.githubusercontent.com/35685689/61547662-21a1d080-aa4c-11e9-8cb8-fe86e9826d8d.png)


- Ruleset files was generating this error:
![image](https://user-images.githubusercontent.com/35685689/61547762-54e45f80-aa4c-11e9-9c0d-a348714e9dcd.png)
It was sending the wrong event so the tab was getting frozen, it has been fixed.

**Comment by adri9valle** [comment]
**Update**

>  Disconnected agents have differents messages across sections.

Now both sections, SCA and inventory data show the same warning:

![image](https://user-images.githubusercontent.com/7983984/61616695-72dadb80-ac69-11e9-9b72-5f0873f43186.png)

![image](https://user-images.githubusercontent.com/7983984/61616704-779f8f80-ac69-11e9-8531-4c7e7b244769.png)

**Comment by adri9valle** [comment]
**Update**

> Reporting for Overview > Security Events doesn't work if wazuh.monitoring is disabled due to the Agent Status visualization is missing.

The reporting services now checks if the tag is general and in this case also, checks if the wazuh.monitoring is enabled or disabled in order to remove the Agent status visualization and prevent the error generating the report.

https://github.com/wazuh/wazuh-kibana-app/blob/45620f9fc1288fe39d0f88dd91c0d267c382c4cc/public/services/reporting.js#L35-L44
