### ISSUE TITLE
Wazuh "Registration date" and "Last keep alive" time are wrong

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh-kibana-app#1614]
|Wazuh version:3.9.2-1
|Component: Wazuh-manager
|Install type:Manager
|Install method:Packages
|Platform|CentOS 7.5

Hello,this question I had asked but no answer.

I just find  the  Wazuh "Registration date" and "Last keep alive" time are 8 hours faster than now
For example, I registed the new wazuh-agent at 2019.07.17 20:08，but  the kibana page shows the Registration date time is 2019.07.18 04:08. There is 8 hours between two different  times.

![image](https://user-images.githubusercontent.com/15324125/61422330-d0a3b680-a93d-11e9-912c-c3fce4fa33ce.png)

I had checked the Wazuh-manager host's time  and Wazuh-agent host's time ,there are same,and there are 8 hours slow than  kibana wazuh "Registration date" and "Last keep alive" time

![image](https://user-images.githubusercontent.com/15324125/61422408-19f40600-a93e-11e9-825f-1b76db3ae9db.png)

![image](https://user-images.githubusercontent.com/15324125/61422419-27a98b80-a93e-11e9-942d-19dfa5d8b574.png)

But When I visit "Security events"-"Discover" page,the event time is right

![image](https://user-images.githubusercontent.com/15324125/61422485-8111ba80-a93e-11e9-82bc-ccf851a5ba61.png)

And   Wazuh-manager host's log time  and Wazuh-agent host's log time is right,too.My host's  timezone is also same.

![image](https://user-images.githubusercontent.com/15324125/61422544-bdddb180-a93e-11e9-928d-6c1be00877a5.png)

And when I used Wazuh'api " /agents?status=Active" to check agent's info I find the response info is right

![image](https://user-images.githubusercontent.com/15324125/61422578-e796d880-a93e-11e9-933b-b4ff64ec281e.png)

Due to this problem,I find if I stop the Wazuh-agent process,but the kibana Wazuh app page also tell me the agent is alive ,after 8 hours this page show the agent is disconnection.

Emmm......I don't know how to solve this question.

I hope to rececive your reply soon,thx!

**Comment by juankaromo** [comment]
Hi @xufengnian I'll explain what's going on

We've recently added a feature to the app so that dates appear with the user's local time. To do this, any date we receive from the server is assumed to come in UTC time, and we add the time difference of the country where the browser is. Well, it seems that your server is configured with the local time of your country, and what the browser is doing is to add the time difference again, so the dates are in the future.  On the other hand, the timezone (en-ZA) you comment is only for the format we want (yyyy/MM/dd ... ).

We have to study again how this feature behaves and improve it, for example, making the timezone configurable by the user and not automatic. I leave the ticket here so you can follow it https://github.com/wazuh/wazuh-kibana-app/issues/1612

Thank you very much for reporting this problem.

**Comment by xufengnian** [comment]
Well, thank you very much for your reply. I'll look forward  it.

**Comment by juankaromo** [comment]
Finally, we've decided to fix this issue from the root. We will guarantee that all dates coming from the Wazuh API will come in UTC time zone. In this way, our approach of adding the browser timezone in the Wazuh app will work fine.

Here is the ticket to solve this in the Wazuh core https://github.com/wazuh/wazuh/issues/3784

**Comment by jesusgn90** [comment]
Ticket https://github.com/wazuh/wazuh/issues/3784 has been fixed and merged for the next minor version of Wazuh (3.10.0), so I'm going to close this ticket too.

Don't hesitate to open a new ticket if you need more help, feel free to ask us as much as you want @xufengnian, we are here to help.

Regards,
Jesús
