### ISSUE TITLE
Wazuh 3.9.3 / ELK 6.8.1 - 2001 - [index_not_found_exception] no such index

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#1616]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.3   | 6.8.1     | 444 |

**Description**
Install ELK and Wazuh on CentOS 7.6 via release RPMs

**Steps to reproduce**
1. Open Wazuh app in Kibana

**Screenshots**
![image](https://user-images.githubusercontent.com/2720787/61478367-484b0300-a989-11e9-9eb3-0968eea90b06.png)

**Comment by juankaromo** [comment]
Hi @rossengeorgiev 

It seems that Elasticsearch is not able to create the .wazuh index that the app needs to manage the API connection. This may be due to several problems:

1. Do you have X-Pack or similar configured? If yes, have you configured correctly the credentials in the kibana.yml?

2. Elasticsearch's Watermark has been exceeded, which means you have low disk space left and it is not possible to create new indexes.

3. You have blocked the creation of new indexes in the settings of Elasticsearch.

For now, let's see if any error log has been generated when trying to create the index in Elastisearch that gives us some more information. Please execute this command:

`cat /var/log/elasticsearch/<cluster_name>.log | grep -i -E "warn|error|critical"`.

Let’s see if there’s any error log to help us identify what’s going on.

Regards.

**Comment by rossengeorgiev** [comment]
Hi @juankaromo, I'm not sure what happened but this morning after rebooting my VM, it now works normally and creates the indices by itself. Very strange. I was unable to replicate the issue after redoing the upgrade. I will reopen if I encounter the issue again.
