### ISSUE TITLE
Defects reported by the DevOps team for v3.9.4-rc1

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1626]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.4   | 6.8.1/7.2.0     | 525 |

- [x] Implicit filters (agent.id) can be destroyed

1. "Agents > Select an agent. Go to any dashboard which allows adding filters. I.e Integrity Monitoring. Check that the 'agent.id' the filter cannot be removed. Then add a new filter with the same 'agent.id'. The filter turns removable now and the dashboard will show data of all agents."

![image](https://user-images.githubusercontent.com/21195730/61850687-2a176280-aeb5-11e9-9b92-740f48659d93.png)

- [x] Table badly dimensioned in Integrity Monitoring section

1. Overview > Integrity monitoring. Top 5 users

![image](https://user-images.githubusercontent.com/21195730/61850707-3dc2c900-aeb5-11e9-8c42-4b0ae6328371.png)

- [x] Breadcrumb is not properly updated

1. "Management > Ruleset. Click on a rule, then open a xml file for editting.
then click on the 'ruleset' link of the breadcrumb. The breadcrumb keeps
the rule/id"

- [x] Huge error toast

1. Search for 'something*' in the search bar

![image](https://user-images.githubusercontent.com/21195730/61850728-474c3100-aeb5-11e9-88d1-b33b23305888.png)

- [x] Timeout errors at search time in Kibana

1. Search for ''*Shellshock*"

![image](https://user-images.githubusercontent.com/21195730/61850745-4f0bd580-aeb5-11e9-992b-8190600aad93.png)

- [x] Pinned agent filter across sections

1. "Overview/General/Dashboard -> Add agent.id: 007 and make it pinned -> Go to Agents/..." The filter "agent.id: 007" is removed and just in case it was the same ID as the agent it becomes to an implicit filter https://github.com/wazuh/wazuh-kibana-app/pull/1637

**Comment by adri9valle** [comment]
**Update**

##### ￼ Huge error toast https://github.com/wazuh/wazuh-kibana-app/pull/1627/commits/786faf3e62d2cad13f512c0f873b36eca6e9787d

Before, when an error occurred in a search on the discover a toast was launched for each visualization in the dashboard, this provokes that the screen becomes flooded with multiple error toast, now we check if the error is the same and prevent multiple same errors in order to show only one and don't flood the screen. 

![image](https://user-images.githubusercontent.com/7983984/61851798-2b965a00-aeb8-11e9-9065-bdb157fe3854.png)

**Comment by adri9valle** [comment]
**Update**

###### Timeout errors at search time in Kibana

This error comes from Kibana in case of the request time response being greater than 30 seconds.
