### ISSUE TITLE
Kibana did not show agent alert log

### ISSUE THREAD

**Issue by zakirpcs** [wazuh/wazuh-kibana-app#1639]
After update wazuh version 3.9.3 kibana did not show agent alert log.  My environment is as below:

wazuh version:  3.9.3
ELK version: 
Elasticsearch: 7.2.0
Kibana: 7.2.0
Filebeat: 7.2.0

How can I find out the issue?

**Comment by juankaromo** [comment]
Hi @zakirpcs ,

Sorry about the inconveniences, we try to improve all the upgrading process day by day.

Please, execute the next commands so we can debug what’s happening.

Check the Wazuh manager daemons, so we can see if some daemon is missing:

`ps aux | grep ossec`

We can look for the status of the Wazuh manager and agent:

`systemctl status wazuh-manager -l` (in manager instance)

`systemctl status wazuh-agent-l` (in agent instance)

In order to verify there really are Wazuh agents connected to de Wazuh-manager, please, run the following command in the manager instance:

`/var/ossec/bin/agent_control -lc`

Now, let’s check if Elasticsearch is up :

`systemctl status elasticsearch -l`

And if Filebeat is up too:

`systemctl status filebeat -l`

We can look for errors at the Elasticsearch cluster log file too:

`cat /var/log/elasticsearch/<your-cluster-name>.log | grep -E "ERROR|WARN"`

It would be nice if you share with us the output from the above commands so we can try to give you better assistance.

Regards,

**Comment by jesusgn90** [comment]
Hi @zakirpcs ,

More than a month from our last response, I'm going to close this ticket. Please, feel free to re-open it or to create a new one if you are still in need of help. We are here to help you.

Regards,
Jesús
