### ISSUE TITLE
Nginx in Kibana for Wazuh doesn't work

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-kibana-app#1647]
| Wazuh | Elastic | 
| ----- | ------- 
| 3.9  | 6.8 |

Hi,

I follow this doc for install Nginx : https://documentation.wazuh.com/3.9/learning-wazuh/build-lab/kibana-setup.html

I built key like in doc, but for the certificate I token certificat.crt of my company in encoding DER.

My configuration of  /etc/nginx/conf.d/default.conf it's this : 
```
server {
    listen 443;
    ssl on;
    ssl_certificate     /etc/pki/tls/certs/certificate.crt;
    ssl_certificate_key /etc/pki/tls/private/kibana-access.key;
    access_log            /var/log/nginx/access.log;
    error_log            /var/log/nginx/error.log;
    location / {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf.d/kibana.htpasswd;
        proxy_pass http://<KIBANA_IP>:5601/;
    }
}
```
After I change kibana.yml for put certificat and enable ssl, and I modify the :  /var/ossec/api/configuration/config.js
For put API in https.

But when I lunch my Kibana I don't have the prompt for authentication. I have https but no prompt why ? 

Can you help me please  ? 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000,
What exactly are you trying to do? 
1. Configure Kibana to use SSL encryption and enable authentication? An up to date guide of this case can be found here: https://documentation.wazuh.com/3.8/installation-guide/optional-configurations/kibana_ssl.html
2. Secure your Wazuh API by enabling HTTPS and changing Wazuh API default credentials? You can easily do that following the steps explained in our doc: https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-server/securing_api.html

Regarding the use of your company's certificate, I see that you put the path of that certificate in `ssl_certificate`, that's right, but you also have to add the `ssl_certificate_key` of that certificate in order to work.

Please let me know if you need further assistance.

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

I resolve my problem, sorry, thanks you.

You can close this issue

**Comment by pablotr9** [comment]
Hi,

I'm glad to see it's working, if you need anything else do not hesitate to ask us again!

Kind regards,
Pablo Torres
