### ISSUE TITLE
Timeouts in cluster monitoring

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1663]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.4   | 7.x     | 527 |

**Description**
It seems that cluster-monitoring makes a disproportionate call for the data we are taking, since it returns a lot of alerts and fall. You have to look for graphs that consume less.
It doesn't make sense that 2 out of 10 times you give us a timeout only in this part of the App for that graph.

**Steps to reproduce**

1. Go to Management > Cluster monitoring
2. See timeout error (sometimes)

**Screenshots**
![image](https://user-images.githubusercontent.com/21195730/62541618-6a35f800-b85a-11e9-8354-8760a94fda81.png)

**Additional context**
We are using Kibana's own calls for monitoring `/elastic/visualizations/cluster-monitoring`.

**Comment by jesusgn90** [comment]
After some researching I've found a possible way to optimize this view and to reduce this load time:

Since the timelion visualizations don't need all the fields under `_source` we can try to reduce those fields to just `cluster.*` and `timestamp`.

This can be done setting the `_source` values in the `searchSource` instance as follows:

```js
searchSource.setField('source', ['timestamp', 'cluster'])
```

![image](https://user-images.githubusercontent.com/8860227/63346792-0b8e7500-c356-11e9-8387-8ea5eaa09da8.png)

Of course, we need to add some conditions to don't do this always, just in case we are feeding those visualizations.

**Comment by jesusgn90** [comment]
PR https://github.com/wazuh/wazuh-kibana-app/pull/1704 improves the load time, and we should not see more timeouts here for standard situations (all components are working)
