### ISSUE TITLE
Testing Wazuh 3.10 - Kibana 6.8

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1724]
All the tests must be done on every common browser.

- [x] Chrome https://github.com/wazuh/wazuh-kibana-app/issues/1724#issuecomment-524294253
  - @juankaromo 
- [x] Firefox https://github.com/wazuh/wazuh-kibana-app/issues/1724#issuecomment-524815733
  - @juankaromo 
- [x] Safari https://github.com/wazuh/wazuh-kibana-app/issues/1724#issuecomment-526595956
  - @juankaromo

**Comment by juankaromo** [comment]
**Testing**

- xpackMainPlugin.registerFeature() for lock Kibana spaces is not available in 6.8

**Comment by juankaromo** [comment]
### **Firefox Testing**


#### Filter checks (Overview and Agents)    

- [ ] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Discover" Filters shouldn't change
- [ ] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Discover" Filters shouldn't change
- [ ] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [ ] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [ ] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [ ] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [ ] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/General/Dashboard" Filters shouldn't change
- [ ] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Dashboard" Filters shouldn't change
- [ ] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Dashboard" The filter "rule.level:7" is removed
- [ ] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" The filter "rule.level:7" persists
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Discover" Filters shouldn't change
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Discover" Filters shouldn't change
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [ ] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [ ] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [ ] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/General/Dashboard" Filters shouldn't change
- [ ] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" Filters shouldn't change
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Dashboard" The filter "rule.level:7" is removed
- [ ] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists

#### Query bar (Overview and Agents)
- [ ] Simple search, example: "ssh".
- [ ] Left wildcard search, example: "*ssh".
- [ ] Right wildcard search, example: "ssh*".
- [ ] Both sides wildcard search, example: "\*ssh\*". (its slowness is a known issue)
- [ ] Filter search, example: "rule.level >= 10".
- [ ] Multiple queries, example "rule.level >= 10 and agent.name : "pop-os"".

#### Visualizations
- [ ] Click on the lens of a field to apply a filter.
- [ ] Using the mouse, select a period of time on a time-based visualization.
- [ ] Dashboards with no alerts for the selected time range should not be broken.
- [ ] Dashboards with no alerts for any time range should not be broken and should not show any toaster.
- [ ] See at least one time every visualization of every dashboard. None of the visualizations should be broken (obviously).

#### Discover related checks
- [ ] View surrounding documents should work
- [ ] View single document should work
- [ ] View the source of a document should work

#### Overview UI
- [ ] Check the "eye" button for enabling/disabling extensions.
- [ ] Metrics for agents should show values (including 0 if there are no agents).
- [ ] F5 on the page should keep the selected extensions.
- [ ] If an extension is disabled, it should not appear as a sub-tab once a dashboard is opened.

#### Reporting
- [ ] Should work with no custom filters.
- [ ] Using custom filters, the report must apply the custom filters.
- [ ] Using custom filters and custom query, the report must apply the custom filters and the custom query.
- [ ] Using a custom query, the report must apply the custom query.
- [ ] Generate a report for Inventory.

#### Management - Status
- [ ] Metrics for agents should show values (including 0 if there are no agents).
- [ ] If the cluster is enabled, it should show a node selector.
- [ ] If the cluster is enabled, it should show a button for restarting the cluster, it should restart it after pressing the button.
- [ ]  If the cluster is enabled, changing node should refresh the view.
- [ ] Check that every daemon metric is consistent.
- [ ] If there are one or more agents, it should show the "Last registered agent" box next to the manager box.

#### Management UI
- [ ] Should show two cards with the different sections

#### Management - Cluster
- [ ] The load time should be fast, no timeouts.
- [ ] Timelions should show data.
- [ ] The Overview should show Top 5 nodes visualization and information about the cluster.
- [ ] The nodes list should show all nodes.
- [ ] The node detail should show Alerts over time visualization and information about the node.

#### Management - Logs
- [ ] If the cluster is enabled, it should show a node selector.
- [ ]  If the cluster is enabled, changing node should refresh the view.
- [ ] Daemon selector should filter the output by the selected daemon.
- [ ] Level selector should filter the output by the selected level.
- [ ] Descending sort should apply a descending sort.
- [ ] Search bar should filter the output.
- [ ] Play real-time should append new logs on the fly.
- [ ] Formatted should export the output in a file for downloading it.

#### Management - Reporting
- [ ] If there are no reports, the table should be empty.
- [ ] If there are reports, they should be downloadable and removable.

#### Management - Ruleset
- [ ] List rules.
- [ ] List custom rules.
- [ ] List decoders.
- [ ] List custom decoders.
- [ ] Edit custom rules.
- [ ] Edit custom decoders.
- [ ] List CDB lists.
- [ ] Create, update CDB lists.
- [ ] Click on file column values should open the file content.
- [ ] Click on a rule should open the rule details.
- [ ] Click on a decoder should open the decoder details.
- [ ] Click on a CDB list should open the CDB list details.

#### Management - Groups
- [ ] List groups.
- [ ] Search groups.
- [ ] Create groups.
- [ ] Remove a group.
- [ ] Add one agent to a group.
- [ ] Add more than one agent to a group.
- [ ] Remove an agent from a group.
- [ ] Remove more than one agent from a group.
- [ ] Edit group configuration.
- [ ] Export group details in PDF using granular options.
- [ ] Export group details in PDF with no granular options.
- [ ] "Formatted" should export the output for the different tables.
- [ ] Click on an agent should redirect to the agent view.

#### Management - Configuration
- [ ] Check that all sections are working as expected.
- [ ] Edit the "ossec.conf" using the Edit configuration link. Edit, Save, Restart a node, Change node should be working as expected.

#### DevTools
If admin mode is enabled:
- [ ] GET should work.
- [ ] PUT should work.
- [ ] POST should work.
- [ ] DELETE should work.
If admin mode is disabled:
- [ ] GET should work.
- [ ] PUT should show a user-friendly error message.
- [ ] POST should show a user-friendly error message.
- [ ] DELETE should show a user-friendly error message.
In any mode:
- [ ] The history must be stored in the browser session storage.
- [ ] Malformed queries should show information messages about the error.
- [ ] The output should be the same as doing a direct "curl".
- [ ] The download button should show a tooltip and download the output JSON.

#### Agents preview
- [ ] If there are no agents yet, the interactive guide should appear.
- [ ] The status chart should be consistent.
- [ ] The status metrics should be consistent.
- [ ] Last registered agent and most active agent should show agents or "---" depending on the environment.
- [ ] All available selectors on the search bar should work.
- [ ] Complex searches such as using AND, OR should work too.
- [ ] "Formatted" button should export the list, try it against 14.000 agents.
- [ ] Sort the table.
- [ ] Refresh the table using "Refresh"
- [ ] Check that links from the "Actions" column are working.
- [ ] Add new agent should open the interactive guide.
  - [ ] Changing OS should refresh the snippet.
  - [ ] Filling the IP should refresh the snippet.
  - [ ] Click on close should close the guide.
  - [ ] Click on the copy icon should copy the snippet.

#### Agent specific view UI
- [ ] Check the "eye" button for enabling/disabling extensions.
- [ ] Metrics for the agent should show values (ID, IP, registration date,...).
- [ ] F5 on the page should keep the selected extensions.
- [ ] If an extension is disabled, it should not appear as a sub-tab once a dashboard is opened.
- [ ] The configuration can't be edited.
- [ ] Export the agent configuration in PDF using granular options.
- [ ] Export the agent configuration in PDF with no granular options.
- [ ] Review that we are not showing non-applicable dashboards depending on the agent OS.
- [ ] Check the FIM table inside FIM is showing information properly.
- [ ] Check all the Inventory tables.
- [ ] Check the agent status indicator on top of the view.
- [ ] Check all SCA tables.

#### App menu
- [ ] Should be visible always, even if we change the state.
- [ ] Should show the index pattern.
  - [ ] If there is more than one index pattern, show a list.
- [ ] Should show the selected API.
- [ ] The Wazuh logo should be fixed on top of the menu.
- [ ] Every link should redirect you to the right section.

#### Settings
- [ ] Add, edit, remove API entries.
- [ ] Change the index pattern.
- [ ] Edit app settings.
- [ ] Show app logs.
- [ ] Review the About section. Check the app version, Kibana version, app revision, and installation date values.

#### Kibana spaces

- [ ] App should work on Default space and there are valid index patterns.
- [ ] App should work on a custom space after creating the index pattern by hand.
- [ ] Hide/Show the plugin depending on the selected space.
- [ ] App should filter the index pattern list depending on the selected space.

#### Admin mode disabled
- [ ] Only GET methods are allowed when sending requests to the Wazuh API.
  - [ ] Groups management, ruleset management...
  - [ ] Sections designed for management should be hidden if the user can't do anything due to the restriction. Example: don't show the user removing a group button if he can't do it.
  - [ ] Dev Tools must respect this restriction too.

#### Misc

- [ ] Index patterns wazuh-alerts-3.x-* and wazuh-monitoring-3.x-* should be created if they are missing.
- [ ] The `.wazuh-version` should be migrated to the new registry file if it exists, then it should be removed.
- [ ] Test all settings from `config.yml`.
- <del>[ ] Kibana dark mode should work properly, all the app theme should be consistent with the dark theme of Kibana.</del>

#### Infrastructure and others
- [ ] Installing the plugin using `kibana-plugin install file:///wazuhapp.zip` should work.
- [ ] Installing the plugin using `kibana-plugin install https://plugin/url/wazuhapp.zip` should work.
- [ ] Using the OSS version of Kibana should work too.
- [ ] Using security features such as X-Pack security should work.
- [ ] Make an upgrade from Wazuh 3.9.0 and Elastic 6.x to Wazuh 3.10.0 and Elastic 7.x without removing indices and without doing any different action from our upgrading guides.

### **Testing report**

**Comment by juankaromo** [comment]
### **SafariTesting**


#### Filter checks (Overview and Agents)    

- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Discover -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists

#### Query bar (Overview and Agents)
- [x] Simple search, example: "ssh".
- [x] Left wildcard search, example: "*ssh".
- [x] Right wildcard search, example: "ssh*".
- [x] Both sides wildcard search, example: "\*ssh\*". (its slowness is a known issue)
- [x] Filter search, example: "rule.level >= 10".
- [x] Multiple queries, example "rule.level >= 10 and agent.name : "pop-os"".

#### Visualizations
- [x] Click on the lens of a field to apply a filter.
- [x] Using the mouse, select a period of time on a time-based visualization.
- [x] Dashboards with no alerts for the selected time range should not be broken.
- [x] Dashboards with no alerts for any time range should not be broken and should not show any toaster.
- [x] See at least one time every visualization of every dashboard. None of the visualizations should be broken (obviously).

#### Discover related checks
- [x] View surrounding documents should work
- [x] View single document should work
- [x] View the source of a document should work

#### Overview UI
- [x] Check the "eye" button for enabling/disabling extensions.
- [x] Metrics for agents should show values (including 0 if there are no agents).
- [x] F5 on the page should keep the selected extensions.
- [x] If an extension is disabled, it should not appear as a sub-tab once a dashboard is opened.

#### Reporting
- [x] Should work with no custom filters.
- [x] Using custom filters, the report must apply the custom filters.
- [x] Using custom filters and custom query, the report must apply the custom filters and the custom query.
- [x] Using a custom query, the report must apply the custom query.
- [x] Generate a report for Inventory.

#### Management - Status
- [x] Metrics for agents should show values (including 0 if there are no agents).
- [x] If the cluster is enabled, it should show a node selector.
- [x] If the cluster is enabled, it should show a button for restarting the cluster, it should restart it after pressing the button.
- [x]  If the cluster is enabled, changing node should refresh the view.
- [x] Check that every daemon metric is consistent.
- [x] If there are one or more agents, it should show the "Last registered agent" box next to the manager box.

#### Management UI
- [x] Should show two cards with the different sections

#### Management - Cluster
- [x] The load time should be fast, no timeouts.
- [x] Timelions should show data.
- [x] The Overview should show Top 5 nodes visualization and information about the cluster.
- [x] The nodes list should show all nodes.
- [x] The node detail should show Alerts over time visualization and information about the node.

#### Management - Logs
- [x] If the cluster is enabled, it should show a node selector.
- [x]  If the cluster is enabled, changing node should refresh the view.
- [x] Daemon selector should filter the output by the selected daemon.
- [x] Level selector should filter the output by the selected level.
- [x] Descending sort should apply a descending sort.
- [x] Search bar should filter the output.
- [x] Play real-time should append new logs on the fly.
- [x] Formatted should export the output in a file for downloading it.

#### Management - Reporting
- [x] If there are no reports, the table should be empty.
- [x] If there are reports, they should be downloadable and removable.

#### Management - Ruleset
- [x] List rules.
- [x] List custom rules.
- [x] List decoders.
- [x] List custom decoders.
- [x] Edit custom rules.
- [x] Edit custom decoders.
- [x] List CDB lists.
- [x] Create, update CDB lists.
- [x] Click on file column values should open the file content.
- [x] Click on a rule should open the rule details.
- [x] Click on a decoder should open the decoder details.
- [x] Click on a CDB list should open the CDB list details.


#### Management - Groups
- [x] List groups.
- [x] Search groups.
- [x] Create groups.
- [x] Remove a group.
- [x] Add one agent to a group.
- [x] Add more than one agent to a group.
- [x] Remove an agent from a group.
- [x] Remove more than one agent from a group.
- [x] Edit group configuration.
- [x] Export group details in PDF using granular options.
- [x] Export group details in PDF with no granular options.
- [x] "Formatted" should export the output for the different tables.
- [x] Click on an agent should redirect to the agent view.

#### Management - Configuration
- [x] Check that all sections are working as expected.
- [x] Edit the "ossec.conf" using the Edit configuration link. Edit, Save, Restart a node, Change node should be working as expected.

#### DevTools
If admin mode is enabled:
- [x] GET should work.
- [x] PUT should work.
- [x] POST should work.
- [x] DELETE should work.
If admin mode is disabled:
- [x] GET should work.
- [x] PUT should show a user-friendly error message.
- [x] POST should show a user-friendly error message.
- [x] DELETE should show a user-friendly error message.
In any mode:
- [x] The history must be stored in the browser session storage.
- [x] Malformed queries should show information messages about the error.
- [x] The output should be the same as doing a direct "curl".
- [x] The download button should show a tooltip and download the output JSON.

#### Agents preview
- [x] If there are no agents yet, the interactive guide should appear.
- [x] The status chart should be consistent.
- [x] The status metrics should be consistent.
- [x] Last registered agent and most active agent should show agents or "---" depending on the environment.
- [x] All available selectors on the search bar should work.
- [x] Complex searches such as using AND, OR should work too.
- [x] "Formatted" button should export the list, try it against 14.000 agents.
- [x] Sort the table.
- [x] Refresh the table using "Refresh"
- [x] Check that links from the "Actions" column are working.
- [x] Add new agent should open the interactive guide.
  - [x] Changing OS should refresh the snippet.
  - [x] Filling the IP should refresh the snippet.
  - [x] Click on close should close the guide.
  - [x] Click on the copy icon should copy the snippet.

#### Agent specific view UI
- [x] Check the "eye" button for enabling/disabling extensions.
- [x] Metrics for the agent should show values (ID, IP, registration date,...).
- [x] F5 on the page should keep the selected extensions.
- [x] If an extension is disabled, it should not appear as a sub-tab once a dashboard is opened.
- [x] The configuration can't be edited.
- [x] Export the agent configuration in PDF using granular options.
- [x] Export the agent configuration in PDF with no granular options.
- [x] Review that we are not showing non-applicable dashboards depending on the agent OS.
- [x] Check the FIM table inside FIM is showing information properly.
- [x] Check all the Inventory tables.
- [x] Check the agent status indicator on top of the view.
- [x] Check all SCA tables.

#### App menu
- [x] Should be visible always, even if we change the state.
- [x] Should show the index pattern.
  - [x] If there is more than one index pattern, show a list.
- [x] Should show the selected API.
- [x] The Wazuh logo should be fixed on top of the menu.
- [x] Every link should redirect you to the right section.


#### Settings
- [x] Add, edit, remove API entries.
- [x] Change the index pattern.
- [x] Edit app settings.
- [x] Show app logs.
- [x] Review the About section. Check the app version, Kibana version, app revision, and installation date values.

#### Kibana spaces

- [x] App should work on Default space and there are valid index patterns.
- [x] App should work on a custom space after creating the index pattern by hand.
- [ ] Hide/Show the plugin depending on the selected space.
- [x] App should filter the index pattern list depending on the selected space.

#### Admin mode disabled
- [x] Only GET methods are allowed when sending requests to the Wazuh API.
  - [x] Groups management, ruleset management...
  - [x] Sections designed for management should be hidden if the user can't do anything due to the restriction. Example: don't show the user removing a group button if he can't do it.
  - [x] Dev Tools must respect this restriction too.

#### Misc

- [x] Index patterns wazuh-alerts-3.x-* and wazuh-monitoring-3.x-* should be created if they are missing.
- [x] The `.wazuh-version` should be migrated to the new registry file if it exists, then it should be removed.
- [x] Test all settings from `config.yml`.
- <del>[ ] Kibana dark mode should work properly, all the app theme should be consistent with the dark theme of Kibana.</del>

#### Infrastructure and others
- [x] Installing the plugin using `kibana-plugin install file:///wazuhapp.zip` should work.
- [x] Installing the plugin using `kibana-plugin install https://plugin/url/wazuhapp.zip` should work.
- [ ] Using the OSS version of Kibana should work too.
- [x] Using security features such as X-Pack security should work.
- [ ] Make an upgrade from Wazuh 3.9.0 and Elastic 6.x to Wazuh 3.10.0 and Elastic 7.x without removing indices and without doing any different action from our upgrading guides.

**Comment by jesusgn90** [comment]
Related:

- https://github.com/wazuh/wazuh-kibana-app/issues/1758
- https://github.com/wazuh/wazuh-kibana-app/issues/1727
