### ISSUE TITLE
Upload ruleset files using a "drag and drop" component

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-kibana-app#1770]
Hi team,

The app currently supports uploading ruleset files, filling a text editor and clicking on a "Save" button. What about having a "drag and drop" box where the user can put a valid ruleset file?

Proposals:

- [x] Create a "drag and drop" component for uploading files using the Wazuh API.
- [x] Integrate it with our ruleset management tabs.
- [x] Upload the files.

**Comment by adri9valle** [comment]
**Update 04.09.2019**

I've created a component in order to use in the different ruleset sections (rules, decoders, and CDB lists).

By the moment has the following capabilities:

- Select or drag and drop multiple files.
- The attached files are listed.
- Max files number is set to 5.
- Max size per file is set to 300Kb.
- In case of rules or decoders, the extension of the files is checked in order to check if is `.xml`.

Working on:
- Once the files are attached remove only one of them if click over the cross icon.
- Get the file content in order to send to the API, currently, only the name and the size are taken.

Demo:

![upload3](https://user-images.githubusercontent.com/7983984/64247961-38bf5380-cf10-11e9-8ed7-bfb1ee3a679f.gif)


**NOTE**: The design, disposition and the way to access to the component will go to change in next iterations.

**Comment by adri9valle** [comment]
**Update 06.09.19**

I've been working with @juankaromo in order to adapt this new capability with the integration of the logtest in the APP https://github.com/wazuh/wazuh-kibana-app/issues/1434. The current status and is the following:

![up-pop-list](https://user-images.githubusercontent.com/7983984/64437030-c5f7d900-d0c5-11e9-904b-ba12f9afb31d.gif)

**NOTE**: The design, disposition and the way to access to the component could change in next iterations.

Now we get the files and their content, but API endpoint to upload files is still missing.

**Comment by adri9valle** [comment]
**Update 19.09.19**

Now the files are uploaded, working on improving the error handler:

![upload](https://user-images.githubusercontent.com/7983984/65259941-d10b2a00-db05-11e9-8275-e1e7c8425c6f.gif)

**Comment by adri9valle** [comment]
**Update 20.09.19**

This functionality is finished:

- Upload rules, decoders, and lists.
- Max 5 files.
- Max 300Kb per file.
- Check .xml extension in rules and decoders.
- Handle errors
    - Don't close the upload component in case of errors
    - In case of error list the files properly uploaded and the were not.
    - Icon to expand the error detail.

![finish](https://user-images.githubusercontent.com/7983984/65317359-f8acd180-db9b-11e9-9b1b-152b6b73d296.gif)

**Comment by adri9valle** [comment]
**Update 01.10.19**

Changed the style and fix when clicking again in import file and lose the popover content:

![image](https://user-images.githubusercontent.com/7983984/65948779-30890400-e43b-11e9-9eb8-81b5f50bfd78.png)
