### ISSUE TITLE
Health Check. 3002 - Cannot read property 'enabled' of undefined (/api/check-stored-api)

### ISSUE THREAD

**Issue by hregis** [wazuh/wazuh-kibana-app#1800]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.9.5   | 7.3.0     | ?|

![Capture d’écran 2019-09-15 à 13 30 36](https://user-images.githubusercontent.com/454387/64920928-333df500-d7bd-11e9-9180-a46474df0dec.png)

Thanks for your help

**Comment by juankaromo** [comment]
Hi @hregis 

This problem may be due to a wrong version between the version of your Wazuh server (manager and API) and the version for which the plugin is built. 

Could you check these two commands? 

`cat /usr/share/kibana/plugins/wazuh/package.json | grep version`

`curl -u foo:bar http://172.16.1.2:55000/version`

Please, paste the output here.

Regards.

**Comment by hregis** [comment]
@juankaromo 
thank you for your response

```
# cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.9.5",
    "version": "7.3.0"
```
```
# curl -ku ****:**** https://localhost:55000/version
{"error":0,"data":"v3.9.5"}
```

**Comment by juankaromo** [comment]
Hi @hregis 

Then it could be due to an incorrect cookie in the cache, perhaps due to an earlier version installed.

You need to delete all cookies stored in your browser and try to enter the Wazuh application again.

In Firefox you must press F12 to open the developer tools. In them, go to Storage, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/65033891-3adcd580-d946-11e9-98a7-872e2cfa6eff.png)

In Chrome you must press F12 to open the developer tools. In them, go to Application, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/65033919-492af180-d946-11e9-9196-eb85c0031cb0.png)

Tell us the results.

Regards.

**Comment by hregis** [comment]
@juankaromo  

yeeessss !!! :-) 
it's ok, 
thank you very much

**Comment by losteelos** [comment]
@juankaromo

I have the same issue and for me the proposed solution doesn't work. However my curl to the api returns:

curl: (52) Empty reply from server

The cat command returns the following:

cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.9.5",
    "version": "7.3.0"

Thanks in advance
