### ISSUE TITLE
Wazuh API configuration page error

### ISSUE THREAD

**Issue by Deanjp** [wazuh/wazuh-kibana-app#1808]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10 | 6.8.2   

**Description**
Following upgrade to 3.10 / 6.8.2 of all components. When I access foo.web/app/wazuh I'm redirected to the API configuration page. I enter the creds for the API user host and port. When I click the save button I get the following:
Settings. 2011 - Could not save data in elasticsearch due to [illegal_argument_exception] Rejecting mapping update to [.wazuh] as the final mapping would have more than 1 type: [wazuh-configuration, doc] (/elastic/api)

**Steps to reproduce**

1. Go to 'foo.web/app/wazuh#/settings?_g=()&tab=api'
2. fill in username, password, host, port fields and click save

Thanks in advance

**Comment by juankaromo** [comment]
Hi @Deanjp ,

This problem is usually due to you upgrading from a previous version of Wazuh. Previously hosts were saved with a document type of `wazuh-configuration` and now the type is `doc`. And the error that is appearing tells you exactly that, that there can be no documents of several types in the same index.

I would recommend that if you don't mind losing the APIS you have configured, you remove the `.wazuh` index so that new elements are created with the correct type.

```js
systemctl stop kibana
curl -XDELETE <elastic-ip>:9200/.wazuh
systemctl restart kibana
```

Wait a few seconds, then try again.

Regards.

**Comment by Deanjp** [comment]
Hi @juankaromo 
That fixed it!

Thanks for your help.

Dean
