### ISSUE TITLE
API reporting errors in Kibana app after upgrade from 3.9.5->3.10.2

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#1843]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10.2   | 6.8.3    | ? |

**Description**
Opening kibana app produces:
```
Health Check. 3002 - It seems the selected API was deleted. (/api/check-stored-api)
```
API and manager services running, app installed without issue, templates are fine, data is coming in. Its just the API connection. Other identical instances upgraded the same way are fine, not showing this issue. API configuration was fine as well, .wazuh index was deleted prior to configuring due to mapping conflict between the configuration 3.9.5 and 3.10.2 (in testing the new config couldn't be saved without removing the index).

**Steps to reproduce**

1. Go to Kibana app

**Comment by juankaromo** [comment]
Hi @sempervictus 

It could be due to an incorrect cookie in the cache, perhaps due to an earlier version installed.

You need to delete all cookies stored in your browser and try to enter the Wazuh application again.

In Firefox you must press F12 to open the developer tools. In them, go to Storage, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/65033891-3adcd580-d946-11e9-98a7-872e2cfa6eff.png)

In Chrome you must press F12 to open the developer tools. In them, go to Application, and Delete all <kibana_ip> cookies:

![image](https://user-images.githubusercontent.com/21195730/65033919-492af180-d946-11e9-9196-eb85c0031cb0.png)

Tell us the results.

Regards.

**Comment by sempervictus** [comment]
Verified & resolved, thank you.
Might want to force invalidation when a new app version is loaded?

**Comment by sempervictus** [comment]
Still get the mis-mapping problem on the .wazuh index, but that seems a sideffect of maintaining ELK6 and ELK7 versions...
