### ISSUE TITLE
Filters don't persist after a refresh

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kibana-app#1898]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.10   | 7.x     | 0543|

**Description**
When applying a filter in any dashboard within the UI, even if it is a pinned filter, if you refresh the browser's window the filters are lost.

**Steps to reproduce**

1. Go to any dashboard.
2. Apply a filter, pin it if you want.
3. Refresh window.
4. Filters are lost.

**Comment by juankaromo** [comment]
Hi @havidarou 

Due to the way in which the implicit filters in our panels are being applied, it is impossible for us to recover what we had when the user refreshes the browser since when changing the tab or refreshing, all the filters are erased and the implicit ones are applied again.

On the contrary, the pinned filters if we can recover them. We have made the change here: https://github.com/wazuh/wazuh-kibana-app/pull/1909

Thanks for the feedback!
