### ISSUE TITLE
Feedback and improvements in 3.12

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1945]
Hi team,

Some feedback for the 3.12 new features

- [x] Revert welcome redesign
![image](https://user-images.githubusercontent.com/21195730/70049993-3c757b80-15ce-11ea-8282-c38e36fbfd4b.png)

- [ ] Tables must show as many rows as fit in windows height.
![image](https://user-images.githubusercontent.com/21195730/70050052-5adb7700-15ce-11ea-918c-36abf1cca48d.png)

- [ ] Remove left side new menu
![image](https://user-images.githubusercontent.com/21195730/70050117-83637100-15ce-11ea-93a9-0684f6433fc1.png)

- [ ] Security events Top 5 users visualization is not shown properly
![image](https://user-images.githubusercontent.com/21195730/70050572-9a569300-15cf-11ea-90d7-148089f5977b.png)

- [x] Buttons without margin
![image](https://user-images.githubusercontent.com/21195730/70050623-b9552500-15cf-11ea-9476-1679d326a57c.png)

### MITRE 
- [ ] Fix new MITRE slides in low resolutions
![image](https://user-images.githubusercontent.com/21195730/70050084-734b9180-15ce-11ea-89ac-96443be504c9.png)

- [ ] Top tactics by agents not shows anything (maybe low resolution and agents name so long)
![image](https://user-images.githubusercontent.com/21195730/70050152-9a09c800-15ce-11ea-984c-6a82d9652f1c.png)
![image](https://user-images.githubusercontent.com/21195730/70050199-b3127900-15ce-11ea-8130-536229f92533.png)

- [x] Remove outside ring of MITRE attacks by agents (only two levels)
![image](https://user-images.githubusercontent.com/21195730/70050236-c6bddf80-15ce-11ea-8a60-f33ddd6469e1.png)

- [x] Full MITRE table clickable by row, no eye button 
![image](https://user-images.githubusercontent.com/21195730/70050289-e1905400-15ce-11ea-99ec-5d35a7fc87ac.png)

- [x] Attack detail flyout is so narrow (more width or centered modal)
![image](https://user-images.githubusercontent.com/21195730/70050325-f8cf4180-15ce-11ea-8549-48b669b1d453.png)

- [ ] Detail text is non-legible (is due to the response, evaluate it with the corresponding team)
![image](https://user-images.githubusercontent.com/21195730/70050450-421f9100-15cf-11ea-821f-7ca0d68d63a4.png)

- [x] Don't overlap the Wazuh API with the flyout
![image](https://user-images.githubusercontent.com/21195730/70050498-67140400-15cf-11ea-8512-4f4a3dc07a10.png)

- [ ] All columns must be sortable 
![image](https://user-images.githubusercontent.com/21195730/70050520-72ffc600-15cf-11ea-8572-0caaced2cc95.png)

- [x] Split elements in the arrays
![image](https://user-images.githubusercontent.com/21195730/70050544-827f0f00-15cf-11ea-9b78-f94b6c5ff32f.png)

**Comment by pablotr9** [comment]
**Update**

-  **Fix new MITRE slides in low resolutions**
This is only happening when using a side navigation bar, can't work on it until we decide what we do with the side navigation bar.

-  **Top tactics by agents not shows anything (maybe low resolution and agents name so long)**
As the title says, this is only happening when the agent's name is very long, it can be avoided in multiple ways.
Some possible solutions:
     1. Change horizontal bars to vertical bars:
![image](https://user-images.githubusercontent.com/35685689/70130650-3096c180-1681-11ea-9708-e5caedb6207a.png)

     2. Truncate agent name (on mouse hover we can see the full name):
![image](https://user-images.githubusercontent.com/35685689/70130498-f0cfda00-1680-11ea-9a0b-52b81aaa673d.png)
      3. Use a Pie chart (it looks like it adapts better to low resolutions):
![image](https://user-images.githubusercontent.com/35685689/70131260-422c9900-1682-11ea-82b9-aa11a94c332e.png)


- **Remove outside ring of MITRE attacks by agents (only two levels)**
Someone asked for that three levels visualization but it's true that it can be a bit confusing.
![image](https://user-images.githubusercontent.com/35685689/70133003-99803880-1685-11ea-9904-ce79f922f046.png)



- **Attack detail flyout is so narrow (more width or centered modal)**
The current size is 's', this is an example for default eui sizes and custom width:
    - 'm' 
![image](https://user-images.githubusercontent.com/35685689/70133518-920d5f00-1686-11ea-836c-84127dfdb63c.png)
     - 'l' 
![image](https://user-images.githubusercontent.com/35685689/70133724-f6c8b980-1686-11ea-9bd4-a6726c232f59.png)
     - Custom width (35% of the current window width) 
![image](https://user-images.githubusercontent.com/35685689/70134185-dc431000-1687-11ea-9021-fa8b73702691.png)


-  **Don't overlap the Wazuh API with the flyout**
It now looks as follows:
![image](https://user-images.githubusercontent.com/35685689/70134643-ca15a180-1688-11ea-8d10-2ac37787bd46.png)

-  **Split elements in the arrays**
![image](https://user-images.githubusercontent.com/35685689/70138708-1fee4780-1691-11ea-836e-5751efffdf4d.png)


- **Full MITRE table clickable by row, no eye button**
The `eye` button has been removed, we can now open extra details flyout by clicking on table rows.
![clickOnRow](https://user-images.githubusercontent.com/35685689/70139445-cdae2600-1692-11ea-97c1-5ea05dc44b95.gif)


-  **Detail text is non-legible (is due to the response, evaluate it with the corresponding team)**
We now transform the markdown text to HTML so we can now show the description correctly. (linebreaks are working, links are working as external links...)
![mitreFormatDescription](https://user-images.githubusercontent.com/35685689/70147847-5f269380-16a5-11ea-9532-bfa7cbaa39e2.gif)
