### ISSUE TITLE
Number of replicas set to 1 by default

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-kibana-app#1957]
| Wazuh | Elastic |
| ----- | ------- |
| 3.10.2   | 7.4.2     |

**Description**
Register the Wazuh API on a single host Elasticsearch cluster creates a replica for the .wazuh index.

**Steps to reproduce**

1. Create a single host Elasticsearch cluster.
2. Set up the Wazuh API.
3. The shard .wazuh has a replica that can't be allocated.

**Screenshots**
![image](https://user-images.githubusercontent.com/47329460/70812709-6bf36780-1dc8-11ea-8104-7e7c7d6a06bc.png)

**Additional context**

You may work around this issue by simply using:
```
PUT .wazuh/_settings
{
  "index.number_of_replicas": 0
}
```

**Comment by joselopezrio** [comment]
This is happening because the default `number_of_replicas` value of elastic is  0. Since we do not use a template for the `.wazuh` index, it is going to generate a replica of it and put the single node status of elastic to yellow. 
This could be easily solved by defining an `auto_expand_replicas` option as it is done with other indices like `.kibana`.
There is a closed elastic issue related to this --> https://github.com/elastic/elasticsearch/issues/33739

**Comment by MiguelCasaresRobles** [comment]
Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/1648

**Comment by juankaromo** [comment]
Hi, 

Since the last release of Wazuh 3.11.0, the .wazuh index has been deprecated in favor of the wazuh.yml configuration file, so this problem no longer applies.

If you have any other questions, problems or suggestions do not hesitate to open a new issue. I'm closing this one for now.

Regards,
