### ISSUE TITLE
API authentication with JWT token

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#1998]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.5     | X |

**Description**

We are going to transform the way we authenticate ourselves through the new **JWT** token-based system. The authentication system we were using until now will be deprecated and we have to implement the new solution based on **JWT** tokens

**Steps**

- [x] Analyze the current authentication system
- [x] Study the implementation of the new token-based system
- [x] Implementing the new authentication system 

Branch: [3.12.0-7.5.1-jwt-authentication](https://github.com/wazuh/wazuh-kibana-app/tree/3.12.0-7.5.1-jwt-authentication)

**Comment by Joanes04** [comment]
**Current API authentication**

Currently, our authentication system is done through **HTTPBasicAuth**, based on a username and password that are sent in the options in each of the requests we make to the **Wazuh API**. This user and password is stored in our **wazuh.yml** file, and in each of the requests to the **Wazuh API**, these values are read and added in the call. 

**New API authentication**

The new authentication system will be carried out using **tokens** managed by **JWT**. We'll have a username and password with which to make a request to the `/security/user/authenticate` method. This method will return a **token**, and with this **token** we can make the rest of our API calls.
The **token** has an expiration date and a token renewal system must be created to make it invisible to the **Wazuh** end user.

**Comment by Joanes04** [comment]
**Implementation of the new API authentication**

We have created an API interceptor in the BackEnd, so that all API requests always use that interceptor. This is a first version that follows the following flow:

![api-interceptor js (3)](https://user-images.githubusercontent.com/9945959/73169795-292dea80-40fd-11ea-82bc-d60dd5badba3.jpg)

As we can see from the diagram, the request is coming through to our interceptor. The first thing we do is check if we have a token stored in the `wazuh-registry.json` file. At this point we would have two alternatives:

**We have token**

If we have the token stored, we would make the request to the Wazuh API 4.0 through the AXIOS http client. If the API response is an error 401, it means that the token we have is no longer valid, so we have to update our authentication, and we will go to the other "alternative". If the response we get from the Wazuh API is correct (status: 200) or an error with status other than 401, we will return it to the BackEnd as a Wazuh API 4.0 response. 

**We don't have a token**

In case we don't have a token stored, we would make a request to Wazuh API 4.0 of : `/security/user/authenticate`. To make this request, we need the **user** and **password** stored in the `wazuh.yml` file. In case we don't have that **user** and **password**, we will return an error to the BackEnd informing about that error.

Once the token request to the Wazuh API 4.0, we have again two possibilities. If you return an error, we will return the error to the BackEnd informing that we cannot get the token. If we get the token, we store it in the `wazuh-registry.json`file and cycle it again from the beginning, with the new token stored and ready to use.

**Comment by Joanes04** [comment]
**UPDATE**

We found a bug, when we tried to get the wazuh-registry token if the wazuh-registry had never been initialized. We have to check that the hosts[id] exist, so that it doesn't skip an exception and cause an error.

> Old format

```
  async getTokenById(id) {
    try {
      if (!id) throw new Error('API id is missing');
      const hosts = await this.getHosts();
      return hosts[id].token || null;
    } catch (error) {
      log('update-registry:getTokenById', error.message || error);
      return Promise.reject(error);
    }
  }
```

> New format

```
  async getTokenById(id) {
    try {
      if (!id) throw new Error('API id is missing');
      const hosts = await this.getHosts();
      return hosts[id] ? hosts[id].token || null : null;
    } catch (error) {
      log('update-registry:getTokenById', error.message || error);
      return Promise.reject(error);
    }
  }
```
