### ISSUE TITLE
Agent status graph show incorrect number of never connected

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#20]
This is on `Overview > General`

![image](https://cloud.githubusercontent.com/assets/2720787/26063552/3b8fb644-3986-11e7-8952-5750b86bf6f9.png)

I have a total of 8 agents, but still get 1 as never connect on the graph.

![image](https://cloud.githubusercontent.com/assets/2720787/26063461/012cc320-3986-11e7-9fd4-0406f3a5c4b1.png)

**Comment by alberpilot** [comment]
Hello @rossengeorgiev 

In order to discard a Manager problem, please verify if the agent is connected writing in manager console:
/var/ossec/bin/agent_control -l

If the agent appears as "Active" it's necessary reboot the process **wazuh-modulesd**. For that:

1. Locate the PID of process:

` ps -xa | grep ossec`

  _761 ?        Ssl    0:00 /bin/node /var/ossec/api/app.js
 **1014 ?        Sl     0:02 /var/ossec/bin/wazuh-modulesd**
 1030 ?        S      0:00 /var/ossec/bin/ossec-execd
 1041 ?        S      0:04 /var/ossec/bin/ossec-analysisd
 1050 ?        S      0:00 /var/ossec/bin/ossec-logcollector
 1061 ?        Sl     0:00 /var/ossec/bin/ossec-remoted
 1338 ?        S      0:06 /var/ossec/bin/ossec-syscheckd
 1346 ?        S      0:00 /var/ossec/bin/ossec-monitord
 2765 pts/0    R+     0:00 grep --color=auto ossec_

2. Kill the process:
`sudo kill -9 1014 `

3. Start the process
`/var/ossec/bin/wazuh-modulesd &bg`

Please, let us know if it's works. 
Best regards,

**Comment by rossengeorgiev** [comment]
Keeps showing 1 disconnect, while `agent_control -l` shows all 8 agents as active

**Comment by havidarou** [comment]
Hi @rossengeorgiev we are currently thinking about how to fix this. 

It is not a Wazuh core issue, but an issue in the plugin itself.

Regards.

**Comment by rossengeorgiev** [comment]
Hi @havidarou sorry for the late answer, but I have seen the issue the latest versions. I will reopen if I do.

**Comment by rossengeorgiev** [comment]
Hi @havidarou sorry for the late answer, but I have seen the issue the latest versions. I will reopen if I do.

**Comment by havidarou** [comment]
Thanks @rossengeorgiev !
