### ISSUE TITLE
NFR: Add documentation for server.defaultRoute: "/app/wazuh"

### ISSUE THREAD

**Issue by mmccarn** [wazuh/wazuh-kibana-app#200]
Full disclosure: I'm a Kibana n00b...

It took me forever to figure out that adding this directive at the end of /etc/kibana/kibana.yml on [the virtual appliance](https://documentation.wazuh.com/current/installation-guide/virtual-machine.html) instructs Kibana to start on the Wazuh plugin homescreen:

```
server.defaultRoute: "/app/wazuh"
```

**Comment by jesusgn90** [comment]
Hi @mmccarn it sounds like you want to open Kibana and go directly to the Wazuh App and it's ok but keep in mind that many users are using Kibana and its own dashboards, discover... not only the Wazuh App. Also it could be an optional configuration but it's not a "must to be done" in order to work properly. We will consider your suggestion. Also consider that Wazuh App is a Kibana plugin.

If you are facing any other kind of issue, let us know. Have a nice day.

Best regards,
Jesús
