### ISSUE TITLE
wazuh-registry JSON broken and undocumented

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#2003]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.1   | 6.8.6    | 1 |

**Description**
Upgrade from 3.11.0 (the original broken one which devs pulled from the archive initially) errors out looking for `wazuh-registry.json` file.
There is no documentation for the fields or format of this file, an empty file produces errors, even with this content:
```
{"hosts":[null],"app-version":"3.11","app-revision":1}
```
which was modified by the app to create that `null` section, the following error is presented:

![image](https://user-images.githubusercontent.com/1331084/72359879-165af500-36bd-11ea-833a-79d77c0ffb5c.png)

What is the intended file format for that json file? The PR doesnt seem to have any template/scaffold for us to work from.

**Steps to reproduce**

1. Install 3.7, upgrade to 3.11.0, upgrade to 3.11.1
2. Try to access the kibana app

**Comment by sempervictus** [comment]
Ended up having to reinstall kibana, the app, remove the kibana and wazuh indices from ES, restart the stack, and it seems to be working now. If this isnt coming up for other people, it might have something to do with this setup running in a cluster.

**Comment by juankaromo** [comment]
Hi @sempervictus 

The `wazuh-version` file in the image no longer exists in 3.11, so if you get this error in 3.11 it may be due to browser caching issues.

This file has been renamed to `wazuh-registry` in 3.11, and it must be created automatically in the initialization of the app.

If you install the App as user kibana it should be created well by the `wazuh-registry.json`, but if you installed it as root with the `--allow-root` parameter it seems that it never creates it.

It is possible that this is because /usr/share/kibana/plugins/wazuh/ is created with root:root, and only the owner has write permissions.

So please remember for future occasions to install the app with the following command:

```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.4.2.zip
```
I hope you'll find it helpful.

Regards
