### ISSUE TITLE
I cant see Alerts and Security events!!

### ISSUE THREAD

**Issue by charleekpg** [wazuh/wazuh-kibana-app#2041]
Hi, 
I install the Wazuh infraestructure (single server), and i install one agent in a windows. The communication of the Agent and Wazuh, its ok:
![image](https://user-images.githubusercontent.com/33208750/73395588-976ddb00-42be-11ea-9eff-3ef8e4c55a29.png)

Additionally, i see the alerts.json, and i see that have info a lot of info (events).

But when i enter to discover --> wazuh-alerts-3.x-*, i cant see nothing:
![image](https://user-images.githubusercontent.com/33208750/73395719-d865ef80-42be-11ea-936a-1989e34d8ea7.png)

In discover --> wazuh-monitoring-3.x-*, i only view a bit of events (everything with 15 minutes of difference, and seems to be checks of the status of the agent)

![image](https://user-images.githubusercontent.com/33208750/73395777-ef0c4680-42be-11ea-8fa2-56e7621aaac4.png)

Additionally, i try to see the logs and i dont see nothing rare.
![image](https://user-images.githubusercontent.com/33208750/73396042-60e49000-42bf-11ea-9dea-b5bb4919598b.png) --> this events are old.

![image](https://user-images.githubusercontent.com/33208750/73396130-896c8a00-42bf-11ea-816d-ccbb8fdd5357.png)

[root@conf.d]# cat /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log | grep -i -E "error|warn"

![image](https://user-images.githubusercontent.com/33208750/73396202-ae60fd00-42bf-11ea-9de2-7ee72519e356.png)
 --> this events are old.

[root@satse01 conf.d]# cat /var/ossec/logs/ossec.log | grep -i -E "(error|warn)"
![image](https://user-images.githubusercontent.com/33208750/73396288-d3ee0680-42bf-11ea-914b-64f5fd0c65db.png) --> old events

Can you help me?

Thank you

**Comment by antoniojpascualv** [comment]
Hi Carlos,
Can you check your Index Management from the Management tab of Kibana to check if your index have actually a size different from 0?
It might be that the information is not reaching to elasticsearch from the alerts.json file

**Comment by dkempny** [comment]
Hello,
if the agent status is `Active` in `Kibana` but you do not see any alerts generated for the agent it could mean that the data is not reaching the Elasticsearch to be indexed there.

Because the alerts are present in the `alerts.json`, the problem can be with `Filebeat` or `Logstash`. Please, check if the daemons are running executing the following commands:

`# systemctl status filebeat`

and 

`# systemctl status logstash`

Please share the output of the above commands with us.

If the daemons are running please share with us your `Filebeat `and `Logstash` configuration as well.

**Comment by dkempny** [comment]
Hello,
we are discussing this issue on https://groups.google.com/forum/?hl=en#!topic/wazuh/hFCMzZSXO3Q

**Comment by juankaromo** [comment]
I close this issue because the problem has been fixed in the above thread. 

Regards.
