### ISSUE TITLE
Kibana wazuh plugin 7.6 install error

### ISSUE THREAD

**Issue by hregis** [wazuh/wazuh-kibana-app#2088]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.11.3   | 7.6.0     | ? |

**Description**

Debian stretch

after upgrading kibana with 7.6 version, i try to install wazuh plugin but i have this error message : 

`Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the force option."`

can you help me please ?

thank

**Comment by emiliodokter** [comment]
I have the same problem on CentOS7

**Comment by juankaromo** [comment]
Hi @hregis @emiliodokter 

It seems that after the last update of Kibana 7.6.0, the installation of the plugins must be done from the Kibana home directory. Please try these steps:

```
cd /usr/share/kibana
sudo -u kibana bin/kibana-plugin install <package-url>
```

I hope this helps and please, let us know the results.

Regards,
Juan Carlos

**Comment by hregis** [comment]
Hi @juankaromo 

it's ok ! Thank you !

**Comment by emiliodokter** [comment]
Hi @juankaromo 

That solution solved the problem. 
Thank you

**Comment by surendarsuren27** [comment]
@juankaromo 

Same issue for me but i am running the Kibana manually like /data/kibana/bin/kibana-plugin since i dont have root access. But i have full access where i'm running the kibana and elasticsearch.

Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option."

So my kibana is not in /usr/share/kibana but in /data/kibana/

**Comment by Joanes04** [comment]
Hi @surendarsuren27,

Since the release of Kibana 7.6.0, the installation of the plugins must be done from the Kibana home directory. Please try these steps:

```
cd /data/kibana
sudo -u kibana bin/kibana-plugin install <package-url>
```

I hope this helps you and please do not hesitate to ask.

Best Regards,
Alberto

**Comment by emnaFeda** [comment]
Hi, please i have the same problem i can' install plugin in kibana 7.6 and in the folder bin in kibana i have just kibana.plugin.bat.
the output in the console like this: so any help please??
C:\Users\pc\Downloads\FOD\Installation\kibana-7.6.0-windows-x86_64\bin>kibana-plugin install https://github.com/flexmonster/pivot-kibana/releases/download/v1.21/flexmonster_pivot-v1.21.zip

Found previous install attempt. Deleting...
Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option."

**Comment by ssamsonn** [comment]
Hi, Hi @surendarsuren27,

I have same problem. 

'' my dev configuration
 - kibana home : /kibana
 - kibana version : 7.6.1
 - plug-in : opendistro_security_kibana_pluing-1.6.0.0
''
After build the source, I tired install plug0in these steps:
''
 cd /kibana/bin
 ./kibana-plugin install file:///kibana/security-kibana-plugin/target/releases/opendistro_security_kibana_plugin-1.6.0.0.zip
Found previous install attempt. Deleting...
Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.

**Comment by ssamsonn** [comment]
> Hi, Hi @surendarsuren27,
> 
> I have same problem.
> 
> < my dev configuration >
> 
> * kibana home : /kibana
> * kibana version : 7.6.1
> * plug-in : opendistro_security_kibana_pluing-1.6.0.0
> 
> After build the source successfully, I tired install plug-in these steps:
> 
> > cd /kibana/bin
> > ./kibana-plugin install file:///kibana/security-kibana-plugin/target/releases/opendistro_security_kibana_plugin-1.6.0.0.zip
> > Found previous install attempt. Deleting...
> > Plugin installation was unsuccessful due to error "Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.

**Comment by juankaromo** [comment]
Hi @ssamsonn 

The installation of the plugin must be done from the **Kibana home directory**. Not from bin directory. Please try these steps:
````
cd /usr/share/kibana
sudo -u kibana bin/kibana-plugin install file:///kibana/security-kibana-plugin/target/releases/opendistro_security_kibana_plugin-1.6.0.0.zip
```

Regards,

**Comment by ssamsonn** [comment]
Hi @juankaromo

That solution solved the problem.
Thank you^^

**Comment by nadeeradasun** [comment]
Hi @juankaromo,

I have the same issue, but i'm working on windows server 2019. Could you please suggest a solution.

Thnak You,
Nadeera.
