### ISSUE TITLE
Configuring Wazuh-Kibana-App to use an alternative index

### ISSUE THREAD

**Issue by hoboscientist** [wazuh/wazuh-kibana-app#211]
Hey. I am working on a monitoring system and I decided to add wazuh into it. But the problem is we are forwarding all the logs into a single index, "xyz", now is there any way that I can configure wazuh to work with the xyz index instead of the regular wazuh-alerts and wazuh-monitoring. I am using ELK Stack 5.6.5 and Wazuh 2.1. Regards.

**Comment by JuanjiJG** [comment]
Hi @hoboscientist,

Our 2.1 version of the app can only work with the `wazuh-alerts` and `wazuh-monitoring` index patterns. That's because we use a specific template in order to properly filter the alerts data provided by Elasticsearch and show the app visualizations correctly.

On our latest version of the Wazuh App for Wazuh 3.1 and Elastic 6.1.2, you can configure the index pattern for the app on the Settings tab, but it must match the pattern of `wazuh-alerts*`, in any other case it warns you that the app won't work correctly.

Feel free to ask more questions if you still have doubts about anything related to the Wazuh App.

Best regards,
Juanjo

**Comment by hoboscientist** [comment]
Does Wazuh 3.1 including App and Api work for ELK Stack 5.6.5 ? And does the configured pattern must be "wazuh-alerts*" or it could be any other like "Rigo*" ?

**Comment by JuanjiJG** [comment]
Hi again @hoboscientist,

Wazuh 3.1 works with Elastic 6. You need to upgrade your current Elastic Stack installation in order to work properly. You can follow our upgrading guide if you want: https://documentation.wazuh.com/current/installation-guide/upgrading/index.html

Regarding your question about if it's possible to use a different pattern, in theory **you can**, but you have to keep in mind that it's necessary to modify several configuration files in order to work properly:

1. First, you need to edit the **[configuration file](https://documentation.wazuh.com/3.x/installation-guide/installing-elastic-stack/elastic_server_rpm.html#logstash)** for Logstash. On the `output` section you can find something like this:
```
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
        document_type => "wazuh"
    }
}
```

2. Second, you need to edit the **[Elasticsearch templates](https://documentation.wazuh.com/3.x/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elasticsearch)** and the sample alert that we provide in our installation guide. These templates use the `"template": "wazuh-alerts-3.x-*"` key-value pair, and you can edit it.

3. And finally, you need to open the `package.json` file and edit the `initialPattern` value with the appropriate pattern that you want to use on the Wazuh App.

If you still have more questions, feel free to comment again.

Best regards,
Juanjo

**Comment by hoboscientist** [comment]
Is this workaround applicable to Wazuh 2.x ?

**Comment by JuanjiJG** [comment]
Hi @hoboscientist,

Unfortunately, it isn't. Our 2.1 version of the Wazuh App only works with the `wazuh-alerts` and `wazuh-monitoring` index patterns. In this previous version, the patterns were hard-coded severely throughout the entire app.

If you want to replace the default index-pattern on the app, you need our latest version, which is compatible with Wazuh 3.1 and the Elastic Stack 6.1.2.

Best regards,
Juanjo

**Comment by hoboscientist** [comment]
Hey @JuanjiJG, 

Thank you for your time and help. I am looking forward to working on ELK Stack 6. 

Regards,
Ashim

**Comment by JuanjiJG** [comment]
Hi @hoboscientist,

Thanks to you for using Wazuh! Don't hesitate to post a new issue if you have more doubts or problems about it.

Best regards,
Juanjo
