### ISSUE TITLE
Reporting in Security Events error

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2120]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12.0  | 7.6.0     | 590 |

**Description**
When creating a report in **Overview > Security events** an error occurs:

![image](https://user-images.githubusercontent.com/9945959/76007177-a0fceb00-5edb-11ea-9789-3d81902a204f.png)

**Steps to reproduce**

1. Go to 'Visualize'
2. Click on 'Security events'
3. Click on 'Generate reports'

**Comment by juankaromo** [comment]
Hi @Joanes04 

This problem was only happening when generating pdfs in Google Chrome browser. It seems that since version 72 of the browser some errors occur with SVG (https://stackoverflow.com/questions/54453987/did-chrome-72-break-dataimage-svgxmlutf8-for-css-background-svgs).

I detected where it broke and set a condition to skip the broken visualizations.

I have also modified the library to generate the reports so that the sources are not downloaded, and to improve the performance.

Everything done is in this commit https://github.com/wazuh/wazuh-kibana-app/commit/18023447c6279d385df84d7f4a5663ed2167fdb5

Regards.
