### ISSUE TITLE
Enriching error messages

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-kibana-app#2215]
Hi team,

We need to give more information to the user when an error occurs in the app. Right now we report that an error has occurred in a certain module or service, but we don't specify what type of error.

For example, during the health check if there is an error in the API we are simply told that the connection is unreachable, but we are not told why, even though the response to the request gives us the reason. We have to show it. 

- [x] Review errors that appear in health check
- [x] Review errors that appear in API settings section
- [x] Review errors that appear in toasts
- [x] Review errors that appear in file validations

Regards,

**Comment by Desvelao** [comment]
## Update
- Services migrated from AngularJS to ReactJS:
  - *ErrorHandler*
  - *CheckDaemonsStatus*
- The references to AngularJS  `errorHandler` service are still in the code.
- Let through errors when they are strings in **healthcheck** and **app settings** sections.
- Improved some messages.

TODO:
- [ ] remove some `console.log` found. Pending of accept.
- [ ] remove references AngularJS `errorHandler` service in controllers. Pending of accept.
- [ ] review error toasts
- [ ] review error in file validations

A strange behavior has been detected when you wanted to upload a cdb list with the same name as an existing one. The `catch` block in `WzRequest.generiqReq` service returns a `error.message` as `Request failed with status code 500` instead the original backend response with `Wazuh API error: 1905 - File was not updated because it already exists`. It seems that the original response coming in `error.response.data`. More info about this: https://github.com/axios/axios/issues/960. Same behavior has been experimented in sample data request section.

**Comment by pablotr9** [comment]
**Update**

Fixed the error message when there is something wrong in the wazuh.yml:
![image](https://user-images.githubusercontent.com/35685689/83851959-62154600-a713-11ea-9176-718edcfea046.png)
---
![image](https://user-images.githubusercontent.com/35685689/83852942-d69cb480-a714-11ea-9f4f-c8033f35b614.png)

Fixed the error message when an API connection failed
![image](https://user-images.githubusercontent.com/35685689/83852050-7f4a1480-a713-11ea-8b1f-b2cb083528bc.png)

-----
![image](https://user-images.githubusercontent.com/35685689/83852829-ac4af700-a714-11ea-9ebd-36d6777e0db6.png)
