### ISSUE TITLE
Alert Summary Export links Raw and formated not working

### ISSUE THREAD

**Issue by arthymian** [wazuh/wazuh-kibana-app#2224]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
CentOS 7
Wazuh 3.12.3
Wazuh API 3.12.3
Elasticsearch 7.6.2
Filebeat 7.6.2
Kibana 7.6.2
Wazuh app 3.12.3-7.6.2

**Description**
Im testing the wazuh VM and for some reason i cant export security or integrity summary alerts
on the raw or formatted links

**Steps to reproduce**

1. Go to 'kibana>Wazuh>Overview>Security Events'
2. Click on 'change time interval to 90 days' "gets me 5 pages of logs"
3. Scroll down to "near under the alerts list to the left, on the raw or formated links"
4. they dont work if the interval is more than 1 page of alerts

**Screenshots**
![image](https://user-images.githubusercontent.com/5605193/81237813-69eca800-8ff8-11ea-9655-8f9220b2771c.png)

**Comment by juankaromo** [comment]
Hi @arthymian 

Thank you for reporting this bug to us. I have to inform you that in the next release of Wazuh, version 3.13, these visualizations as a summary table of alerts will disappear. 

That's because the data shown in these tables are not real, and are, as its name indicates, a summary of a significant sample of the stored data chosen by Elasticsearch. It is for this reason that we have decided to remove them in favor of the Events overview (currently the discover view) that shows information of all the stored data.

Regards!
