### ISSUE TITLE
Store wazuh inventory data in elasticsearch

### ISSUE THREAD

**Issue by gittygoo** [wazuh/wazuh-kibana-app#2233]
**Describe the solution you'd like**
Currently the inventory data (and others) is being stored on an sqlite db on /var/ossec/queue/db/* there should be an option to store this on elasticsearch aswell.

**Additional context**
Ideally we would like to take the "space consumption" from the manager side and keep all the data on elasticsearch also that we can co-relate data easier

**Comment by juankaromo** [comment]
Hi @gittygoo 

In the near future we will start to store in Elasticsearch the states of all the modules, among them Inventory data of an agent. This will help us to have a follow up of how a module evolves through time. 

It's on our roadmap, so keep an eye out for new issues because we'll start working on it soon.

Best regards,

**Comment by PGBI** [comment]
@juankaromo Has this ever been implemented? We were confused as to why our disk space was filling up although we configured Wazuh to store data in an Elasticsearch cluster.
If not, is there an unclosed ticket I could follow?
