### ISSUE TITLE
New index pattern 

### ISSUE THREAD

**Issue by rwagner-inf** [wazuh/wazuh-kibana-app#23]
Hello Guys!

Could you consider creating another index besides wazuh-alerts automatically?
I would like wazuhapp already to create an index for the file /var/ossec/logs/archives/archives.json.

Another doubt. If I use the wazuhapp plugin I still need to use "template =>" /etc/logstash/wazuh-elastic5-template.json "in the logstash configuration, since the wazuh app automatically creates the index?

I used it in my logstash configuration and the following occurred:
Wazuhapp created the wazuh-alerts index with all the fields with the "searchable" and "aggregatable" options checked, until then all OK. After a while I updated the index on the management page and in most of the fields the options "searchable" and "aggregatable" disappeared.

It would not be necessary to display the data for this index on the wazuhapp dashboards.
What I want is for the wazuh-archives index to have the same wazuh-alerts setting, that all fields have "searchable" and "aggregatable" checked.

**Comment by snaow** [comment]
Hi @rwagner-inf !

Nice to see you again. Let me put together some answers.

> Could you consider creating another index besides wazuh-alerts automatically?
> I would like wazuhapp already to create an index for the file /var/ossec/logs/archives/archives.json.

Since not all our users are going to enable(and forward) "archives" option from Wazuh, we can not create an index-pattern for no existing indices (if we detect more and more users start using this, we could set up it by default as we do with the current wazuh-alerts-* indices)

You could create the index manually (one-time configuration). I am not sure if you took a look into the archives.json tutorial I created some days ago, @santiago-bassett  wrote it at:

[https://groups.google.com/d/msg/wazuh/Y_hKnH4Vep4/O-XTBOHHBwAJ](https://groups.google.com/d/msg/wazuh/Y_hKnH4Vep4/O-XTBOHHBwAJ)

> Another doubt. If I use the wazuhapp plugin I still need to use "template =>" /etc/logstash/wazuh-elastic5-template.json "in the logstash configuration, since the wazuh app automatically creates the index?

Partially correct, you don't need that configuration (template) in Logstash because Wazuh App set up the template on the first boot, but that is not related to the index creation.
Index creating is made daily when Logstash [insert a new document](https://github.com/wazuh/wazuh/blob/master/extensions/logstash/01-wazuh.conf#L37).

Still we recommend to keep the template configuration in Logstash, it will act as a double-check on the environment to make sure template is loaded and ready.

> I used it in my logstash configuration and the following occurred:
> Wazuhapp created the wazuh-alerts index with all the fields with the "searchable" and "aggregatable" options checked, until then all OK. After a while I updated the index on the management page and in most of the fields the options "searchable" and "aggregatable" disappeared.
> 

On the beginning (some months ago), Wazuh App, by default, was forcing all the index pattern fields to be "searchable" and "aggregatable", that way Kibana will allow us to draw visualizations without having data on the index ("Saved field is now invalid" error).
Currently we are inserting a sample alert, which is less elegant but more reliable, meaning we don't need to force the index pattern, you could refresh it as many times as you need and the App will keep working, don't worry about all fields not being checked.
I believe we will remove the index-pattern forcing in further releases.

> What I want is for the wazuh-archives index to have the same wazuh-alerts setting, that all fields have "searchable" and "aggregatable" checked.

What is exactly your intention? Create visualizations using data "not being there" already?
The process of forcing an index-pattern is tricky, we are "cheating" Kibana to be as we need, I won't recommend it, that is why we switch from "forcing index pattern" to "inserting sample alert".

I hope Kibana guys fix this error, since version 5.0.1 any user is able to create visualizations using fields which are not present on the indices.

I hope it helps, let us know any questions.

Best,
Pedro.

**Comment by rwagner-inf** [comment]
Hi @snaow, thanks for reply!

> You could create the index manually (one-time configuration). I am not sure if you took a look into the archives.json tutorial I created some days ago, @santiago-bassett wrote it at:
https://groups.google.com/d/msg/wazuh/Y_hKnH4Vep4/O-XTBOHHBwAJ

Yes, I took a look at the tutorial, congratulations to the tutorial. I have run it, and after following the tutorial steps the indices are created, but as I said, the fields in the "wazuh-archives- *" index do not have the "searchable" and "aggregatable" options checked for all items, only The "wazuh-alerts- *" has this characteristic.

I spent the morning trying to tweak it in wazuhapp, for it to create the index "wazuh-archives- *" automatically and with the "searchable" and "aggregatable" options in all the fields. I got it!

I have modified the following files:
/usr/share/kibana/plugins/wazuh/server/startup/initialize.js
/usr/share/kibana/plugins/wazuh/server/startup/integration_files/kibana_fields_file.json
/usr/share/kibana/plugins/wazuh/server/startup/integration_files/objects_file.json
/usr/share/kibana/plugins/wazuh/server/api/wazuh-elastic.js

If you want I'll give you the files so that you can check the modifications I've made.

> What is exactly your intention? Create visualizations using data "not being there" already?

Exactly, the intent is to create visualizations and do searches in an easier way.
I also collect information from "archives.json" and would like to make it easy for the index created for it. I'm not even using much now, but when I need to, I know this would be ready to be used.

> but that is not related to the index creation.
Index creating is made daily when Logstash insert a new document.

I do not understand much about this template file, what this file does. Can I use it to set the "searchable" and "aggregatable" options?
I have to learn more about it. If you have any specific material on that would appreciate it. I do not really like elastic documentation, I think it's unintuitive.

Thanks again for your help @snaow!
And sorry for the English.

**Comment by snaow** [comment]
Hi @rwagner-inf,

No worries for the English, believe me, English is not my best skill neither.

It's great you modified Wazuh Apps source code for replicate alerts index pattern behaviour for archives.

The template file set a mapping for the index creation, meaning, when a new index is created and match for a template, fields type are set according to the template content.
This is not related with "aggregatable" and "searchable" which is built-in on Kibana, Elasticsearch is working on a "field_capabilities" API to make us able to set those setting as we needed, currently, there is no way to manually set anything.

Be aware of forcing index-pattern by modifying .kibana documents, I was doing that on Wazuh App to get set all fields "aggregatable" and "searchable" but due to it is not the normal Kibana behaviour when you click on "Refresh" all the index pattern will become different.
That is why we are now inserting a "Same alert" containing all the needed fields and making Kibana able to draw all the visualizations we need.

Thanks for the feedback, interest and contributions.
Cheers,
Pedro 'snaow' Sanchez.

**Comment by rwagner-inf** [comment]
Ok Pedro!
I hope Wazuh continues to grow, I am grateful to know that I am contributing in some way.

Thanks for your attention!
