### ISSUE TITLE
Wazuh app package v.3.13.0 for Kibana with version 6.8.8 is missed 

### ISSUE THREAD

**Issue by slushz** [wazuh/wazuh-kibana-app#2380]
Hi!, the v.3.13.0 wazuh app package for Kibana with version 6.8.8 is missed.

root@XXXXX:/usr/share/kibana# sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.0_6.8.8.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.0_6.8.8.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.0_6.8.8.zip/https://packages.wazuh.com/wazuhapp/wazuhapp-3.13.0_6.8.8.zip-6.8.8.zip
Plugin installation was unsuccessful due to error "No valid url specified."
root@XXXXX:/usr/share/kibana# 

Could you please prepare package?

Thank you in advance!

**Comment by juankaromo** [comment]
Hi @slushz ,

I am sorry to tell you that the latest version of Wazuh 3.13.0 was released with support for the latest stable ELK version 7.7.1 (at the time) and for the latest version with Open Distro support at the time (7.7.0). Recently both the new ELK release 7.8.0 and the new Open Distro version 1.9.0 were released, which also supports Elastic version 7.8.0. For all these versions that I tell you Wazuh is already compatible.

The problem with the old versions is that in this new version of Wazuh we have made many improvements and implemented certain features that use Kibana's functionalities that are only available from version 7.7.0. For this reason we have stopped supporting the 6.8 branch of the ELK.

For my part, I encourage you, if possible, to upgrade your environment to 7.8.0 so that you can try out all the new features offered by the new version of Wazuh 3.13.0. Here https://documentation.wazuh.com/3.13/release-notes/release_3_13_0.html you can see all the new features it includes, and here https://documentation.wazuh.com/3.13/upgrade-guide/index.html you can find our update guide that will be very useful.

Regards,
