### ISSUE TITLE
Error disabling basic_auth in API settings

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh-kibana-app#2397]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.8     | XXX |

**Description**

If we disable the `basic_auth` in the file: `/var/ossec/api/configuration/config.js`the application keeps asking for the **user** and **password** fields to keep working. It would be necessary to control that configuration, to put obligatory or not the fields **user** and **password**

**Steps to reproduce**

1. Go to` '/var/ossec/api/configuration/config.js' ` file
2. Edit the config **basic_auth** to "no"
3. Open the Wazuh UI

**Screenshots**

![image](https://user-images.githubusercontent.com/9945959/88166756-10b80c00-cc18-11ea-91b8-6f54241671e8.png)

**Comment by Yashvendra** [comment]
Hi,

This issue is also present when using **_wazuh-plugin==3.12.3_** and **_Kibana==7.7.1_** which is claimed to be compatible according to this [matrix](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix).

However, it seems to be working fine when using **_wazuh-plugin==3.13.0_** and **_Kibana==7.7.1_**. In this combination, when we disable the authentication for wazuh-API, kibana works absolutely fine with no credentials supplied in `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`

**Comment by victorst79** [comment]
Hi @Yashvendra,

This bug will become deprecated, in the next version of Wazuh "_basic_auth_" it will be **deprecated**, this option can no longer be disabled. Authentication is now always done using the JWT token.

Stay up to date with our updates to install the new version of Wazuh.

Regards,
Victor Santaella.
