### ISSUE TITLE
SCA checks limit

### ISSUE THREAD

**Issue by odintree** [wazuh/wazuh-kibana-app#2460]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.13   | 7.8   | 444 |

**Description**
Hi team, 

While testing these SCA policies:
- https://github.com/wazuh/wazuh-ruleset/blob/4.0-SCA/sca/debian/cis_debian10.yml
- https://github.com/wazuh/wazuh-ruleset/tree/4.0-SCA/sca/rhel/cis_rhel7_linux.yml

In the `SCA` section I noticed that the amount of checks shown is not the same that the number of checks within the policy.
It looks like the generated CSV file shows a different number of checks too.

**Steps to reproduce**

1. Download the `cis_debian10.yml` or `cis_rhel7_linux.yml` policies and place them in the `agent` instance under `/var/ossec/ruleset/sca`. 
2. Go to Agents > `agent name` > SCA, then the policy. 
3. Click on `Export Formatted` to download the CSV file.

**Screenshots**
On the screenshot below you will be able to see the result of the policy `cis_debian10.yml`. It says there are 70 (Pass) +  115 (Fail) +  7(Not applicable) = 192. In the list we could see that there are: 7 (pages) * 10 (per page) - 1 (since the last page got 9 events) = 69. 
![image](https://user-images.githubusercontent.com/23520694/92958937-63b97d00-f46b-11ea-9022-33b4fc58c3b3.png)
Here is the screenshot of the CSV content that we can generate: 
![image](https://user-images.githubusercontent.com/23520694/92959425-17bb0800-f46c-11ea-9ac5-2b8ac0079717.png)
It has 88 events (the first line is a header). 

The same thing happen with `cis_rhel7_linux.yml` policy: 
![image](https://user-images.githubusercontent.com/23520694/92959520-433df280-f46c-11ea-9f7f-2f10f9b7b793.png)
![image](https://user-images.githubusercontent.com/23520694/92959556-52bd3b80-f46c-11ea-9e3b-7ff604bc8f5c.png)
183 vs 65 vs 100 (in the CSV) 

**Additional context**
Here is the example of the SCA from this version it has no issue here:
![image](https://user-images.githubusercontent.com/23520694/92959727-a039a880-f46c-11ea-93bf-d2e096779e79.png)
Also, the CSV has correct amount of events

Kind regards,
Do Tuan Anh.

**Comment by mikykeane** [comment]
Adding to this issue. In the main dashboard, I could only see the last 65 policies in the RHEL7 new SCA policy. 

But if I do queries. I can see any check that I want:

![image](https://user-images.githubusercontent.com/4438081/96775401-cba6a000-13e7-11eb-9ac4-50b1f77794cd.png)


But otherwise, this one is the first that I can see:

![image](https://user-images.githubusercontent.com/4438081/96775566-fee92f00-13e7-11eb-92e3-43b87619d54c.png)




Testing, it seems is not about the number of events. But about the size of them. In the new one, events have much more information. Adding new compliances and longer Descriptions. But if I do them with simpler ones, I can see more in Kibana, though not all of them. See the image attached. In this example, events started at 63, missing 62 checks and we could go up to page 16. Seeing well over 100 checks

![image](https://user-images.githubusercontent.com/4438081/96778543-23470a80-13ec-11eb-985e-13997e143077.png)

**Comment by Desvelao** [comment]
It depends on https://github.com/wazuh/wazuh/pull/6064. When the merge is ready, it requires to be checked if that solves the problem in WUI.

**Comment by frankeros** [comment]
Hi team, 
we checked this issue with branch 4.0.1 of wazuh.
Both mentioned rulesets return the items properly now. The items are
![cis_debian10](https://user-images.githubusercontent.com/26828184/98378674-1bf74200-2025-11eb-8ab5-45a36de2f78e.png)
![cis_rhel7](https://user-images.githubusercontent.com/26828184/98378689-20bbf600-2025-11eb-9e82-17914ff388e5.png)

Currently, there is an issue with the search bar of this section in our branch 4.0-7.9. But there is fix that resolves this, and it is closet to be merged.
Tested with https://github.com/wazuh/wazuh-kibana-app/tree/4.0-7.9-fix-sca-checks
![image](https://user-images.githubusercontent.com/26828184/98378725-29acc780-2025-11eb-8016-e8f835924323.png)
