### ISSUE TITLE
"Field" is a required parameter on some tabs in app

### ISSUE THREAD

**Issue by dizaar** [wazuh/wazuh-kibana-app#2504]
| Wazuh | Elastic   | Rev |
| ------- | ------   |  --- |
| 3.13.2  | 7.8.0     |   ?   |

Hi, installed and configured last wazuh-manager, wazuh-api and kibana app. I can connect agents, can see some details from agent tab. But clicking "System auditing", "Security events" raises an error "Field is a required parameter", "Inegrity monitoring" gives just "Internal server error".
![изображение](https://user-images.githubusercontent.com/17981664/94615333-42042680-02b0-11eb-88fa-109ff1f428dc.png)
A bit stuck where to look for the error.
Wazuh manager and api are on a different host rather kibana. Template is loaded from repo, but patterns pointed there are wazuh-alerts-4.x-*, wazuh-monitoring-4x-*. When I start service after several minutes I see that patter wazuh-alerts-3.x is created. Please help to find miconfiguration in my setup. Thx.

**Comment by jsanchez91** [comment]
Hi @dizaar 

Yes, your problem is that you don't have the right template. You could tell me the documentation you followed to install and configure the Filebeat module.

On the other hand, follow these steps to change the template:

1. Download the template:
```bash
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.13.2/extensions/elasticsearch/7.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json
```

2. Restart filebeat:
```bash
systemctl restart filebeat
```

3. Check if the template has been updated
```bash
curl http://[YOUR_ELASTIC_HOST]:9200/_cat/templates | grep wazuh

# Response
```

Let me know if these steps fix your problem.
Regards,
Jose.

**Comment by dizaar** [comment]
Hi, @jsanchez91. Steps you provided helped to fix template issue and i found my mistake - i was using template from master branch. But error with "Field is required" is still present.

**Comment by jsanchez91** [comment]
Hi @dizaar,

The error 'Field is required' can be caused by two reasons:

1. The index pattern is wrong, go to Kibana -> Management -> Index Patterns, select your wazuh-alerts-* index pattern and press the trash button.
![image](https://user-images.githubusercontent.com/3064506/94670585-0c445980-0313-11eb-81ce-70db30bd1a04.png)

Then go to the WazuhUI, this will create the index pattern again
![image](https://user-images.githubusercontent.com/3064506/94670697-2ed67280-0313-11eb-981e-f83efdd1edc1.png)

Enter any dashboard to check if the error persists.

2. If the error persists, the "wazuh-alert" indexes may be wrong.
The quickest solution is to remove the indexes so that new ones are generated correctly.

```bash
curl -XDELETE http://[YOUR_ELASTIC_HOST]:9200/wazuh-alerts-*
```
If you cannot remove the indexes because they contain sensitive information you can re-index all the documents to match the template by following the steps described in this Issue:
https://github.com/wazuh/wazuh-kibana-app/issues/2403#issuecomment-664856961

**Comment by dizaar** [comment]
@jsanchez91, You're awesome. Thank You so much. Everything works like a charm after indices deletion. I think, I missed something during install or have been lost in copying/pasting some commands. Everything is great. You're doing a great job. I appreciate this.
