### ISSUE TITLE
App fails to load if index pattern renamed and doesn't start with "wazuh".

### ISSUE THREAD

**Issue by jjrbg** [wazuh/wazuh-kibana-app#2508]
**Description**
App fails to load if index pattern renamed and doesn't start with "wazuh".

**Steps to reproduce**

1. Change index pattern used by filebeat according to this guide: https://documentation.wazuh.com/3.13/user-manual/kibana-app/reference/configure-indices.html
2. Open Wazuh App

**Additional context**
getListOfIndexPatterns function only considers index patterns matching "wazuh*" to be valid.

https://github.com/wazuh/wazuh-kibana-app/blame/master/public/react-services/saved-objects.js#L25

If index patterns must start with "wazuh" then the documentation should state this, otherwise, this should pull in the "pattern" configuration variable from wazuh.yml?

**Comment by Desvelao** [comment]
Hi @jjrbg 

You are right, the Wazuh app is considering index patterns starting with `wazuh` in `v3.13`. It's a known bug that it will be fixed in `v4.0`.

As a workaround, you could fix it modifying the Wazuh app source code. To do this:
1. Stop the Kibana service.
2. Open the file `/usr/share/kibana/plugins/wazuh/public/react-services/saved-objects.js` and edit the line:
https://github.com/wazuh/wazuh-kibana-app/blob/269d65b08b6f7ac17f5838261a8e0a46646089d0/public/react-services/saved-objects.js#L25

removing the `&search=wazuh*`

so the line should look like this: 
```
`/api/saved_objects/_find?type=index-pattern&search_fields=title`
```
3. Remove the bundles:
`rm -rf /usr/share/kibana/optimize/bundles`
4. Restart the Kibana service:
This can take a few time because it will recreate the new bundles.

Please let me know if it helps.

**Comment by jjrbg** [comment]
Thanks Toni,
I’ve already amended the src and forced a reoptimize.

When you say it’s a known bug - is there an Issue on GitHub? I couldn’t
find one.

Thanks again

**Comment by Desvelao** [comment]
No issue was created to solve this problem exclusively, but it was mentioned in this issue https://github.com/wazuh/wazuh-kibana-app/issues/2461#issuecomment-691853341.

The solution of this problem, it was included in this commit: https://github.com/wazuh/wazuh-kibana-app/commit/2983841eb38cf90415c717431844c66b561b496b#diff-633288369b70190d7c7c854f3bd152ccL26

**Comment by jsanchez91** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.
