### ISSUE TITLE
No data in statistics and monitoring indexes

### ISSUE THREAD

**Issue by fuzzy-one** [wazuh/wazuh-kibana-app#2670]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.3   | 7.9.1     | 4014 |

**Description**
No data in statistics and monitoring indexes. I was not able to locate any error in kibana or elasticsearch logs. This functionality was working before upgrading from 3.x to 4.x.

**Screenshots**
![image](https://user-images.githubusercontent.com/1921285/100871754-70b59d80-34a9-11eb-8342-d326bd917f1d.png)

![image](https://user-images.githubusercontent.com/1921285/100871588-2e8c5c00-34a9-11eb-8c7f-651143b2600a.png)

![image](https://user-images.githubusercontent.com/1921285/100871636-42d05900-34a9-11eb-9666-3e6790d4923a.png)

![image](https://user-images.githubusercontent.com/1921285/100871654-4b289400-34a9-11eb-80d4-3c39e21e2907.png)

![image](https://user-images.githubusercontent.com/1921285/100871445-fab13680-34a8-11eb-9ebe-54d65328b7ad.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by frankeros** [comment]
Hi @fuzzy-one 
do you still have the same problem?

**Comment by fuzzy-one** [comment]
Hi @frankeros 
Yes, I'm still having this issue and have not made any progress identifying the cause.

**Comment by frankeros** [comment]
Hi @fuzzy-one

In order to check if the indices are generating properly, you can run in Kibana (menú) / Dev Tools this query
`GET _cat/indices`
it should return something like this
![image](https://user-images.githubusercontent.com/26828184/102612101-e60ea880-410e-11eb-9c05-545c77f80f23.png)

----

Also, you can check in Kibana (menú) / Discover if the index pattern `wazuh-monitoring`-* and `wazuh-statistics-*` are really empty
![image](https://user-images.githubusercontent.com/26828184/102612967-77324f00-4110-11eb-9a6e-5bbb937300ec.png)
remember to put a large time interval to obtain as much data as possible

----

Finally, I invite you to review the migration [guide](https://documentation.wazuh.com/4.0/upgrade-guide/index.html), in order to check if all steps were successfully completed.

Please, let me know any feedback

Regards

**Comment by bpickhardt** [comment]
I'm also seeing my indexes for wazuh-monitoring after the 4.x upgrade not working correctly.  It is occurring on all 3 of my Wazuh instances after the upgrade I did in December.  I discovered this today while I was reviewing the indexes on the ELK server.  What I am seeing is that there is a wazuh-monitoring index for each day of the month in December but that all of the indexes created after the upgrade to 4.x have 0 documents in them.  I've been looking around trying to figure out what could cause the task that runs to add documents to not run and had little success.

I can verify that I followed that upgrade document when I performed the upgrade in December and upon review I do not believe I missed any steps.  I'm considering reinstalling the Kibana plugin but I'm unsure if that will help as I don't know where the scheduled task to add the docs runs.

![image](https://user-images.githubusercontent.com/39538529/103946081-cd852300-50fb-11eb-8a71-ba1a0b601552.png)

**Comment by frankeros** [comment]
Hi @bpickhardt 
can you check if you have the index template for monitoring? In Kibana / Dev Tools run 
`GET _template/wazuh-agent`

**Comment by bpickhardt** [comment]
> Hi @bpickhardt
> can you check if you have the index template for monitoring? Please run in Kibana / Dev Tools
> `GET _template/wazuh-agent`

Looks like the template exists.
![image](https://user-images.githubusercontent.com/39538529/104518141-df177080-55bc-11eb-8934-61c89d764e1f.png)

**Comment by frankeros** [comment]
to check if the index pattern has the correct title, can you share the result of this query from Kibana / Dev tools, please? 
```json
GET _search
{
  "_source": "index-pattern.title", 
  "query": {
    "match": {
      "type": "index-pattern"
    }
  }
}
```

**Comment by bpickhardt** [comment]
Here's the results of that.  I removed my filebeat indexes from the output. It seems off the non 3.x indexes created with 4.x are not there.

`
{
  "took" : 2963,
  "timed_out" : false,
  "_shards" : {
    "total" : 63,
    "successful" : 63,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 31,
      "relation" : "eq"
    },
    "max_score" : 4.2307563,
    "hits" : [
      {
        "_index" : ".kibana_2",
        "_type" : "_doc",
        "_id" : "index-pattern:wazuh-monitoring-3.x-*",
        "_score" : 4.2307563,
        "_source" : {
          "index-pattern" : {
            "title" : "wazuh-monitoring-3.x-*"
          }
        }
      },
      {
        "_index" : ".kibana_2",
        "_type" : "_doc",
        "_id" : "index-pattern:wazuh-alerts-3.x-*",
        "_score" : 4.2307563,
        "_source" : {
          "index-pattern" : {
            "title" : "wazuh-alerts-3.x-*"
          }
        }
      },
      {
        "_index" : ".kibana_3",
        "_type" : "_doc",
        "_id" : "index-pattern:wazuh-monitoring-3.x-*",
        "_score" : 3.591424,
        "_source" : {
          "index-pattern" : {
            "title" : "wazuh-monitoring-3.x-*"
          }
        }
      },
      {
        "_index" : ".kibana_3",
        "_type" : "_doc",
        "_id" : "index-pattern:wazuh-alerts-3.x-*",
        "_score" : 3.591424,
        "_source" : {
          "index-pattern" : {
            "title" : "wazuh-alerts-3.x-*"
          }
        }
      },
      {
        "_index" : ".kibana_3",
        "_type" : "_doc",
        "_id" : "index-pattern:metrics-*",
        "_score" : 3.591424,
        "_source" : {
          "index-pattern" : {
            "title" : "metrics-*"
          }
        }
      },
      {
        "_index" : ".kibana_3",
        "_type" : "_doc",
        "_id" : "index-pattern:logs-*",
        "_score" : 3.591424,
        "_source" : {
          "index-pattern" : {
            "title" : "logs-*"
          }
        }
      }
    ]
  }
}
`

**Comment by bpickhardt** [comment]
I'm not an ELK wizard but I figured I could handle trying that.  Here's what I did.  I'm not sure how often docs should be getting added to the wazuh-monitoring index but viewing it for about 15 minutes did not show any docs being added.

1) Stop filebeat
2) Delete index template wazuh
3) Delete index template wazuh-agent
4) Delete index pattern wazuh-alerts-*
5) Delete index pattern wazuh-monitoring-*
6) Delete index pattern wazuh-statistics-*
7) Follow the upgrade kibana instructions at this link except instead of step 3 to update Kibana via apt I just stopped the service.
https://documentation.wazuh.com/4.0/upgrade-guide/elasticsearch-kibana-filebeat/upgrading-elastic-stack.html
8) Start back up filebeat
9) Login to Kibana
10) Verify the index templates and index patterns were recreated.
11) Verify the wazuh plugin in Kibana works
12) Check if the wazuh-monitoring index is getting docs added
13) Restart kibana
14) Check again if the wazuh-monitoring index is getting docs added (wait 15 minutes)

**Comment by bpickhardt** [comment]
I checked back on it today and the index is populating now.  I just didn't wait long enough yesterday.

**Comment by frankeros** [comment]
If everything is resolved I'll close the Issue.
If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)
