### ISSUE TITLE
Fields dinamic decoder

### ISSUE THREAD

**Issue by greenbitlock** [wazuh/wazuh-kibana-app#2693]
Hi, my name is Sérgio

I am creating custom decoder for my firewall logs. already validated by ossec log test. I would like to know if when we create new fields like msg_id in tag order, it shows this field in kibana.

**Comment by frankeros** [comment]
Hi @greenbitlock 
thanks for open a new Issue. 
The answer is yes, they should be displayed in Kibana. 
If you aren't able to see them in the Wazuh app, In order to help you, you can share some useful information.
First, you should validate if the new fields are displayed in Kibana / Discover.
![image](https://user-images.githubusercontent.com/26828184/102540828-63460900-408e-11eb-9d2f-76036becd3ec.png)
---
If they aren't displayed, you can check if the alerts were generated properly by checking into the `Wazuh Manager` host
 running for example (using default path for alerts.json) `cat /var/ossec/logs/alerts/alerts.json | grep <NEW_FIELD>
` replacing `<NEW_FIELD>` with one of your custom fields.

I will be waiting for any feedback. 

Regards

**Comment by greenbitlock** [comment]
Hello good afternoon, thanks for your attention. The data does not appear in the discovery, nor does it appear in the alerts.json file. It only appears in the \ var \ ossec \ logs \ archives \ archives.json file. Follow the settings.

- Log Watchguard
2020 Dec 16 00:07:56 FIREWALL-INT->172.16.0.3 Dec 16 00:06:25 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 60 tcp 20 64 172.16.0.181 172.16.0.161 60778 10050 offset 10 S 3853443561 win 4210  (ByPass-IN-00)


- \var\ossec\etc\decoder\loca_decoders.xml
<decoder name="watchguard">
        <prematch>^FIREWALL-INT-\S+ \S+ \d\d \d\d:\d\d:\d\d \S+ firewall:</prematch>
</decoder>
<decoder name="watchguard-01">
        <parent>watchguard</parent>
        <regex offset="after_parent">msg_id="\S+ (\S+) \S+ \S+ \S+ (\S+) \S+ \S+ (\S+) (\S+) (\d+) (\d+) \S+ \d+ \S+ \d+ \S+ \d+  \S+</regex>
        <order>action,protocol,srcip,dstip,srcport,dstport</order>
</decoder>

- \var\ossec\etc\rules\local_rules.xml
<group name="watchguard,">
        <rule id="256000" level="10">
                <decoded_as>watchguard</decoded_as>
                
                <description>Watchguard message grouped.</description>
        </rule>

</group>

- result ossec-logtest

2020 Dec 16 00:07:56 FIREWALL-INT->172.16.0.3 Dec 16 00:06:25 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 60 tcp 20 64 172.16.0.181 172.16.0.161 60778 10050 offset 10 S 3853443561 win 4210  (ByPass-IN-00)


**Phase 1: Completed pre-decoding.
       full event: '2020 Dec 16 00:07:56 FIREWALL-INT->172.16.0.3 Dec 16 00:06:25 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 60 tcp 20 64 172.16.0.181 172.16.0.161 60778 10050 offset 10 S 3853443561 win 4210  (ByPass-IN-00)'
       timestamp: '2020 Dec 16 00:07:56'
       hostname: 'Wazuh'
       program_name: '(null)'
       log: 'FIREWALL-INT->172.16.0.3 Dec 16 00:06:25 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 60 tcp 20 64 172.16.0.181 172.16.0.161 60778 10050 offset 10 S 3853443561 win 4210  (ByPass-IN-00)'

**Phase 2: Completed decoding.
       decoder: 'watchguard'
       action: 'Allow'
       protocol: 'tcp'
       srcip: '172.16.0.181'
       dstip: '172.16.0.161'
       srcport: '60778'
       dstport: '10050'

**Phase 3: Completed filtering (rules).
       Rule id: '256000'
       Level: '10'
       Description: 'Watchguard message grouped.'
**Alert to be generated.

/var/ossec/logs/archives/archives.json
{"timestamp":"2020-12-18T16:42:25.764-0200","agent":{"id":"000","name":"Wazuh"},"manager":{"name":"Wazuh"},"id":"1608316945.8888296","full_log":"Dec 18 16:40:53 FIREWALL-INT firewall: msg_id=\"3000-0148\" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53  (ByPass-IN-00)","predecoder":{"program_name":"firewall","timestamp":"Dec 18 16:40:53","hostname":"FIREWALL-INT"},"decoder":{},"location":"172.16.0.3"}

**Comment by greenbitlock** [comment]
follow
- \var\ossec\etc\decoder\loca_decoders.xml
```
<decoder name="watchguard">
        <prematch>^FIREWALL-INT-\S+ \S+ \d\d \d\d:\d\d:\d\d \S+ firewall:</prematch>
</decoder>
<decoder name="watchguard-01">
        <parent>watchguard</parent>
        <regex offset="after_parent">msg_id="\S+ (\S+) \S+ \S+ \S+ (\S+) \S+ \S+ (\S+) (\S+) (\d+) (\d+) \S+ \d+ \S+ \d+ \S+ \d+  \S+</regex>
        <order>action,protocol,srcip,dstip,srcport,dstport</order>
</decoder>

```
- \var\ossec\etc\rules\local_rules.xml
```
<group name="watchguard,">
        <rule id="256000" level="10">
                <decoded_as>watchguard</decoded_as>
                <!--<field name="action">\.+</field>-->
                <description>Watchguard message grouped.</description>
        </rule>
</group>
```

**Comment by greenbitlock** [comment]
What I'm doing wrong?

**Comment by frankeros** [comment]
Hi @greenbitlock,
After asking the team, we could see that you are testing your rule with a wrong log

>     * Log Watchguard
>       2020 Dec 16 00:07:56 FIREWALL-INT->172.16.0.3 Dec 16 00:06:25 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 60 tcp 20 64 172.16.0.181 172.16.0.161 60778 10050 offset 10 S 3853443561 win 4210  (ByPass-IN-00)

It should be
```
 Dec 18 16:40:53 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53 (ByPass-IN-00)
```
Because it comes from the full_log filed of your log in `archives.json`
> /var/ossec/logs/archives/archives.json
> {"timestamp":"2020-12-18T16:42:25.764-0200","agent":{"id":"000","name":"Wazuh"},"manager":{"name":"Wazuh"},"id":"1608316945.8888296","full_log":"Dec 18 16:40:53 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53 (ByPass-IN-00)","predecoder":{"program_name":"firewall","timestamp":"Dec 18 16:40:53","hostname":"FIREWALL-INT"},"decoder":{},"location":"172.16.0.3"}

But your current decoder will not match with this new log

> ```
> <decoder name="watchguard">
>         <prematch>^FIREWALL-INT-\S+ \S+ \d\d \d\d:\d\d:\d\d \S+ firewall:</prematch>
> </decoder>
> <decoder name="watchguard-01">
>         <parent>watchguard</parent>
>         <regex offset="after_parent">msg_id="\S+ (\S+) \S+ \S+ \S+ (\S+) \S+ \S+ (\S+) (\S+) (\d+) (\d+) \S+ \d+ \S+ \d+ \S+ \d+  \S+</regex>
>         <order>action,protocol,srcip,dstip,srcport,dstport</order>
> </decoder>
> ```

Your decoder should be some like this to match with this log
```
  <decoder name="watchguard">
      <program_name>firewall</program_name>
  </decoder>
  <decoder name="watchguard-01">
          <parent>watchguard</parent>
          <regex>msg_id="\S+" (\S+) \S+ \S+ \S+ (\S+) \S+ \S+ (\S+) (\S+) (\d+) (\d+)</regex>
          <order>action,protocol,srcip,dstip,srcport,dstport</order>
  </decoder>
```
Using the "correct" log we got this result
```
/var/ossec/bin/ossec-logtest                                                                                                                                                  
2020/12/22 19:24:26 ossec-testrule: INFO: Started (pid: 13839).
ossec-testrule: Type one log per line.
Dec 18 16:40:53 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53 (ByPass-IN-00)
**Phase 1: Completed pre-decoding.
       full event: 'Dec 18 16:40:53 FIREWALL-INT firewall: msg_id="3000-0148" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53 (ByPass-IN-00)'
       timestamp: 'Dec 18 16:40:53'
       hostname: 'FIREWALL-INT'
       program_name: 'firewall'
       log: 'msg_id="3000-0148" Allow 10-Servidores 10-Servidores 62 udp 20 127 172.16.23.125 172.16.0.52 53115 53 (ByPass-IN-00)'
**Phase 2: Completed decoding.
       decoder: 'watchguard'
       action: 'Allow'
       protocol: 'udp'
       srcip: '172.16.23.125'
       dstip: '172.16.0.52'
       srcport: '53115'
       dstport: '53'
**Phase 3: Completed filtering (rules).
       Rule id: '256000'
       Level: '10'
       Description: 'Watchguard message grouped.'
**Alert to be generated.
```

Also, we were noticed that you tried to work with the fields on your rule

> ```
> <group name="watchguard,">
>         <rule id="256000" level="10">
>                 <decoded_as>watchguard</decoded_as>
>                 
>                 <description>Watchguard message grouped.</description>
>         </rule>
> </group>
> ```

There are default fields like `action, protocol, srcip, dstip, srcport, dstport` that they already have their own tag to include directly inside a rule instead of using the tag `field`. 
But if you add a custom field, then you should use the tag `field`
for example
```
 <group name="watchguard,">
        <rule id="256000" level="10">
                <decoded_as>watchguard</decoded_as>   
                <field name="myField">\.+</field>            
                <description>Watchguard message grouped.</description>
        </rule>
        <rule id="256001" level="12">
                <if_sid>256000</if_sid>
                <action>Allow</action>
                <description>Watchguard action allow.</description>
        </rule>
</group>
```
I'll be waiting for any feedback

Best

**Comment by greenbitlock** [comment]
Great, it worked perfectly, Thank you very much. One more thing, can I resolve the ip by the name of the srcip and dstip fields?

**Comment by frankeros** [comment]
I'm glad that it worked. 
I'm not sure if I understand your question. But here is some documentation that can be useful for you. 
https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=srcip#srcip

**Comment by greenbitlock** [comment]
I was not clear, I would like the device name to appear on the kibana and not the ip, but in my log there is only the source and destination ip. Is there any way I can apply some dns filter in the srcip and dstip fields to resolve the ip to the name?

**Comment by frankeros** [comment]
this would be possible only if the hostname came as a custom field inside of the `full_log`, but not from external sources.

**Comment by greenbitlock** [comment]
Got it, can I change the type of the field? Example, srcip and dstip are as a string, can you change to ip or geo_ip?

**Comment by frankeros** [comment]
For these static fields, you should change their type from the Wazuh template installed for Filebeat, you can check it in the installation [guide](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html#installing-filebeat) (step 3)
you should change the type for the corresponding field in the json, restart `wazuh-manager`, and `filebeat` services.
In order to force to Filebeat set up the new template, you should run
`filebeat setup --index-management`
To make sure it worked, you can check it from your browser in Kibana (menu)/ Dev tools and run this query
 `GET _template/wazuh`

![image](https://user-images.githubusercontent.com/26828184/103284096-14b33b80-49b9-11eb-80c3-da2483073c7a.png)



Also, you should change (just in case the index fields failed  from KIbana or they were empty) in the plugin code this file
`/usr/share/kibana/plugins/wazuh/public/utils/known-fields.js`, find the corresponding fields and change their type. 
After that you should remove the Kibana bundles running
`rm -rf /usr/share/kibana/optimize/bundles`
and restart Kibana


In case you have indices previously generated, you should reindex them following this [guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) of Elastic.
This step must be after replacing the template.

**Comment by greenbitlock** [comment]
Thank you very much, helped me a lot.

**Comment by frankeros** [comment]
I'm glad I could help you, if everything is resolved I'll close the Issue.
If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)

Regards
