### ISSUE TITLE
Error in FIM events with Windows registry event

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#2736]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.3   | 7.9.1     | 4014 |

Opendistro 1.11.0

**Description**
Opening an FIM event (registry) description of a Windows agent  from his `syscheck.path` link this return an error 

**Steps to reproduce**

1. Go to Wazuh / Integrity monitoring / Events
2. Click on `syscheck.path` link of a Windows registry item 
3. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/26828184/103771242-1c509100-5006-11eb-8766-3892c0da7452.png)

**Additional context**
When you try do the same from Dev tools the same error happens
![image](https://user-images.githubusercontent.com/26828184/103771939-6ede7d00-5007-11eb-861e-bc554ade236b.png)
![image](https://user-images.githubusercontent.com/26828184/103771979-7bfb6c00-5007-11eb-939e-ca538b3d3cad.png)

**Comment by davidjiglesias** [comment]
### **Status update:**

Hi team,

We are currently working on a solution for this bug. 

Pending tasks:
- [ ] Analyze and debug error, replicate
- [ ] Investigate and determine why the use case is not detected by the unit tests
- [ ] Investigate the behaviour for v3.13.2 to understand if the bug was introduced in v4.0.0
- [ ] Propose and develop a solution for the bug

**Comment by davidjiglesias** [comment]
To be fixed in https://github.com/wazuh/wazuh/issues/7117
