### ISSUE TITLE
wazuh kibana index name auto change

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh-kibana-app#2768]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.0  | 7.9.1     | 444 |

when I update ELK to 7.9.1 and update wazuh manager to 4.0.0,I find the wazuh kibana index always auto change,

for example I create kibana index in stack management and name "wazuh-alerts-*"
![image](https://user-images.githubusercontent.com/15324125/104262215-279e3380-54c2-11eb-9399-abf6ac573dc6.png)

it works,but after one day,when I login the kibana ,the index has been changed,like this

![image](https://user-images.githubusercontent.com/15324125/104262236-32f15f00-54c2-11eb-9a51-f9320a791925.png)

because the index name is change,I can not use kibana to search wazuh alert log,unless I create the "wazuh-alerts-*"index

so I feel very confused,what can I do to repair it?

**Comment by frankeros** [comment]
Hi @xufengnian 
This happens because Kibana is assigning a `uuid` as the id for your index pattern, to avoid this you have to set a custom id as the index pattern itself in the second step.

![image](https://user-images.githubusercontent.com/26828184/104310872-329d9780-54b3-11eb-95a8-a4136d6c9df7.png)

**Comment by xufengnian** [comment]
Thank you very much! Your answer help me a lot!
