### ISSUE TITLE
Checking APP for versión 4.1.0

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-kibana-app#2771]
Hi team, we're going to check wazuh app for 4.1.0 versión and we will apply the changes in the API that we're refered in #6398.

Error/Bugs repaired:
- [ ] Fix problems in /inventory monitoring/Inventory with Windows agent. Related to #2736 and #2679

**Comment by frankeros** [comment]
Fixed bug for 4.1 when open the Rule tab in a Summary Alert from Modules / Security Events / Dashboard / Sumary Alerts
It happens with rules like 502 and 503 because the Match field in the rule details came with a object instad of a string
Solved [here](https://github.com/wazuh/wazuh-kibana-app/pull/2781/commits/8c9f10335c58013dbc2325fcfdb665ba1e193b90)

4.0 
![image](https://user-images.githubusercontent.com/26828184/104603276-00c73500-565b-11eb-902b-20424b4e2b3f.png)

4.1
![image](https://user-images.githubusercontent.com/26828184/104603307-07ee4300-565b-11eb-9f74-4efed149fe23.png)
