### ISSUE TITLE
A user without group read permissions can view the list of existing groups

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#2928]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0| 4101-1 |

**Description**

A user without group read permissions can view the list of existing groups using deploy new agent menu.

**Steps to reproduce**

1. Create a user with reading permissions only for agents that belong to a group
2. Go to `Agents`
3. In `Assign agent to a group`, you can see all existing groups.

**Video**

https://user-images.githubusercontent.com/11089305/106776631-8b8cc580-6644-11eb-8717-842d160a0bf7.mp4

**Comment by sortizowlh** [comment]
This problem was solved with this PR for wazuh 4.1.1:
[https://github.com/wazuh/wazuh/pull/7342](https://github.com/wazuh/wazuh/pull/7342)
[https://github.com/wazuh/wazuh/pull/7393](https://github.com/wazuh/wazuh/pull/7393)

Using wazuh version 4.1.0:
The dev tools query `GET /agents` returns the list of all groups, even without permissions.
Now, at wazuh 4.1.1 version, the user can't access `management/groups` without permissions, and the dropdown menu for deploy a new agent is locked.

![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/fee29d55-b7af-435a-8b9d-35d531341ee1)
![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/ad02c217-1af4-460b-aad6-169725caa6c5)
![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/01098754-0840-45b9-9163-90c4aa735a2c)
![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/0ab71aab-ce9a-4a01-bc6b-be2ba0fe0b41)
