### ISSUE TITLE
Improve message for run_as validation in Role Mapping section

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3036]
Hi team, 
As UX improvement we should show different text in the alert on the Role Mapping section when the Wazuh user has `allow_run_as` as `false` and another text when the host has `run_as` as `false` in wazuh.yml, in order to clarify the message to the user.
Validating first for the `run_as` in the wazuh.yml

![image](https://user-images.githubusercontent.com/26828184/109559167-1bddef00-7ab9-11eb-8b73-b1255d236888.png)

I propose these texts:
- When `run_as` from wazuh.yml is `false`: 
> For the role mapping to take effect, enable `run_as` in `/usr/share/kibana/data/wazuh/config/wazuh.yml` configuration file, restart the Kibana service and clear your browser cache and cookies.
- When `allow_run_as` from API is `false`: 
> The role mapping has no effect because the current Wazuh API user has `allow_run_as` disabled.

**Comment by s-ocando** [comment]
Hi team, 

I suggest the following messages: 

 - When `run_as` from `wazuh.yml` is false:
 
For the role mapping to take effect, enable `run_as` in `/usr/share/kibana/data/wazuh/config/wazuh.yml` configuration file, restart the Kibana service and clear your browser cache and cookies.

This suggested message gives clear instructions to the users on how to activate the Wazuh RBAC. 

- When `allow_run_as` from API is false:
  
 The role mapping has no effect because the current Wazuh API user has `allow_run_as` disabled.
