### ISSUE TITLE
Make index name configurable

### ISSUE THREAD

**Issue by megastef** [wazuh/wazuh-kibana-app#31]
The Kibana plugin should support configurable index names to integrate Wazuh with hosted Elasticsearch stacks like [Logsene](https://sematext.com/logsene). It looks the index prefix is hard coded in JS source code:
https://github.com/wazuh/wazuh-kibana-app/blob/bf237f0363ed76a51eac08a3a5582578ef0c2aa1/server/startup/initialize.js#L21-L22
I assume Dashboard definitions would need to be generated with the configured index name.

**Comment by snaow** [comment]
Hi @megastef,

That's a great idea we have been thinking of, it would be great to make it configurable but I can think about several complications we would have.
Dashboards, visualizations and searches are based in a specific set of field names, if the index-pattern if configurable new indices should contain Wazuh alerts, otherwise the visualizations won't match.

The valid uses case could be to forward Wazuh events to indices containing as well other kind of documents and configure Wazuh App to request from those indices, it will only display Wazuh-related events and omit the other ones, anyway, it make sense to make the index-pattern configurable via config.json so let's keep this issue open and we will update it once we start working on it.

Thanks for the feedback and ideas.

**Comment by megastef** [comment]
We are aware of the problem that Kibana stores index names in the visualisation JSON structure. One way might be to use the JSON file as a template and generate the JSON for a configured index. See e.g. my little nodejs script to convert Kibana Dashboards objects: https://gist.github.com/megastef/a7fae73a7ca65def1950ac2eef947931

**Comment by havidarou** [comment]
Hi @megastef we are "kind of" doing that for version 3.0_6.0.0.

Because an index-pattern is generated using an id, we have to, at initialization time, wait for the id and then modify the JSON son that we insert the right id and everything works ok.

As to the original purpose of the issue...you would need to modify more parts of the data flow, for example, Logstash configuration file is prepared to inject the index with a predefined pattern in its name.

If you change the pattern in Kibana, but not in Logstash, you would end up with problems because the data filtering wouldn't be right.

And if you change the pattern in Logstash, the right templates prepared in Elasticsearch couldn't be applied, ending up with the default one, and later, the Wazuh App and dashboards not recognising the index field types.

Regards.

**Comment by havidarou** [comment]
Hi @megastef, 

we've implemented that in the newer 3.0.0 version (though it has not been released yet).

It will be configurable in the package.json initialPattern variable.

Regards.

**Comment by havidarou** [comment]
Yesterday we released our version 3.0.0, that goes along Elastic Stack 6.x and this request is now available.

Regards.
