### ISSUE TITLE
Sample data appears to install by itself, can't remove

### ISSUE THREAD

**Issue by water-breather** [wazuh/wazuh-kibana-app#3179]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.2     | 4104 |

**Description**
Sample data appears to been added automatically, can't remove.

**Steps to reproduce**

1. Was updating default api passwords for reserved accounts
2. Go to any module or Settings->Sample Data 
3. Reports sample data is installed
4. Click button to remove sample data
5. navigate to another module or config section and back
6. sample data appears to be installed again

**Screenshots**
![image](https://user-images.githubusercontent.com/82603686/115082104-f7a06b00-9eca-11eb-9cb2-0bdb006772f5.png)

![image](https://user-images.githubusercontent.com/82603686/115082137-038c2d00-9ecb-11eb-96e3-12f97468c5ff.png)

**Additional context**
It is not clear if sample data has been added or not. It does not appear to be contained in any of the wazuh-alerts-3.x indices

Using multiple wazuh managers with single wazuh-kibana app using api selector to switch between managers in wazuh-kibana app

using custom wazuh-alerts-3.x index name/pattern (but template is updated to current version)

receive following error when navigating around wazuh-kibana app: 
![image](https://user-images.githubusercontent.com/82603686/115082240-32a29e80-9ecb-11eb-9f19-b0ba504b0d50.png)

**Comment by CPAlejandro** [comment]
Hi @water-breather, 
I'm going to need you to show me the result of the following checks:
-In Kibana Dev Tools run the following command: `GET _cat/indices/*sample*`
With this we will see if there are sample data indices.
![image](https://user-images.githubusercontent.com/17100196/115220163-864dfb80-a108-11eb-9b08-4ea5775e05fc.png)

- Show me the Sample alerts prefix that you can find in Wazuh /Settings/Configuration
![image](https://user-images.githubusercontent.com/17100196/115220087-7209fe80-a108-11eb-9e72-e41b8c8fdce1.png)

- I also need to know if when you click Remove data in the Wazuh Sample Data section, an error appears on the screen and if not, show me the console and network section of your browser's dev tools after having pressed any of the remove data buttons, which you can access by pressing F12 on your browser. With a capture of both parts it would serve me.
![image](https://user-images.githubusercontent.com/17100196/115220262-9ebe1600-a108-11eb-9ebd-8c2187e3895b.png)
![image](https://user-images.githubusercontent.com/17100196/115220299-a978ab00-a108-11eb-91ce-a48d95f295b3.png)

**Comment by water-breather** [comment]
Results of GET _cat/indices/*sample*: NONE
Sample alerts prefix: wazuh-alerts-3.x-
After clicking remove buttons: standard message appears indicating sample data was removed, no new information appears in console
after clicking remove buttons: 
![image](https://user-images.githubusercontent.com/82603686/115252421-1122fc00-a0f1-11eb-861a-043b98029ea0.png)

**Comment by CPAlejandro** [comment]
Hi @water-breather , thanks for your feedback.
When you tell me that the result of this request: `GET _cat/indices/sample` is NONE, you made the request like this: `GET _cat/indices/*sample*`? Those `*` are very important, they help us to know if the title of the index contains `sample`, without them you simply look for indexes whose name is only "sample"
To see exactly what is happening when deleting sample data, go to `Settings/Sample Data` and before pressing `remove data` from any of the 3 buttons, open `dev tools` (Pressing F12), go to the `network` tab, click on the icon of the left top second row 
![image](https://user-images.githubusercontent.com/17100196/115367804-cd022b00-a1c6-11eb-8758-4d534c8ccce1.png)
, which will clean the network tab of requests so that we can see only those that are generated when pressing the remove data button and then click on any of the `remove data` buttons, then you will be generated in the network tab that you had open an option called `security`, click on it and show us the `response` window, such and how I show you in this capture:
![image](https://user-images.githubusercontent.com/17100196/115367871-da1f1a00-a1c6-11eb-88da-97efe8dc6060.png)

**Comment by water-breather** [comment]
updated to 4.1.5 version of wazuh-manager and kibana app to resolve issue with modulesd crashing, this issue appears to have disappeared in the process.

**Comment by CPAlejandro** [comment]
I'm glad I could help you.
If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)
Regards
