### ISSUE TITLE
Visualize Button in new Top 5 Window not visible

### ISSUE THREAD

**Issue by madhatta-ct** [wazuh/wazuh-kibana-app#3188]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4  | 7.10.2    | 4105 |

**Description**
The Visualize button in the new pop-out style window when clicking on an available field no longer appears, this prevents me from getting a result set larger than the first 500.

If I go to Kibana's Discover tab it is there so makes me believe its a Wazuh app bug as opposed to a Kibana bug

**Steps to reproduce**

1. Go to 'Modules > Security Events'
2. Click on 'Events'
3. Click on any field in the 'Available Fields' section
4. You will see the button is no longer there

**Screenshots**
Wazuh App:
<img width="409" alt="Wazuh App" src="https://user-images.githubusercontent.com/56031621/115349613-5a884f80-a1b4-11eb-81c7-99ee04770d46.png">

Kibana "Discover" App
<img width="404" alt="Discover App" src="https://user-images.githubusercontent.com/56031621/115349680-6d028900-a1b4-11eb-9b3e-5a4b0b7f7e5e.png">

**Additional context**
I also have an ODFE instance, also 4.1.4 and App Rev 4105 and same result

**Comment by frankeros** [comment]
We need to update the current version of the section `Events` based on the last changes of the Discover plugin.

**Comment by Desvelao** [comment]
I was trying to update the Discover with the more recent version (`7.12.1`) but I got some problems with dependencies that Kibana 7.10.2 (current Kibana version for Wazuh app) doesn't own. This causes multiple problems which should be patched to try to do work the integration.

Due to this, we keep the current Discover and when the Wazuh app requires a more recent Kibana version, we could consider updating the Discover. This affects the module `Events` tab from the Wazuh app.

### Changes
- Fixed the `Visualize` button in the Events sidebar.

**Comment by madhatta-ct** [comment]
Thanks a stack for the effort here! Appreciate it
