### ISSUE TITLE
Elasticsearch/Kibana 5.6.0-1 released today.

### ISSUE THREAD

**Issue by mmccune** [wazuh/wazuh-kibana-app#32]
The wazuh plugin needs to be updated for the new release.

**Comment by jlruizmlg** [comment]
Hi Mmccune

We are working on it!

Thanks for letting us know!


Regards
-----------------------
Jose Luis Ruiz
Wazuh Inc.
jose@wazuh.com

On September 11, 2017 at 3:56:13 PM, mmccune (notifications@github.com)
wrote:

The wazuh plugin needs to be updated for the new release.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wazuh/wazuh-kibana-app/issues/32>, or mute the thread

**Comment by guilhermebasalia** [comment]
Dear Good Afternoon,
What would be the estimate or date for the release of version 5.6.0 Kibana WAZUH?

**Comment by jlruizmlg** [comment]
Hi @guilhermebasalia we have this version already in our server, can you try to install it?

**Comment by guilhermebasalia** [comment]
Hi @jlruizmlg of course, I'd love to test, could send me the link?

**Comment by jlruizmlg** [comment]
It's the same, from this link: [https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#kibana](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#kibana)

Uninstall the old one if you have it:

```
/usr/share/kibana/bin/kibana-plugin remove wazuh
```

Install thew new one:

```
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
```

**Comment by dig412** [comment]
The new version works great for me with Kibana 5.6.0.
Thanks for getting the plugin fixed so quickly!

**Comment by jlruizmlg** [comment]
Perfect! Nice to hear that!!! Have a nice weekend!
