### ISSUE TITLE
Broken format in Discover due to checks.metaFields setting

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-kibana-app#3215]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.5  | 7.10.0  |  4106 |

**Description**

If we refresh the index pattern **manually** from the Kibana settings, the format in Discover is broken (screenshot 3).

**Details**
- There are 5 meta fields. If  `_source` and `_index` meta fields are removed, the **manual** refresh of the index pattern fails. This causes the broken format in Discover.
- By default, the app uses a setting (`checks.metaFields: true`) to remove all the fields starting with `_`.

**Screenshots**

<details>
<summary>1</summary>

![image](https://user-images.githubusercontent.com/8913336/116895972-06f61700-ac34-11eb-933c-65e6eab193ab.png)

</details>

<details>
<summary>2</summary>

![image](https://user-images.githubusercontent.com/8913336/116896041-1ecd9b00-ac34-11eb-995d-40f8d7a84001.png)

</details>

<details>
<summary>3</summary>

![image](https://user-images.githubusercontent.com/8913336/116896110-2e4ce400-ac34-11eb-9a20-99c3d45886f5.png)

</details>

<details>
<summary>4</summary>

![image](https://user-images.githubusercontent.com/8913336/116896532-a4e9e180-ac34-11eb-9525-32778ecb1a97.png)

</details>

<details>
<summary>5</summary>

![image](https://user-images.githubusercontent.com/8913336/116896738-d498e980-ac34-11eb-855d-043977cdc4a4.png)

</details>

> **The main goal is to remove all meta fields (or most of them) without breaking the Discover format and allowing the index patterns to be refreshed manually without any issues**

**Comment by frankeros** [comment]
related to #2676

**Comment by Desvelao** [comment]
@pablomarga testing with the number of metafields to put in the Kibana settings saw if there is only one, when trying to refresh the index pattern manually (`Stack management > Index patterns`), a toast is displayed with an error.

I checked the Kibana API `endpoint` that fails and the reason is that the metafield when is a `string`, try to convert to JSON (`JSON.parse`), but it fails and the request returns a `Bad request`. This is a problem related to Kibana itself. When only there is a metafield, the request or endpoint to refresh the index pattern should be adapted to not return a `Bad request`.

https://github.com/elastic/kibana/blob/v7.10.2/src/plugins/data/server/index_patterns/routes.ts#L113-L117
