### ISSUE TITLE
Wazuh Kibana application NodeJS server returning Wazuh API credentials in clear text

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#336]
Greetings!

While inspecting the network tab of my browser debugger tools to figure out why the Wazuh Kibana application was not initializing, I saw the Wazuh API password in the response of the `https://wazuh.dev.cloud.coveo.com/api/wazuh-api/checkStoredAPI` API call.

![screen shot 2018-03-23 at 16 56 41](https://user-images.githubusercontent.com/3448802/37853149-b65096b6-2ebb-11e8-8e86-298666607764.png)

In the [wazuh-api.js](https://github.com/wazuh/wazuh-kibana-app/blob/6b89fa1b84b76c678bcbf932f0493d4d3bb16e2b/server/api/wazuh-api.js#L86) file, in the `checkStoredAPI` API call handler, the Wazuh API password is being fetched and then returned in clear text to the client application.

Would it be possible not to return the API password to the Kibana application? 😄 

The fix is quite simple. Replace `wapi_config.password` content with `****` before returning `wapi_config` in the `data` field of the response.

Thanks for your time!

**Comment by havidarou** [comment]
Hi @JPLachance ,

you are right.

This is kind of the way it worked before, but after a lot of refactoring and code rewriting we must have lost it.

Will fix this as soon as possible.

Thanks!

Regards.

**Comment by JPLachance** [comment]
@havidarou, the PR https://github.com/wazuh/wazuh-kibana-app/pull/337 is fixing the issue.

Question: would it be possible to build a fixed version for Kibana 6.1.1? If not, can you explain to me how I can build my own package for that specific version of Kibana?

Thanks :)

**Comment by jesusgn90** [comment]
Hi @JPLachance , as @havidarou said, it's right. I just included the fix on [https://github.com/wazuh/wazuh-kibana-app/pull/339](https://github.com/wazuh/wazuh-kibana-app/pull/339) because it has more places to hide the password than your PR also I included the query size you citated on another issue. 

Any case thank you so much for your great feedback, it's great a user look at our code and review it like you! 

Regarding to make your own package, please follow the next steps:

1. Git clone your desired Wazuh App branch
2. Replace the Kibana version on the Wazuh App `package.json` file by your desired version (6.1.1)
3. Remove `.git` directory
4. `npm install`
5. Build a `zip` with all the content

_Since sometimes there are breaking changes between different Elastic version it's possible to have a broken package if you only change the `package.json` version field._

My suggestion: download the Wazuh App package for 6.1.1, extract it, add your modification and build it again.

Additional information: we usually works on the branch with the latest version as name (i.e: 3.2), your next pull request should be from a fork of our latest branch and targets our latest branch not the master branch, because the master branch includes our latest stable code not the currently working code. I'm going to close this issue, open a new issue if you are facing any kind of trouble. Have a nice day @JPLachance.

Best regards,
Jesús
