### ISSUE TITLE
Propose the Office365 Dashboard design

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3379]
| Wazuh version | 
|---|
|4.3.0|

### Office365 Module views proposal

- Dashboard
- Inventory

**Comment by asteriscos** [comment]
Hi team,
these are the first prototypes

`Dashboard`
![office365mockup](https://user-images.githubusercontent.com/9343732/123089688-a4ccbd80-d3fd-11eb-8a8a-3aa5067a1709.png)

`Inventory`
![Framework](https://user-images.githubusercontent.com/9343732/123089727-b1e9ac80-d3fd-11eb-9317-c67bff7b06f2.png)

**Comment by mpRegalado** [comment]
Alternate proposal for the first tab
![office365mockup - Inventory](https://user-images.githubusercontent.com/80431234/123255272-f05f9400-d4ef-11eb-9048-25a188a3a398.jpg)
![office365mockup - Inventory - Explained](https://user-images.githubusercontent.com/80431234/123255279-f2295780-d4ef-11eb-9a78-b4870837629f.jpg)

**Comment by asteriscos** [comment]
Added **filter options** to `Inventory` tab
![office365-framework-version2](https://user-images.githubusercontent.com/9343732/123400447-0e87cb80-d5a6-11eb-84a1-09149776b492.png)

**Comment by mpRegalado** [comment]
![office365mockup dashboard](https://user-images.githubusercontent.com/80431234/123646534-9a5c5a80-d827-11eb-8089-608d907f593e.png)
A simple modification to the dashboard where we suggest the user some filters that could provide an insight on specific behaviors

![User flyout](https://user-images.githubusercontent.com/80431234/123646809-d42d6100-d827-11eb-83a4-ab0674288916.png)
A possible side panel displaying information about a selected user or IP address

**Comment by asteriscos** [comment]
Small fix: Added the `User Type` filter

![office365-framework-v3](https://user-images.githubusercontent.com/9343732/123649728-5d30a200-d800-11eb-8be0-ca285cced926.png)

**Comment by mpRegalado** [comment]
Modification of the proposal in https://github.com/wazuh/wazuh-kibana-app/issues/3379#issuecomment-867560365

![office365mockup inventory primary](https://user-images.githubusercontent.com/80431234/123923687-82045100-d989-11eb-908a-cb0677cf0408.png)
On the left column there would be a list of categories with filters one would consider relevant for the specific module, such as High level alerts, subscription or record type in the case of office365. On the right side, there would be an inventory table much like the one in security events, tables indicating results based on user or IP rather than events is also included in the mockup for some extra information but can be easily removed.

Clicking on any one property would navigate to a second page that shows information about events that match it
![office365mockup inventory secondary](https://user-images.githubusercontent.com/80431234/123924320-25556600-d98a-11eb-8d36-6c4251c9cf04.png)
We could specify different visualizations to navigate to depending on the module/property

**Comment by mpRegalado** [comment]
After the meeting there were the following conclusions:
**For the Inventory panel:**

- Based on https://github.com/wazuh/wazuh-kibana-app/issues/3379#issuecomment-871185990
- Pick either side panel with filter options or top search bar
- Add module information, such as last polling, configuration information, active subscriptions, which machine retrieves the information, etc.
- Decide whether `Inventory` is a proper name for this section or it needs a new one

**For the dashboard:**

- Based on https://github.com/wazuh/wazuh-kibana-app/issues/3379#issuecomment-869699847
- Show a different board for each subsciption
- Pick a proper switching method (drop down menu, tabs, etc..)
- Meet with threat analysis to specify which visualizations are the most relevant to show

**Comment by asteriscos** [comment]
Hi team,
I designed dashboards for Exchange, Sharepoint, Azure AD and a General one. The main concept is the following example:

![Dashboards-AzureAD](https://user-images.githubusercontent.com/9343732/124638992-02332680-de62-11eb-8355-5a8445cc381b.png)


Another possibility for the **Subscription selector** is a dropdown as this one:

![image](https://user-images.githubusercontent.com/9343732/124639340-6eae2580-de62-11eb-97c0-3f942bb81a5c.png)
