### ISSUE TITLE
bulk_get on each index pattern on Wazuh Kibana application load

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh-kibana-app#343]
Greetings!

After starting to use our existing Elasticsearch cluster to store Wazuh alerts, I noticed that the Wazuh Kibana application is performing a lot of API calls to Elasticsearch on initialization.
![screen shot 2018-03-27 at 10 47 39](https://user-images.githubusercontent.com/3448802/37975015-56def6de-31ac-11e8-83dd-4fce43e78053.png)

After going through the pain of identifying which part of the code is doing those call, I found that the in the wz-menu.js code, there is a call to [`patternHandler.getPatternList()`](https://github.com/wazuh/wazuh-kibana-app/blob/9990a63a42df395b2acee828635662da77fdd565/public/directives/wz-menu/wz-menu.js#L31) which is handled by the `patternHandler` service. Somehow, the getPatternList function is doing a bulk_get on each pattern, which is very very slow when we have more than 3 patterns.
![screen shot 2018-03-27 at 10 36 28](https://user-images.githubusercontent.com/3448802/37976072-a21bac4e-31ae-11e8-8a39-2d68060214da.png)

Would it be possible for the Wazuh Kibana application to ignore other patterns and care only about Wazuh patterns?

Steps to reproduce:
1. Create many patterns with indices behind them
2. Create many patterns that don't have indices behind them
3. Load the Wazuh Kibana application

Thanks for your help and time!

**Comment by havidarou** [comment]
Hi @JPLachance ,

At app's startup we check all of the index-patterns in Kibana to see which of them could potentially be compatible with Wazuh alerts in order to present it as an option for the visualizations.

We have changed the code to be faster, ignoring the courier service and directly querying elasticsearch...I believe it is in revision 387 (you can check the app's revision by looking at its ```/usr/share/kibana/plugins/wazuh/package.json``` file).

Besides that, you can disable the pattern selector in the upper right of the screen by modifying ```/usr/share/kibana/plugins/wazuh/config.yml``` and using false in the selector (end of the file).

The pattern list will still be loaded in settings though.

After that change in config.yml you have to restart Kibana.

Hope that helps!

We really appreciate your feedback, so don't hesitate to contact us.

Regards.

**Comment by jesusgn90** [comment]
Hello again @JPLachance,

our next packages are going to be _painless_ regarding to the index pattern management. The way we'll create the visualizations will change and the way we fetch/show/select the index pattern will change as well. You won't need any more to be concerned about disable/enable the selector or something similar. Any case for current packages the way @havidarou described is the right way for now. 

_Note: the branch to track this feature is the same as the citated branch on the other issue: https://github.com/wazuh/wazuh-kibana-app/tree/3.2-xpack-rbac_

Best regards,
Jesús
