### ISSUE TITLE
Edit default index in wazuh-kibana

### ISSUE THREAD

**Issue by hastaki** [wazuh/wazuh-kibana-app#3454]
Hello
I need edit index type string in number (for example)
please tell me how to do it
![bytes](https://user-images.githubusercontent.com/86711270/124922336-1150da80-e002-11eb-9877-585761454908.PNG)

**Comment by gabiwassan** [comment]
Hi @hastaki,
In order to help you, this [guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings) can help you to change the type of data.
You could do it from Kibana DevTools, with an administrator user.

![image](https://user-images.githubusercontent.com/11060558/124988983-0bb0c000-e015-11eb-95f7-182f0eee8eb9.png)


Best!

**Comment by hastaki** [comment]
> Привет @hastaki ,
> Для того , чтобы помочь вам, это [руководство](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings) поможет вам изменить тип данных.
> Вы можете сделать это из Kibana DevTools с правами администратора.
> 
> ![изображение](https://user-images.githubusercontent.com/11060558/124988983-0bb0c000-e015-11eb-95f7-182f0eee8eb9.png)
> 
> Лучший!

 I read this manual, but I still can't figure it out, I need an example for a similar fix
