### ISSUE TITLE
Amazon module dashboard

### ISSUE THREAD

**Issue by naveenkumar199901** [wazuh/wazuh-kibana-app#3487]
This issue is related to the Amazon AWS modules wazuh. When you add data to these modules a refresh of the index pattern is needed so when you enter any of these modules a toast shows up saying that the index pattern was refreshed successfully but it is not true. This refresh is not applied until you refresh the whole page.but when Add Sample Data then show Dashboard can you help me for this . and when add real data then error in some unknown filed in index pattern

**Comment by MauGaP** [comment]
Hi, how are you? 
I will try to help you fix this issue.

In order to better guide you, can you give us more information about the system? (Wazuh Version, Kibana version, all-in-one/distributed server installation, etc) I need this information in order to create a similar environment to test this.

Also, Can you add some screenshots of the errors? and a little more detailed steps to reproduce? what are the fields that you have conflicts in the index pattern?

Best!

**Comment by frankeros** [comment]
Hi @MauGaP
were you able to solve the problem?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).
