### ISSUE TITLE
Agent status didnt change from "disconnected" to "active" immediately 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-kibana-app#349]
I have reed this documentation [tutroial](https://documentation.wazuh.com/3.x/user-manual/agents/agent-life-cycle.html), and it's said:

> Disconnected:
> If the connection is made through UDP, the manager will consider the agent disconnected if it does not receive any keep alive messages from the agent within a half an hour.
> If the connection is made through TCP, the manager will consider the agent disconnected immediately after the connection is lost.

i more interested to use `tcp` protocol because in documentation page said it will change the status to "disconnected " immediately after the connection is lost.

so i configure in my **Wazuh-manager** like this conf on my `ossec.conf`

```
 <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
  </remote>
```

and in my agent, `ossec.conf`

```
<client>
    <server>
      <address>192.168.56.101</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>debian, debian8, debian8.10</config-profile>
    <notify_time>60</notify_time>
    <time-reconnect>300</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```

After i shutdown one of my agent, the connection in Kibana Wazuh App still in `active' status. I have to wait for approximately 20-30 minutes for the status are in "disconected"s status. What could go wrong with my configuration ?

**Comment by jesusgn90** [comment]
You are right @gagantous we have something wrong here, it's probably related to the Wazuh Manager itself I've just opened a new issue on [https://github.com/wazuh/wazuh/issues/507](https://github.com/wazuh/wazuh/issues/507) you can track it. 

On the other hand, the Wazuh App is showing the agent status on two ways:

1. Agents status visualization on Overview (it fetch data each 10 minutes so it could be outdated by 10 minutes)
2. The agent list on Agents section, it fetch data from the Wazuh Api, it should be up to date always (if the agent is with TCP and the Wazuh manager works as expected).

Since this is a Wazuh manager issue but this is the Wazuh App repository I'm going to close it, but any case I'm going to copy this issue to the citated Wazuh manager issue in order to have your information on that issue. Thanks for your patience, have a nice day.

Best,
Jesús
