### ISSUE TITLE
No template found for the selected index-pattern

### ISSUE THREAD

**Issue by hastaki** [wazuh/wazuh-kibana-app#3505]
Hello
There was an error of such a plan
![image](https://user-images.githubusercontent.com/86711270/127306643-8ab57df1-5a33-4f59-9395-bc567f51d5af.png)
I was creating a new index to change the datatype
I set it by default and this problem occurred
If you set wazuh-alerts- * by default, then the problem disappears

**Comment by gabiwassan** [comment]
Hi @hastaki,
In order to help you, you can follow this [Troubleshooting guide](https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#no-template-found-for-the-selected-index-pattern).

Let me known if this works for you.

_**Very important: Clean the browser’s cache and cookies.**_
Best!
