### ISSUE TITLE
Disable RBAC for wazuh kibana plugin

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh-kibana-app#3545]
Hello,

We are using Cognito for AWS and this creates usernames for kibana in a random manner eg (cognito/GOOGLE_googleIdNumber). This makes the creation of usernames in Wazuh for Kibana usage impossible. Is there any way to disable role access all together so that anyone with access to kibana AND has access to the wazuh index to be able and use the app without setting up roles?

Thanks a lot,
Tony

**Comment by frankeros** [comment]
Hello @antonisnyc94, 
I'm not sure if understand what do you mean. 
I guess your problem is mapping Kibana users (from OpenDistro or X-Pack),  to the Wazuh roles to give access to the different Wazuh app sections. 
I'm mean setting this in `Wazuh / Security / Roles mapping` section. right? 
![image](https://user-images.githubusercontent.com/26828184/130281728-c3237645-4466-4eee-97d1-0fbd1b060181.png)

Well if this is your scenario, maybe you can solve this problem by mapping a Kibana role instead of each Kibana user 
when you set the third auth service (Cognito for example) to the Kibana security plugin surely you're adding the users into a Kibana role, you can use thisrole/s in a custom Role Mapping 

![image](https://user-images.githubusercontent.com/26828184/130283008-ec412089-86a6-45e6-a8e9-3fc8152fc7ba.png)
where my-custom-role is a Kibana role

Please let me know if this was helpful. 
Regards!

**Comment by frankeros** [comment]
Hi @antonisnyc94, were you able to solve your problem?

**Comment by antonisnyc94** [comment]
@frankeros At this point everyone has admin rights as i initially wanted. I believe i was able to do this by disabling xpack.RBAC in the wazuh.yaml file in kibana.
