### ISSUE TITLE
No Index - Wazuh-Monitoring-3.x*

### ISSUE THREAD

**Issue by claudiopbail** [wazuh/wazuh-kibana-app#356]
Hi guys,

I have an Elastic Cluster with 3 nodes at cenario below:

Server-1: ElasticSearch
Server-2: ElasticSearch + Logstash
Server-3: ElasticSearch + Kibana

All in version 6.2.2.

I Install Wazuh-Manager + Wazuh-API 3.2.1 in Server-2. My configurations it's OK, but the Wazuh-Monitoring-3.x-* index was not created.

I go to index patterns, but none "Wazuh-Monitoring" index exists.

The logstash it's OK and the "wazuh-alerts" index was correctly created too.

Could anyone help with this issue?

**Comment by jesusgn90** [comment]
Hi @claudiopbail,

since a Wazuh team member (Miguel Ángel) is helping you on the Google mailing list , https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/ebXL4TXlyM0/4J2COz9FBwAJ, I'm going to close this issue to avoid duplicate threads. Any case feel free to open many issues as you need, have a nice day.

Best,
Jesús
