### ISSUE TITLE
Request for Wazuh App for non-vulnerable Kibana Versions

### ISSUE THREAD

**Issue by jsoliani** [wazuh/wazuh-kibana-app#3612]
| Wazuh | Elastic | Rev   | Security |
| ----- | ------- | ---- | -------- |
| 4.2.1 | 7.11.2 | 40212 | Platinum |

  Hi team, hope you are doing great.

**Description**
 Since vulnerabilities were found using Elasticsearch versions lower than 7.14.0 and Kibana versions lower than 7.13.0, a new Wazuh Kibana App is requested that supports the versions with the vulnerabilities fixed.

---
 CVE ID: CVE-2021-22142 
 CWE-1104: Use of Unmaintained Third Party Component.
 
Kibana contains an embedded version of the Chromium browser that the Reporting feature uses to generate the downloadable reports. If a user with permissions to generate reports is able to render arbitrary HTML with this browser, they may be able to leverage known Chromium vulnerabilities to conduct further attacks. Kibana contains a number of protections to prevent this browser from rendering arbitrary content. 

 - Affected Versions: All Kibana versions before 7.13.0 (solved in version 7.13.0)
   CVSSv3 - 6.6: AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H 
---
 CVE ID: CVE-2021-22145 
 CWE-125: Out-of-bounds Read 

Elasticsearch memory disclosure issue (ESA-2021-16). A memory disclosure vulnerability was identified in Elasticsearch’s error reporting. A user with the ability to submit arbitrary queries to Elasticsearch could submit a malformed query that would result in an error message returned containing previously used portions of a data buffer. This buffer could contain sensitive information such as Elasticsearch documents or authentication details.

 - Affected Versions: Elasticsearch 7.10.0 to 7.13.3 (solved in 7.13.4, there is no known workaround for this issue.)
   CVSSv3: 8.0 - AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H 
---
 CVE ID: CVE-2021-22148 

Enterprise Search Privilege Escalation issue ( ESA-2021-19). A flaw in Elastic App Search was discovered where API keys were not bound to the same engines as their creator. This could lead to a less privileged user gaining access to unauthorized engines. 

 - Affected Versions: Elastic Enterprise Search versions prior to 7.14.0 (solved in 7.14.0).
   CVSSv3: 8.1 - AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N
---
 CVE ID: CVE-2021-22149

Enterprise Search Privilege Escalation issue (ESA-2021-20). A flaw in Elastic App Search was discovered where API keys were missing authorization via an alternate route. Using this vulnerability, an authenticated attacker could utilize API keys belonging to higher privileged users. 

 - Affected Versions: Elastic Enterprise Search versions prior to 7.14.0 (solved in 7.14.0).
   CVSSv3: 8.1 - AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N
---

**Expected Result**
1. A Wazuh Kibana App that supports versions where these vulnerabilities are fixed (Kibana 7.14 and Elasticsearch 7.14).

  Thanks in advance,
  Let me know what else you need or if I missed anything.

Regards,
John Soliani.-

**Comment by iasdeoupxe** [comment]
Once month ago another version 7.14.1 was released fixing another bunch of vulnerabilities:

Kibana code execution issue (ESA-2021-21)

It was discovered that a user with fleet admin permissions could upload a malicious package. Due to using an older version of the js-yaml library, this package would be loaded in an insecure manner, allowing an attacker to execute commands on the kibana server.

Affected Versions:
Kibana versions 7.10.2 through 7.14.0

Solutions and Mitigations:
Users should upgrade to Kibana version 7.14.1

CVSSv3: 6.6 - AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H
CVE ID: CVE-2021-22150

Kibana path traversal issue (ESA-2021-22)

It was discovered that Kibana was not validating a user supplied path, which would load .pbf files. Because of this, a malicious user could arbitrarily traverse the Kibana host to load internal files ending in the .pbf extension.

Thanks to Luat Nguyen of CyberJutsu for reporting this issue.

Affected Versions:

Kibana versions before 7.14.0

Solutions and Mitigations:
Users should upgrade to Kibana version 7.14.1

CVSSv3: 3.1 - AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N
CVE ID: CVE-2021-22151

Kibana html injection issue (ESA-2021-23)

It was discovered that kibana was not sanitizing document fields containing html snippets. Using this vulnerability, an attacker with the ability to write documents to an elasticsearch index could inject HTML. When the Discover app highlighted a search term containing the HTML, it would be rendered for the user.

Affected Versions:

Kibana version 7.14.0

Solutions and Mitigations:

Users can set “doc_table:highlight” to “false” in the Kibana Advanced Settings. Users who do not wish to do this, and are currently on version 7.14.0 should upgrade to version 7.14.1.

CVSSv3: 4.3 - AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N
CVE ID: CVE-2021-37936

Kibana Node.js security vulnerabilities (ESA-2021-24)

Node.js version 14.17.3 is affected by several security vulnerabilities: CVE-2021-22930, CVE-2021-3672, CVE-2021-22931, CVE-2021-22930, and CVE-2021-22939. We do not believe an attacker can exploit these against Kibana, but we are upgrading Node.js out of an abundance of caution. Kibana 7.14.1 upgrades Node.js to version 14.17.5 to resolve these issues.

Affected Versions:

Kibana versions before 7.14.1

Solutions and Mitigations:

Users should upgrade to Kibana version 7.14.1

CVSSv3:
CVE ID: CVE-2021-22930, CVE-2021-3672, CVE-2021-22931, CVE-2021-22930, CVE-2021-22939

**Comment by frankeros** [comment]
Related to #3310

**Comment by iasdeoupxe** [comment]
New vulnerabilities in Kibana found:

Kibana Path Traversal issue (ESA-2021-26)

It was discovered that on Windows operating systems specifically, Kibana was not validating a user supplied path, which would load .pbf files. Because of this, a malicious user could arbitrarily traverse the Kibana host to load internal files ending in the .pbf extension.
Thanks to Dominic Couture for finding this vulnerability.

Affected Versions:

All versions from 7.9.0 through 7.15.1

Solutions and Mitigations:
Users should upgrade to Kibana version 7.15.2

CVSSv3: 3.1 - AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N
CVE ID: CVE-2021-37938

Kibana Information Disclosure issue (ESA-2021-27)

It was discovered that Kibana’s JIRA connector & IBM Resilient connector could be used to return HTTP response data on internal hosts, which may be intentionally hidden from public view. Using this vulnerability, a malicious user with the ability to create connectors, could utilize these connectors to view limited HTTP response data on hosts accessible to the cluster.

Affected Versions:

All versions from 7.8.0 through 7.15.1

Solutions and Mitigations:

Users should upgrade to Kibana version 7.15.2

CVSSv3: 4.1 - AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:N/A:N
CVE ID: CVE-2021-37939

**Comment by iasdeoupxe** [comment]
https://documentation.wazuh.com/current/release-notes/release-4-2-5.html#what-s-new:

> Support for Kibana 7.13.4.
>
> Support for Kibana 7.14.2.

Looks like the most severe vulnerabilities are now solved since we can update Kibana to 7.14.2. It only looks like these two newer versions are not mentioned on the index page here so user might not be aware of this update possibility:

https://github.com/wazuh/wazuh-kibana-app/#wazuh---kibana---open-distro-version-compatibility-matrix
