### ISSUE TITLE
Improve home button 

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh-kibana-app#3618]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.1  | 7.10.2 | 4202-1| ODFE|

| Browser |
| ------- |
| Chrome|

**Description**
Hi team!

In Wazuh cloud environments, when clicking the Wazuh home button all bundles are reloaded, which affects the user experience as it takes longer to access the tab.

We need this button to work the same as the **`Wazuh > Modules > Modules directory`** button.

If this is not possible due to Kibana's constraints, an alternative would be to add a home button placed inside the Wazuh app that can be quickly accessed.

**Screenshots**

![image](https://user-images.githubusercontent.com/33484080/134326487-a8e0bf92-f8c8-4b6d-9717-618a6d69aa4d.png)

Best regards.

**Comment by frankeros** [comment]
Hi @Phandora we can't do that the button works like the menu entry because this button is overridden by a custom script (just for the cloud version) that is running at the top of the DOM on the client-side, the menu is an HTML link instead of a call to action from React as the menu does. 

I'm closing this issue.
