### ISSUE TITLE
Time-consuming Agents section

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#3623]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

**Description**
The `Agents` section for the app can take too much time to load and render some elements. This is due to the requests related to Elasticsearch when the selected app time filter involves numerous documents or the Elasticsearch response is slow. The `Agents` section should be fast because it is frequently visited.

**Tasks**
- [ ] Research about how to enhance the performance. Some possible solutions:
  - Limit the time filter range to a specific value and doesn't depend on the app selected time filter
  - Move the related UI elements to another view (`Evolution` visualization and `Most agent active` stat)
  - Add a time picker
- [ ] Apply the better solution

**Acceptance criteria**
- The view should be fast and not be affected by environments with numerous documents in its indices.

**Comment by asteriscos** [comment]
## Initial analysis

#### Environment
The initial test was made in a local environment with 110k agents

#### Sitespeed Watefall

![image](https://user-images.githubusercontent.com/9343732/181313533-4dca677c-d037-4976-b2a9-97a6c3310892.png)

### Analysis

In this first approach we detected that the most time consuming requests were made to Wazuh API in agent related endpoints, such as:

- `/agents/summary/status`
- `/agents`
- `/agents/000/config/auth/auth`
- `/agents/000/config/request/remote`

These requests are made by:

_agents-preview_ controller
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/agents-preview.js#L80

_agents-table_ component
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-table.js#L170
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-table.js#L171
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-table.js#L232

_agents-preview_ component
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-preview.js#L113
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/agents-preview.js#L115

_register-agent_ component
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/register-agent.js#L213
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/controllers/agent/components/register-agent.js#L223

In this analysis we observed the _register-agent_ component is loading as soon as the agents-preview controller initializes, but this component should be rendered only if the user clicks on **_Deploy Agent_** wizard button.
This can be easily fixed by changing the `ng-show` to `ng-if` when the agent deployment wizard is active:
https://github.com/wazuh/wazuh-kibana-app/blob/4.3-7.10/public/templates/agents-prev/agents-prev.html#L39

The analysis of this section is still in progress.

**Comment by AlexRuiz7** [comment]
Performance comparative is in the PR

**Comment by asteriscos** [comment]
## Fix strategy

The strategy used in the issue [Agents section performance improvements #4363](https://github.com/wazuh/wazuh-kibana-app/pull/4363) is to:

- Reduce the number of requests to Wazuh API 
- Use the same request to feed all the components that require the information
- Load widgets requests in parallel asynchronously whenever possible _(avoid sequential requests)_
- Replace the top big loading icon with 3 independent loading indicators to be able to show data as soon as it is available _(Related with the previous point)_

Pending issue: 
- [ ]  #4388
