### ISSUE TITLE
The registry values of are not displayed in FIM - Events

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-kibana-app#3677]
| Wazuh | Elastic |  Security |
| ----- | ------- | -------- |
| 4.2.4   | 7.10.2     |  ODFE |

| Browser |
| ------- |
| Chrome|

**Description**
Opening the Windows Registry Detail from FIM / Events, the registry values are getting error 500.
But if you pin the corresponding Windows agent, the values are displayed ok.

**Preconditions**
1. With a new session in incognito.
2. Without an agent selected.

**Steps to reproduce**
1. Navigate to 'FIM / Events'
2. Click on the `syscheck.path` value of a Windows registry
3. The table Registry values is empty and the console shows an 500, and the request shows and `undefined` in his body

**Expected Result**
1. The table Registry values shows all values

**Actual Result**
1. The table Registry values is empty

**Screenshots**
Without an agent selected
![image](https://user-images.githubusercontent.com/26828184/140053977-bf7bbfdf-542f-4a37-9a0a-17dff3b05047.png)

With an agent selected
![image](https://user-images.githubusercontent.com/26828184/140054896-b4b970bb-8f8b-462b-9c5e-1a78bebe1e1e.png)

**Additional context**
Pinning the windows agents the values are displayed correctly.

**Comment by yenienserrano** [comment]
**Description**
It was added to see the ID of the agent that corresponds to the file that you want to see, since the ID of the pinned agent was being taken only

**PR**

Add id when agent is not pinned [#3689](https://github.com/wazuh/wazuh-kibana-app/pull/3689)

**Test**

_Preconditions_
Without an agent selected.

_Steps_ 
1. Navigate to 'FIM/Events'
2. Click on the `syscheck.path` value of a Windows registry
3. See if the registry value table is not empty.
4. Pin an agent
5. Click on the `syscheck.path` value of a Windows registry
6. See if the registry value table is not empty.

**Check List**

- [x] See registry values ​​with a pinned agent
- [x] See registry values ​​without a pinned agent


**Screenshots**

_Without an agent selected_

![image](https://user-images.githubusercontent.com/63758389/142483345-e5ef9c30-d627-4da6-b70e-43875fccec5f.png)

_With an agent selected_

![image](https://user-images.githubusercontent.com/63758389/142483548-e804bbd1-ccc7-4ee4-9811-4b6e85e12b11.png)
