### ISSUE TITLE
No template found for the selected index pattern in CCS

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-kibana-app#3745]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5   | 7.10.2     | 4xxx | ODFE |

| Browser |
| ------- |
| Any |

**Description**
In an environment configured as Cross Cluster Search where we have 2 remote clusters (`remote1_prod`, `remote2_prod`), when the health check is done we have the error:
![image](https://user-images.githubusercontent.com/37050249/146948612-1145791d-f345-4ecb-987c-db5cf042c169.png)

This was working without issues in Wazuh 4.1.5, and when we upgraded to 4.2.5 this started to happen.

**Steps to reproduce**
1. Install Wazuh 4.1.5 and configure an environment of Elasticsearch Cross Cluster search.
2. Upgrade the environment to 4.2.5
3. Execute the Wazuh App Health Check.

**Expected Result**
1. All health checks ok.

**Actual Result**
1. Error in templates for the index patterns of the remote clusters.

**Troubleshooting**
1. Tried adding the index patterns to the template and that is not possible because the `:` are not accepted:
![image](https://user-images.githubusercontent.com/37050249/146949503-46568e71-e656-4d79-a7bf-966421b6b99c.png)
2. Tried with this configurations in the Wazuh App:
![image](https://user-images.githubusercontent.com/37050249/146949762-c15ff0f5-428e-4a0f-a959-4e54b5904502.png)
![image](https://user-images.githubusercontent.com/37050249/146949792-f96a6a25-ec5e-4484-9a25-98417c7b5e95.png)
But without success, same error.

Thank you in advance!

**Comment by Desvelao** [comment]
From Wazuh app version `4.2.0`, the configuration for `checks.template` and `checks.fields` was unified under the `checks.pattern`. This does some environments can't pass the `Alerts index pattern` in the health check due to the `template` check.

There is a PR that runs the check depending on the app configuration https://github.com/wazuh/wazuh-kibana-app/pull/3783. The planning is this change be available in Wazuh app 4.3.0.

Related issue https://github.com/wazuh/wazuh-kibana-app/issues/3765
