### ISSUE TITLE
Vulnerability scan does not show in the Wazuh GUI

### ISSUE THREAD

**Issue by Esmirbec** [wazuh/wazuh-kibana-app#3807]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.5  | 7.10.2 |

| Browser |
| ------- |
| Chrome, Firefox, Edge|

**Description**
Vulnerability Scan section on the Wazuh GUI shows no results

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to 'Wazuh -> Agents -> Select an agent '
2. Click on ' click on Vulnerability tab'
3. Shows no results
4. 4. When I check logs on the server and agents, it shows that vulnerability scan was performed on each of the agents

**Expected Result**
1.  Seeing Vulnerabilities on agents (all agents are Windows Agents)

**Actual Result**
1. There are no results for selected time range. Try another one.

**Screenshots**
Added screenshot
![wazuh](https://user-images.githubusercontent.com/98118776/150400125-1c0aa108-bf78-4abf-b815-e7f4badd7691.png)

**Comment by Desvelao** [comment]
Hi @Esmirbec ,

I see you could solve the problem referred to this issue in the comment https://github.com/wazuh/wazuh-kibana-app/issues/3808#issuecomment-1021124386.

As you can see in the screenshot, there are 3 filters applied:
- `manager.name`
- `rule.groups`
- `agent.id`

If you have some alerts that match these filters in the range of time selected, you should see the alerts in the dashboard. Maybe you can check if you have alerts related to the Vulnerabilities modules that were indexed in Elasticsearch, and you can inspect the value for  `manager.name` property. In the case that the `manager.name` of an indexed alert is different from value for that filter displayed in Kibana, this could be the reason because the alert is not displayed.
