### ISSUE TITLE
Events documents are redirecting to the homepage - OpenSearch

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-kibana-app#3850]
| Wazuh | OpenSearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 1.2.x| 4.3 RC2 (OpenSearch) | OSFE |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Events documents links are redirecting to the home page

**Preconditions**
1. The user need to have event's data

**Steps to reproduce**
1. Navigate to Modules/security events/events
2. Click on the "Event" tab
3. Select one particular event
4. Click the link for single document

**Expected Result**
1. The user should be redirected to the expected documentation

**Actual Result**
1. The user is redirected to the OpenSearch home page

**Screenshots**

**Additional context**
This happens with surrounding documents too

**Comment by Mayons** [comment]
@Desvelao this bug is still reproducible on RC for WazuhDashboard.The links are redirecting to an empty page
![image](https://user-images.githubusercontent.com/33849347/155583868-c56292a1-9543-4a6a-a2da-45141a82f2cb.png)

**Comment by Desvelao** [comment]
> @Desvelao this bug is still reproducible on RC for WazuhDashboard.The links are redirecting to an empty page ![image](https://user-images.githubusercontent.com/33849347/155583868-c56292a1-9543-4a6a-a2da-45141a82f2cb.png)

I experienced the same result as @Mayons reported. It seems the problem could be due to a configuration for the base URL of Wazuh dashboard that does the URL contains `/wazuh?security_tenant=global` and a route resolver can't replace `/wazuh#` by `/opensearch-dashboards#`.

If navigating to another plugin and going to the `Wazuh` plugin, the URL doesn't have the `?security_tenant=global`, containing `/wazuh#` and this section of URL is replaced in the mentioned resolver.
