### ISSUE TITLE
Environment redesign

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#3872]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Dashboard | -      | Packages/Sources | -  |

Using the inventory and the mock server, we should be able to update our working environments to work without other Wazuh components.

This environment will allow us to test the UI and the ELK queries deeper, increasing the robustness of our delivery.

## Goals

When this issue is completed, we should be able to launch a development or testing environment using docker-compose. The environments' folder within our repository, [wazuh-kibana-app](https://github.com/wazuh/wazuh-kibana-app) should take care of setting up everything for us, without configure anything locally.

## Considerations

- The containers should persist through restart cycles, avoiding loosing data. We can use [persistent volumes](https://docs.docker.com/storage/volumes/) to persist data without modifying the container images.

- These environments must be compatible with multiple platforms (Linux, Windows, Mac) so we can assume the presence of [docker-desktop](https://www.docker.com/products/docker-desktop/) (free for open source projects). 

- The environments should work without using the Wazuh Manager or Wazuh Agent components. We want to use a mock server and an event generator to develop and test our application. This allows us to test situations which are difficult to reproduce with a real instance of these components, like endpoint failures. 

- Some tests might require to use a Wazuh deployment. We should leverage the official docker images published by CI/CD along without own images.

- Assume we use an editor which support Docker, like Visual Studio Code.

## Main tasks

- [x] Design the development environment, so we can develop new features and fixes with it.
- [x] Design the testing environment, so we can test our fixes and features against multiple combinations of platform versions automatically.
- [x] Generate these environments, including all supported platforms (ELK, Wazuh-dashboards, Splunk)
- [x] Generate documentation on how to use these environments and how to maintain them over time. We should include this documentation in this site and in our repo wiki.

**Comment by matiasmoreno876** [comment]
Currently working on the following PR:

> Environments for 7.20.2
https://github.com/wazuh/wazuh-kibana-app/pull/3888

> Environments for < 7.16.3
https://github.com/wazuh/wazuh-kibana-app/pull/3914

**Comment by matiasmoreno876** [comment]
Below I present a graph of how is the model that is being implemented for development environments,

Thanks to this approach, it is not necessary to have any dependencies installed on our local machines to be able to run our app, since they will be used within the kibana-dev container.

![environments](https://user-images.githubusercontent.com/49887871/160151159-73e9b751-9efa-4443-9a8e-f0868c77399b.png)

**Comment by matiasmoreno876** [comment]
Currently the environments that will be available for development are the following:

**Release 4.3**

Templates Elastic Dev

- [ ] es_basic-wz_cluster-agent-7.10.2
- [ ] es_odfe-wz_cluster-agent-1.13.2
- [ ] es_xpack-wz_cluster-agent-7.10.2

Templates Opensearch Dev

**Comment by AlexRuiz7** [comment]
## Status

The new environments are being worked in this branch: [feature/3872-environments-docker](https://github.com/wazuh/wazuh-kibana-app/tree/feature/3872-environments-docker)


We've been using these environments until now. Not only they were hosted in a personal, private GitHub repository, but most of the Docker images and their configurations were mostly hand-made, this is, no official images were used, at least for Wazuh.

The versions of Wazuh and the platform to be launch were defined in a _.env_ file, which fed the docker-compose, deciding the Docker image to use.

The environment ups a whole Wazuh architecture, which forced us to wait for core developments to finish in order to start our developments. Also, this was a great handicap when we need to force particular conditions, for example, during bug hunting and fixing.

Lastly, the UI and its platform was configured and launched from the host system, which required the developers to install the required dependencies in their system, and to maintain their configurations.

In addition to this, the compiled Docker images were not hosted anywhere, so each developer had necessarily to compile the images at least once, compiling Wazuh from source in some cases, when no packages were available yet. This meant a huge lost of time for each developer.

![12_08_2022 (TH)-old_envs](https://user-images.githubusercontent.com/15186973/187955681-5199ec83-a657-487d-9268-a38c70d68afc.png)

------------

The main goal of the new environments is to unchain our team from core / framework developments, so we no longer need to wait for their developments to be finished to start ours. With the implementation of a mock server, we can start our developments as soon as we receive a contract from the @wazuh/framework team, this is, their [OpenAPI specification](https://github.com/wazuh/wazuh/blob/master/api/api/spec/spec.yaml).

Wazuh, as a whole, is now compressed into a container which runs a mocked service, over whom we have full control.

The Docker images for the platforms we use; and Wazuh's, during testing, are now based on official images, which we pre-configure, compile and upload to our Quay.io repository. No hand-made images are used anymore. This brings us closer to a production environment, at least in terms of configurations, and saves a lot of time for the developers, and they no longer need to compile the images, only to download them.

A big difference with this new approach, is that the UI and the platform are new dockerized and autoconfigured, making it much easier for the developers to get started.

Optionally, the Docker environments can be monitored using Grafana and Prometheus, tools that are also dockerized and that communicates with the development environments using a dedicated Docker network, which all containers use.

Finally, a bash script is used to manage the environments. The developer runs this script providing the desired versions to use, and the absolute path to the app's source code, which is mounted as a volume in the container. The only precondition is that the source code must be checked out at the correct development branch (for the correct platform, Elastic, OpenSearch, Wazuh Indexer)

![12_08_2022 (TH)-new_envs_mon](https://user-images.githubusercontent.com/15186973/187955669-164c4746-cd85-4bc7-88da-4f6b8d8db2e4.png)


Latest update: 01-09-2022

**Comment by AlexRuiz7** [comment]
Currently running a last quality and validation check.

Development environments
- [ ] kbn-dev
- [ ] osd-dev

Pre-release and release environments
- [ ] wazuh-4.2-es
- [ ] wazuh-4.3-es
- [ ] wazuh-4.3-wz

Utility environments
- [ ] verdaccio (npm cache)
- [ ] imposter (mock server)
- [ ] mon (monitoring environments based on Grafana and Prometheus)

**Comment by AlexRuiz7** [comment]
Remaining environments (not implemented yet)
- [ ] odfe-dev
- [ ] wazuh-4.3-odfe

**Comment by AlexRuiz7** [comment]
Environments that need custom indices permissions (to manage sample data, wazuh-monitoring, ...):

- [ ] wazuh-4.2-es/pre
- [ ] wazuh-4.2-es/rel

**Comment by AlexRuiz7** [comment]
The scripts to launch production environments now provide a command to deploy an Ubuntu agent and attach it to the Docker Compose project. This has been achieved by including the [correct label](https://docs.docker.com/engine/reference/commandline/run/#set-metadata-on-container--l---label---label-file) to the `docker run` command.

![image](https://user-images.githubusercontent.com/15186973/194590530-030366b2-dd10-4046-8d55-9c3c41279d5a.png)

In the future, we'll include agents to the rel.yml files (docker-compose.yml), when the Wazuh agents are dockerized.
https://github.com/wazuh/wazuh-docker/issues/412

**Comment by AlexRuiz7** [comment]
Adding the labels to every production environment:

Pre-release and release environments
- [ ] wazuh-4.2-es/rel
- [ ] wazuh-4.3-es/rel
- [ ] wazuh-4.3-wz/rel
- [ ] wazuh-4.3-odfe/rel

**Comment by AlexRuiz7** [comment]
Fixed a problem in some environments where Docker would create 2 networks for the same project. For example: `wz-43-rel` and `wz-43-rel_default`

**Comment by AlexRuiz7** [comment]
In relation to [this](https://github.com/wazuh/wazuh-kibana-app/issues/3872#issuecomment-1265304141), I've been trying to set up the permissions required by the app using configuration files, but does not seem to work. However, I've been able to create the required role and user using the UI.

As I haven't found any suitable way to create users and roles using configuration files, I do not see any other option than to create via API, so I'd need to add these requests during in the environment building process somehow (probably using a cURL image).

Resources I've followed:

File-based:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.17/defining-roles.html#roles-management-file
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/defining-roles.html#roles-management-file
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/security-trb-roles.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/security-files.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/file-realm.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/mapping-roles.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/users-command.html

UI:
- https://www.elastic.co/guide/en/kibana/current/role-mappings.html

**Comment by AlexRuiz7** [comment]
How to set up permissions using the API:

1. Create a [new role](https://www.elastic.co/guide/en/kibana/current/role-management-api-put.html#_examples_3)

```bash
PUT _security/role/wazuh_indices
{
  "cluster": ["all"],
  "indices": [
    {
      "names" : [
        "wazuh-*"
      ],
      "privileges" : [
        "all"
      ]
    }
  ]
}
```
2. Create a new user (`kibana_system` is reserved, hence can't be modified)

```bash
PUT _security/user/wazuh_app
{
  "username" : "wazuh_app",
  "password" : "wazuh_app",
  "roles" : [
    "kibana_system",
    "wazuh_indices"
  ],
  "full_name" : "",
  "email" : ""
}
```
In step 2, the `kibana_system` and our `wazuh_indices` roles are mapped to the user.

3. Replace the Kibana internal (`kibana.yml`) user with the new role: 
```yml
elasticsearch.username: wazuh_app
elasticsearch.password: wazuh_app
```

**Comment by AlexRuiz7** [comment]
I've added a script to the kbn_dev environment that runs as the Kibana's docker compose service healthcheck. Successfully solves the problem:

- `wazuh-monitoring` index created and storing data:
![image](https://user-images.githubusercontent.com/15186973/200356501-5e39f00d-048d-4f9c-aa4a-f28f1c42b77a.png)

- No error messages in the console:
![image](https://user-images.githubusercontent.com/15186973/200356753-c4ecf934-b90f-487a-a2d1-d97408f510f5.png)

Changes are in this commit https://github.com/wazuh/wazuh-kibana-app/pull/4435/commits/5398d8f8b5273e91d3bc25270e59c0d43b28293c

I'll extend the changes to the rest of Elastic environments tomorrow.

**Comment by AlexRuiz7** [comment]
Problem detected in `wazuh-4.3-es:pre` related to the index patterns

![image](https://user-images.githubusercontent.com/15186973/201315307-5bdedf00-7d14-4c5d-b754-58c07b2c8131.png)

These are the logs from Filebeat, which is the component that sends the index patterns to Kibana, afaik.

```log
sh-4.2# filebeat setup -e
...
2022-11-11T09:53:18.813Z        INFO    instance/beat.go:299    Setup Beat: filebeat; Version: 7.10.2
2022-11-11T09:53:18.814Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://es01:9200
2022-11-11T09:53:18.814Z        INFO    [publisher]     pipeline/module.go:113  Beat name: filebeat
2022-11-11T09:53:18.816Z        INFO    beater/filebeat.go:117  Enabled modules/filesets: wazuh (alerts),  ()
2022-11-11T09:53:18.817Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://es01:9200
2022-11-11T09:53:18.825Z        INFO    [esclientleg]   eslegclient/connection.go:314   Attempting to connect to Elasticsearch version 7.17.6
ILM policy and write alias loading not enabled.

2022-11-11T09:53:18.827Z        INFO    template/load.go:183    Existing template will be overwritten, as overwrite is enabled.
2022-11-11T09:53:18.828Z        INFO    template/load.go:117    Try loading template wazuh to Elasticsearch
2022-11-11T09:53:18.878Z        INFO    template/load.go:109    template with name 'wazuh' loaded.
2022-11-11T09:53:18.879Z        INFO    [index-management]      idxmgmt/std.go:298      Loaded index template.
Index setup finished.
Loading dashboards (Kibana must be running and reachable)
2022-11-11T09:53:18.879Z        INFO    kibana/client.go:119    Kibana url: http://kibana:5601
2022-11-11T09:53:20.881Z        INFO    kibana/client.go:119    Kibana url: http://kibana:5601

2022-11-11T09:54:29.613Z        INFO    instance/beat.go:815    Kibana dashboards successfully loaded.
Loaded dashboards
2022-11-11T09:54:29.613Z        WARN    [cfgwarn]       instance/beat.go:556    DEPRECATED: Setting up ML using Filebeat is going to be removed. Please use the ML app to setup jobs. Will be removed in version: 8.0.0
Setting up ML using setup --machine-learning is going to be removed in 8.0.0. Please use the ML app instead.
See more: https://www.elastic.co/guide/en/machine-learning/current/index.html
2022-11-11T09:54:29.614Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://es01:9200
2022-11-11T09:54:29.628Z        INFO    [esclientleg]   eslegclient/connection.go:314   Attempting to connect to Elasticsearch version 7.17.6
2022-11-11T09:54:29.629Z        INFO    kibana/client.go:119    Kibana url: http://kibana:5601
2022-11-11T09:54:29.668Z        WARN    fileset/modules.go:421  X-Pack Machine Learning is not enabled
Loaded machine learning job configurations
2022-11-11T09:54:29.669Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://es01:9200
2022-11-11T09:54:29.679Z        INFO    [esclientleg]   eslegclient/connection.go:314   Attempting to connect to Elasticsearch version 7.17.6
2022-11-11T09:54:29.681Z        INFO    fileset/pipelines.go:143        Elasticsearch pipeline with ID 'filebeat-7.10.2-wazuh-alerts-pipeline' loaded
Loaded Ingest pipelines
```

**Comment by AlexRuiz7** [comment]
Pre-release environment for Elastic & Kibana 7.17.6, using mocked Wazuh 4.3.9
![image](https://user-images.githubusercontent.com/15186973/201358053-6b2c1bd3-b055-45fa-b71c-d2b30d7a884b.png)
