### ISSUE TITLE
macOS ULS configuration can not be added

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-kibana-app#3921]
| Wazuh | Opensearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.0   | 1.2.0    | 4301-1 | Wazuh Indexer |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**

Adding the new configuration for macOS ULS logs in a group configuration breaks the app.

**Steps to reproduce**
1. Navigate to any group's configuration.
2. Add the following: 
```<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,trace" level="info">process == "sshd" OR message CONTAINS "invalid"</query>
</localfile>
```
3. Then save it.

**Screenshots**
![macosthroughgroups](https://user-images.githubusercontent.com/16334770/160592224-d8cfb735-8d54-4974-b581-ea75f9a4a128.gif)

![networktabrequestmacos](https://user-images.githubusercontent.com/16334770/160592199-29dec254-d363-4018-bc23-0bee000b9168.png)

**Additional context**
The configuration can be added from the CLI `/var/ossec/etc/shared/default/agent.conf` and works as expected.

**Comment by MiguelCasaresRobles** [comment]
This issues seems to be connected to: https://github.com/wazuh/wazuh/issues/12903

The Wazuh API should validate this.

**Comment by juliancnn** [comment]
As @MiguelCasaresRobles  tells us, this issue is strictly related to:

- Verify-agent-conf tool considers macOS logformat as invalid (https://github.com/wazuh/wazuh/issues/12903)
- Precedence/Multigroup it is not applied for macos localfile configuration (https://github.com/wazuh/wazuh/issues/12904)

Initially, the `macos` localfile block was only supported by MacOS, linux (Manager) does not recognize this option, triggering troubles with validations and centralized configuration.

The 3 issues are fixed in the PR: https://github.com/wazuh/wazuh/pull/13035

If you wish you could test the PR with these [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.0-0.commitca1e731.x86_64.rpm) and [rpm](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.0-0.commitca1e731_amd64.deb) packages

DEMO:

https://user-images.githubusercontent.com/1891958/161874743-388222cc-bfd7-440e-831f-87b6f24a9dac.mp4
