### ISSUE TITLE
Amazon AWS dashboard not showing information in some graphs

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-kibana-app#3931]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.10.2  | 4301-1 | ODFE |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The AWS module shows "No results found" for both the Accounts and Regions sections. I'm not sure if this is a bug because Cloudtrail is the only integration I enabled in this case.

**Preconditions**
N/A

**Steps to reproduce**
1. Enable the Cloudtrail integration in Wazuh ([instructions](https://documentation.wazuh.com/current/amazon/services/supported-services/cloudtrail.html)).
2. Go to the Amazon AWS module in the Wazuh APP. 

**Expected Result**
All graphs inside the module should show any information.

**Actual Result**
All graphs show information, except for `Regions` and `Accounts` which say: `No results found
`
**Screenshots**
![image](https://user-images.githubusercontent.com/23361101/161022601-cf15aa78-d371-44a9-be47-bc594de42839.png)

**Additional context**
The alerts that were generated do contain fields for Regions and Accounts but then they are not displayed on the dashboard.
![image](https://user-images.githubusercontent.com/23361101/161024865-d8933785-4b94-4240-ade3-4cd0f0f688cc.png)

**Comment by mandeeps13k** [comment]
Hi Team,

Any updates on timeline for the fix of this issue ?

It would be great to have this issue fixed because the dashboards currently are not able display AWS Account IDs from cloudTrail logs. Even with logs from many different aws account IDs, the `accounts` as well as `regions` spaces in the AWS Dashboards remain empty. 

It would be really great if this is fixed at the earliest. Looking forward to it.
Thanks.

**Comment by gdiazlo** [comment]
Related issues 
- #2004 
- #2260
- https://github.com/wazuh/wazuh/pull/4459

**Comment by AlexRuiz7** [comment]
We tested the PR https://github.com/wazuh/wazuh/pull/4459 and confirmed that adding these mappings results in a transformation of fields from `aws.awsRegion` to `aws.region`, so the Dashboards are rendering the results properly now.

In order to test this, we configured the AWS module, as defined in the step nr.1 of this issue, and then, appending AWS logs to the `alerts.json` file.

![image](https://user-images.githubusercontent.com/15186973/191794547-1c33282b-6520-4f3f-b07d-d8b1fdf3eb6f.png)


![image](https://user-images.githubusercontent.com/15186973/191794078-098412da-a5ff-4791-971b-ab55410a0ecb.png)

**We need to test if this continues to work in a fresh environment**, as we used the [Elastic API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/set-processor.html) to update the ingest pipelines with the new mappings.

**Comment by Machi3mfl** [comment]
## Task:  test in a fresh environment
Tested PR [https://github.com/wazuh/wazuh/pull/4459](https://github.com/wazuh/wazuh/pull/4459) in a fresh environment.
![Selection_043](https://user-images.githubusercontent.com/6089438/192036426-0ffce09b-879e-4c34-887a-a471432f4e60.png)
![Selection_042](https://user-images.githubusercontent.com/6089438/192036444-7a8bdef3-d159-4983-914f-3134bda4eeec.png)
