### ISSUE TITLE
Sorting the alerts on any panel does not work 

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-kibana-app#3940]
**Describe the bug**

It is not possible to sort the alerts on any panel of the application (tested on `Security Evets -> Events` and `Vulnerabilities -> Events`).

**To Reproduce**

1. Go to  `Security Events -> Events` or `Vulnerabilities -> Events`

![image](https://user-images.githubusercontent.com/1891958/161291896-41ad8c8a-d08e-4678-85e7-778e3085656d.png)

2. Try sorting the events by some field. (Blue arrows)

![image](https://user-images.githubusercontent.com/1891958/161292030-7e53282c-367b-4215-9748-819fccc94f5c.png)

Result: events do not get ordered

https://user-images.githubusercontent.com/1891958/161292414-6539708d-9cbe-4f8d-8776-1e553e065dd5.mp4

**Expected behavior**

Events are sorted by the selected field

**Wazuh Indexer Version**

4.3.0 RC

**Wazuh Dashboard Version**

4.3.0 RC

**Plugins**

Default installation

**Host/Environment (please complete the following information):**

 - OS: Arch Linux (Rolling release)
 - Browser and version: Firefox and Chrome last versions

**Additional context**

-

**Comment by JcabreraC** [comment]
When we want to sort the data by columns, it is not able to sort alphabetically.
Issue: **[BUG] Sorting the alerts on any panel does not work** [#3949](https://github.com/wazuh/wazuh-kibana-app/issues/3940)



https://user-images.githubusercontent.com/1891958/161297899-513f1c27-b9a1-48a9-9e13-f77c393226ff.mp4



For example:
- `CVE`: Sort the column correctly
- `Package name`: Incorrectly sorts the column
- `severity`: Does not make any kind of order

**Comment by gdiazlo** [comment]
The multi-field sorting in discover is tricky. It is something general as you can see https://discuss.elastic.co/t/sorting-in-discover-not-working/204626/5

When the discover widget shows events, it automatically sorts the results by timestamp. If a user clicks other fields to sort, it becomes a multi-field sorting of timestamp plus the new field the user wants to sort.

In order to get the expected results, it is necessary to disable the timestamp field sorting.
