### ISSUE TITLE
Wazuh app empty

### ISSUE THREAD

**Issue by ruzzetto** [wazuh/wazuh-kibana-app#406]
Hi,
I've installed agent on a win10 machine and centos7. They're registered with manager. I configured agents in order to enable syscollector (even on manager) and try to generate some events in order to alert get fired (for example windows login failed, or "su" password wrong).

No data in wazuh app. Both for my attempts and vulnerabilities check.

Bye,
Fabio

**Comment by JuanjiJG** [comment]
Hello @ruzzetto,

Syscollector is used to fetch information from your agents or manager such as the list of installed programs, hardware, etc. You can read the reference manual [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html).

Currently, `syscollector` doesn't generate any kind of alerts on the manager. Instead, the `vulnerability-detector` module does generate alerts when detects vulnerable packages thanks to `syscollector`.

In order to properly configure it, you have to add the `syscollector` configuration block on all your agents (and also the manager if you want to scan it for vulnerabilities too):
```xml
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>
```

And restart all the agents...:
```
systemctl restart wazuh-agent
```
And the manager (if you applied this configuration to it too):
```
systemctl restart wazuh-manager
```

The next step is enabling the `vulnerability-detector` module **on the manager**. To do this, usually you'll find by default the module pre-configured, but disabled:
```xml
<wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>1d</interval>
  <run_on_start>yes</run_on_start>
  <update_ubuntu_oval interval="15h" version="16,14">yes</update_ubuntu_oval>
  <update_redhat_oval interval="15h" version="7,6">yes</update_redhat_oval>
</wodle>
```

Just make sure that the `<disabled>` label has the `no` value. Then, restart your manager:
```
systemctl restart wazuh-manager
```

Now, after restarting the manager, it will start the vulnerabilities scan. You'll have to wait some minutes until it's finished, but after that, you should see alerts on the **Vulnerabilities** tab in the Wazuh app.

If you still have more questions, don't hesitate to post a new comment.

Regards,
Juanjo

**Comment by ruzzetto** [comment]
Hi @JuanjiJG ,
thanks for support. Yesterday I read a post where you suggest to user to configure agent and manager in order to enable syscollector. So, configuration is already right according your suggestions in that post. Where can i view data collected by syscollector? 
Regards,
Fabio

**Comment by JuanjiJG** [comment]
Hello @ruzzetto, and sorry for the late response.

The data collected by `syscollector` can be found on every specific manager or agent database. For example, the database for the manager can be found at:
```
sqlite3 /var/ossec/queue/db/000.db
```

Using the `.schema` function will list all the available tables. After opening the database with the `sqlite3` command, we can check the `sys_hwinfo` table with:
```
sqlite> SELECT * FROM sys_hwinfo;
```

There are many other tables such as `sys_programs` or `sys_processes` that you can check out.

Feel free to post a new comment if you still have questions or problems with this.

Regards,
Juanjo

**Comment by ruzzetto** [comment]
Ok thanks. So the info stored into database are shown in agent preview right?

Anyway I'd like to populate wazuh app with some kind of data but it's impossible. I've added 4 agents and all the dashboards are empty. No alerts fired. I even activated oscap on a client but nothing appear on the dashboard.
Regards,
Fabio

**Comment by JuanjiJG** [comment]
Hello again @ruzzetto,

Not all agent info stored in the database is shown on the agent preview on the Wazuh app. For example, we still have to work on implementing the `syscollector` module information on the Wazuh app.

Regarding your problem with no data available on the agents, we should see if you've properly configured your Elastic installation. Could you please execute the following commands and paste here the output?

```
lsof /var/ossec/logs/alerts/alerts.json
curl -XGET localhost:9200/_cat/templates?v
```

Thanks for your patience.

Best regards,
Juanjo

**Comment by ruzzetto** [comment]
Hi Juanjo,
thanks for your reply. That's the command output:
```
lsof /var/ossec/logs/alerts/alerts.json
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
ossec-ana 3931 ossec   10w   REG  253,3    67490 50233 /var/ossec/logs/alerts/alerts.json

 curl -XGET localhost:9200/_cat/templates?v
name                          index_patterns           order version
wazuh-kibana                  [.kibana*]               0
kibana_index_template:.kibana [.kibana]                0
wazuh-agent                   [wazuh-monitoring-3.x-*] 0
wazuh                         [wazuh-alerts-3.x-*]     0
```

Fabio

**Comment by ruzzetto** [comment]
Hi Juanjio,
I'm pretty sure I follwed carefully the guide (I started from scratch). Anyway I tried your suggestion and now i see:
```
 lsof /var/ossec/logs/alerts/alerts.json
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
ossec-ana 3931    ossec   10w   REG  253,3    67490 50233 /var/ossec/logs/alerts/alerts.json
java      9558 logstash   82r   REG  253,3    67490 50233 /var/ossec/logs/alerts/alerts.json
```
is that right?
Thanks,
Fabio

**Comment by ruzzetto** [comment]
Great Junajo! Now it's a very useful app.

Thanks again, you and your team are professional and always available to help us! 

Best Regards,
Fabio

**Comment by JuanjiJG** [comment]
It's always our pleasure to help you @ruzzetto!

Don't hesitate to open a new issue anytime you have problems when using Wazuh or the app. In addition to this, your opinions and feedback are really appreciated for us. 😄

I'll proceed to close this issue.

Regards,
Juanjo
