### ISSUE TITLE
The agent keeps appearing after removal

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#4062]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 (rc6)   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Firefox |

**Description**
Within a group, when an agent is deleted it remains present in the view until the page is manually refreshed or the user goes to another page and then returns.

**Preconditions**
1. A group must exist

**Steps to reproduce**
1. Navigate to 'Management/Groups'
2. Select a group
3. Select the 'Manage agents' option
4. Add an agent
5. Select the back button to return to the details of the group
6. In the row of the added agent, select the 'Remove agent from this group' option

**Expected Result**
1. The row should be deleted

**Actual Result**
1. The row remains after being removed

**Screenshots**

https://user-images.githubusercontent.com/39094716/164253330-7d2f5a98-1ce0-4062-b180-15b7e68ca2bb.mp4

**Comment by chantal-kelm** [comment]
I have tried to reproduce the problem in kibana 7.10.2 and 7.16.3 in Google Chrome and Firefox browsers (as stated), but have not succeeded.

**Comment by Desvelao** [comment]
# Research
I could not reproduce the problem. 

Seeing the video and reviewing the source code as the toast is displayed, I guess it could have some problem with the Wazuh API request and the toast message appeared with a successful process. This is possible with the current logic because the toast message is displayed without awaiting the Wazuh API response. This behavior is considered a bug, so we will fix it.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4167.
