### ISSUE TITLE
Secure with Password

### ISSUE THREAD

**Issue by MPJHorner** [wazuh/wazuh-kibana-app#407]
Fantastic application, I installed with VMware template very easily.
The kibana web application, am I missing something?

What is the simple way to protect access to the web interface?

**Comment by JuanjiJG** [comment]
Hello @MPJHorner,

What do you mean with "missing something"?

Regarding to your question about protecting the access to the web interface, currently we can suggest you a couple of things:
1. You can use our documentation guide to [set up SSL and authentication for Kibana](https://documentation.wazuh.com/current/installation-guide/optional-configurations/kibana_ssl.html). With this tutorial, you'll get a user and password prompt in order to open the whole Kibana web interface.
2. You can use the [X-Pack plugin](https://www.elastic.co/products/x-pack) from the Elastic team to enable features such as advanced security, role-based access control, etc. You can read instructions about how to install it [here](https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html), but keep in mind that the security capabilities requires a paid license.

In the future, both Wazuh and the Wazuh app will provide native role-based access control capabilities, but for the moment, we don't have an ETA for that functionality. Sorry for the inconvenience.

In any case, if you still have more questions, don't hesitate to post a new comment.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello again @MPJHorner,

It's been more than a month since the last response to this issue. I'll proceed to close it. Don't hesitate to open a new one if you have questions or need help with Wazuh.

Regards,
Juanjo
