### ISSUE TITLE
Wrong top 5 information when filtering by `agent.name`

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-kibana-app#4086]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.x     | 4301-1 | Basic, ODFE, Xpack |

| Browser |
| --- |
| Firefox|

### Description

In `Security Events`  menu, `agent.name` field `Top 5 values` only shows 2 values.

Using a cluster environment with 2 nodes and 4 agents, `agent.name` only shows two values: `Centos` and `wazuh-manager-worker-0`. Also, the percentages show that those two values suppose 100% when this is not true.

https://user-images.githubusercontent.com/11089305/164708316-88ce70af-4de1-419c-84fa-7f4ac235a028.mp4

If we filter using `agent.name=WIndows`, and we check the `Top 5 values` using `agent.name`, we can see that now, the Top 5 values are completely different, and also suppose 100%.

**Comment by Rebits** [comment]
@gdiazlo The `agent.name` option seems to work as expected in the `Security Events` noew. However, we can see that `Top 5 values` for this field is inconsistent if we go to `MITRE>Events` panel.
We can check that only 4 values are shown, which sums 100%. If we go to the visualization we can see that this is not true.


https://user-images.githubusercontent.com/11089305/165727605-4e5ff780-1b8d-4032-8e17-268bceff3240.mp4

**Comment by chantal-kelm** [comment]
# Investigation of the issue:

Each agent that appears in the `Top 5 values` ​​has a count value, this value is converted to a percentage and among the agents shown, which can be a maximum of 5 (this is how it is set in the code), they make a total of 100%. Image is attached.
Then when clicking on the visualize button in the `Top values` ​​there is no maximum number of agents to show, the count value is also converted to a percentage and between the agents shown they add up to 100%

![image](https://user-images.githubusercontent.com/99441266/167943952-389592f1-a2c1-42bf-9f38-229d8d8d1a11.png)

# Replicating the case exposed in:

# 7.10.2 `Modules` -> `Security Events` -> `Events`: When filtered by cluster.name, we click on the `agent.name` field and verify Top 5 values ​​we can see the count and percentage (attached image).
By clicking on the `visualize` button you can see that the filter is maintained, the count values ​​are different from those that the same agent had in the top 5 values ​​and that is why the order of the graph shows first an agent that was not in first place in the top 5 values.

`Analytics` -> `Discover` in `7.10.2` and `7.16.3` behave the same as `Modules` -> `Security Events` -> `Events` in version `7.10.2`.

# 7.16.3 ` Modules` -> `Security Events` -> `Events`: What is different compared to `7.10.2` is that when you click on the `visualize` button you can see that the cluster.name filter disappears, and when you reapply it the count values ​​are different from those that the same agent had in the top 5 values ​​and that is why the order of the graph shows first an agent that was not in the first place in the top 5 values.

# Wazuh Info `Modules` -> `Security Events` -> `Events`: In the top 5 values ​​it shows 2 agents. By clicking on the `visualize` button you can see that 3 agents are shown, the filter is maintained, the count values ​​change and that is why the order of the graph first shows an agent that was not first in the top 5 values.

# Wazuh Info `OpenSearch Dashboards` -> `Discover`: The behavior is the same as in Wazuh info `Modules` -> `Security Events` -> `Events`.

# Wazuh info -> `Modules` -> `Miter ATT&CK` -> `Events` -> `agent.name` In the top 5 values ​​shows 2 agents. By clicking on the `visualize` button you can see that 3 agents are shown, the filters (`cluster.name` and `rule.mitre.id`) are maintained, the count values ​​change and that is why the order of the graph shows first an agent that was not first in the top 5 values.

**Comment by Desvelao** [comment]
# Research

> For Kibana 7.10.2 and Wazuh dashboard 4.3.0

## Wazuh plugin - Module/Events

The values displayed in the `Top 5 values` are coming from a request taking into account the filters and selected time range. The response will only contain the first 500 results.

Request payload:
![image](https://user-images.githubusercontent.com/34042064/168225796-6d05f648-5193-4653-af68-6278923d2012.png)
Response:
![image](https://user-images.githubusercontent.com/34042064/168226029-5efacd3f-4611-49d3-8c8c-fab1d2155b4e.png)

These results are used to get the `Top 5 values`, so the values are related to the results. This indicator doesn't show the top 5 values of all documents that match the query conditions as we could think.

The values of the percentages are calculated in relation to the query results. So depending on the case, for example, if there are more than 5 values, the sum of values displayed in the `Top 5 values` is less than 100%. If there are 5 or fewer values, then the sum of values is 100%.

More than 5 unique values in the results:
![image](https://user-images.githubusercontent.com/34042064/168227323-32f2b601-edf7-49cb-af01-b5e86a78a4f8.png)

Less than 5 unique values in the results:
![image](https://user-images.githubusercontent.com/34042064/168227499-18884d82-ba8a-4068-93d7-4440f7564643.png)

When clicking on the `Visualize` button, the visualization can display more unique values due to its configuration.
![image](https://user-images.githubusercontent.com/34042064/168227909-ab8006ea-ad93-4098-b716-339eb0aa9eea.png)

## Discover plugin

The Discover plugin of the platform works in the same way as the `<Module>/Events` section of the Wazuh plugin.

# Conclusion
As the behavior in the `<Module>/Events` of the Wazuh plugin and Discover plugin are equals, we don't consider this a problem.

Another thing, it is that we want to change the behaviour and try to display the values considering all the documents
