### ISSUE TITLE
The default filter does not disappear after clicking visualize button

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh-kibana-app#4143]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.0   | 7.10.2    | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

The default filter disappears after clicking the visualize button on the popup.

**Steps to reproduce**
1. Navigate to Modules/Security Events
2. Click on Events
3. Click on Agent.name
4. Click on Visualize in the popup

**Expected Result**
1. When clicking the visualize button of the popup the default filter (cluster.name) is maintained.

**Actual Result**
1. When clicking the visualize button of the popup the default filter (cluster.name) disappears.

**Screenshots**

https://user-images.githubusercontent.com/99441266/168893798-8fe8caad-7146-40d9-bf96-f7f76f72e073.mp4

**Comment by chantal-kelm** [comment]
In branch 7.16.3 when clicking on the visualize button the filters are eliminated, in branch 7.10.2 the filters are also eliminated but visually we never stopped seeing them since the visualize plugin added them again.
When clicking on the visualize button: In the 7.16.3 branch the lens plugin is used instead in the 7.10.2 branch the visualize plugin is used.
We think it is best if the 7.10.2 branch behaves like the 7.16.3 branch and the filters are removed, when we click on the visualize button.

**Video showing the bug fixed:**

https://user-images.githubusercontent.com/99441266/168916666-069981a5-ea6e-4145-b28f-7607cd536921.mp4

**Comment by Desvelao** [comment]
## Research

When the user clicks on the `Visualize` button in a `<Module>/Events` causes navigation to another plugin. A component used to display the `<Module>/Events` section in the Wazuh plugin, contains logic to remove the filters in the `filterManager` when it is unmounted, see https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.0-7.10.2/public/components/common/modules/main.tsx#L59-L64. As the destiny plugin uses the search bar component and it uses the same `filterManager` used by the Wazuh plugin, the changes in the filters done by the Wazuh plugin affects to the destiny plugin.

Depending on the Kibana version, the final behavior is different:
- KIbana 7.10.2: the navigation is done to the `visualize` plugin. When this plugin starts, set the filters in the `filterManager` using the `_a` query parameter, that contains the filters before the navigation. This does that set the filters as previously the navigation.
- Kibana 7.16.x-7.17.x: the navigation is done to the `lens` plugin. Apparently, this plugin doesn't set the filters using the URL as it does the `visualize` plugin in Kibana 7.10.2 and will use the filters that are set in the `filterManager`.

## Remediation
As we are not sure about the use case that requires removing the filters when a specific component used in the `<Module>/Events` is unmounted, we won't remove this logic.

A possible solution to let the filters are not affected when navigating to the `lens` plugin, is to avoid removing the filters when the URL contains a substring related to the `lens` plugin. The solution is not the one we want, but we can't get a better one without understanding the requirement of removing the filters when the component is unmounted.

We will apply this solution to the plugins for Kibana 7.16.x and 7.17.x, not to the plugin for Kibana 7.10.2 because as we saw, the final result is that filters are maintained in spite of filters are removed by the Wazuh plugin and added by the `visualize` plugin.
