### ISSUE TITLE
TypeError: cannot read properties of undefined on the main Agents view

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#4158]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
On the Agent view, the navigation to the Inventory Data throws an error only when the Agent view has been previously resized.

**Steps to reproduce**
1. Navigate to an Agent's view.
2. Resize your browser's window.
3. Open the browser's console.
4. Navigate to the `Inventory Data` section.
5. See the error.

**Screenshots**

![typeerror](https://user-images.githubusercontent.com/15186973/169108914-37fbccb9-6216-4732-acef-ffef52962d9c.gif)

**Comment by AlexRuiz7** [comment]
Also, on the `Inventory Data` view, the Agent's name (Ubuntu in this case) becomes a link to the previous view, but it is not colored as a link (should be on a light blue color instead of black).

On hover, the text is shown as a link, but it's hard to guess that's a link at first. In order to improve the UI/UX, this text should be colored properly, as the rest of the links on the App, and/or add a `back` arrow ◀️ <.

Link's appearance on its common state and on hover:
![image](https://user-images.githubusercontent.com/15186973/169109480-e05deca1-044d-4121-b374-5b6debc2f263.png)

![image](https://user-images.githubusercontent.com/15186973/169110731-38991872-5a4c-4b89-8e8c-4c2daade17b3.png)

**Comment by chantal-kelm** [comment]
Debugging I saw that the error occurs inside a function called myRender. I got to see that myRender is called only from the updateVis function and that function is called from:

- The component Will unmount which is when the component is unmounted

- And the componentdidupdate which is when the component is updated.

I saw that updateVis executes 2 functions renderComplete and myRender, and what is happening is that when it is executed from the WillUnmount, the updateVis function executes myRender and myRender since it is asynchronous, it passes to the callStack and what is synchronous continues to be executed.
The WillUnmount component then executes the destroyAll function, what destroyAll does is set visHandler to null.
When it finishes doing the synchronous thing, it will do the asynchronous function, this asynchronous function searches inside visHandler but since destroyAll set visHandler to null, it shows the error in the console.
Commenting out the updateVis function inside WillUnmount fixes the problem.
I do not see the need for myRender to be executed when the component is unmounted, but it is necessary for the renderComplete function to be executed.
So what I propose as a solution that does not interfere with the current logic is to add the renderComplete function inside the WillUnmount component.

**Comment by AlexRuiz7** [comment]
Thanks for the report.

We could schedule a meeting to discuss your proposal.

**Comment by Desvelao** [comment]
# Research

The error appears when the `visHandler.render` method is called with a not found DOM node, because the view changed to the `Inventory data`.

The `visHandler.render` method is called in the `myRender` component method and this by `updateVis` component method.

```
this.updateVis > ? this.myRender > ? visHandler.render
```

Reviewing the source code, there are some strange. The `updateVis` component method is currently called when the component was [updated](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.1-7.10.2/public/kibana-integrations/kibana-vis.js#L118) or [unmounted](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.1-7.10.2/public/kibana-integrations/kibana-vis.js#L111) and in my opinion, this doesn't have sense because the visualization should be only built when the component is mounted. The current logic causes indirectly the error when it complies with some conditions. In the `myRender` component method, there is a [condition that controls when the visualization should be created](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.1-7.10.2/public/kibana-integrations/kibana-vis.js#L273) and use the `visHandler.render` method to render it, but this condition is checked when the component is updated or will unmount. The error is caused when the `KibanaVis` component is unmounted adn the visualization was not created, it calls to `updateVis` > `myRender`, surpasses the condition, and tries to build the visualization because it wasn't built previously. The method `visHandler.render` fails because the selected DOM node is not present in the current view for that moment, that is `Inventory data` section. Moreover, this case does that the visualization is not visible in the panel.

![Image](https://user-images.githubusercontent.com/34042064/170670150-bcd4b1a1-421e-47be-bbd9-77b345b3d22d.png)


For another hand, as @chantal-kelm said, it seems that it doesn't have the sense to update the visualization when the component goes to be unmounted. We should review if there is something that is required to do before unmount the component.

**Comment by AlexRuiz7** [comment]
Related to this issue, React clearly doesn't like our code.

![image](https://user-images.githubusercontent.com/15186973/173376784-6be2513f-9f89-4f4d-a904-f1dc8122c77d.png)
