### ISSUE TITLE
Invalid search leads to page crash

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4168]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.X   | -      | - | - |

**Description**

An invalid search can cause a page crash. The error toast seems to behave correctly, but it can cause a crash, as shown in the video.

https://user-images.githubusercontent.com/2181918/170484179-89ae0b04-3813-46a8-ba1c-b7122e23d631.mp4

**Comment by Desvelao** [comment]
# Research
The supposed crash is caused in the table of `Modules/Security events`. This table is used in some flyouts to display the alerts in this format.

When the component fetches the data, builds the query and it fails due to a problem with the syntax. Currently, if there is a fails when getting the alerts, the error is stored in logs and considered `CRITICAL`. It means, the view will change to the blank screen view (see the url).

![image](https://user-images.githubusercontent.com/34042064/170677697-4b53d465-e23a-49fa-a4a9-ec785c474132.png)

# Remediation

The first thing to do is to change as the error is considered.

If we consider as `BUSINESS`, a toast will displayed. It could be a good solution, but there is a problem with this approach. The table component seems to fetch the data multiple times, when the query (or another filter) changes. This will do that each proces to build the query fails and multiple toasts appear with the error. We would have to review if we could avoid these multiple requests, but the it could be hard due to the component logic. If we will solve this, the user would see 2 toasts: a from the table and another from the visualizations. Viewing two messages could be considered suboptimal.

If we would want only a message is displayed, we could let this is from the visualizations, so we will have to remove the toast messages from the data fetching oon the table.

**Comment by AlexRuiz7** [comment]
# Research
The supposed crash is caused in the table of `Modules/Security events`. This table is used in some flyouts to display the alerts in this format.

When the component fetches the data, it builds the query, and fails due to a problem with the syntax. Currently, if there are errors getting the alerts, they are stored in logs and considered `CRITICAL`. It means, the view will change to the blank screen view (see the URL).

![image](https://user-images.githubusercontent.com/34042064/170677697-4b53d465-e23a-49fa-a4a9-ec785c474132.png)

# Remediation

The first thing to do is to change how the error is considered.

If we consider the error severity as `BUSINESS`, a toast will be displayed. It could be a good solution, but there is a problem with this approach. The table component seems to fetch the data multiple times, when the query (or another filter) changes. This will cause each process that builds the query to fail, and multiple toasts will show up with the error. We will have to review if we can avoid these multiple requests, but it could be hard due to the component logic. If we solve this, the user would see 2 toasts: one from the table and another from the visualizations. Viewing two messages could not be the best result.

If we want only a message to be displayed, we could use the one from the visualizations, so we will have to remove the toast messages from the table.

**Comment by Desvelao** [comment]
# Possible approach

Change the error level managed by the error manager from `CRITICAL` to `BUSINESS`.

This will display a toast message when there is an error fetching the alert data.

![image](https://user-images.githubusercontent.com/34042064/172864292-53e35e6e-4011-491a-8420-5e93736120da.png)

In the previous screenshot, the toasts are coming from:
- data fetching in the table of the `Modules/Security events` (`KQLSyntaxError`)
> https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/components/common/modules/discover/discover.tsx#L171-L182
> https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/components/common/modules/discover/discover.tsx#L231-L242
> Replacing the log level from `CRITICAL` to `BUSINESS` in the previous code
- data fetching of the visualizations (`Search error`)
- unknown origin (`KQLSyntaxError`)

This approach increases the number of toasts displayed in the UI, but avoids the behavior of redirection to the `blank-screen` section and displays that there was an error when fetching the data.

Patch: [wazuh-kibana-app-4168-approach-1.txt](https://github.com/wazuh/wazuh-kibana-app/files/8871107/wazuh-kibana-app-4168-approach-1.txt)
