### ISSUE TITLE
Short refresh timeout on manager restart

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-kibana-app#4181]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.3   | 4.3.3     | 4331-1 | Wazuh-dashboard |

| Browser |
| ------- |
| Firefox |

**Description**
Hello!

We have detected a short period of wait on manager restart procedure that leads me to an error in the healtcheck section.

**Preconditions**
1. Environment up and running (Manager included).

**Steps to reproduce**
1. Navigate to management->configuration
2. Click on edit configuration
3. Change vulnerability-detector to enabled or disabled
4. Click save
5. Click restart manager button
6. See the error

**Expected Result**
1. Show a pop up to restart in X seconds, maybe 15 or perform a some kind of wait process.

**Actual Result**
1. Immediate restart with error result

**Screenshots**

https://user-images.githubusercontent.com/10661307/171423090-94d6d336-d28f-4bc7-bc9f-9c1097c4eaf8.mp4

![image](https://user-images.githubusercontent.com/10661307/171422953-ca70d933-7abe-4af2-b7b9-b873457cc705.png)

**Comment by yenienserrano** [comment]
Investigating a little more the logic of the restart, we could see that what causes the redirection to the healtcheck is because in the `wz-fetch.js` file, in the `makePing` function (line 195), it makes a polling to check when the API is available and in the first iteration calls the `checkDeamons()` method (line 158), which has a call to the API `(WzRequest. apiReq('GET', '/manager/status', {})))`, the function `apiReq()` (line 107), which is in the file `wz-request.ts`, calls `await this.genericReq('POST', '/api/request', requestData);` (line 114) and when it has no results from the API redirects to the healtcheck method.

![image](https://user-images.githubusercontent.com/63758389/174055510-8e881d07-5f9d-465d-8108-2df5c7bab6b9.png)

**Comment by davidjiglesias** [comment]
The issue is still happening:

![image](https://user-images.githubusercontent.com/48716145/180416697-085f8e3a-6734-4737-9ca2-5d5e20b50fa0.png)
