### ISSUE TITLE
OS dropdown options on Agents Overview page are not working

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#42]
![image](https://user-images.githubusercontent.com/2720787/32275403-06fad67c-bf03-11e7-8323-b24d0be53ea6.png)

**Comment by jesusgn90** [comment]
Hi @rossengeorgiev , just noticed about that bug. I was working on it just now when read you message, i'll let you know about the fixing state as soon as possible. 

Regards, Jesús.

**Comment by havidarou** [comment]
Hi @rossengeorgiev could you tell us what is your Wazuh and Kibana versions? 

By the icons I see in the screenshots, seems Wazuh 2.x and Kibana 5.x

Regards.

**Comment by rossengeorgiev** [comment]
@havidarou I've tried it on `Wazuh 2.1.0+Kibana 5.5.0` and `Wazuh 2.1.1+Kibana 5.6.3`

**Comment by havidarou** [comment]
@rossengeorgiev  we are looking into it, thanks.

**Comment by JuanjiJG** [comment]
Hi @rossengeorgiev 

I've been working on this issue. I tried to reproduce it in both environments **(Wazuh 2.1.0/Kibana 5.5.0 and Wazuh 2.1.1/Kibana 5.6.3)**, and I got the following results:

* On the first one **(2.1.0/5.5.0)**, I couldn't get to work Kibana because I get the version mismatching error when I use the wazuh-kibana-app 2.0.1 plugin.
	* I also tried with the **2.1.0** version of the plugin, but it cannot be installed because it needs Kibana 5.5.1 at least.
* The **(2.1.1/5.6.3)** stack was also tried, and it ran with no errors, and the filters 
worked properly.

After this research, we couldn't find the bug that you reported. We need further details of your environment to make sure we can get to the bottom of that bug:

1. Did you modify any file to avoid the installation errors, such as editing the `package.json` from Kibana?
2. Could you provide us the version of the *Wazuh Kibana Plugin* that you're using? You can check it on the **gear icon at the top right corner** of the Wazuh section in Kibana.
3. We also need the following version info **(root permissions needed)**:
	1. Kibana - Use the following command: `/usr/share/kibana/bin/kibana --version`
	2. Wazuh Manager - Use this: `/var/ossec/bin/manage_agents -V`
	3. Wazuh API - Use this: `cat /var/ossec/api/package.json`

Best regards!

Juanjo

**Comment by rossengeorgiev** [comment]
Hi @JuanjiJG, for the first version pair I used the plugin from #39

Now I am on 2.1.1/5.6.3 and I have a mix of agents versions. Some on latest ossec agent, wazuh-agent 2.0.1 and 2.1.1.

```bash
root@mon_____ ~ $  /usr/share/kibana/bin/kibana --version
5.6.3
root@mon_____ ~ $ /usr/share/kibana/bin/kibana-plugin list
wazuh@2.1.1
----------------------------------------------------------------------------
root@log_____ ~ $ /var/ossec/bin/manage_agents -V

Wazuh v2.1.1 - Wazuh Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as
published by the Free Software Foundation. For more details, go to
https://www.gnu.org/licenses/gpl.html

root@log_____ ~ $ cat /var/ossec/api/package.json
{
  "name": "wazuh_api",
  "version": "2.1.1",
  "description": "Wazuh API.",
  "main": "app.js",
  "author": "Wazuh",
  "license": "GPL-2.0",
  "dependencies": {
    "apicache": "^0.2.0",
    "body-parser": "^1.15.2",
    "cors": "^2.7.1",
    "express": "^4.14.0",
    "htpasswd": "^2.3.4",
    "http-auth": "^3.0.1",
    "moment": "^2.15.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-api.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-api/issues"
  },
  "devDependencies": {
    "mocha": "^3.0.0",
    "should": "^11.1.0",
    "supertest": "^2.0.0"
  }
}
```

**Comment by JuanjiJG** [comment]
Hi again @rossengeorgiev

As @malbarral told you, we don't provide support of Wazuh 2.1.1 for Elastic Stack 5.5.0, so we suggest you updating to a compatible version of Elastic Stack for Wazuh 2.1.1, as you can see in this [link](https://github.com/wazuh/wazuh-kibana-app#installation).

About different agent versions, are those RHEL agents from the image using OSSEC Agent?

Regards,
Juanjo

**Comment by rossengeorgiev** [comment]
Hi @JuanjiJG sorry for the confusion. As I said, I am now updated to the latest. The rhel boxes from the image use the latest wazuh-agent. They wont have OS columns filled up otherwise. I also have Ubuntus and they are not showing either. Like I said, its a mix and maybe that is the cause?

**Comment by JuanjiJG** [comment]
Hi again @rossengeorgiev

We don't think the mix of agent versions causes this issue. We suggest you resetting your Kibana installation and reinstalling the Wazuh plugin. I'll explain you the necessary steps for that:

**WARNING** - This process **will delete your Kibana settings**, so you'll need to register the API credentials again. Proceed with caution:

*You can get more detailed information following the documentation: [Link](https://documentation-v3.wazuh.com/installation-guide/installing-elastic-stack/index.html)*

1. **Stop the Kibana service** (root permissions needed):
	* Systemd: `$ systemctl stop kibana`
	* SysV Init: `$ service kibana stop`

2. **Delete both configuration files**:
	* curl -XDELETE localhost:9200/.kibana
	* curl -XDELETE localhost:9200/.wazuh

3. **Remove the Wazuh plugin**: `/usr/share/kibana/bin/kibana-plugin remove wazuh`

4. **Reinstall the Wazuh plugin**: `/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip`

5. **Restart the Kibana service**:
	* Systemd: `$ systemctl start kibana`
	* SysV Init: `$ service kibana start`

Now you can open a new web browser window and save again the API credentials. After that, the Wazuh plugin should be correctly reinstalled and working again.

Let me see if the issue is still present.

Regards,
Juanjo

**Comment by rossengeorgiev** [comment]
Hi @JuanjiJG, I wiped those indexes + wazuh-monitoring, but nothing changed on my live system. I do run a custom index for kibana, but I can't really wipe that because it has a lot of customization for kibana. Perhaps, I can't see any wazuh related stuff being saved in there.

I also setup a test env (wazuh/ES/everthing from scratch) to test this, but OS platforms tab seems to update. Maybe I haven't found the exact conditions that make it break. However, the OS version tab is still broken and shows nothing in all cases. 

I've wiped my browser storages as well in the process.

**Comment by JuanjiJG** [comment]
Hi again @rossengeorgiev

As far as I know, the indexes doesn't make any relationship with the OS tabs from Agents Overview, since that information is obtained with API calls.

We want to check something. Could you please open your Internet browser's ***developer console*** and see if there's any errors showing up? Usually you can open it with the <kbd>F12</kbd> key on Firefox and Google Chrome.

Regards.
Juanjo

**Comment by rossengeorgiev** [comment]
@JuanjiJG I figured it out. The drop downs only include the first 30 hosts. I spotted this line in `api.log`.

`WazuhAPI 2017-11-13 12:16:10: [::ffff:192.168.11.1] GET /agents/?offset=0&limit=30 - 200 - error: '0'`

And I've confirmed it to be the case after testing with the following `client.keys` file:

```
001 fakehost01 any 1111111111111111111111111111111111111111111111111111111111111111
002 fakehost02 any 1111111111111111111111111111111111111111111111111111111111111111
003 fakehost03 any 1111111111111111111111111111111111111111111111111111111111111111
004 fakehost04 any 1111111111111111111111111111111111111111111111111111111111111111
005 fakehost05 any 1111111111111111111111111111111111111111111111111111111111111111
006 fakehost06 any 1111111111111111111111111111111111111111111111111111111111111111
007 fakehost07 any 1111111111111111111111111111111111111111111111111111111111111111
008 fakehost08 any 1111111111111111111111111111111111111111111111111111111111111111
009 fakehost09 any 1111111111111111111111111111111111111111111111111111111111111111
010 fakehost10 any 1111111111111111111111111111111111111111111111111111111111111111
011 fakehost11 any 1111111111111111111111111111111111111111111111111111111111111111
012 fakehost12 any 1111111111111111111111111111111111111111111111111111111111111111
013 fakehost13 any 1111111111111111111111111111111111111111111111111111111111111111
014 fakehost14 any 1111111111111111111111111111111111111111111111111111111111111111
015 fakehost15 any 1111111111111111111111111111111111111111111111111111111111111111
016 fakehost16 any 1111111111111111111111111111111111111111111111111111111111111111
017 fakehost17 any 1111111111111111111111111111111111111111111111111111111111111111
018 fakehost18 any 1111111111111111111111111111111111111111111111111111111111111111
019 fakehost19 any 1111111111111111111111111111111111111111111111111111111111111111
020 fakehost20 any 1111111111111111111111111111111111111111111111111111111111111111
021 fakehost21 any 1111111111111111111111111111111111111111111111111111111111111111
022 fakehost22 any 1111111111111111111111111111111111111111111111111111111111111111
023 fakehost23 any 1111111111111111111111111111111111111111111111111111111111111111
024 fakehost24 any 1111111111111111111111111111111111111111111111111111111111111111
025 fakehost25 any 1111111111111111111111111111111111111111111111111111111111111111
026 fakehost26 any 1111111111111111111111111111111111111111111111111111111111111111
027 fakehost27 any 1111111111111111111111111111111111111111111111111111111111111111
028 fakehost28 any 1111111111111111111111111111111111111111111111111111111111111111
029 fakehost29 any 1111111111111111111111111111111111111111111111111111111111111111
030 fakehost30 any 1111111111111111111111111111111111111111111111111111111111111111
031 centos7-2.local any 2222222222222222222222222222222222222222222222222222222222222222
```
![image](https://user-images.githubusercontent.com/2720787/32725609-acb00f9c-c86d-11e7-8248-88142498ee3b.png)

**Comment by rossengeorgiev** [comment]
On a side note, could use a little less padding between the rows 😄

**Comment by JuanjiJG** [comment]
Hi again @rossengeorgiev, sorry for the delay.

Thank you very much for diving into the bug and find the problem. We'll get it fixed for the next release.

Best regards.
Juanjo
