### ISSUE TITLE
Error messages on a clean install—error app log messages

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4203]
**Describe the solution you'd like**

After installing the Wazuh UI, the application shows some errors. We need to avoid the generation of these errors, as it leads the user to think the application might have a problem when there is none. 

We need to examine the errors shown in the different platforms we support and devise solutions to make the first start more robust.

Error in a clean install in the error app log message page: 

![image](https://user-images.githubusercontent.com/2181918/172042019-db23a791-5a68-4140-887a-b96556d2863b.png)

Related issues:
* #4209

**Comment by Desvelao** [comment]
# Research
I was researching the problem and this could be related to the `statistics` jobs done by the plugin's backend to index data releated to the manager or cluster (depending on if cluster is disabled or not).

Checking the plugin logs, I got:
```
error: 2022/06/06 8:46:0: cron-scheduler|SaveDocument: resource_already_exists_exception
```

The log is coming from https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.3-7.10.2/server/start/cron-scheduler/save-document.ts#L66.

The error is caused when trying to create an index that already exists. This error is logged by the plugin.

The `statistics` plugin job defines 4 jobs:
- 2 for manager mode
- 2 for cluster mode

The execution of these jobs runs in a fixed interval of time and in parallel. 

The problem appears when the index where the data will be stored doesn't exist. A cause of each job checks the existence of the target index before indexing data, and if it doesn't exist it is created. When each job runs, this gets that the target index is not created, so tries to create it. Taking in account that the jobs run in parallel, one of these jobs will create the target index and the other job will fail when trying to create the target index because it already exists.

# Remediation

Due to the jobs running in parallel and the checking of the existence of the target index being done at the same time, the condition to create the target index is bypassed in each job. So a possible solution, it would be to manage the error thrown by the request to create the target index. If the error is related to the index already existing, don't throw the error. The affected logic is https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.3-7.10.2/server/start/cron-scheduler/save-document.ts#L50-L63.

Should the plugin log the error caused in the creation of the index by this scenario as a warning or ignore it?
