### ISSUE TITLE
Error Performing Checks

### ISSUE THREAD

**Issue by ruzzetto** [wazuh/wazuh-kibana-app#421]
Hi,
every morning when I try to access to wazuh app, I get an error "Performing checks (3/4)".
I have to restart kibana in order to get it works.
Is there something to investigate?

Regards,
Fabio

**Comment by jesusgn90** [comment]
Hello @ruzzetto ,

Please, could you give us a bit more information? If you are having troubles at the health check (3/4) you should see a message (or maybe more than one) which says you what's could be happening.

It would be nice if you paste here all the information you think could be useful for us. Thanks in advance.

Regards,
Jesús

**Comment by ruzzetto** [comment]
Hi @jesusgn90 sure :)
That's the picture: every morning login to kibana and try to switch to wazuh app but I get the error "Performing check (3/4) ...... No template found for the selected index-pattern"
Then, after "systemctl daemon-reload" or "systemct restart kibana" app is working fine.
Thanks again Jesus,

Fabio

**Comment by jesusgn90** [comment]
Ok, could you please paste the output of the next commands?

```
# curl elastic_ip:9200/_cat/templates
# curl "elastic_ip:9200/.kibana/_search?q=type:index-pattern&size=9999&_source=false&pretty"
```

Regards,
Jesús

**Comment by ruzzetto** [comment]
```
# curl elastic_ip:9200/_cat/templates
logstash                      [logstash-*]               0          60001
.ml-notifications             [.ml-notifications]        0          6020499
.watch-history-7              [.watcher-history-7*]      2147483647
.watches                      [.watches*]                2147483647
.monitoring-beats             [.monitoring-beats-6-*]    0          6020099
.ml-state                     [.ml-state]                0          6020499
.triggered_watches            [.triggered_watches*]      2147483647
.ml-meta                      [.ml-meta]                 0          6020499
security_audit_log            [.security_audit_log*]     2147483647
.monitoring-kibana            [.monitoring-kibana-6-*]   0          6020099
wazuh-kibana                  [.kibana*]                 0
.ml-anomalies-                [.ml-anomalies-*]          0          6020499
.monitoring-es                [.monitoring-es-6-*]       0          6020099
logstash-index-template       [.logstash]                0
kibana_index_template:.kibana [.kibana]                  0
.monitoring-logstash          [.monitoring-logstash-6-*] 0          6020099
.monitoring-alerts            [.monitoring-alerts-6]     0          6020099
wazuh-agent                   [wazuh-monitoring-3.x-*]   0
security-index-template       [.security-*]              1000

# curl "elastic_ip:9200/.kibana/_search?q=type:index-pattern&size=9999&_source=false&pretty"
```
in this case the command doesn't return me value

Regards,
Fabio

**Comment by jesusgn90** [comment]
Hello again @ruzzetto ,

your problem is a missing template for Elasticsearch. As you can see here:

- https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html

The step 3) says you must to insert the proper template to create the _wazuh-alerts_ indices on the right way.

> Load  the Wazuh template for Elasticsearch:
> `# curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-`

Now we have a problem for one or more indices of _wazuh-alerts_. Any index created with the proper template not being applied has a different structure. 

My suggestion:

1. Backup all your wazuh-alerts-3.x-* indices, https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html
2. Delete all malformed wazuh-alerts-3.x-* indices:

```
# systemctl stop logstash
# curl -XDELETE elastic_ip:9200/wazuh-alerts-3.x*
```

3. Insert the template:

```
# curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://elastic_ip:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
```

4. Restore alerts from manager to Elasticsearch using this tool:

- https://github.com/wazuh/wazuh/tree/master/extensions/elasticsearch/restore_alerts

__Note__: There is a known bug on Logstash, I don't know if your current version has the fix applied, you can found it here https://github.com/elastic/logstash/pull/9285

Apply the fix before use the restore_alerts script in order to avoid any kind of trouble related to Logstash.

```
# mkdir /usr/share/logstash/logstash-core/spec
# curl -so  /usr/share/logstash/logstash-core/spec/logstash/pipeline_spec.rb https://raw.githubusercontent.com/andrewvc/logstash/d85aa88c3a393e481e3cdfbfe75268ec9984b81e/logstash-core/spec/logstash/pipeline_spec.rb
# curl -so  /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb https://raw.githubusercontent.com/andrewvc/logstash/d85aa88c3a393e481e3cdfbfe75268ec9984b81e/logstash-core/lib/logstash/pipeline.rb
```

Once you have downloaded the script and the configuration file:

```
# chmod a+x ./restore_alerts.sh
# ./restore_alerts.sh
```

It'll ask you for type of reindexation, select from Wazuh manager to Elasticsearch.

Verify the indices are restored:

```
# curl elastic_ip:9200/_cat/indices
```

Once done, restart Logstash:

```
# systemctl restart logstash
```

Today's index wont be restored, so tomorrow repeat the whole process described above to ensure your today's data is indexed, but tomorrow use only the today's date when the script asks you from `date_from` and `date_to`.

Hope it helps, regards,
Jesús

**Comment by ruzzetto** [comment]
Ok, the script hangs here:
```
##### Starting, reindexing alerts from 2018-01-01 to 2018-04-26
###### Procesing: /var/ossec/logs/alerts/2018/Jan/ossec-alerts-01.json.gz
gzip: /var/ossec/logs/alerts/2018/Jan/ossec-alerts-01.json.gz: No such file or directory
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
```
After 30 minutes, I stopped it

Regards,
Fabio

**Comment by jesusgn90** [comment]
Hello again @ruzzetto ,

there are some important points here:

- The machine where you execute the whole process must to be the Wazuh manager machine
- You should use a user with super-user privileges
- Since an index per day is created the date range you are using is too big, use only 4-5 days per iteration
- The reindexation process could be very slow so be patient
- The warning about the _ossec-alerts-01.json.gz_ could mean two things: you are not on the Wazuh manager machine or there is no alerts for that day. If you are on the second scenario it's okay and doesn't matter.

Regards,
Jesús

**Comment by ruzzetto** [comment]
Hi @jesusgn90 ,

- The machine where script has been executed is Wazuh manager

- Script has been run as root

- Tried again with 2 days range, it hangs anyway

- It's the second scenario.

Thanks again,
Fabio

**Comment by jesusgn90** [comment]
Hi @ruzzetto ,

maybe the problem here is regarding to X-Pack security, could you try to disable the Elasticsearch security temporary?

Add this line to `/etc/elasticsearch/elasticsearch.yml`:

```
xpack.security.enabled: false
```

Restart Elasticsearch:

```
# systemctl restart elasticsearch
```

Wait up to Elasticsearch is online again (few seconds, `curl elastic_ip:9200` up to it replies you). If it works now, leave the security disable and once finished restore its security removing the line added.
Also remember the script is slow.

Regards,
Jesús

**Comment by ruzzetto** [comment]
Hi,
last friday I stopped script because it was running for more than one hour.
I'm trying again now.

Regards,
Fabio

**Comment by jesusgn90** [comment]
Ok Fabio,

after one hour you have tried to check if there are restored indices?

```
# curl elastic_ip:9200/_cat/indices?pretty
```

Also as a tip you could check Logstash log file as follow:

```
# tailf /var/log/logstash/logstash-plain.log
```

Execute the above command on a separated CLI, this way you could check in real-time how Logstash is working.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hi @ruzzetto ,

First time ever seen that weird ouput using the restoring script. At this point my suggestion is to open a parallel thread on the https://discuss.elastic.co/ forums directly. In order to get a fast response from the Elastic team you should explain your problem as follow:

- Provide them your Elastic stack version for each component. 
  - Tell them all about your installed plugins, such X-Pack
- Paste the main error logs from Logstash
- Explain that you are trying to pipe some json files to Logstash in order to insert your data to Elasticsearch
- Also tell them you have the proper template and this script works on other environments with success

Once the Elastic team give us a clue about this handicap, feel free to share here your last steps and we can continue helping you.

Best regards,
Jesús

**Comment by ruzzetto** [comment]
Hi Jesus,
since this is a testing environment I could start again from scratch with a clean installation

Fabio

**Comment by jesusgn90** [comment]
Ok @ruzzetto ,

This time please take care about the key steps such inserting the right template for the wazuh-alerts indices. Also I suggest to fully clean dirty installations dince they have lot of trash that could cause problems on further installations. 

Useful links:

- https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/index.html
- https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html
- https://discuss.elastic.co/c/elasticsearch

Also we have a mailing list on Google:

- https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/wazuh

Some tips:

- Ensure Logstash is not running before the template is inserted properly on Elasticsearch
- The "cat" API from Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html

I'm going to close the issue but if you are facing new problems feel free to open many issues as you need.

Best regards,
Jesús
