### ISSUE TITLE
Improve visualizations text size 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4211]
**Describe the solution you'd like**

We want the visualization legend text size to match the body text size used in the tables. Currently, the text size is a little bit bigger in the visualizations and makes the page feel odd. (sizes of the severity and summary visualizations), the sizes of details visualization might need an adaptation, so the three visualizations looks are coherent.

Also, the legend is unaligned with the chart. We need to improve this so the legend is vertically aligned with the chart in the center.
![image](https://user-images.githubusercontent.com/2181918/172133166-bdaa6e94-82ad-4f85-865d-6f4f2b852009.png)

We need to propose new designs and evaluate which one would fit better.

We changed these visualizations already in:
* #4164
* #4077 
* #4049

**Comment by chantal-kelm** [comment]
The two graphs, the lists and the select were centered.
The font size was also corrected to the same used in the table.

![Screenshot from 2022-06-13 13-47-33](https://user-images.githubusercontent.com/99441266/173411950-944ae33f-bc61-4ade-b40a-894a265bda80.png)
![Screenshot from 2022-06-13 13-47-54](https://user-images.githubusercontent.com/99441266/173411957-1de49b5f-baa0-45e6-aab6-446e4529a7f9.png)

**Comment by chantal-kelm** [comment]
It was concluded that it was better not to implement some changes in the styles, in order to maintain some consistency in the visual.
This is how it currently looks with the latest changes.
The font size has been changed so that it is uniform throughout the view, including the font size of the select.

**Modules/Vulnerabilities**
![Screenshot from 2022-06-16 13-03-15](https://user-images.githubusercontent.com/99441266/174115637-cfdd6f03-83dd-4d88-9171-92e6cadc2cbd.png)

The other view where font size also impacts is Agents which looks like this:
![Screenshot from 2022-06-16 13-03-53](https://user-images.githubusercontent.com/99441266/174115682-c35f00e2-09c2-4478-9122-06bd21de1dab.png)
