### ISSUE TITLE
Error generating report after unpinning an Agent that has never connected

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#4230]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

When we want to generate a report of any module of any agent, if we have selected 1 agent that never connected and we switch to one that is active, and click on generate report you get an error message.

`[request body.time]: expected at least one defined value but got [undefined]`

![image](https://user-images.githubusercontent.com/63758389/172592594-a21dfa7e-2fad-4894-83a7-2ff586dab217.png)

**Preconditions**
1. have 2 agents 1 active and 1 never connected

**Steps to reproduce**
1. Navigate to 'Security events'
2. Click on 'Explore agent'
3. Select the never connected agent
4. Change the selected agent to the active one
5. Click on 'Generate report'

**Expected Result**
1. generate report
![image](https://user-images.githubusercontent.com/63758389/172593573-ab178d13-f9c4-4193-b840-2c91031c0a4e.png)

**Actual Result**
1. report is not generated
![image](https://user-images.githubusercontent.com/63758389/172593702-e538265d-35f5-4281-9c41-149c61e4a2f7.png)

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
# Research

The problem is happening when changing the selected agent, (independently of its status), and clicking on the `Generate report` button.

## Digging
The `Generate report` button when clicked, sends a request to a plugin endpoint. The error displayed in the UI is related to that `time` property, sent as part of the request payload, has not the expected value by the plugin endpoint.

The request payload is set here. https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/react-services/reporting.js#L100-L114

The `time` property is coming of the method [`getAppliedFilters`](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/factories/vis-handlers.js#L48-L118) method of `VisHandlers` singleton. This method gets the filters of the stored visualizations handlers in an internal array. https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/react-services/reporting.js#L91

When changing the selected agent, the singleton of `VisHandlers` removes all the visualization handlers https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.4-7.10.2/public/components/visualize/wz-visualize.js#L85. As these visualization handlers are not added again to the `VisHandlers` singleton, when clicking on the `Generate report` button, the method `getAppliedFilters` of `VisHandlers` returns an empty object because it can't get the filters using the visualizations handlers, due to there are no visualizations handlers.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4240.
