### ISSUE TITLE
Large CDB lists upload fails silently

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#4288]
Wazuh indexer 4.3.4

| Browser |
| ------- |
| all |

**Description**
When a CDB list file with a size above 1MB but below 10MB is uploaded the Wazuh dashboard plugin silently fails.

**Steps to reproduce**
Create a file with more than 1MB with valid CBD entries but less than 10MB and attempt to upload. 
Note how it doesn't fail and suggests to restart for the changes to take effect.

**Expected Result**
1. List to be uploaded or a correct error message be given

![CDBtoolarge](https://user-images.githubusercontent.com/36071202/175578073-ed20d05f-e31d-4a40-b1f2-f8255c33ab2f.png)

**Actual Result**
1. List is never uploaded. Looking at developer tools reveals the API's error message

**Screenshots**

https://user-images.githubusercontent.com/36071202/175578319-eb4d41c1-9012-4881-b6bb-38390256144e.mp4

**Additional context**
This is related to https://github.com/wazuh/wazuh-kibana-app/issues/1947

**Comment by jctello** [comment]
Other silent messages are when there's an existing list with a questionable filename and it is attempted to be edited:


https://user-images.githubusercontent.com/36071202/175601799-cc4cd393-9faf-4d02-a89b-645246c9a021.mp4

Or when the API times out because there CDB list is too large:

https://user-images.githubusercontent.com/36071202/175601521-fe31b936-c012-4368-9382-8c40cbca4806.mp4

**Comment by Desvelao** [comment]
# Research

Cases:

1. CDB list with a size above 1MB and below 10MB
Due to recent changes, a message is now displayed in the UI.
![Image](https://user-images.githubusercontent.com/34042064/177266307-65e33b9a-5a34-4573-93d5-22cc63f94008.png)

2. The error is not managed. We need to display a toast when there is 

3. The error is not managed.

For cases: 2 and 3, we need to display a toast with information about the error.

I am reviewing the action buttons of tables for `Rules/Decoders/CDB Lists` and all the buttons need to manage the error and display a toast.

**Comment by Desvelao** [comment]
Solved in: https://github.com/wazuh/wazuh-kibana-app/pull/4307
