### ISSUE TITLE
Deployment variables wrongly use protocol for syslog if it is declared first

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-kibana-app#4318]
| Manager | Indexer | Rev  | Security |
| ----- | ------- | ---- | -------- |
| v4.3.5  |  Wazuh Indexer 4.3.5    | 4306 | Basic |

**Description**
When the configuration stanza for a remote syslog collection is specified before than that for the agent's secure connection on the manager's `ossec.conf` the protocol shown in the Deploy agent screen will be that of the syslog configuration instead of the agents.

This is because [here](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.5-1.2.0-wzd/public/controllers/agent/components/register-agent.js#L224) the plugin asks for the first remote connection instead of verifying the type of connection.

**Preconditions**
The manager must be configured as follows:
```xml
<!--
  Wazuh - Manager - Default configuration for centos 7.9
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>yes</logall_json>
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>wazuh@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>

  <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>

  <remote>
    <connection>syslog</connection>
    <port>514</port>
    <protocol>udp</protocol>
    <allowed-ips>0.0.0.0/0</allowed-ips>
  </remote>

  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>
...
```

**Steps to reproduce**
1. Place a remote syslog connection before the secure agent connection as shown above
2. Go to Agents > Deploy new agent
3. Select the options for any operating system
4. Observe how the protocol reflects the configuration for syslog instead of the agent

**Expected Result**
1. Protocol should not be shown in deployment variables, so the default (TCP) will be used

**Actual Result**
1. Protocol is specified as UDP in deployment variables

**Screenshots**
![image](https://user-images.githubusercontent.com/36071202/178235286-7bcebe9e-14a7-4c12-9d82-bb8f10708304.png)

**Additional context**
The API reply for this configuration is:
```json
{
  "data": {
    "remote": [
      {
        "connection": "syslog",
        "ipv6": "no",
        "protocol": [
          "UDP"
        ],
        "port": "514",
        "allowed-ips": [
          "0.0.0.0/0"
        ]
      },
      {
        "connection": "secure",
        "ipv6": "no",
        "protocol": [
          "TCP"
        ],
        "port": "1514",
        "queue_size": "131072"
      }
    ]
  },
  "error": 0
}
```

**Comment by gdiazlo** [comment]
In the case described, the  Wazuh API returns:

`{"data": {"remote": [
{"connection": "syslog", "ipv6": "no", "protocol": ["UDP"], "port": "514", "allowed-ips": ["0.0.0.0/0"]}, 
{"connection": "secure", "ipv6": "no", "protocol": ["TCP"], "port": "1514", "queue_size": "131072"}]}, 
"error": 0}`

The API specification does detail what kind of object is returned by each request as per its [documentation](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_config).

The `remote` object specification ([ref](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html)) does not allow us to make decisions automatically about the protocol used by a new agent. 

If we use the port to identify where an agent should connect, we assume there are no cases in which the user might change the port used for agent communication. 

We can make the user select which `remote` an agent should connect to, but this might be a burden for the kind of user interested in the agent registration wizard. 

Design proposal:
* if there is only one remote, we use it to select the protocol (same as today)
* If there are multiple remotes, select those of them who are configured as `secure`, and present the user a dropdown to select the `name` of the desired remote
* Propose to add the `name` attribute to the remote, so a user can tell the difference between remotes by name.

**Comment by gdiazlo** [comment]
We have decided we will use the first entry of type `secure`:
- if a `connection` is `secure`, the protocol can be `TCP`, `UDP` or both.
- if the protocol is `TCP` or both, then we the protocol selected will be TCP, so no environment variable will be set.
- if the protocol is `UDP` and only `UDP`, then we will generate the variable `WAZUH_PROTOCOL` with value `udp`

**Comment by chantal-kelm** [comment]
This is how the "Deploy new agent" section looks like today after adding the development of this issue

https://user-images.githubusercontent.com/99441266/194386566-f9011991-bc33-4d6f-9512-ef29e669eefc.mp4

**Comment by jctello** [comment]
Hi @chantal-kelm thank you for the video, it shows as corrupt in several OS/Browser combinations but I was able to download it. 

I see that while it is  taking the first `secure` remote setting as expected, when there is no `secure` remote setting it will incorrectly claim you do not have permissions to read groups and provide an installation command without the manager's address and the syslog's protocol.

It should instead provide a warning to the user that there's no secure protocol configured and agents will not be able to be communicate with the manager.

It's important to note that this broken behavior is observed Wazuh v4.3.8 but it would make sense to include it in the scope of this issue.

**Comment by chantal-kelm** [comment]
We are getting a 500 error when we put in the ossec.conf the connection "syslog", if we try with "secure" it works fine and returns a 200.
This issue is being consulted with Framework.

https://user-images.githubusercontent.com/99441266/196984070-35e5b1e6-2522-4510-90a0-34fb968f6b40.mp4

**Comment by chantal-kelm** [comment]
This [PR](https://github.com/wazuh/wazuh-kibana-app/pull/4760) fixes this issue and now only displays the WAZUH_PROTOCOL variable if a connection is type secure and its protocol is UDP.

In the video you can see that when a connection is secure and its protocol is UDP, the variable WAZUH_PROTOCOL appears in the installation command, otherwise it does not appear.

https://user-images.githubusercontent.com/99441266/197762041-43f6068f-2a5c-47c5-92f7-34771fb9b8cb.mp4

### Test
*Go to the Agents tab
*Click on the 'Deploy new agent' button
*Verify that when a connection is type secure and its protocol is UDP, the variable WAZUH_PROTOCOL appears in the installation command, otherwise it does not appear.

You can use this data for testing purposes:
CASE 1: Variable WAZUH_PROTOCOL should appear in the install command.

```
{
    "data": {
      "remote": [
        {
          "connection": "syslog",
          "ipv6": "no",
          "protocol": [
            "UDP"
          ],
          "port": "514",
          "allowed-ips": [
            "0.0.0.0/0"
          ]
        },
        {
          "connection": "secure",
          "ipv6": "no",
          "protocol": [
            "UDP"
          ],
          "port": "1514",
          "queue_size": "131072"
        }
      ]
    },
    }, "error": 0
  }
```

Case 2: WAZUH_PROTOCOL variable should not appear in the install command

```
{
    "data": {
      "remote": [
        {
          "connection": "syslog",
          "ipv6": "no",
          "protocol": [
            "UDP"
          ],
          "port": "514",
          "allowed-ips": [
            "0.0.0.0/0"
          ]
        },
        {
          "connection": "secure",
          "ipv6": "no",
          "protocol": [
            "TCP"
          ],
          "port": "1514",
          "queue_size": "131072"
        }
      ]
    },
    }, "error": 0
  }
```

**Comment by chantal-kelm** [comment]
Added message and link to documentation when connection type is unsecure

![Screenshot from 2022-10-26 14-12-47](https://user-images.githubusercontent.com/99441266/198092779-2e125d6c-6374-470e-aa04-b40b49eefdd0.png)

**Comment by chantal-kelm** [comment]
Connection: Secure Protocol: UDP :

https://user-images.githubusercontent.com/99441266/198362522-3a11be0f-5339-4fe1-a80f-ab74ea004261.mp4

Connection: Secure Protocol: TCP :

https://user-images.githubusercontent.com/99441266/198362710-14078974-98da-4f83-bf17-723f40dee910.mp4

Connection: Syslog

https://user-images.githubusercontent.com/99441266/198362818-e2f8f5e2-e349-4427-825c-2256fee6f7f1.mp4

Error handling and warning in the UI to the client.

https://user-images.githubusercontent.com/99441266/198363223-246b9ddf-53b3-42cf-98f2-bd28a97cc32e.mp4

**Comment by Machi3mfl** [comment]
Researching with the team and with the collaboration of @Desvelao and @chantal-kelm.
We found that the following issues are related and we need to treat and think of solutions for both new features at the same time
- #4318
- #4109

Exists different use cases to consider to prepare the new feature. We need to consider both params `WAZUH_MANAGER, WAZUH_PROTOCOL` to define the values of each other 
We can't treat it separately because the protocol depends on the selected node in the Server Address input and we need to consider it to avoid showing a wrong deploy new agent command to the user.

The new `Server Address Multi Selector` behavior is documented in this [comment issue](https://github.com/wazuh/wazuh-kibana-app/issues/4109#issuecomment-1287309466)

![image](https://user-images.githubusercontent.com/6089438/198694302-2bd2af17-3fec-4116-a439-2527c66f1bae.png)
  
## Uses cases to consider.

### 1.When the user adds in the selector `2 nodes/workers` and both share the `same protocol (UDP/TCP)`.

**Solution to consider**
- We should select the shared protocol that allows running the deploy new agent command without issues (register agents in both nodes)

## 2. When the user adds in the selector `2 nodes/workers`  that one of them has only `UDP protocol`. 

**Solution to consider**
If we add the` WAZUH_PROTOCOL=UDP` in the command the node with TCP will not work.

**Solution to consider**

- We should allow to the user selects the Server Address input nodes that not shares protocol? 
- We should show an alert message saying that the command couldn't work because we are selecting nodes that don't share connection protocol?

## 3.When the user types the IP/DNS address manually
In this case, if the is not registered, we can't know what protocol is used.

**Solution to consider**

- We should allow to the user enter an address manually?
- We should try to suggest the WAZUH_PROTOCOL param?

Feel free to add more use cases that I didn't consider. And we add this thread to share opinions and find a better solution for bringing a better user experience and avoiding problems with the deploy new agent command

**Comment by chantal-kelm** [comment]
According to what we have discussed with the Framework team these are the cases we are going to take into account:

- In all cases the client can only choose one IP.

- When the client has the IP address configured then in the server address field you will see that IP address and the protocol will be TCP.

![Screenshot from 2022-11-03 09-56-51](https://user-images.githubusercontent.com/99441266/199726502-4f744651-2a97-4915-b784-c10aab774606.png)

- In case the user does not have the IP address configured then a selector will be shown in the server address where the manager and cluster will be shown, the user can choose one and based on the one he chooses, the protocol will be TCP or UDP as appropriate, the user can also write an IP and in that case the protocol will be TCP.

**Comment by Machi3mfl** [comment]
Issue solved in [https://github.com/wazuh/wazuh-kibana-app/pull/4776](https://github.com/wazuh/wazuh-kibana-app/pull/4776)

**Comment by Machi3mfl** [comment]
Bug found in manual testing fixed in PR https://github.com/wazuh/wazuh-kibana-app/pull/4849
