### ISSUE TITLE
Group report generation fails randomly

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-kibana-app#4348]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.5-1 and 4.3.6-1   | 7.14.4     | 4xxx | Basick |

| Browser |
| ------- |
| Firefox |

**Description**
When trying to generate a group report, sometimes it fails to get generate the report when the configurations component is selected, with the following error:
```json
{"statusCode":500,"error":"Internal Server Error","message":"5029 - Reporting was aborted (Cannot read property 'length' of undefined)"}
```

**Preconditions**
1. Create a group with 1+ agents

**Steps to reproduce**
1. Navigate to groups tab at `https://ip/app/wazuh#/manager/?tab=groups`
2. Click on the Group you want to generate
3. Click on `Generate reports`
Note: The error occurs randomly, and it can be triggered by selecting and deselecting the `configurations` component checkbox. It is more clearly reproduced on Postman.

**Expected Result**
1. Group report fails to generate

**Actual Result**
1. Group report is generated successfully

**Screenshots**
![imagen](https://user-images.githubusercontent.com/14501079/179777765-519863db-4135-4aa3-9298-cab2c34fdb9d.png)
![imagen](https://user-images.githubusercontent.com/14501079/179778565-1f2fbff0-3569-461a-8ee7-f02edaa1937b.png)
![imagen](https://user-images.githubusercontent.com/14501079/179778953-9d8e0d57-6cd9-4940-945b-35e82abbaf38.png)
- Postman exampe
![imagen](https://user-images.githubusercontent.com/14501079/179787919-1f312ac3-dfed-468d-a488-b56f83511114.png)

**Additional context**
The error was found in `kibana-wazuh-app` and `wazuh-dashboard version 4.3.5-1 (installed from documentation) and 4.3.6-1 (installed from packages), during testing for Wazuh-qa Issue  [#3100](https://github.com/wazuh/wazuh-qa/issues/3100)

**Comment by Desvelao** [comment]
# Research

I could replicate this problem and it seems to be related to a problem accessing a property that is `undefined` due to a failed request to Wazuh API (expired token, no permission for the requested endpoint).

The error is located [here](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.5-7.10.2/server/controllers/wazuh-reporting.ts#L1269) when accessing to the `length` of `affected_items`. If the Wazuh API request fails, the `configuration` variable is empty, so accessing to `configuration.affected_items.length` throws the error.

Expiring the token, I got the next plugin log:
```
{"date":"2022-07-20T09:48:28.798Z","level":"debug","location":"reporting:createReportsGroups","message":"Request failed with status code 401"}
```

We should refactor this [block](https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.5-7.10.2/server/controllers/wazuh-reporting.ts#L1256-L1269) to avoid this problem.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4350.
