### ISSUE TITLE
Search tools to collect some metrics to know the performance level of the app

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4351]
We need to improve the use of some performance tools to know which metrics we manage in different part's of the app.
With these, we are going to know what can be improved and in which way.

The suggested tools are:
### Sitespeed.io
1) With this tool we can code some automated scenarios with the navigation on the app, and the tools collect all the metrics and show a report at the end of the execution.
2) It seems pretty similar to our automated test cases in the use, so I consider that we can explore the use of this tool.
### JMeter
1) This tool it's orientated to analyze the behavior of the backend request
2) This would allow us to identify and enhance all the requests that could be improved to have a better performance

**Comment by Mayons95** [comment]
After some research I could execute a scenario with Sitespeed navigating from the login page to the agent section of the app recollecting some metrics.
I attached a ZIP File. In the index.html you are going to be able to see all the metrics that were collected.
[2022-07-20-16-59-54.zip](https://github.com/wazuh/wazuh-kibana-app/files/9162482/2022-07-20-16-59-54.zip)

![image](https://user-images.githubusercontent.com/104914131/180306456-21f6c286-2025-4f51-aef9-59cfb4a3ccc0.png)

Also today with @asteriscos we investigate how we can collect the different API request that the app generates in a normal use.
We were able to connect JMeter recording tool to Wazuh App to collect different API requests and perform different's test scenarios.
I left here a screenshot of the report generated by JMeter with the next scenario:
Login to Wazuh App
Navigate to Agents Dashboard

![image](https://user-images.githubusercontent.com/104914131/180307560-5c51f307-9f1b-4ba2-b024-5b7fb072ab81.png)

The next steps we suggest is to define:
1) Environments to work (Dev & Prod)
2) Scenarios to design and test.

C.C: @asteriscos @gdiazlo

**Comment by asteriscos** [comment]
## Thoughts
After analyzing the two solutions we considered in the begin of this issue, we decided to continue working with **_Sitespeed_** because:

1) It has reusable test scenarios for different environments. We just need to change the CSS selectors to perform a new test in a different environment. If the requests change there's no need to change the script.
2) Sitespeed reporting is more user friendly, it has more metrics to analyze about the performance test execution.
3) Sitespeed also integrate metrics from the UI, that's JMeter does not.
4) Sitespeed has a HAR compare functionality where it's possible to compare two Sitespeed test execution by a HAR file generated by the tool itself. This could be very useful to analyze how much the changes that we are going to implement actually improve the application performance

![Screenshot from 2022-07-26 18-51-14](https://user-images.githubusercontent.com/9343732/181069446-1402036d-baca-4c8b-bc66-17e1522cde5f.png)


As part of this tool analysis and for the time being, we are developing the testing scripts in [this repository](https://github.com/Mayons95/wazuh-performance-test/).
