### ISSUE TITLE
Office365 view presents incorrect value for max event level

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#4355]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3.6   | 7.10.2    | 4xxx | Basic |

| Browser |
| ------- |
| all|

**Description**
Max rule level value seems to be inverted (min).
![image](https://user-images.githubusercontent.com/1331084/180648258-96c73427-f61e-45b7-967c-7f794e039200.png)

**Comment by AlexRuiz7** [comment]
Hello @sempervictus 

Thanks for using Wazuh and reporting this bug with us.

We'll further investigate this and fix it as soon as possible.

Best regards,
Alex

**Comment by Tostti** [comment]
I have been investigating this issue.
The problem is due to an incorrect term in the aggregation of office / Max Rule Level on the file `components/overview/metrics/metrics.tsx`. I will proceed to fix it

**Comment by Tostti** [comment]
The issue was that the aggregation was using the `timestamp` term instead of `rule.level`.  

**Before the changes**
![image](https://user-images.githubusercontent.com/42900763/189980588-1a3db59f-272c-4839-823e-4056fbe0cbde.png)

**After the changes**
![image](https://user-images.githubusercontent.com/42900763/189980766-de7b4a6b-d09a-4199-a865-aa450bfc5606.png)

**Comment by sempervictus** [comment]
Awesome, thank you for hunting that down.

**Comment by Tostti** [comment]
Closing after merge of #4508 
Backports was merged too.
