### ISSUE TITLE
Fix references to Elasticsearch in plugin for Wazuh stack

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-kibana-app#4361]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
There are some references to `Elasticsearch` that should be renamed to `Wazuh indexer` in the plugin for Wazuh dashboard.

Found references:
- https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.6-1.2.0-wzd/server/controllers/wazuh-elastic.ts#L128
- https://github.com/wazuh/wazuh-kibana-app/blob/v4.3.6-1.2.0-wzd/server/controllers/wazuh-elastic.ts#L171

Both messages could be displayed in the UI depending on how the error to these endpoints is managed.

Todo:
- Search if there are more references that should be renamed.

**Possible solutions**
- Replace the references centralizing the name.
- Remove the brand reference

**Comment by chantal-kelm** [comment]
### Description

Fixed references to Elasticsearch in Wazuh-stack plugin. Removed also the checkPattern function and its tests since it was not being used.

### PR
[#4894]

### Evidence

Before

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/202715537-8b0e1113-ad04-4009-9a84-536443cfdbb8.png">

After

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/202715800-aa20c999-bbf6-4859-b7c4-315b9db9acbe.png">

### Steps to test

Go to the devTools and run in the console:

```
GET _cat/templates
DELETE _template/wazuh*
```

Then go to the health Check and check that it returns the following error:

`[Alerts index pattern] 4002 - Could not retrieve templates from Wazuh indexer due to An unknown error occurred when fetching templates from Wazuh indexer`
