### ISSUE TITLE
Broken breadcrumbs in Wazuh Dashboard 2.x

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-kibana-app#4502]
| Wazuh | OSD |
| ----- | ------- |
| 4.4   | 2.2.1     |

| Browser |
| ------- |
| Chrome, Firefox, Safari|

**Description**
New styles added to the breadcrumbs in this OSD [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1954) breaks our custom breadcrumbs, along with other issues:

- Logo rendering.
- API selector tag.
- Breadcrumbs.

This issue happens in OpenSearch Dashboards v2.2.1 and higher.

**Preconditions**
1. OSD 2.2.1 up and running

**Steps to reproduce**
1. Navigate to Wazuh
3. See the navigation bar

**Expected Result**
![image](https://user-images.githubusercontent.com/63758389/189851232-76533d84-a759-4dea-a4cd-c081d73a1ac8.png)

**Actual Result**
![image](https://user-images.githubusercontent.com/63758389/189851368-3eb98811-f1b4-4026-810c-04fe200adbb8.png)

**Comment by Machi3mfl** [comment]
### Task progress
Researching the styles in the `Opensearch Navbar` i found:

- Problems with a class called `osdBreadcrumbs` that add a CSS `filter` and cover the entire navbar.
If we remove this css property the breadcrumb is fixed but the problem is that is a default Opensearch style. 

![image](https://user-images.githubusercontent.com/6089438/193952711-71507fdf-5883-45c1-9bd2-10975d3876dd.png)


We cannot modify the style because is a native osd style. I'm research how to fix it without overriding the style.

**Comment by yenienserrano** [comment]
The new form of the breadcrumb is

![image](https://user-images.githubusercontent.com/63758389/195862331-19118b2c-a05e-4399-85ba-7425d4e255ec.png)

![image](https://user-images.githubusercontent.com/63758389/195862115-c19955dc-53b3-4222-bd71-dfe21291147c.png)
