### ISSUE TITLE
Adapt new workflows 

### ISSUE THREAD

**Issue by matiasmoreno876** [wazuh/wazuh-kibana-app#4603]
## Describe the solution you'd like

Recently in the project new workflows were added to Github actions, which help us to perform tasks automatically, these workflows were tested in an external repository, currently there are some points which must be adapted to work properly, these points came out based on the tests on the PR 
[#4574](https://github.com/wazuh/wazuh-kibana-app/pull/4574)

- [ ] Execute a complete test execution form Github action to WZD Environment
- [ ] Execute a complete test execution from Github action to Kibana Environment

Related issue: #4575

**Comment by Mayons95** [comment]
This issue was reponed because there were some problems related with different paths for the cypress implementation, particularly on the path of cypress.
We implemented with @matiasmoreno876 a solution for this.
Testing it's pending.
After executing a complete test from the Github Actions for Kibana or WZD environment, we will close this issue.

**Comment by Mayons95** [comment]
After reviewing the changes implemented by @matiasmoreno876 I executed the actions from the 4.4-7-10 branch with success. To execute with success the actions, the changes should be implemented in the main branch.

I will close this issue seems that the problem that cause the reopen of this issue is fixed.
