### ISSUE TITLE
The evolution chart overlaps with the agent information with a screen width minor than 1300px

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4910]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.16.3     | Xpack |

| Browser |
| ------- |
| Chrome|

**Description**
The evolution chart overlaps with the agent information with a screen width minor than 1300px

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to the agent page
2. Edit the screen width to less than 1300px

**Expected Result**
1. The agent info should not overlap

**Actual Result**
1. The evolution chart overlaps with the agent information with a screen width minor than 1300px

**Screenshots**

![Screenshot from 2022-11-18 16-47-52](https://user-images.githubusercontent.com/104914131/202790547-a3aca7fb-4464-4cdb-b2ff-0fbc29a0e9ea.png)

![Screenshot from 2022-11-18 16-47-28](https://user-images.githubusercontent.com/104914131/202790550-55976bb5-9290-4688-a4c5-24c96ad64e27.png)

![Screenshot from 2022-11-18 16-47-11](https://user-images.githubusercontent.com/104914131/202790552-ef41fe2e-68bb-4730-8999-1a4765189b2f.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Desvelao** [comment]
# Research

I could replicate the problem. It is happening in the development branch of `4.4-7.16`.

The affected visualization is different from other maintained development branches. I am reviewing the branches and the required changes.

**Comment by davidjiglesias** [comment]
Does this replicate in v4.3.X?

**Comment by Desvelao** [comment]
# Research

The problem is happening in the branch `4.4-7.16`.

I could replicate the problem and I experienced another problem related to a duplicate panel. I was working on a solution for both problems. While I was testing the solution, I found a rare problem, where the visualization was displayed, but the condition to display that there is no data in the selected range of time was fulfilled. I think there is a problem with the method to build the visualization. For another hand, the visualization is related to the `wazuh-monitoring-*` indices. Using the development environments, I didn't have data related to `wazuh-alerts-*` indices and this causes the visualization to display different results when there is data of these indices. The work was done in: ef70c34bad6469a7435d69394b825f3733e5b068


I commented on the problems of this issue in the daily meeting and we go to check if the problem related to the UI that opened this issue is happening for the latest versions of 4.3.x. In this case, we could consider this issue as a known issue and could not fix it for 4.4.0.

For another hand, I found a required change to do in the development branch `4.4-7.16` related to a problem due to resolving conflicts: 2563e060101b4b5bab3fae94382917abbadf6a47

**Comment by Desvelao** [comment]
The problem related to the UI is not happening in 4.3.10.

Using a Kibana 7.16.3:


![Image](https://user-images.githubusercontent.com/34042064/207394886-2b04f3c3-bd35-4b7a-a5a9-859b6240f6e5.png)

![Image](https://user-images.githubusercontent.com/34042064/207394627-d1f58e98-5bd5-420f-a658-7fd41c98fa39.png)


![Image](https://user-images.githubusercontent.com/34042064/207394986-7226299e-e9e7-47a7-a32a-171958c854d6.png)


![Image](https://user-images.githubusercontent.com/34042064/207394707-63d08701-9e0a-4975-96dc-1dffebe9e05e.png)

**Comment by Desvelao** [comment]
# Case replication

With the next conditions:
- There are indices related to alerts
- There are no indices related to monitoring

The `resultState` property of the `AgentsPreview` component is `ready`. This causes the panel with `No data found` message to be displayed and the height of some containers is not setting the expected height due to a wrong condition.


## Digging

I was comparing the differences in the development branches `4.3-7.16` and `4.4-7.16` and I found some changes related to conditions to set the height of some containers and other strange things. 

`4.3-7.16` - `4.4-7.16`: https://github.com/wazuh/wazuh-kibana-app/compare/4.3-7.16...4.4-7.16#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462L253-L308

Strange things I saw:
1. Removed the conditional rendering of the agent status evolution visualization: https://github.com/wazuh/wazuh-kibana-app/pull/4479/files#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462L264

This change removes the feature to display conditionally the visualization depending on if the monitoring job is enabled.

2. Removed some styles affecting related containers of the visualization:
https://github.com/wazuh/wazuh-kibana-app/pull/4479/files#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462L269
https://github.com/wazuh/wazuh-kibana-app/pull/4479/files#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462L278

I don't know what is the reason for the deletion. Do you remember the reason @asteriscos ?

3. Unfunctional condition. A boolean is compared against a string, this causes the condition could be falsy. I think it had a problem resolving the conflicts here. https://github.com/wazuh/wazuh-kibana-app/pull/4479/files#diff-9f89d90556bc520d79685e9c92d6d0452a844a9af08c5aba988bd291a6f69462R301-R302

For another hand, the pull request (https://github.com/wazuh/wazuh-kibana-app/pull/4479) has no reviewers:confused:

**Comment by Desvelao** [comment]
# Solution

I created a pull request to solve the problem in the UI that was described in the issue. https://github.com/wazuh/wazuh-kibana-app/pull/4996

The PR doesn't fix other problems found while researching the solution because more problems appeared. These were commented here: https://github.com/wazuh/wazuh-kibana-app/issues/4910#issuecomment-1348889355
