### ISSUE TITLE
Kibana mismatch version error is not displayed

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-kibana-app#4915]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.17.6     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox|

**Description**
The kibana mismatch error is not displayed. I tried to force it by using a Wazuh API 4.3.8 and installing the 4.4.0 RC1 app.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to the Wazuh App

**Expected Result**
1. The mismatch error should be displayed

**Actual Result**
1. A no connect API error it's displayed, but the API it's connected.

**Screenshots**

![Screenshot from 2022-11-22 12-48-41](https://user-images.githubusercontent.com/104914131/203359031-2b3bcb35-c571-480a-89c6-53de58312a2b.png)

**Comment by Tostti** [comment]
# Research
This error is caused due to the implementation of https://github.com/wazuh/wazuh-kibana-app/pull/4103, in which the method for the requests was changed from 'GET' to 'POST'. That leads to the error shown in the screenshot. It also prevents the second check to be made and the user to be warned that there is a mismatch between API and Kibana app versions.

**Comment by asteriscos** [comment]
# Proposed solution
When this error is thrown, suggest to the user it may be related to a version mismatch.
