### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-kibana-app#4956]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4   | 7.x     | 4xxx | Basic, ODFE, Xpack |

**Description**
There are unused dependencies and old dependencies that need to be updated. We have to analyze which dependencies need to be updated. The main goal is to prevent possible vulnerabilities.
We need to update `winston@3.0.0` dependency and delete `"angular-chart.js": "1.1.1"`.

Plan

- Kibana 7.10.2

| Dependency | Action | Comments |
| --- | --- | --- |
| `angular-chart.js` | Remove | Remove unused code and remove the dependency |
| `pdfmake` | - | it can't be upgraded due to the NodeJS version |
| `winston` | Upgrade | Upgrade to 3.5.1 | 

- Kibana 7.16-7.17

| Dependency | Action | Comments |
| --- | --- | --- |
| `angular-chart.js` | Remove | Remove unused code and remove the dependency |
| `pdfmake` | Upgrade | Upgrade to 0.2.6 |
| `winston` | Upgrade | Upgrade to 3.5.1 |

- Wazuh dashboard 4.4.0

| Dependency | Action | Comments |
| --- | --- | --- |
| `angular-chart.js` | Remove | Remove unused code and remove the dependency |
| `pdfmake` | Upgrade | Upgrade to 0.2.6 |
| `winston` | Upgrade | Upgrade to 3.5.1 |

**Comment by Desvelao** [comment]
# Research

There are some vulnerabilities related to the `charts.js` dependency.
We saw that this library is a subdependency of the plugin. This is a dependency of `angular-charts.js` library. This has as dependency `charts.js`. https://github.com/jtblin/angular-chart.js/blob/1.1.1/package.json#L68

We have researched that this could not be used in the current plugin, despite the source code import.
It seems that this library was included in the plugin for Wazuh 3.9.0.
https://github.com/wazuh/wazuh-kibana-app/pull/1364
> https://github.com/wazuh/wazuh-kibana-app/pull/1364/files#diff-606723423f3cff920611ae97db1265f19fba8f00d880ba0366ce5cc709163256R44-R47
> https://github.com/wazuh/wazuh-kibana-app/pull/1364/files#diff-1485c6a2e0bdd765d6fc49dcf6889c236db796fa458f27263a412050ad34bc8bR48-R50
In the current plugins, the `angular-charts.js` library could not be used.

I found we could be using the functionality of charts.js here:
`public/templates/discover/discover.html`
![image](https://user-images.githubusercontent.com/34042064/205681822-eb02de29-6473-4548-a801-e9929ba946c7.png)

The public/templates/discover/discover.html file could not be used. It is related to the previous message. So the import of this file could be removed because it is not used.
https://files.slack.com/files-pri/TMYFNFQ3W-F04E5387073/image.png

**Comment by Desvelao** [comment]
# New request

We have been asked to upgrade the `pdfmake` dependency to `0.2.6`. This requires NodeJS 12 or higher https://github.com/bpampuch/pdfmake/blob/0.2.6/package.json#L47 so this could be problematic in platforms that use a lower version.

| Platform | NodeJS version |
| --- | --- |
| Kibana 7.10.2 | 10.23.1 |
| Kibana 7.16.0 | 16.13.0 |
| Kibana 7.17.0 | 16.13.2 |
| Kibana 7.17.6 | 16.16.0 |
| OpenSearch Dashboards 2.4.0 | 14.20.0 |

> :exclamation: Kibana 7.10.2 could give problems installing the `pdfmake` (v0.2.6) dependency.

**Comment by Desvelao** [comment]
TODO:
- [ ] Create a pull request for Kibana 7.10.2 due to upgrading the `pdfmake` is incompatible with the NodeJS version used in this platfrom.
