### ISSUE TITLE
Compatibility with [Elastic | OpenSearch] (version)

### ISSUE THREAD

**Issue by solftclone** [wazuh/wazuh-kibana-app#5100]
Hi, I am trying to install wazuh kibana app version 7.17.5 for elastic 8.4.1. I am getting below error
"plugin installation is unsuccessful due to error "plugin wazuh 7.17.5 is incompatible with kibana 8.4.1"

Could you please help me with that? Like which wazuh kibana app plugin I can use for kibana 8.4.1.

Please respond as soon as possible

**Comment by Desvelao** [comment]
Hi @solftclone,

The error you got is related to the Kibana version of the Wazuh plugin is pointing to must match the Kibana version.

Unfortunately, at the moment, there is no plugin compatible with Kibana 8.4.1. You can check the available plugins in the compatibility matrix: https://github.com/wazuh/wazuh-kibana-app/wiki/Compatibility. If you want to use the Wazuh plugin to manage your Wazuh deployment, you will need a Kibana whose version has a compatible Wazuh plugin (see the compatibility matrix). In the case, you are only interested in the dashboards and there is no plugin compatible with the Kibana version that you are using, you could build custom dashboards or replicate the provided ones by the Wazuh plugin with the Dashboards plugin of your current Kibana version.

**Comment by solftclone** [comment]
Hi, thanks for the reply. Actually i want to use kibana 8.4.1 version only and I want to build wazuh kibana app package for that using wazuh packages.
Can we do that? 
and i think supporting kibana 8.4.1 feature is in progress right?

**Comment by solftclone** [comment]
Hi @Desvelao , can you please guide me on am I able to build wazuh kibana app package for kibana 8.4.1 or I need to wait until support to kibana 8.4.1 is provided .

Or will you provide me the steps to replicate provided ones dashboard by wazuh plugin with my current kibana dashboard.

Thanks

**Comment by solftclone** [comment]
Hi @Desvelao , Actually, I want to know just for curiosity like can we create two docker instances of kibana in security onion ,one having kibana 8.4.1 version and other one is something 7.X range and for that 7.x version we can add wazuh kibana app plugin and use the wazuh kibana app plugin facilities.

**Comment by Desvelao** [comment]
Hi @solftclone ,

> I want to know just for curiosity like can we create two docker instances of kibana in security onion

Unfortunately, I am not familiar with Security Onion.

This depends on how you deployed the Docker containers. If you can modify this deployment, you should be able to start a container with Kibana 7.x that has a compatible Wazuh plugin.

**Comment by solftclone** [comment]
Hi, why compatible version of wazuh kibana plugin to 8.4.1 is not released? I tried multiple things and all those things that you suggested but as I am new to all this technologies I am not able to achieve my goal of adding kibana plugin to kibana 8.4.1. Isn't it possible for you to work on compatible version of kibana 8.4.1. I will also contribute into that. You just told me what to do? .

please I needed this plugin

**Comment by kmfreder1** [comment]
@solftclone While I have not tested versions that are this far apart, you may try to downgrade Kibana to the latest version of 7.x where there is a supported Wazuh App.  I believe the version would be 7.17.6.  Kibana is not version tied to the Elasticsearch that it talks to, so this may be a workaround for now.  As to your question about Security Onion, Security Onion's Kibana is fully dockerized, so you can do a straight install of a second Kibana instance.  Please note that you will have to change the listening port from 5601 or 443, whichever you plan to use, since these are taken by Security Onion already.  You could instead use 5602 or 44301 or some other non-used port.  You will also then have to open those new port numbers on the firewall with so-firewall in order for those ports to be approached.  Hope this helps.

**Comment by branchnetconsulting** [comment]
According to [here](https://www.elastic.co/support/eol), it appears that at the moment Elastic.co releases 9.0.0, all 7.x versions of the Elastic stack would immediately go end-of-life.  If that is correct, then if Wazuh does not release an 8.x-compatible version of the Wazuh web interface (plugin) before Elastic Stack 9.0.0 is released, then all Wazuh users and customers depending on Elastic Stack for alert storage will be forced into an end-of-life scenario that would be very difficult to remediate.  That would be very very bad.

**Comment by branchnetconsulting** [comment]
I don't know Elastic's projected timeline, but it appears 9.0.0 has been in beta since the middle of last year.
https://www.nuget.org/packages/Serilog.Sinks.Elasticsearch/9.0.0-beta7

**Comment by Desvelao** [comment]
> Hi, why compatible version of wazuh kibana plugin to 8.4.1 is not released? I tried multiple things and all those things that you suggested but as I am new to all this technologies I am not able to achieve my goal of adding kibana plugin to kibana 8.4.1. Isn't it possible for you to work on compatible version of kibana 8.4.1. I will also contribute into that. You just told me what to do? .
> 
> please I needed this plugin

Hi @solftclone, there is currently no compatible plugin for the Kibana 8.x versions. Each Kibana version expects a specific compatible plugin.

Kibana 8.x introduced multiple changes that do the recent Wazuh plugin for Kibana 7.17.x is not functional because requires adapting to the new changes of Kibana. In the last months, we have not been able to dedicate the appropriate time until we worked on the issue https://github.com/wazuh/wazuh-kibana-app/issues/4567. In that issue, we could solve some compatibility problems, but there are others that have not been solved. Unfortunately, that issue is on hold at the moment. I can't say you when we could follow the work on the issue.

I don't know your use case, but if you need Kibana 8.4.1 for some reason. At this moment, you can't install a compatible plugin for that Kibana version. So, if your use case lets to separate the functionalities, then you could use different deployments instead to try to centralize it in the same Kibana/Elasticsearch. I mean:
- a Kibana/Elasticsearch deployment for Security Onion (using of Kibana 8.4.1 as you mentioned)
- a compatible stack with Wazuh for the tasks related to Wazuh

In case you want to deploy a stack for Wazuh see these links:
- https://documentation.wazuh.com/current/installation-guide/index.html
- https://documentation.wazuh.com/current/deployment-options/index.html

If you don't need any proprietary feature of the Elastic stack ( in the Kibana and/or Elasticsearch products ), my recommendation is you deploy the Wazuh stack that uses the Wazuh dashboard and Wazuh indexer applications. They are based on distributions of OpenSearch Dashboards and OpenSearch (forks of Kibana and Elasticsearch 7.10.2). If you need or want the Elastic stack, then you should know the latest supported version is 7.17.6.

**Comment by Desvelao** [comment]
I will close the issue due to inactivity.
