### ISSUE TITLE
Create redistributable boards for Elastic

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5185]
We want to implement new boards and panels based on our documentation, which will cover the following:

- [Security analysis](https://documentation.wazuh.com/current/_images/screenshot-01-Wazuh-Security-Analytics1.png)
- [Intrusion detection](https://documentation.wazuh.com/current/_images/screenshot-02-Wazuh-Intrusion-Detection1.png)
- [Log data analysis](https://documentation.wazuh.com/current/_images/screenshot-03-Wazuh-Log-Data-Analysis1.png)
- [File integrity monitoring](https://documentation.wazuh.com/current/_images/screenshot-04-Wazuh-File-Integrity-Monitoring1.png)
- [Vulnerability detection](https://documentation.wazuh.com/current/_images/screenshot-05-Wazuh-Vulnerability-Detection1.png)
- [Configuration assessment](https://documentation.wazuh.com/current/_images/screenshot-06-Wazuh-Configuration-Assessment1.png)
- [Incident response](https://documentation.wazuh.com/current/_images/screenshot-07-Wazuh-Incident-Response1.png)
- [Regulatory compliance](https://documentation.wazuh.com/current/_images/screenshot-08-Wazuh-Regulatory-Compliance1.png)
- [Cloud security](https://documentation.wazuh.com/current/_images/screenshot-09-Wazuh-Cloud-Security1.png)
- [Containers security](https://documentation.wazuh.com/current/_images/screenshot-10-Wazuh-Containers-Security1.png)

We want to use our sample data as the base for its creation. 

- Create an Elastic environment using the latest version (8.6.0)
- Upload our sample data collection
- Using the dashboard plugin from the Elastic stack, create each query and panel to compose each one of the dashboards

**Comment by chantal-kelm** [comment]
I have generated a script to which I put alerts and it creates a csv file.

When I upload this file to elastic I get an error, I have tried with other formats and I also get the same error.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/215854176-e59e2487-1797-4d61-b5c6-e8d57297c7cb.png">

I have been investigating and I am trying to solve the error.

**Comment by chantal-kelm** [comment]
Today's breakthrough: the first dashboard has been built:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/216128094-0769646d-e036-4c5e-aa91-489426c65bf0.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/216128180-5808e192-d458-48e2-9e0e-783c61afff1d.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/216128701-e183ccb8-38a1-4051-8c39-6cd16e0982bd.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/216128821-e44132a7-b6f6-4211-a881-3b8428c53190.png">

**Comment by Tostti** [comment]
Today I adapted all the dashboards to be compatible with the integration guide. 
I also created three more files: 

**Integrity monitoring**
![imagen](https://user-images.githubusercontent.com/42900763/226476163-39d1139d-634e-4907-9c43-824e093df026.png)

**Log data analysis**
![imagen](https://user-images.githubusercontent.com/42900763/226476230-73886b6a-0819-410e-a689-94fb54db8619.png)

And also a file called `all-dashboards.ndjson` that contains all the dashboards to the moment, to be able to import them in one step.

**Comment by Tostti** [comment]
Today I updated the `incident-response` dashboard

**Comment by chantal-kelm** [comment]
Due to some modifications that were made to the dashboards in terms of design and as we saw with my partner @Desvelao that they have been built with the visualize plugin, which is an older plugin, it was decided with @gdiazlo to use the dashboards that we had done days ago for kibana, which are made with the newer plugin called lens, and it was also decided to make dashboards with the plugin offered by Opensearch.

**Comment by chantal-kelm** [comment]
The integration environment has no mapping added and the charts were generated without mapping so they are using the fields with the "keyword" (e.g. agent.name.keyword).

<img width="1792" alt="Captura de pantalla 2023-04-17 a la(s) 15 20 42" src="https://user-images.githubusercontent.com/99441266/232766846-3083dea3-23db-458d-8ae4-906e4733102f.png">

**Comment by chantal-kelm** [comment]
Elastic 8.6.2 dashboards are compatible, work fine with elastic 8.7.0 version

<img width="1792" alt="Captura de pantalla 2023-04-18 a la(s) 15 13 50" src="https://user-images.githubusercontent.com/99441266/232867334-e8015048-5d3e-4690-8084-457a35363285.png">

**Comment by chantal-kelm** [comment]
We were with my colleague @Desvelao reviewing the pipeline transformations in Filebeat, to see if it was necessary to do them in Logstash, but in this case it is not necessary because those fields are not used in any of the dashboards.

Also, my colleague @Desvelao suggested to add a versioning for the dahboards, that we decided with @gdiazlo to add in the name of each dashboard, this way we have them identified and if later we are making updates or releasing more dashboards and some user is asking us some query, we can know which version he has. Also by @Desvelao suggestion we add the word Wazuh to the name of each dashboard, this way the user can identify them better.

### Elastic

<img width="290" alt="Captura de pantalla 2023-04-24 a la(s) 15 37 56" src="https://user-images.githubusercontent.com/99441266/234086438-0d385586-40f6-4984-890f-ed7c5c97993c.png">
