### ISSUE TITLE
Release 4.4.0-rev.03 - RC1 - Kibana UI regression testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5208]
## Description

This issue aims to track the effort to perform complete regression testing on Wazuh App 4.4.0 rev 03 for RC1

| Test         | Chrome | Safari | Firefox | Package |
|--------------|--------|--------|---------|---------|
| Example test | 🟢/🔴  | 🟢/🔴  | 🟢/🔴   | 🟢/🔴   |
 
### Status legend
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, **create and add** the issue to the Bug Tracking section. 

### Testing plan

- [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199)

### Testing notes

1) All the mentioned versions will be tested
2) It's necessary to include evidence of each test performed
3) In case to identify a bug/problem, the new feature should be linked to this issue

  - [x] 7.17.8
  - [x] 7.17.7
  - [x] 7.16.3
  - [x] 7.10.2
  - [x] WzD 4.4.0-03

Testing template: 
[template_testing_4.4.0-RC1.md](https://github.com/wazuh/wazuh-kibana-app/files/10709775/template_testing_4.4.0-RC1.md)

**Comment by Tostti** [comment]
# WZD

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199) | :black_circle: | :black_circle: | :black_circle: | WZD |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5199" target="_blank">Crash in vulnerabilities module due to references missing field</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:


</details>

**Comment by Tostti** [comment]
# 7.17.8

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199) | :black_circle: | :black_circle: | :black_circle: | WZD |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5199" target="_blank">Crash in vulnerabilities module due to references missing field</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:
</details>

**Comment by yenienserrano** [comment]
# 7.10.2

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199) | :black_circle: | :black_circle: | :black_circle: | WZD |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5199" target="_blank">Crash in vulnerabilities module due to references missing field</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:
</details>

**Comment by yenienserrano** [comment]
# 7.17.7

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199) | :black_circle: | :black_circle: | :black_circle: | 7.17.7 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5199" target="_blank">Crash in vulnerabilities module due to references missing field</a></summary>

Chrome - :black_circle:



Firefox - :black_circle:




Safari - :black_circle:
</details>

**Comment by yenienserrano** [comment]
# 7.10.2

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

| Test | Chrome | Firefox | Safari | Package |
| --- |  --- | --- | --- | --- |
| [Crash in vulnerabilities module due to references missing field](https://github.com/wazuh/wazuh-kibana-app/issues/5199) | :black_circle: | :black_circle: | :black_circle: | 7.10.2 |


**Details**
<details>
<summary>:black_circle: <a href="https://github.com/wazuh/wazuh-kibana-app/issues/5199" target="_blank">Crash in vulnerabilities module due to references missing field</a></summary>

Chrome - :black_circle:


Firefox - :black_circle:


Safari - :black_circle:
</details>
