### ISSUE TITLE
Compatibility with OpenSearch Dashboard 1.2

### ISSUE THREAD

**Issue by ribalraza009** [wazuh/wazuh-kibana-app#5232]
## Description
Hey! I have cloned OpenSearch-Dashboards version 2.6, and I want to add wazuh-kibana-app in it in development environment. I tried to do it but on `yarn osd bootstrap` It gave me dependencies version conflict. I tried to match opensearch-dashboards dependencies with wazuh-kibana-app dependecies but it caused trouble with sub-dependencies of opensearch-dashboards. Can you guide me how to setup compatible opensearch-dashboards and wazuh-kibana-app development environment?

**Comment by Desvelao** [comment]
Hi @ribalraza009,

At the current moment, there is no compatible plugin with OpenSearch Dashboards 2.6.x and we had not tried the compatibility with that version yet, so you could find more problems related to the compatibility problems.

Attending to your question about dependencies. We know about a related problem, but I am not sure if you are experiencing the same one.

If your problem is the Wazuh plugin dependencies should match with the same version of the dependencies of the OpenSearch Dashboards, then you could try the following steps:

1. **Without including the source code of the Wazuh plugin** in the `plugins` directory of OpenSearch Dashboards source code, install the dependencies of OpenSearch Dashboards
```
yarn osd boostrap
```

2. Using a Wazuh plugin branch compatible with OpenSearch Dashboards, add the source code of plugin to the `plugins `direcotyr of the OpenSearch Dashbaords and install the plugin dependencies.

> Ensure you are using a Wazuh plugin branch compatible with OpenSearch Dashboards. The `wazuh-kibana-repository` has many branches that are compatible with Kibana. The compatible branches with OpenSearch Dashboards usually have the `-wzd` suffix or the literal branch `4.5` is pointing to OpenSearch Dashboards. As I said previously, we didn't try OpenSearch Dashboards 2.6.x.

```
cd plugins/wazuh
yarn
```

This should solve the problem of the mismatch of dependencies OSD-Wazuh plugin.

If this doesn't solve the problem, share the error or problem you are experiencing.

Please keep in mind the next time not to mention colleagues if they are not participating in the issue. Thank you.

**Comment by ribalraza009** [comment]
Thank you @Desvelao for responding to the compatibility issue, and sorry from my side for mentioning the colleagues. 
For now, I am using OpenSearch-Dashboards branch/version 1.2 which is compatible with wazuh-kibana-app branch 4.3-1.2-wzd. Both use node version 10.24.1 and 10.23.1 respectively. So when I run `yarn osd bootstrap` it is giving me the following dependency error:
```
@mapbox/hast-util-table-cell-style@0.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
```
 I am unable to track down the package is using this dependency because no yarn.lock file is generating, can you help me in this issue

**Comment by Desvelao** [comment]
Hi @ribalraza009 ,

If I understood you correctly, you are trying to create a Wazuh plugin compatible with OpenSearch Dashboards 2.6.0. You only said OpenSearch Dashboards 2.6, but I guess you are referring to the only available version which is 2.6.0. Correct me if I am wrong.

OpenSearch Dashboards 2.6.0 uses NodeJS `14.20.1`: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.6.0/.nvmrc

And for the error you shared, there is a compatibility problem with the requirements of some of the dependencies with your NodeJS version which is 10.24.1. This should be solved if you use the expected NodeJS version for OpenSearch Dashboards 2.6.0 which is NodeJS 14.20.1.

**Comment by ribalraza009** [comment]
no, it's not the case, Now I am using OpenSearch Dashboard 1.2, with Wazuh 4.3 , it's working but just one error occurs when `'yarn osd bootstrap' ` is executed:
```
@mapbox/hast-util-table-cell-style@0.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
```

**Comment by Desvelao** [comment]
> no, it's not the case, Now I am using OpenSearch Dashboard 1.2, with Wazuh 4.3 , it's working but just one error occurs when `'yarn osd bootstrap' ` is executed:
> 
> ```
> @mapbox/hast-util-table-cell-style@0.2.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
> error Found incompatible module.
> ```

Hi @ribalraza009,

We have developed the Wazuh plugin for a platform based in OpenSearch Dashboards 1.2.0 and we have not had that problem. So I guess you could have other features/plugins apart from the Wazuh plugin that could be using the `@mapbox/hast-util-table-cell-style@0.2.0` dependency, please, review if you are using some more than the OpenSearch Dashboards 1.2.0 or the Wazuh plugin. The problem could be related to another feature/plugin.

You could be interested to see the dependants of that package: 
- https://www.npmjs.com/browse/depended/@mapbox/hast-util-table-cell-style
- https://github.com/mapbox/hast-util-table-cell-style/network/dependencies

Or you can give a try to the following command to know the reason for that package. From the root of OpenSearch Dashboards 1.2.0 source code, run:
```
yarn why @mapbox/hast-util-table-cell-style
```

**Comment by Desvelao** [comment]
Hi @ribalraza009 , did you solve the problem?

**Comment by ribalraza009** [comment]
@Desvelao Yes thank you so very much, I was able to setup dev environment (OpenSearch-Dashboards + Wazuh-Kibana-App).

**Comment by viveknagar0301** [comment]
Hi @ribalraza009 I am also getting the same problem. Can you please tell me how you had solved the problem
