### ISSUE TITLE
Several failed requests when creating/deleting Role mapping

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-kibana-app#5361]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.1   | 7.x     | RC1 | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Safari |

**Description**

Every time I create/delete a Role mapping, failed requests are made even if the token has not expired.

**Preconditions**
1. Verify that the token does not expires soon.

**Steps to reproduce**
1. Navigate to 'Security/Roles Mapping'
2. Click on 'Create Rol Mapping'
3. Create a Rol mapping
4. Delete a Rol mapping

**Expected Result**
1. No requests with 401 responses

**Actual Result**
1. Multiple 401 responses

**Screenshots**

<img width="550" alt="Screenshot 2023-04-10 at 12 46 16" src="https://user-images.githubusercontent.com/39094716/230887553-1973573d-399e-439c-8968-230e27161a9c.png">
  <img width="550" alt="Screenshot 2023-04-10 at 12 47 40" src="https://user-images.githubusercontent.com/39094716/230887669-18255a1a-34dd-471f-86ba-7b06a06d9856.png">
  <img width="701" alt="Screenshot 2023-04-10 at 12 49 14" src="https://user-images.githubusercontent.com/39094716/230888053-7d70cd18-e07f-4fce-9662-cabfb1f0e480.png">
  <img width="806" alt="Screenshot 2023-04-10 at 12 51 53" src="https://user-images.githubusercontent.com/39094716/230888308-14b404bf-9022-4f3d-b5c6-d3859660ef4f.png">

**Comment by Desvelao** [comment]
Hi, the requests are failing due to a mechanism of Wazuh API when a role mapping is edited, it deprecates all the affected tokens. This causes the next requests that use the previous valid token, to fail with status code `401`. When the request with status code 401 is detected, then the plugin gets a new valid token. This request is done through the `login` endpoint that is visible in the report you did.
![image](https://user-images.githubusercontent.com/34042064/231161118-cd6d6b10-e33e-4267-96ca-4babf640c7bf.png)

I could replicate it in Wazuh 4.3.10, setting the `run_as` API host setting as `true`.

Request done to create the role mapping (Wazuh API security rule):
![image](https://user-images.githubusercontent.com/34042064/231161353-2c0f0e21-ed33-47f2-8349-71c39670a32b.png)

Failed request after creating the role mapping in the Wazuh plugin:
![image](https://user-images.githubusercontent.com/34042064/231161457-4f5f5c7f-cd61-46bc-8544-fc7f952eb107.png)

Related references:
- https://documentation.wazuh.com/current/user-manual/api/configuration.html#security-configuration
- https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html

**Comment by Desvelao** [comment]
If we consider optimizing the request done to the Wazuh API, then we could force to get a new token after this type of action is done instead of falling into the mechanism of the Wazuh plugin to refresh the Wazuh API token.

**Comment by gdiazlo** [comment]
Closing as is the expected behavior. We can revisit this in the future, if we decide to change it.
