### ISSUE TITLE
Issue with Wazuh while integrating with Maria-db

### ISSUE THREAD

**Issue by aravindcyberfort** [wazuh/wazuh-kibana-app#5378]
While integrating maria-db logs with Wazuh I have an issue, as the logs were forwarded to the wazuh server but it's not reflecting on the Dashboard, please help me to fix this issue.

![Screenshot (5)](https://user-images.githubusercontent.com/130983319/232461754-f0763f6d-a2d5-4463-925c-20d86b2c3370.png)
![Screenshot (6)](https://user-images.githubusercontent.com/130983319/232461815-383a7b6c-d343-4b7b-bf9f-9f202af71ea9.png)
![Screenshot (7)](https://user-images.githubusercontent.com/130983319/232461831-d7244622-0b75-4234-a742-cf1dae1bed38.png)

**Comment by Desvelao** [comment]
Hi @aravindcyberfort ,

I see you enabled the `logall_json` setting in the Wazuh server that causes the analyzed events will be saved in the `/var/ossec/logs/archives/archives.json` file.

You should know that Wazuh has 2 types of events:
- `archives`: all the events received by Wazuh
- `alerts`: all the events that match a Wazuh rule and the rule level is equal or higger than the minimum level (by default 3)

References:
- https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html?highlight=wazuh-archives#wazuh-indexer

Depending on what you want to get:
- index the `archives` logs and be visible in Wazuh dasbboard/Kibana
- generate an alert of specific log
I will give some information about these topics.

# How to index the Wazuh archives data into Wazuh indexer/Elasticsearch

If you are pretending to see the logs saved in `/var/ossec/logs/archives/archives.json` file, then you should ensure that the `archives` dataset of `wazuh` module for Filebeat is enabled.

> Do it in each manager you want to forward the `archives` Wazuh events to Wazuh indexer.

1. Enable the `archives` dataset of `wazuh` module for Filebeat.

Set the `enabled` setting of `archives` dataset to `true` in the Filebeat configuration file (`/etc/filebeat/filebeat.yml`). You should set something like:
```
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: true
```
> Note the `enabled` setting of `archives` dataset is set to `true`.

2. Restart the `filebeat` service:

Depending on your service manager:

- systemd
```
systemctl restart filebeat
```

- SysV
```
service filebeat restart
```

After that, you should check Filebeat is forwarding the logs. They are indexed to indices called `wazuh-archives-4.x-YYYY.MM.DD` (`YYYY`, `MM` and `DD` are placeholders of year, month and day).

You could check the indices you have with a request to Wazuh indexer/Elasticsearch through the `Dev Tools` plugin of the Wazuh dashboard:

```
GET /_cat/indices
```

Ensure you have indices called `wazuh-archives-4.x--YYYY.MM.DD`.

In the case you want to use the data of the `wazuh-archives-4.x--YYYY.MM.DD` in the Wazuh or Discover plugin, you need to create an index pattern whose name matches the names of these indices.

Go to `Stack management` -> `Index patterns` and create a new one called for example: `wazuh-archives-*`, select `tiemstamp` for the time field. This index pattern should match with the indices `wazuh-archives-4.x--YYYY.MM.DD`. After the index pattern is created, then you could select in the Wazuh or DIscover plugin to use this data.

# See the MariaDB data as an alert in Wazuh

To a Wazuh alert has to be generated and visible in the Wazuh dashboard, this follows the following flow:

1. Wazuh agent collects the logs
2. The log is sent to the Wazuh server.
3. Wazuh server analyzes the log using decoders and rules.
4. If the log matches with a Wazuh rule and the rule level is higher than the minimum level, then an alert is generated and saved to `alerts.json` file located at `/var/ossec/logs/alerts/alerts.json` (this is enabled by default).
5. Filebeat reads the `/var/ossec/logs/alerts/alerts.json` file and sends the data to Wazuh indexer/Elasticsearch storing in `wazuh-alerts-4.x-YYYY.MM.DD` indices
6. With an index pattern that matches these indices, the data is visible in the Wazuh or Discover plugin of Wazuh dashboard/Kibana.

If you want the log as a Wazuh alert and the Wazuh default ruleset has not a rule that matches the log you want to be alerted, then you could need to create a custom rule or decoders. Blog: https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/

**Comment by aravindcyberfort** [comment]
4.If the log matches with a Wazuh rule and the rule level is higher than the minimum level, then an alert is generated and saved to alerts.json file located at /var/ossec/logs/alerts/alerts.json

I used custom ruleset and decoder but the logs doesn't loaded at /var/ossec/logs/alerts/alerts.json, but showing in archives.json, may the decoder and rule doesn't matched.
Please provide the ruleset and decoder for mariadb.

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 
4.If the log matches with a Wazuh rule and the rule level is higher than the minimum level, then an alert is generated and saved to alerts.json file located at /var/ossec/logs/alerts/alerts.json

I used custom ruleset and decoder but the logs doesn't loaded at /var/ossec/logs/alerts/alerts.json, but showing in archives.json, may the decoder and rule doesn't matched.
Please provide the ruleset and decoder for mariadb.

**Comment by Desvelao** [comment]
Hi @aravindcyberfort ,

Wazuh has some decoders and rules for MariaDB, but I am not sure if they match the logs you are collecting.

For example, for Wazuh 4.4.0: 
- decoders: https://github.com/wazuh/wazuh/blob/v4.4.0/ruleset/decoders/0378-mariadb_decoders.xml
- rules: https://github.com/wazuh/wazuh/blob/v4.4.0/ruleset/rules/0535-mariadb_rules.xml

If your logs don't match with the decoders or rules that there is in your environment, then you will have to create them. Some references:
- https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/

You can use the `wazuh-logtest` tool to try your custom decoders and rules. More information: https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/how-it-works.html#use-cases-test-log-from-wazuh-logtest-tool

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 
I have tried using custom decoder and rules, and the log test works, but the logs are only loaded at /var/ossec/logs/archives/archives.json and not showing up at /var/ossec/logs/alerts/alerts.json
But other than mariadb, like mysql the logs are showing at alerts.json
![Screenshot (10)](https://user-images.githubusercontent.com/130983319/232749826-db49acdc-79ef-4bdc-8a01-a2276b3245b7.png)
![Screenshot (11)](https://user-images.githubusercontent.com/130983319/232749868-8d156271-bfe2-4a7f-986b-58e0aec26b60.png)
![Screenshot (12)](https://user-images.githubusercontent.com/130983319/232749880-ad115279-e6e8-47e3-b251-c941dd87334d.png)

**Comment by Desvelao** [comment]
Hi @aravindcyberfort ,

From you screenshot:
![Screenshot (10)](https://user-images.githubusercontent.com/130983319/232749826-db49acdc-79ef-4bdc-8a01-a2276b3245b7.png)

I see you tested a log with the `wazuh-logtest` tool.

The log you used here, is being pre-decoded ( I guess the log can not be decoded using a specific decoder for MariaDB or you need to define a custom one). As you can see in step 3, the log matches the `rule` with ID `1002` which has the rule level as 2.

![image](https://user-images.githubusercontent.com/34042064/232753436-7a2e7f4f-d7e9-4353-acfa-d51c39332952.png)

The generated alerts are events that match a Wazuh rule and its level is equal or higher than the minimum level (configurable, see https://documentation.wazuh.com/current/user-manual/manager/alert-threshold.html#defining-an-alert-level-threshold). The minimum level by default is 3 and the trigger rule level is 2, so the alert will not be generated. If you want to get the alert of level 2 to be visible in the Wazuh dashboard, then you have to modify the minimum alert level.

You should take into account, that reducing the minimum alert level will increase the disk usage because more alerts will be logged in the `alerts.json` and `alerts.log` file and indexes to Wazuh indexer/Elasticsearch indices.

In the case you want to be alerted of some specific situations with the MariaDB application, you can build custom rules (and decoders if needed) whose rule level is equal or higher to the minimum alert level instead of seeing more events you could have not interested.

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 

Logs of Login failed:

{"timestamp":"2023-04-18T16:38:13.543+0530","rule":{"level":2,"description":"Unknown problem somewhere in the system.","id":"1002","firedtimes":8,"mail":false,"groups":["syslog","errors"],"gpg13":["4.3"]},"agent":{"id":"001","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1681816093.1256380","full_log":"\t\t    33 Connect\tAccess denied for user 'root-aravind'@'localhost' (using password: YES)","decoder":{},"location":"/var/log/mysql/mariadb-audit.log"}

Logs of DML/DLL commands of mariadb:

{"timestamp":"2023-04-18T16:49:20.188+0530","agent":{"id":"001","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1681816760.1275205","full_log":"20230418 16:49:20,ubuntu-mariadb,root,localhost,34,65,QUERY,mysql,'DROP DATABASE aravind',0","decoder":{},"location":"/var/log/mysql/mariadb-audit.log"}

Here the alerts for login failed is indexing to the dashboard, but the DML/DLL logs are not showing up in alerts.json and so not indexing.
can you provide the decoder and rule for the above DML/DLL command?

**Comment by Desvelao** [comment]
> Hi @Desvelao
> 
> Logs of Login failed:
> 
> {"timestamp":"2023-04-18T16:38:13.543+0530","rule":{"level":2,"description":"Unknown problem somewhere in the system.","id":"1002","firedtimes":8,"mail":false,"groups":["syslog","errors"],"gpg13":["4.3"]},"agent":{"id":"001","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1681816093.1256380","full_log":"\t\t 33 Connect\tAccess denied for user 'root-aravind'@'localhost' (using password: YES)","decoder":{},"location":"/var/log/mysql/mariadb-audit.log"}
> 
> Logs of DML/DLL commands of mariadb:
> 
> {"timestamp":"2023-04-18T16:49:20.188+0530","agent":{"id":"001","name":"ubuntu-mariadb","ip":"192.168.40.62"},"manager":{"name":"wazuh-ML"},"id":"1681816760.1275205","full_log":"20230418 16:49:20,ubuntu-mariadb,root,localhost,34,65,QUERY,mysql,'DROP DATABASE aravind',0","decoder":{},"location":"/var/log/mysql/mariadb-audit.log"}
> 
> Here the alerts for login failed is indexing to the dashboard, but the DML/DLL logs are not showing up in alerts.json and so not indexing. can you provide the decoder and rule for the above DML/DLL command?

Hi @aravindcyberfort ,

I was researching and the logs you want to be displayed in the Wazuh dashboard could not be matching the default decoders and rules.

I will try to create some decoder and rule to the alert that can be generated and be visible in the Wazuh dashboard.

I need the next things to try to replicate your environment and your use case.
1. Wazuh server version
2. How the MariaDB logs are being collected? If they are collected from a file, it would be interesting if you share how these logs are saved in the file. I want to know what configuration you added to the Wazuh agent to the logs are collected.

Anyways, my recommendation is you read the Wazuh documentation on how to collect the logs, and the creation of custom decoders and rules so you know how this flow works and you can create them for your use cases if the default ruleset doesn't include it.

References:
- https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/index.html
- https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/
- https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/how-it-works.html#use-cases-test-log-from-wazuh-logtest-tool

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 
1. Wazuh version- v4.4.1
2. How I configured Maria to get audit logs?
-     Audit plugin installed and enabled on MariaDB
-     Installed rsyslog on our MariaDB server and forwarded as 
       ***.* @192.168.40.61:514**
- Did configuration at /etc/mysql/ and edited my.cnf file. as 
    [mariadb]
**# Install audit plugin
plugin_load_add = server_audit

# Enable audit plugin
server_audit=FORCE_PLUS_PERMANENT

# Logging output to a file
server_audit_logging=ON
server_audit_file_path=/var/log/mysql/mariadb-audit.log

# What we want to log
server_audit_events='CONNECT,QUERY,TABLE,QUERY_DDL,QUERY_DML,QUERY_DCL,QUERY_DML_NO_SELECT'

# Audit configured Syslog
server_audit_syslog_ident='mariadb-audit'**

- edited ossec.conf file, located here: /var/ossec/etc/ as
    **<remote>
    <connection>syslog</connection>
    <port>514</port>
    <protocol>udp</protocol>
    <allowed-ips>192.168.40.0/24</allowed-ips>
    </remote>**


![Screenshot (15)](https://user-images.githubusercontent.com/130983319/232976168-20219f31-62e8-48f7-bfef-64a2713efba5.png)
![Screenshot (16)](https://user-images.githubusercontent.com/130983319/232976202-0c209d39-9d50-49f1-80c6-e9a81ddb3555.png)

![Screenshot (17)](https://user-images.githubusercontent.com/130983319/232976238-bcf63108-49c1-4787-88d0-1d5e7d020117.png)
![Screenshot (18)](https://user-images.githubusercontent.com/130983319/232976250-176f15fb-bdb0-4a6a-8885-cc838c016ec2.png)

**Comment by Desvelao** [comment]
Hi @aravindcyberfort ,

By your last message (https://github.com/wazuh/wazuh-kibana-app/issues/5378#issuecomment-1514156986), I understand you are sending the MariaDB logs through remote syslog and you configurated the Wazuh manager to allow receivign logs from the MariaDB server.

My doubt is that you have configurated a log file for MariaDB located at `/var/log/mysql/mariadb-audit.log`.

I see you had some events saved in the `archives.json` file whose `location` is related to this file in the screenshot:
![image](https://user-images.githubusercontent.com/34042064/233021144-d558956d-d915-4875-9c2f-099a75a7dc74.png)
This makes me think that you configurated the Wazuh agent to collect the logs of this file and not use the remote syslog.

For another hand, I see when you tried to use the `wazuh-logtest` the `location` is an IP address:
![image](https://user-images.githubusercontent.com/34042064/233020125-c1cea290-da15-4405-a7bb-4ac9fadf8c13.png)
So I guess you could have used it through remote syslog.

Could you clarify the method you are using to ingest the logs?

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 
Apart from the above chaos,
How to index Mariadb DML and DDL command logs from Mariadb server to wazuh dashboard?

**Comment by aravindcyberfort** [comment]
Hi @Desvelao 
![2023-04-19_15-06](https://user-images.githubusercontent.com/130983319/233040428-a9fe0cc6-d5e4-4cb4-9893-c5000cb3a8bd.png)
![2023-04-19_15-14](https://user-images.githubusercontent.com/130983319/233040474-b033899b-d9ce-47f0-8c18-82f0fa67e6f7.png)

![2023-04-19_15-16](https://user-images.githubusercontent.com/130983319/233040579-e82dfaeb-5402-47b5-8627-6c42c3af364e.png)
![2023-04-19_15-18](https://user-images.githubusercontent.com/130983319/233040628-22a8b08f-5123-4b08-bd8f-04953258eb35.png)


Here I created a Database in my mariadb server  and it's log is reflected in wazuh server at /var/ossec/logs/archives/archives.json but it's not showing up im /var/ossec/logs/alerts/alerts.json
Only the logs at /var/ossec/logs/alerts/alerts.json is indexed to wazuh dashboard.
The DML and DDl commands like CREATE, DROP, SHOW commands log are coming to /var/ossec/logs/archives/archives.json but not to /var/ossec/logs/alerts/alerts.json so the DML DDL logs are not indexing to wazuh dashboard.
but the mariadb login failed logs is indexed.

![2023-04-19_15-36](https://user-images.githubusercontent.com/130983319/233042304-bc767fbc-573e-4eb7-9fe7-4bcef4213297.png)

**Comment by Desvelao** [comment]
Hi @aravindcyberfort ,

Thank you for the information.

# Regarding your last comment

You pointed 2 actions that are logged into the `archives.json` file.

## Action: user executes the command to create a new database in MariaDB

The collected log of the action of creating a new database is not matching with any Wazuh rule. This means, if you want to get a Wazuh alert, then you have to create a rule that matches this type of log.

Log:
```
20230419 14:55:04\t    33 Query\tCreate DATABASE Desvelao
```

![image](https://user-images.githubusercontent.com/34042064/233275938-e451075b-9cac-4374-b84c-701b851aad47.png)

## Action: failed login to MariaDB

The action of failed login to the MariaDB, generates a log that matches with a generic rule. This rule has an ID `1002`. If you see the `full_log` property, you can see the log content. If you see the definition for the matching rule (rule ID 1002) for 4.4.1 https://github.com/wazuh/wazuh/blob/v4.4.1/ruleset/rules/0020-syslog_rules.xml#L25-L29

```xml
<var name="BAD_WORDS">core_dumped|failure|error|attack| bad |illegal |denied|refused|unauthorized|fatal|failed|Segmentation Fault|Corrupted</var>

  <rule id="1002" level="2">
    <match>$BAD_WORDS</match>
    <description>Unknown problem somewhere in the system.</description>
    <group>gpg13_4.3,</group>
  </rule>
```
The rule ID 1002 has the next conditions to match:
- `match`: that uses the variable `BAD_WORDS`. If the log matches with the regular expression of the `match` statement, then this condition will be fulfilled. In this case, the log is matching the `failed` (case insensitive) word that is included in the `BAD_WORDS` variable.

I tried the log:
```
20230419 15:09:04,ubuntu-mariadb,root-Desvelao,localhost,34,0,FAILED_CONNECT,,,1698
```
using the Ruleset Test feature that under the hoods runs the `wazuh-logtest` tool of the Wazuh manager and the log matches the rule ID 1002 as your case.
![image](https://user-images.githubusercontent.com/34042064/233108120-ed3a73b3-02bc-45c3-ac2f-e1ab1734602a.png)

References:
- https://documentation.wazuh.com/4.4/user-manual/ruleset/ruleset-xml-syntax/rules.html#match
- https://documentation.wazuh.com/4.4/user-manual/ruleset/ruleset-xml-syntax/rules.html#bad-words

To summarize, the action of failed login in the MariaDB is matching a generic rule. If the matched rule level is equal or higher to the minimum level, then it generates a Wazuh alert. I guess you modified the minimum level to allow the alert with level 2 can be generated, because the matched rule that you can see in the Wazuh dashboard/Kibana has level 2 and the minimum level by default is 3. If the alert is generated (event matches a rule and the rule level is equal or higher to the minimum level) this will be saved in the `/var/ossec/etc/logs/alerts/alerts.json`. As result and thank Filebeat, this is indexed to Wazuh indexer/Elasticsearch and you can see it in the Wazuh dashboard/Kibana.

But this could not be what you want. The log is coming from MariaDB application, so it will be more interesting if the matched rule is more specific to this application or related to the failed login in MariaDB if you want to be more specific. In the case the default ruleset doesn't have a rule for your use case, then you should create a specific rule that matches the type of log that indicates the circumstance you want to be alerted.

# Research

I was researching the default decoders related to MariaDB included in Wazuh 4.4.1 (the version you are using).

There is a pair of decoders related to MariaDB logs whose log format is expected to be syslog.
https://github.com/wazuh/wazuh/blob/v4.4.1/ruleset/decoders/0378-mariadb_decoders.xml#L19-L30
These decoders are decoding logs as:
```
May 24 11:51:30 mysql09a mysql-server_auditing:  mysql09a.local,ahc_shwb01_t,ahc-web29d.local,849705,0,DISCONNECT,ahc_shwb01_t,,0
```

This pair of decoders are expecting the log has syslog format and the program name contains the `mysql` word. This could be the reason because you could be getting alerts from mysql and not from MariaDB. This depends on the log coming from MariaDB has the `mysql` word or not in the program name of the log.

And there are other decoders related to when the log is file: https://github.com/wazuh/wazuh/blob/v4.4.1/ruleset/decoders/0378-mariadb_decoders.xml#L32-L71

The default MariaDB decoders are not matching with the logs you are getting.

I was reading about MariaDB logging and from your previous comments, I think you are using the `audit_plugin` https://mariadb.com/kb/en/mariadb-audit-plugin/.

The documentation of MariaDB `audit_plugin` has a section related to the log format:
https://mariadb.com/kb/en/mariadb-audit-plugin-log-format/

The MariaDB audit plugin logs can be configurated with the next outputs:
- `file`: send the log to a file (configurable) with the next format:
```
[timestamp],[serverhost],[username],[host],[connectionid],
[queryid],[operation],[database],[object],[retcode]
```
- `syslog`: send the log to syslogd using the format:
```
[timestamp][syslog_host][syslog_ident]:[syslog_info][serverhost],[username],[host],
[connectionid],[queryid],[operation],[database],[object],[retcode]
```

Depending on the configurated output, the content of the log is different. If you want to get a Wazuh alert, then you should ensure that the log that is analyzed (received) by Wazuh matches a Wazuh rule and the rule level is equal to or higher than the minimum alert level.

**Comment by Desvelao** [comment]
## Integrating your use case log

First, you should decide what the output of MariaDB audit plugin logs is: `file` or `syslog`. Depending on the selected output and according to the MariaDB audit plugin log format documentation, the log content is different. Once you know the format of log, you could build a decoder that allows extracting data from the log.

### Example

Suppose you configure the MariaDB audit plugin output to `syslog` and send the logs through rsyslog from MariaDB server to the Wazuh manager. I see you could have done this when you received this log:
![image](https://user-images.githubusercontent.com/34042064/233020125-c1cea290-da15-4405-a7bb-4ac9fadf8c13.png)

Example of received log according to the mentioned configuration:
```
Apr 19 18:04:04 ubuntu-mariadb mariadb[181]: 20230419 15:09:04,ubuntu-mariadb,root-Desvelao,localhost,34,0,FAILED_CONNECT,,,1698
```

We could build the following decoders to extract data from the log:

```xml
<decoder name="custom-mariadb-syslog">
    <program_name>mariadb</program_name>
</decoder>

<decoder name="custom-mariadb-syslog-fields">
    <parent>custom-mariadb-syslog</parent>
    <regex> (\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*)</regex>
    <order>mariadb.info,mariadb.server_host,mariadb.username,mariadb.host,mariadb.connectionid,mariadb.queryid,mariadb.operation,mariadb.database,mariadb.object,mariadb.retcode</order>
</decoder>
```

Explanation:

```xml
<decoder name="custom-mariadb-syslog">
    <program_name>mariadb</program_name>
</decoder>
```

This decoder is used in the pre-decoding phase. If the log is in a valid syslog format, then in our example log:
```
Apr 19 18:04:04 ubuntu-mariadb mariadb[181]: 20230419 15:09:04,ubuntu-mariadb,root-Desvelao,localhost,34,0,FAILED_CONNECT,,,1698
```
the `mariadb` word before the `[181] is the application or program name. This can be matched through the `program_name` decoder option: https://documentation.wazuh.com/4.4/user-manual/ruleset/ruleset-xml-syntax/decoders.html#program-name.

```xml
<decoder name="custom-mariadb-syslog-fields">
    <parent>custom-mariadb-syslog</parent>
    <regex> (\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*)</regex>
    <order>mariadb.info,mariadb.server_host,mariadb.username,mariadb.host,mariadb.connectionid,mariadb.queryid,mariadb.operation,mariadb.database,mariadb.object,mariadb.retcode</order>
</decoder>
```

Then, we define another decoder that is a child of the previous decoder. This means this decoder will be used if the parent decoder matches the log.

This decoder extracts some data of the log using the `regex` option (https://documentation.wazuh.com/4.4/user-manual/ruleset/ruleset-xml-syntax/decoders.html#regex-decoders) and the `order` https://documentation.wazuh.com/4.4/user-manual/ruleset/ruleset-xml-syntax/decoders.html#order that defines the field names of the extracted data.

We add both custom decoders to the `local_decoders.xml` file or you can create a new decoder file. You can do it through the Wazuh plugin for Wazuh dashboard or Kibana, or by modifying/adding the custom decoder file in the Wazuh manager.

```
<decoder name="custom-mariadb-syslog">
    <program_name>mariadb</program_name>
</decoder>

<decoder name="custom-mariadb-syslog-fields">
    <parent>custom-mariadb-syslog</parent>
    <regex> (\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*),(\.*)</regex>
    <order>mariadb.info,mariadb.server_host,mariadb.username,mariadb.host,mariadb.connectionid,mariadb.queryid,mariadb.operation,mariadb.database,mariadb.object,mariadb.retcode</order>
</decoder>
```

![image](https://user-images.githubusercontent.com/34042064/233289816-0faeb4c8-3ee5-40f3-8616-cebd692819c2.png)

After adding the custom decoders, restart the Wazuh manager to the changes take effect.

Then, we create a custom rule that matches the log. We add to the `local_rules.xml` file or a new custom rule file through the Wazuh plugin for Wazuh dashboard/Kibana or editing/creating a custom rule file in the Wazuh manager.

```xml
<group name="mariadb,">
  <rule id="100100" level="3">
    <decoded_as>custom-mariadb-syslog</decoded_as>
    <description>MariaDB group messages.</description>
  </rule>
</group>
```

Explanation:

We create a new custom rule whose ID is 100100, the rule level is 3 and the log was decoded using out custom MariaDB syslog decoder called `custom-mariadb-syslog`. We add a rule description through the `description` option. If the rule level is equal or higher to the minimum alert level, then the alert will be generated, you should take this in account.

![image](https://user-images.githubusercontent.com/34042064/233291092-041fa830-d366-4b63-b8dc-7f104e13c5d8.png)

After adding the new custom rule, restart the Wazuh manager.

Then, once we created the custom decoders and custom rule, we can test if they are working and check if an alert is generated for the related log. To do this, you can use the `Ruleset Test` tool of the Wazuh plugin or the `wazuh-logtest` tool of the Wazuh manager.

For my case, I used the `Ruleset Test` tool of the Wazuh plugin.
![image](https://user-images.githubusercontent.com/34042064/233293162-24f456d8-ec92-48d1-a724-a54f57696f5d.png)

As you can see in the screenshot:
I tested the example log.

In the pre-decoding phase, the `program_name` is `mariadb` that matches with the `program_name` we specified in one of the custom decoders we added.

In the decoding phase, you can see the extracted data fields from the log.

In the rule matching phase, you can see the log matches with the custom rule we added.

And finally a message inform us, that the alert will be generated, it is because the log matches a rule and the rule level is equal or higher to the minimum alert level.

**Comment by Desvelao** [comment]
I will close this issue due to inactivity.
