### ISSUE TITLE
Invalid XML config generation

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#5617]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.x   | 7.x     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**

Under Agents -> Agent -> Configuration we can set up different agent configuration options, and generate an XML portion of the agent configuration. But the generated XML is not valid for an agent, because the xml labels are generated with invalid names.

![image](https://github.com/wazuh/wazuh-kibana-app/assets/2181918/b1f4a471-9f05-4587-b0eb-4882e94c1b59)

We need to fix the generated XML, so it is a valid agent configuration.

**Comment by jbiset** [comment]
# Research

When parsing the JSON obtained from the request to retrieve the active agent configuration, some tags are not generated correctly according to the documentation.
This problem can arise because the JSON format needs some modifications to be compatible with XML parsing, taking into account the specifications described in the documentation.
The JSON response is parsed using the [js2xmlparser](https://www.npmjs.com/package/js2xmlparser) library.

## ASSOCIATED DOCUMENTATION
- https://documentation.wazuh.com/4.4/user-manual/reference/ossec-conf/localfile.html#query
- https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/index.html


## JSON RESPONSE
To confirm whether it is not an issue with the imposter, it checks that its response is not different from the non-imposter version.
Although the imposter's response is not as comprehensive as the real response, it can be corroborated that it follows the same format as the real response.

<details>

- Agent log-collector payload
![agent-config_log-collector_payload](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/c70a7950-9f82-4d11-8318-d23e3a182141)


- Agent log-collector response
![agent-config_log-collector_response](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/078b638e-f32b-4c5a-b432-df800fdfc668)


- Agent log-collector payload imposter
![agent-config_log-collector_payload_imposter](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/9f911596-f422-470d-95e7-f90a908d5d1a)


- Agent log-collector response imposter
![agent-config_log-collector_response_imposter](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/014db36f-a0cc-4df4-8f94-ab37311a57c5)


</details>

## ANALYSIS
Based on the above, conflicts have been found with the 'logformat' and 'query' tags.

### log_format
In XML, the tag is expected to be displayed as `log_format`, but it appears as `logformat` This issue would be resolved if the response came with the name `log_format`.

<details>

- Snippet of the JSON response
```
{
    "logformat": "command",
    "command": "df -P",
    "alias": "df -P",
    "ignore_binaries": "no",
    "target": [
        "agent"
    ],
    "frequency": 360
}
```

- Snippet of the current  result
```
<localfile>
    <logformat>command</logformat>
    <command>df -P</command>
    <alias>df -P</alias>
    <ignore_binaries>no</ignore_binaries>
    <target>agent</target>
    <frequency>360</frequency>
</localfile>
```


- Expected result
```
<localfile>
    <log_format>command</log_format>
    <command>df -P</command>
    <alias>df -P</alias>
    <ignore_binaries>no</ignore_binaries>
    <target>agent</target>
    <frequency>360</frequency>
</localfile>
```

</details>

### query
According to the documentation specification, the `query` tag should not contain a `value` tag. However, it can have `type` and `level` as attributes.

<details>

![JSON_response_parse-to_XML](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/3c19a3f6-3228-4099-89a2-8b8ed8ef4569)

</details>

**NOTE:** _Investigation continues with respect to the rest of the labels._

**Comment by jbiset** [comment]
Consulting with Framework-team and Core in thread: https://wazuh-team.slack.com/archives/C038AR25C8N/p1688989534242789

**Comment by jbiset** [comment]
# Improvement proposal to redefine the JSON structure of the Log Collector and FIM (Log data analysis)


## ALTERNATIVE 1 - Recommended
This alternative would not imply a pre-processing of the JSON for the XMLParser, generating an automated solution in case the attributes or the structure change at any time. Although it generates coupling to the library used for the XMLParser.
This alternative is based on the documentation of [js2xmlparser](https://www.npmjs.com/package/js2xmlparser) library.

### QUERY label

#### Snippet of the current JSON response

```
{
    "channel": "Security",
    "logformat": "eventchannel",
    "query": {
        "value": "Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and\n      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and\n      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and\n      EventID != 5152 and EventID != 5157]"
    },
    "ignore_binaries": "no",
    "only-future-events": "yes",
    "target": [
        "agent"
    ],
    "reconnect_time": 5
}
```

#### Possible response case solution

- Windows case
```
{
    "channel": "Security",
    "log_format": "eventchannel",
    "query": "Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and\n      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and\n      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and\n      EventID != 5152 and EventID != 5157]",
    "ignore_binaries": "no",
    "only-future-events": "yes",
    "target": [
        "agent"
    ],
    "reconnect_time": 5
}
```

- macOS case
```
{
    "location": "macos",
    "log_format": "macos",
    "query":  {
        "@1": {
            "type": "log,trace"
        },
        "@2":{
            "level": "debug"
        },
        "#": "process == \"sshd\" OR message CONTAINS \"invalid\""
    }
}
```

### DIRECTORIES label

#### Snippet of the possible current JSON response

```
{
    "directories": [
        {
            "opts": [
                "check_md5sum",
                "check_sha1sum",
                "check_perm",
                "check_size",
                "check_owner",
                "check_group",
                "check_mtime",
                "check_inode",
                "check_sha256sum"
            ],
            "dir": "/bin",
            "recursion_level": 256,
            "diff_size_limit": 51200
        },
        {
            "opts": [
              "check_md5sum",
              "check_sha1sum",
              "check_perm",
              "check_size",
              "check_owner",
              "check_group",
              "check_mtime",
              "check_inode",
              "check_sha256sum"
            ],
            "dir": "/other_dir",
            "recursion_level": 0,
            "diff_size_limit": 51200
        }
    ]
}
```

#### XML Current result
```
<directories>
    <opts>check_md5sum</opts>
    <opts>check_sha1sum</opts>
    <opts>check_perm</opts>
    <opts>check_size</opts>
    <opts>check_owner</opts>
    <opts>check_group</opts>
    <opts>check_mtime</opts>
    <opts>check_inode</opts>
    <opts>check_sha256sum</opts>
    <dir>/bin</dir>
    <recursion_level>256</recursion_level>
    <diff_size_limit>51200</diff_size_limit>
</directories>
<directories>
    <opts>check_md5sum</opts>
    <opts>check_sha1sum</opts>
    <opts>check_perm</opts>
    <opts>check_size</opts>
    <opts>check_owner</opts>
    <opts>check_group</opts>
    <opts>check_mtime</opts>
    <opts>check_inode</opts>
    <opts>check_sha256sum</opts>
    <dir>/other_dir</dir>
    <recursion_level>0</recursion_level>
    <diff_size_limit>51200</diff_size_limit>
</directories>
```

#### XML Expected result
```
<directories check_md5sum="yes" check_sha1sum="yes" check_perm="yes" check_size="yes" check_owner="yes" check_group="yes" check_mtime="yes" check_inode="yes" check_sha256sum="yes" recursion_level="256" diff_size_limit="51200">
    /bin
</directories>
<directories check_md5sum="yes" check_sha1sum="yes" check_perm="yes" check_size="yes" check_owner="yes" check_group="yes" check_mtime="yes" check_inode="yes" check_sha256sum="yes" recursion_level="0" diff_size_limit="51200">
    /other_dir
</directories>
```

#### Possible response case solution

- General case
```
{
    "directories": [
        {
            "@1": {
                "check_md5sum": "yes"
            },
            "@2": {
                "check_sha1sum": "yes"
            },
            "@3": {
                "check_perm": "yes"
            },
            "@4": {
                "check_size": "yes"
            },
            "@5": {
                "check_owner": "yes"
            },
            "@6": {
                "check_group": "yes"
            },
            "@7": {
                "check_mtime": "yes"
            },
            "@8": {
                "check_inode": "yes"
            },
            "@9": {
                "check_sha256sum": "yes"
            },
            "@10": {
                "recursion_level": "256"
            },
            "@11": {
                "diff_size_limit": "51200"
            },
            "#": "/bin"
        },
        {
            "@1": {
                "check_md5sum": "yes"
            },
            "@2": {
                "check_sha1sum": "yes"
            },
            "@3": {
                "check_perm": "yes"
            },
            "@4": {
                "check_size": "yes"
            },
            "@5": {
                "check_owner": "yes"
            },
            "@6": {
                "check_group": "yes"
            },
            "@7": {
                "check_mtime": "yes"
            },
            "@8": {
                "check_inode": "yes"
            },
            "@9": {
                "check_sha256sum": "yes"
            },
            "@10": {
                "recursion_level": "0"
            },
            "@11": {
                "diff_size_limit": "51200"
            },
            "#": "/other_dir"
        }
    ]
}
```


## ALTERNATIVE 2
This alternative implies a pre-processing of the JSON before the XMLParser. This leads to support tasks in case the attributes or the structure change at any time; but decreases the coupling to the library used for the XMLParser.

### QUERY label

- Windows case - No changes with Alternative 1

```
{
    "channel": "Security",
    "log_format": "eventchannel",
    "query": "Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and\n      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and\n      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and\n      EventID != 5152 and EventID != 5157]",
    "ignore_binaries": "no",
    "only-future-events": "yes",
    "target": [
        "agent"
    ],
    "reconnect_time": 5
}
```

- macOS case


```
{
"_attributes": {
  "type": "log,trace",
  "level": "debug"
},
"_content": "Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and\n      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and\n      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and\n      EventID != 5152 and EventID != 5157]",
}
```


### DIRECTORIES label

#### Possible response case solution

```
{
    "directories":[
        {
            "_attributes": {
                "check_md5sum": "yes",
                "check_sha1sum": "yes",
                "check_perm": "yes",
                "check_size": "yes",
                "check_owner": "yes",
                "check_group": "yes",
                "check_mtime": "yes",
                "check_inode": "yes",
                "check_sha256sum": "yes",
                "recursion_level": "256",
                "diff_size_limit": "51200"
            },
            "_content": "/bin"
        },
        {
            "_attributes": {
                "check_md5sum": "yes",
                "check_sha1sum": "yes",
                "check_perm": "yes",
                "check_size": "yes",
                "check_owner": "yes",
                "check_group": "yes",
                "check_mtime": "yes",
                "check_inode": "yes",
                "check_sha256sum": "yes",
                "recursion_level": "0",
                "diff_size_limit": "51200"
            },
            "_content": "/other_dir"
        }
    ]
}
```

**Comment by jbiset** [comment]
# Decided solution

We have decided to remove the display of the JSON and XML formats of the Management configurations in the modal that appears when one of the configurations is selected, for example, Log Collection. This is decided based on the fact that they are features that do not present use cases and, in particular, the XML format generates an invalid XML configuration.
Since this is a functionality provided through the HOC pattern, the best solution is to remove the corresponding tabs and views, leaving only the default one and access to the corresponding help links.

## EXAMPLES SCREEN - LOG COLLECTION

### :red_circle:  DEFAULT SCREEN WITH TABS (SETTINGS, JSON, XML)
![Example_Screen_1](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/781564f9-e744-40f6-bd77-42f616f86e3c)

### :red_circle:  JSON SCREEN WITH TABS
![Example_Screen_2](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/d3ca7fe7-d5f1-4819-b327-9887b6668bf9)

### :red_circle:  XML SCREEN WITH TABS
![Example_Screen_3](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/fdc93158-d920-4d9f-bfb3-0b69d09f4b5b)

### :green_circle: DEFAULT SCREEN WITHOUT TABS
![Example_Screen_Resolved](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/c3be376e-68f6-43b5-87eb-e22b5f8e59f0)

Thus, the current documentation was also reviewed in search of references to the visualization features in the JSON and XML formats, especially, in the links that are proposed as help:
- https://documentation.wazuh.com/4.4/user-manual/capabilities/log-data-collection/index.html
- https://documentation.wazuh.com/4.4/user-manual/reference/ossec-conf/localfile.html
No references or images of these features have been found.

Given this decision, the Core team is also notified that the Issue created no longer has an effect. Reference to it is left below.
- https://github.com/wazuh/wazuh/issues/17891
