### ISSUE TITLE
Wrong order of values

### ISSUE THREAD

**Issue by ByteAndBits** [wazuh/wazuh-kibana-app#5621]
Hi,

the order of values from data fields are not correct.

Example.
1
11
111
2
22
222

It should:
1
2
11
22
111
222

Also filters with range doesn´t work.

{
  "query": {
    "range": {
      "data.field": {
        "gte": 1,
        "lte": 3,
      }
    }
  }
}

show all values between 1 and 399.

**Comment by Desvelao** [comment]
Hi @ByteAndBits,

regarding your message:

>
>

> Hi,
> 
> the order of values from data fields are not correct.
> 
> Example. 1 11 111 2 22 222
> 
> It should: 1 2 11 22 111 222

Could you indicate where it is happening? If this is related to data indexed in Wazuh indexer or Elasticsearch, maybe the problem is related to the field mapping type as explained below.
 
> Also filters with range doesn´t work.
> 
> { "query": { "range": { "data.field": { "gte": 1, "lte": 3, } } } }
> 
> show all values between 1 and 399.

This could be caused because the field mapping for `data.field` field is a `keyword` instead of a number (`long`, `integer`, `short`, etc...). If the field mapping is a `keyword` then the value is managed as a string instead of a number. In this case, it makes sense you get those values as a response.

You can check the `data.field` field mapping type doing the following request to Wazuh indexer or Elasticsearch:
```
GET <INDEX_NAME_OR_INDEX_PATTERN>/_mapping/field/<FIELD>
```
where:
- `<INDEX_NAME_OR_INDEX_PATTERN>` is an index or index pattern.
Examples:
index name: `wazuh-alerts-4.x-2023.06.29`
index pattern: `wazuh-alerts*`

Example:
```
GET wazuh-alerts*/_mapping/field/data.field
```

For example, the `rule.id` field mapping is defined as `keyword`.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/bd4fc05b-fa09-492e-ab5b-4c910c541038)

If I do a `range` query similar to the provided one:

```
GET wazuh-alerts*/_search?size=500
{
  "query": {
    "range": {
      "rule.id": {
      "gte": 1,
      "lte": 3
      }
    }
  },
  "_source": "rule.id"
}
```

I get values starting with the chracters: `1`, `2` or `3` as `1496` or `2626`.

Screenshot:
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/f5ad1ee7-228b-4056-a3e6-e2b0538b2956)

For another hand, if I use the same query in a field (`rule.level`) whose mapping type is a `long` (number)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/9815c38a-6248-469c-bf65-2d4496439571)

```
GET wazuh-alerts*/_search?size=500
{
  "query": {
    "range": {
      "rule.level": {
      "gte": 1,
      "lte": 3
      }
    }
  },
  "_source": "rule.level"
}
```

I get the values you are expecting to, between `1` and `3` due to the defined range query.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/4d24964d-3238-4e78-8ac1-07615e178d90)

References:
- Range query: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-range-query.html
- Keyword field type: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/keyword.html
- Number field type: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/number.html

**Comment by ByteAndBits** [comment]
Hi,

that´s it. Field type is "keyword" and not "integer".

How can I change the field type? If I use the pencil next to the type, the field is greyed out.

**Comment by Desvelao** [comment]
Hi @ByteAndBits,

The field mapping type is set for each index.

I assume the field you are mentioning is related to a Wazuh alert. This alert is indexed to indices called `wazuh-alerts-4.x-YYYY.MM.DD` where `YYYY` is the year, `MM` is the month and `DD` is the day.

In the configuration of Wazuh, a template called `wazuh` is indexed to Wazuh indexer. This template defines the settings and some field mapping types for indices whose name matches the index patterns: `wazuh-alerts-4.x-*` and `wazuh-archives-4.x-*`. When a new index is created and its name matches some of these index patterns, then the index is created with the defined settings and field mapping types of the template.

You can see the indexed `wazuh` template through this request:
```
GET /_template/wazuh
```
> You can use the Wazuh dashboard Dev Tools plugin to do the request

![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/240e2b1a-52cf-4348-b967-8c074660f15d)

You should check if there is a defined mapping type for the field you want to change.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/a22f7275-d8e9-485f-b7b5-69243ddd882c)

:warning: Before you proceed, you should know that some fields are used in the visualizations displayed in the Wazuh plugin for Wazuh dashboard. Changing the mapping type of these fields could cause problems when trying to see the visualizations that use that field. There are so many fields that are not used in the visualizations, and this could be the case for the specific `data.<FIELD>` you are referring to.

There are 2 possibilities, regarding the template:
- the mapping type **is defined** for the field
- the mapping type **is not defined** for the field

## Field mapping type is defined in the template

1. Change in the `wazuh` template the mapping type for the field to something that matches your requirements (numbers: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/number.html). You can do this through:
- Edit the static file that is hosted in each Wazuh server host located at `/etc/filebeat/wazuh-template.json`. If you edit this file, after saving it you need to run:
```
filebeat setup --index-management
```
> Important: Do this in each Wazuh server host
- Wazuh indexer API: review this documentation that should apply https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-templates-v1.html

2. Check the mapping type for the field changed in the indexed template.
Use the Dev Tools plugin of Wazuh dashboard to do the request:
```
GET /_template/wazuh
```

These changes in the template will be reflected in the new indices that match the index patterns of `wazuh-alerts-4.x-*` and `wazuh-archives-4.x-*`. This means the change doesn't apply to the existent indices.

3. Due to if the mapping type is already defined for an index this can not be changed, you will need to create new indices where you will store the data of the existent related indices. This process can be done through reindexing the data.

Reindex a index:
```
POST _reindex
{
  "source": {
    "index": "SOURCE_INDEX",
  },
  "dest": {
    "index": "DESTINATION_INDEX",
  }
}
```
where:
- `SOURCE_INDEX` is the name of the existent index that has wrong the mapping type for the field
- `DESTINATION_INDEX` is the name of the index where the data will be indexed. You should ensure this index doesn't exist and matches the index pattern names of the template.

For example, let us suppose that you need to reindex an index called `wazuh-alerts-4.x-2023.06.29` because this has the worng mapping type you want to change.
```
POST _reindex
{
  "source": {
    "index": "wazuh-alerts-4.x-2023.06.29",
  },
  "dest": {
    "index": "wazuh-alerts-4.x-2023.06.29-fixed",
  }
}
```
> Note the destination index matches the index patterns of the `wazuh` template which are `wazuh-alerts-4.x-*` and `wazuh-archives-4.x-*`

After reindexing, you could check the mapping type for the field in the new index changed:
```
GET wazuh-alerts-4.x-2023.06.29-fixed/_mapping/field/<FIELD>
```
where:
- `<FIELD>` is the field you changed the mapping type

4. One time you reindexed the existent index and the data was copied to the destination index, you could remove the original index:
```
DELETE <INDEX_NAME>
```

In the example:
```
DELETE wazuh-alerts-4.x-2023.06.29
```

Important: you need to do this in each index that has defined the wrong mapping type for the field.

*Optional: if you want the index name with the expected mapping type for the field to have the original name (`wazuh-alerts-4.x-2023.06.29`), then you could reindex from the `fixed` index (`wazuh-alerts-4.x-2023.06.29-fixed`) to the original index name (`wazuh-alerts-4.x-2023.06.29`) but this index doesn't exist previously to the reindex process.*

## Field mapping type is not defined in the template

If the mapping type for the field is not defined, then you could define the mapping type in the template (step 1). After the indexed template has the addition of a new mapping type, this only applies to the new indices, not to the existing ones. If you have existent indices with the wrong mapping type for the field, you need to follow the instructions to reindex the data as I explained above (steps 2, 3, 4).

## Update fields for index pattern

After you fix the mapping type for the field in all the affected indices and removed the original indices that were reindexed, you need to update the fields for the index pattern.

In wazh dashboard, go to `Stack management` > `Index patterns`, selects the related index pattern that could be called `wazuh-alerts-*` and click on the refresh button.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/e3843570-92d3-490d-b5cb-04fa4ac2d641)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/3e973137-53b9-4a8e-939f-1bce0bebb291)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/c067a8c3-1f60-4f79-87dd-f6b7e4d11285)
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/bf5bd67d-5525-430d-a1c2-e832274fb54b)

**Comment by ByteAndBits** [comment]
Hi,

perfect howto! 

Thank´s a lot.
