### ISSUE TITLE
Compatibility with Elastic v8.7.0

### ISSUE THREAD

**Issue by pandamasta** [wazuh/wazuh-kibana-app#5737]
## Description

Hello we are running Elastic v8.7.0
But according to the downloading page you only support:

Wazuh v4.4.5 - Kibana 7.10.2, 7.16.x, 7.17.[0-9] - Revision 02

Do you forseen to support Elastic v8.7 or upper soon ?

Thanks for your feedbacks and all your hard work :)

For that, we need to:

- [ ] Review opensearch and opensearch-dashboard latest stable changelog. 
- [ ] Identify improvements and potential impact on the UI.
- [ ] Develop a testing environment to verify our components would work under this new build.

**Comment by gdiazlo** [comment]
We will support Elastic version 8 and up though integrations, instead of with a plugin. This will allow users to use the latest tech from Elastic, Splunk, and others without waiting for Wazuh to release a plugin. 

The strategy will be based on sending the events from Wazuh to these 3rd party platforms and then create dashboards natively on each platform. Wazuh will provide a set of pre-created dashboards.

The tradeoff is that the Wazuh management will require a Wazuh indexer/dashboard deployment.
