### ISSUE TITLE
Data filter not saved when creating monitors for Alerting in OpenSearch Plugins

### ISSUE THREAD

**Issue by ace-109** [wazuh/wazuh-kibana-app#5956]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | Beta 1 | Chrome |

**Description**
During testing of [19149](https://github.com/wazuh/wazuh/issues/19149), some issues were encountered while using the Wazuh dashboard. The data filter does not save selected filters.

**Preconditions**
1. Wazuh 4.6.0 OVA

**Steps to reproduce**
1. Navigate to `OpenSearch Plugins`
2. Click on `Alerting`
3. Select `Monitors`, `Create monitor`
4. Assign a monitor name
5. Scroll down to `Data source`
6. Select an `Index` and use `Timestamp` as `Time field`
7. Scroll down to `Query`, under `Data filter - optional` 
8. Add a filter with any of the options

**Expected Result**
The filter is should be saved

**Actual Result**
The filter disappears from the UI after selecting. 

**Screenshots**
![FIlter not wokring 2](https://github.com/wazuh/wazuh-kibana-app/assets/41423652/0707f39e-1b13-45e6-a323-ce597219c1e4)

**Comment by AlexRuiz7** [comment]
I could replicate the issue and had these messaged in the browser's console:

`unknown query operator detected`

![image](https://github.com/wazuh/wazuh-kibana-app/assets/15186973/784802ca-0799-4972-aa4f-04effb006526)

Nothing we can do here but to [report the issue](https://github.com/opensearch-project/alerting-dashboards-plugin/issues) to OpenSearch. I already checked and this one hasn't been reported.

- Replicated in 2.8.0
- **Could not replicate in 2.10.0. It's fixed in this version.**

We are using OpenSearch 2.10.0 in 4.8.0, so this will be fixed by then.

**Comment by AlexRuiz7** [comment]
Triaged. Issue is not blocked by management.

**Comment by gdiazlo** [comment]
I'm closing this as it will be fixed in 4.8.0
