### ISSUE TITLE
Fix new Kibana 6.3.0 autocomplete functionality on the app

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-kibana-app#643]
Kibana 6.3.0 introduced a new Kuery syntax search bar with autocomplete feature. We have to fix it to be fully compatible with the app.

We'll hide the option for the moment because although it's working on the Discover sub-tab, it doesn't work on the Panels subtab.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Temporary fixed in https://github.com/wazuh/wazuh-kibana-app/pull/644/commits/0a53d4087802a8d256d26aba336c0e3d222d606b just hidding it. The main problem here comes from a hardcoded piece of code at `kbn-vis` directive as you can see here:

```js
.query({ language: 'lucene', query: implicitFilter })
```

Since Kibana adds Kuery support in the search bar when auto-complete is activated, we need to review what's happening when using Kuery instead Lucene in our visualizations and if the whole app has consistency using Kuery syntax.

Regards,
Jesús

**Comment by jesusgn90** [comment]
After some researching work, this issue is included in #654, so we are going to close this one. You could track #654 to stay updated.

Regards,
Jesús
