### ISSUE TITLE
wazuh Kibana App view bug !!!

### ISSUE THREAD

**Issue by myh0st** [wazuh/wazuh-kibana-app#697]
es 6.2.4 + kibana 6.2.4 + wazuh api 3.3.1 + wazuh app 3.3.1 

Agent name is participle：

![1](https://user-images.githubusercontent.com/26624320/42549125-2cebc132-84fd-11e8-856d-308d90803382.png)

Other cases：

![2](https://user-images.githubusercontent.com/26624320/42549182-87785d36-84fd-11e8-88bc-c932f57c2efa.png)

can you help me ?

**Comment by jesusgn90** [comment]
Hi @myh0st ,

I've just tried to reproduce your situation and I can't reproduce it:

![test-01](https://user-images.githubusercontent.com/8860227/42557111-e110e0d0-84ed-11e8-8b98-d957f21cb434.png)

As you can see, I've used similar agent names in order to be equal to your situation.

Which exactly view (E.g: Overview > General) is giving you that result?

One more question, could you verify if you've inserted the Elasticsearch template?

```
# curl elastic_ip:9200/_cat/templates/wazuh
```

Regards,
Jesús

**Comment by myh0st** [comment]
Thank you for your help, the problem is solved. You are awesome, haha ！
