### ISSUE TITLE
ASCII Sort for Column "Rule ID" in Table "Alerts summary" in "Overview/Security events" Tab

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh-kibana-app#962]
Hello,

### Steps to Reproduce
1. Open the _Overview / Security events_ tab in Kibana
1. go down to the graph  _Alerts / summary_ on the left bottom
1. first column from the left _Rule ID_, press the arrow for sort in ascending or descending order
1. you'll notice the sorting of _rule id's_ is in ASCII sort and not in numerical order, see example here:

Rule ID | Description | Level | Count
-- | -- | -- | --
1010 | Process segfaulted. | 5 | 6
110010 | Windows: Administrators Group Changed on host | 3 | 104
110011 | Windows: Security Enabled Local Group Changed on host | 3 | 91
18103 | Windows error event. | 5 | 30
18107 | Windows Logon Success. | 3 | 3,506
18109 | Windows: Session reconnected/disconnected to winstation. | 3 | 7
18140 | Windows: System time changed. | 5 | 9
18145 | Windows: Service startup type was changed. | 3 | 25
18148 | Windows is starting up. | 3 | 3
18149 | Windows User Logoff. | 3 | 2,503

### User Acceptance Criteria
1. Column should be sortable in numeric order, ascending or descending

**Comment by jesusgn90** [comment]
Hello @juergenc ,

The problem now comes from Elasticsearch, the type of that field is not a number, so the sorting algorithm is using it string comparation instead number comparation, we need to upgrade our Elasticsearch template.

Take look into the next two outputs:

```
curl <elastic_ip>:wazuh-alerts-3.x-2018.10.09/_mapping/wazuh/field/rule.id
{
  "wazuh-alerts-3.x-2018.10.09": {
    "mappings": {
      "wazuh": {
        "rule.id": {
          "full_name": "rule.id",
          "mapping": {
            "id": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}
```

```
curl <elastic_ip>:wazuh-alerts-3.x-2018.10.09/_mapping/wazuh/field/rule.level
{
  "wazuh-alerts-3.x-2018.10.09": {
    "mappings": {
      "wazuh": {
        "rule.level": {
          "full_name": "rule.level",
          "mapping": {
            "level": {
              "type": "long"
            }
          }
        }
      }
    }
  }
}
```

As you can see, we have `rule.level` properly typed, but not `rule.id`, I don't know if we are going to change it in further releases due to compatibility reasons. In the mean time you can try to change it by yourself as follow:

1. Download our template:

```
curl https://raw.githubusercontent.com/wazuh/wazuh/3.6/extensions/elasticsearch/wazuh-elastic6-template-alerts.json -o custom-template.json
```

2. Edit the template, look for rule.id:

```
 "rule": {
     "properties": {
     ....
     "id":  {
          "type": "keyword",
          "doc_values": "true"
      },
```

replace it by this:

```
 "rule": {
     "properties": {
     ....
     "id":  {
          "type": "long",
          "doc_values": "true"
      },
```

3. Insert your custom template over the existing one for Wazuh:

```
curl -XPUT 'http://<elastic_ip>:9200/_template/wazuh' -H 'Content-Type: application/json' -d @custom-template.json
```

From now and onwards your indices will use this template. Keep in mind that already created indices won't be affected, this means you'll have indices with different field types and that will end in multiple errors when using Kibana and a few other things. There is a solution for this, is reindexing existing indices into new indices using this new mapping (re-mapping).

On a side note: don't do this in production environments, you can break multiple things in your environment. I hope it helps and sorry about the inconveniences.

I hope it helps.

Best regards,
Jesús
