### ISSUE TITLE
OS Name Filter for Windows Systems shows Systems which are not matching the Filter Criterion

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh-kibana-app#963]
### Steps to Reproduce
1. Have several Windows agents registered with different _OS names_, I have here systems with _OS names_ 1.1 _Microsoft Windows 7 Professional Service Pack 1_, 
1.2 _Microsoft Windows 8.1 Pro_, 
1.3 _Microsoft Windows Server 2008 R2 Standard Edition Service Pack1 6.1.7601_,
1.4 _Microsoft Windows Server 2012 R2 Standard 6.3.9600_,
1.5 _Microsoft Windows Server 2016 Standard 10.0.14393_
1. Open _Agents_ tab in Kibana by clicking on the _Agents_ buttom on the top menu bar
1. Select _Microsoft Windows 7 Professional Service Pack 1_ item from the _OS Name_ pull-down menu
1. The agent listed in the first row matches the _OS Name_ filter criterion, the second and third not

ID | Name | IP | Status | Group | OS name | OS version | Version
-- | -- | -- | -- | -- | -- | -- | --
033 | llw-96421 | 10.23.53.101 | Active | windows | Microsoft Windows 7 Profefessional Service Pack 1 | 6.1.7601 | Wazuh v3.6.1
035 | operaciones-sit | 192.168.16.59 | Active | windows | Microsoft Windows Server 2008 R2 Standard Edition Service Pack1 | 6.1.7601 | Wazuh v3.6.1
036 | masterlpcb01 | 192.168.16.107 | Disconnected | windows | Microsoft Windows Server 2008 R2 Standard Edition Service Pack1  | 6.1.7601 | Wazuh v3.6.1

5. Second example, select _Microsoft Windows 8.1 Pro_ item from the _OS Name_ pull-down menu
6. The agent listed in the first row matches the _OS Name_ filter criterion, the second not

ID | Name | IP | Status | Group | OS name | OS version | Version
-- | -- | -- | -- | -- | -- | -- | --
030 | seguridad06 | 10.23.53.104 | Active | windows | Microsoft Windows 8.1 Pro | 6.3.9600 | Wazuh v3.6.0
034 | lwik004 | 10.4.163.30 | Active | windows | Microsoft Windows Server 2012 R2 Standard | 6.3.9600 | Wazuh v3.6.1

**Comment by jesusgn90** [comment]
Hello @juergenc ,

The problem here comes from the way we are fetching the data. Currently when you see `CentOS Linux 7` the request under the hood is using the next payload to request the data:

```js
{
  "os.platform": "centos"
  "os.version": "7"
}
```

That agent has the following OS properties:

```js
"os": {
        "major": "7",
        "name": "CentOS Linux",
        "uname": "Linux |master |3.10.0-862.2.3.el7.x86_64 |#1 SMP Wed May 9 18:05:47 UTC 2018 |x86_64",
        "platform": "centos",
        "version": "7",
        "codename": "Core",
        "arch": "x86_64"
      }
```

So let's fetch the data using the next query:

```js
GET /agents
{
  "os.name": "CentOS Linux"
}
```

This results in:

```
API error: 604 - Filter error. Allowed filters: [ offset  limit  sort  search  q  status  os.platform  os.version  manager  version  node  older_than  group  name  ip  select ]
```

That's why are currently using it, by the way I've just created this issue https://github.com/wazuh/wazuh-api/issues/192, once the Wazuh API provide us those filters, we'll update the Wazuh app. 

Thanks a lot for reporting this, really appreciate it.

Kind regards,
Jesús

**Comment by jesusgn90** [comment]
Hi @juergenc ,

This task will be included in https://github.com/wazuh/wazuh-kibana-app/issues/1002, this problem is a mixing between the Wazuh API itself and the Wazuh app logic, but definitively you are fully right and we'll include this in the mentioned task. 

Many thanks one more time about your valuable feedback.

Best regards,
Jesús
